"""Batch 13: Add ~1300 more questions to reach ~7000 total"""
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(a)}', 'Alternative', 'Misconception', 'Unsure'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# --- JAVA (+250) ---
gen([
    ("Spring Boot", "What is the embedded Tomcat in Spring Boot?", "Built-in Tomcat server that runs without external deployment"),
    ("Spring Boot", "What is the spring-boot-starter-web?", "Starter for building web applications with Spring MVC"),
    ("Spring Boot", "What is the spring-boot-starter-data-jpa?", "Starter for Spring Data JPA with Hibernate"),
    ("Spring Boot", "What is the spring-boot-starter-security?", "Starter for Spring Security"),
    ("Spring Boot", "What is the spring-boot-starter-test?", "Starter for testing with JUnit, Mockito, and Hamcrest"),
    ("Spring Boot", "What is the spring-boot-maven-plugin?", "Plugin that packages Spring Boot as executable JAR"),
    ("Spring Boot", "What is the fat JAR in Spring Boot?", "JAR with all dependencies bundled for standalone execution"),
    ("Spring Boot", "What is the @SpringBootTest annotation?", "Annotation for integration testing Spring Boot applications"),
    ("Spring Boot", "What is the @WebMvcTest annotation?", "Annotation for testing Spring MVC controllers in isolation"),
    ("Spring Boot", "What is the @DataJpaTest annotation?", "Annotation for testing JPA repositories in isolation"),
    ("Spring Boot", "What is the @RestClientTest annotation?", "Annotation for testing REST clients"),
    ("Spring Boot", "What is the @JsonTest annotation?", "Annotation for testing JSON serialization"),
    ("Spring Boot", "What is the @MockBean annotation?", "Adds mock to Spring application context"),
    ("Spring Boot", "What is the @SpyBean annotation?", "Wraps a real bean with Mockito spy"),
    ("Spring Boot", "What is the TestRestTemplate?", "Template for REST integration tests"),
    ("Spring Boot", "What is the WebTestClient?", "Reactive web test client"),
    ("Spring Boot", "What is the @ConfigurationProperties?", "Binds external config to typed objects"),
    ("Spring Boot", "What is the @Value annotation?", "Injects property values into fields"),
    ("Spring Boot", "What is the @PropertySource annotation?", "Specifies property file locations"),
    ("Spring Boot", "What is the @TestPropertySource annotation?", "Property sources for test contexts"),
    ("Spring Boot", "What is the application.yml?", "YAML-based configuration file"),
    ("Spring Boot", "What is the bootstrap.yml?", "Configuration for Spring Cloud bootstrap phase"),
    ("Spring Boot", "What is the @RefreshScope annotation?", "Refreshes beans on configuration changes"),
    ("Spring Boot", "What is the Actuator info endpoint?", "Custom application information endpoint"),
    ("Spring Boot", "What is the Actuator health endpoint?", "Application health check endpoint"),
    ("Spring Boot", "What is the Actuator metrics endpoint?", "Application metrics like memory and GC"),
    ("Spring Boot", "What is the Actuator env endpoint?", "Environment properties endpoint"),
    ("Spring Boot", "What is the Actuator beans endpoint?", "Lists all beans in application context"),
    ("Spring Boot", "What is the Actuator mappings endpoint?", "Lists all request mappings"),
    ("Spring Boot", "What is the Actuator threaddump endpoint?", "Thread dump information endpoint"),
    ("Spring Boot", "What is the Actuator heapdump endpoint?", "Heap dump download endpoint"),
    ("Spring Boot", "What is the Actuator loggers endpoint?", "Logger configuration endpoint"),
    ("Spring Boot", "What is the Actuator shutdown endpoint?", "Graceful shutdown endpoint (disabled by default)"),
    ("Spring Boot", "What is the management.server.port property?", "Port for Actuator endpoints"),
    ("Spring Boot", "What is the management.endpoints.web.base-path?", "Base path for Actuator web endpoints"),
    ("Spring Boot", "What is the Spring Boot DevTools?", "Development-time tools with auto-restart and LiveReload"),
    ("Spring Boot", "What is the LiveReload in DevTools?", "Browser auto-refresh on code changes"),
    ("Spring Boot", "What is the remote DevTools?", "Remote application debugging support"),
    ("Spring Boot", "What is the @Profile annotation?", "Activates bean based on active profile"),
    ("Spring Boot", "What is the application-dev.yml?", "Profile-specific configuration for development"),
    ("Spring Boot", "What is the spring.profiles.active property?", "Activates specific profiles"),
    ("Spring Boot", "What is the @ConditionalOnProperty annotation?", "Conditional bean creation based on property"),
    ("Spring Boot", "What is the @ConditionalOnClass annotation?", "Conditional bean creation based on class existence"),
    ("Spring Boot", "What is the @ConditionalOnMissingBean annotation?", "Creates bean only if no matching bean exists"),
    ("Spring Boot", "What is the @ConditionalOnBean annotation?", "Creates bean only if matching bean exists"),
    ("Spring Boot", "What is the @ConditionalOnExpression annotation?", "Conditional on SpEL expression evaluation"),
    ("Spring Boot", "What is the auto-configuration order?", "Controlled by @AutoConfigureOrder and @AutoConfigureBefore/After"),
    ("Spring Boot", "What is the spring.factories file?", "Auto-configuration registration file under META-INF"),
    ("Spring Boot", "What is the @EnableAutoConfiguration exclusion?", "Exclude specific auto-configuration classes"),
    ("Spring Boot", "What is the spring-autoconfigure-metadata.properties?", "Auto-configuration metadata for filtering"),
    ("Spring Boot", "What is the @EntityScan annotation?", "Specifies entity scanning packages"),
    ("Spring Boot", "What is the @EnableJpaRepositories annotation?", "Enables JPA repository scanning"),
    ("Spring Boot", "What is the spring.jpa.hibernate.ddl-auto property?", "Schema generation strategy: none, validate, update, create, create-drop"),
    ("Spring Boot", "What is the spring.datasource.url property?", "JDBC URL for data source connection"),
    ("Spring Boot", "What is the HikariCP connection pool?", "Default high-performance connection pool in Spring Boot"),
    ("Spring Boot", "What is the @Transactional in tests?", "Rolls back test data after each test"),
    ("Spring Boot", "What is the TestEntityManager?", "Helper for JPA test data management"),
    ("Spring Boot", "What is the MockMvc class?", "Performs HTTP requests in MVC tests"),
    ("Spring Boot", "What is the jsonPath in tests?", "JSON expression assertions in test results"),
    ("Spring Boot", "What is the @Sql annotation?", "Executes SQL scripts before test methods"),
    ("Spring Boot", "What is the @SqlGroup annotation?", "Groups multiple @Sql annotations"),
    ("Spring Boot", "What is the @OutputCapture annotation?", "Captures System.out and System.err in tests"),
    ("Spring Boot", "What is the REST Docs?", "Documentation generation from Spring MVC tests"),
    ("Spring Boot", "What is the OpenAPI / Swagger?", "API documentation standard and tooling"),
    ("Spring Boot", "What is the springdoc-openapi library?", "OpenAPI documentation for Spring Boot"),
    ("Spring Boot", "What is the @Operation annotation?", "OpenAPI operation description"),
    ("Spring Boot", "What is the @ApiResponse annotation?", "OpenAPI response description"),
    ("Spring Boot", "What is the @Schema annotation?", "OpenAPI schema description"),
    ("Spring Boot", "What is the Spring Data REST?", "Exposes JPA repositories as REST endpoints"),
    ("Spring Boot", "What is the @RepositoryRestResource annotation?", "Configures Spring Data REST export"),
    ("Spring Boot", "What is the Spring Data REST projections?", "Custom JSON views for entities"),
    ("Spring Boot", "What is the Spring HATEOAS?", "Hypermedia-driven REST API support"),
    ("Spring Boot", "What is the hateoas EntityModel?", "Wraps entity with hypermedia links"),
    ("Spring Boot", "What is the hateoas CollectionModel?", "Wraps collection with hypermedia links"),
    ("Spring Boot", "What is the WebMvcConfigurer interface?", "Configures Spring MVC programmatically"),
    ("Spring Boot", "What is the @CrossOrigin annotation?", "Enables CORS for controller methods"),
    ("Spring Boot", "What is the @ExceptionHandler in controllers?", "Handles exceptions within controller"),
    ("Spring Boot", "What is the @ControllerAdvice?", "Global exception handling for controllers"),
    ("Spring Boot", "What is the @InitBinder annotation?", "Custom data binding initialization"),
    ("Spring Boot", "What is the @ModelAttribute annotation?", "Binds method parameter from model"),
    ("Spring Boot", "What is the @SessionAttributes annotation?", "Stores model attributes in HTTP session"),
    ("Spring Boot", "What is the @Valid annotation?", "Triggers bean validation"),
    ("Spring Boot", "What is the @Validated annotation?", "Triggers validation on groups"),
    ("Spring Boot", "What is the Bean Validation API (JSR 380)?", "Validation framework with annotations like @NotNull, @Size"),
    ("Spring Boot", "What is the @NotNull constraint?", "Validates value is not null"),
    ("Spring Boot", "What is the @NotEmpty constraint?", "Validates string/collection is not empty"),
    ("Spring Boot", "What is the @NotBlank constraint?", "Validates string is not blank (null or whitespace)"),
    ("Spring Boot", "What is the @Size constraint?", "Validates size within min/max bounds"),
    ("Spring Boot", "What is the @Min/@Max constraint?", "Validates numeric value within range"),
    ("Spring Boot", "What is the @Pattern constraint?", "Validates string matches regex"),
    ("Spring Boot", "What is the @Email constraint?", "Validates email format"),
    ("Spring Boot", "What is the @Positive/@PositiveOrZero constraint?", "Validates positive number"),
    ("Spring Boot", "What is the @Negative/@NegativeOrZero constraint?", "Validates negative number"),
    ("Spring Boot", "What is the @Past/@Future constraint?", "Validates date in past or future"),
    ("Spring Boot", "What is the custom validator?", "User-defined validation annotation and implementation"),
    ("Spring Boot", "What is the ConstraintValidator interface?", "Implement custom validation logic"),
    ("Spring Boot", "What is the Error Handling in REST?", "Returning proper HTTP status and error body"),
    ("Spring Boot", "What is the ResponseEntityExceptionHandler?", "Base class for global error handling"),
    ("Spring Boot", "What is the ProblemDetail (RFC 7807)?", "Standard error response format"),
    ("Spring Boot", "What is the @ResponseStatus annotation?", "Sets HTTP status code for exception"),
    ("Spring Boot", "What is the @ResponseStatusException?", "Programmatic HTTP status exception"),
    ("Spring Boot", "What is the WebMvcTest slice?", "Loads only web layer components for testing"),
    ("Spring Boot", "What is the @AutoConfigureMockMvc?", "Auto-configures MockMvc for tests"),
    ("Spring Boot", "What is the @AutoConfigureWebClient?", "Auto-configures WebTestClient for tests"),
    ("Spring Boot", "What is the @AutoConfigureRestDocs?", "Auto-configures REST Docs for tests"),
    ("Spring Boot", "What is the @AutoConfigureCache?", "Auto-configures cache for tests"),
    ("Spring Boot", "What is the @DirtiesContext annotation?", "Marks test context as dirty for reload"),
    ("Spring Boot", "What is the @Timed annotation?", "Fails test if execution exceeds time limit"),
    ("Spring Boot", "What is the @Repeat annotation?", "Repeats test multiple times"),
    ("Spring Boot", "What is the @Commit annotation?", "Commits transaction after test"),
    ("Spring Boot", "What is the @Rollback annotation?", "Rolls back transaction after test"),
    ("Spring Boot", "What is the JMX support in Spring Boot?", "Management with JMX MBeans"),
    ("Spring Boot", "What is the @EnableMBeanExport annotation?", "Enables JMX bean export"),
    ("Spring Boot", "What is the @ManagedResource annotation?", "Exposes bean as JMX MBean"),
    ("Spring Boot", "What is the @ManagedAttribute annotation?", "Exposes bean property as JMX attribute"),
    ("Spring Boot", "What is the @ManagedOperation annotation?", "Exposes bean method as JMX operation"),
    ("Spring Boot", "What is the Spring Boot Admin?", "Administration UI for Spring Boot applications"),
    ("Spring Boot", "What is the Micrometer library?", "Vendor-neutral metrics collection library"),
    ("Spring Boot", "What is the Micrometer MeterRegistry?", "Registry for creating and managing meters"),
    ("Spring Boot", "What is the Micrometer Counter?", "Monotonically increasing counter"),
    ("Spring Boot", "What is the Micrometer Gauge?", "Single value measurement"),
    ("Spring Boot", "What is the Micrometer Timer?", "Time duration and throughput measurement"),
    ("Spring Boot", "What is the Micrometer DistributionSummary?", "Distribution of values"),
    ("Spring Boot", "What is the Micrometer LongTaskTimer?", "Tracks long-running tasks duration"),
    ("Spring Boot", "What is the @Timed annotation in Micrometer?", "Times method execution automatically"),
    ("Spring Boot", "What is the Micrometer's Prometheus format?", "Exposes metrics in Prometheus text format"),
    ("Spring Boot", "What is the Grafana dashboard?", "Visualization for metrics from Prometheus"),
    ("Spring Boot", "What is the Spring Boot Docker image?", "Containerized Spring Boot application"),
    ("Spring Boot", "What is the buildpacks support?", "Building container images without Dockerfile"),
    ("Spring Boot", "What is the Paketo buildpacks?", "Cloud Native Buildpacks for Spring Boot"),
    ("Spring Boot", "What is the spring-boot:build-image goal?", "Maven goal to build OCI image"),
    ("Spring Boot", "What is the Layered JAR in Spring Boot?", "Separates dependencies into layers for efficient Docker builds"),
    ("Spring Boot", "What is the Spring Boot layered JAR index?", "File listing layer contents for optimization"),
    ("Spring Boot", "What is the Spring Boot Native (GraalVM)?", "Compiles Spring Boot to native executable"),
    ("Spring Boot", "What is the Spring AOT (Ahead-of-Time)?", "Pre-computes Spring configuration for native images"),
    ("Spring Boot", "What is the @NativeHint annotation?", "Hints for GraalVM native compilation"),
    ("Spring Boot", "What is the Spring Boot 3.0?", "Version with Jakarta EE 9+, GraalVM, and observability"),
    ("Spring Boot", "What is the Jakarta EE migration?", "Moving from javax.* to jakarta.* namespace"),
    ("Spring Boot", "What is the spring-boot-starter-webflux?", "Starter for reactive web applications"),
    ("Spring Boot", "What is the WebFlux vs WebMVC?", "WebFlux is reactive/non-blocking; WebMVC is servlet-based"),
    ("Spring Boot", "What is the Mono type?", "Reactive type for 0 or 1 element"),
    ("Spring Boot", "What is the Flux type?", "Reactive type for 0 to N elements"),
    ("Spring Boot", "What is the @Controller vs @RestController in WebFlux?", "Same as MVC but with reactive return types"),
    ("Spring Boot", "What is the RouterFunction in WebFlux?", "Functional routing definition"),
    ("Spring Boot", "What is the HandlerFunction in WebFlux?", "Functional request handler"),
    ("Spring Boot", "What is the WebClient in WebFlux?", "Reactive HTTP client"),
    ("Spring Boot", "What is the ServerResponse in WebFlux?", "Reactive HTTP response builder"),
    ("Spring Boot", "What is the reactive MongoDB support?", "Reactive Spring Data MongoDB with ReactiveMongoRepository"),
    ("Spring Boot", "What is the reactive Redis support?", "Reactive Spring Data Redis with ReactiveRedisTemplate"),
    ("Spring Boot", "What is the reactive Cassandra support?", "Reactive Spring Data Cassandra"),
    ("Spring Boot", "What is the reactive R2DBC?", "Reactive database connectivity for SQL databases"),
    ("Spring Boot", "What is the R2DBC vs JDBC?", "R2DBC is reactive/non-blocking; JDBC is blocking"),
    ("Spring Boot", "What is the DatabaseClient in R2DBC?", "Reactive database client for SQL"),
    ("Spring Boot", "What is the spring-boot-starter-data-r2dbc?", "Starter for R2DBC database access"),
    ("Spring Boot", "What is the RSocket protocol?", "Reactive socket protocol for bidirectional communication"),
    ("Spring Boot", "What is the @MessageMapping in RSocket?", "Maps RSocket messages to handler methods"),
    ("Spring Boot", "What is the Spring Cloud Config?", "External configuration management for distributed systems"),
    ("Spring Boot", "What is the Config Server?", "Centralized configuration server"),
    ("Spring Boot", "What is the Config Client?", "Client fetching configuration from Config Server"),
    ("Spring Boot", "What is the Spring Cloud Gateway?", "API Gateway built on Spring WebFlux"),
    ("Spring Boot", "What is the GatewayFilter in Cloud Gateway?", "Filters modifying requests/responses"),
    ("Spring Boot", "What is the Predicate in Cloud Gateway?", "Route matching conditions"),
    ("Spring Boot", "What is the Spring Cloud Circuit Breaker?", "Resilience4j integration for circuit breaking"),
    ("Spring Boot", "What is the Resilience4j library?", "Fault tolerance library with circuit breaker, retry, rate limiter"),
    ("Spring Boot", "What is the @CircuitBreaker annotation?", "Enables circuit breaker for method"),
    ("Spring Boot", "What is the @Retry annotation?", "Retries method on failure"),
    ("Spring Boot", "What is the @RateLimiter annotation?", "Limits call rate to a method"),
    ("Spring Boot", "What is the @TimeLimiter annotation?", "Limits execution time of a method"),
    ("Spring Boot", "What is the @Bulkhead annotation?", "Isolates method execution with thread pool or semaphore"),
    ("Spring Boot", "What is the Spring Cloud Sleuth?", "Distributed tracing for Spring Boot (deprecated by Micrometer Tracing)"),
    ("Spring Boot", "What is the Micrometer Tracing?", "Distributed tracing with Brave or OpenTelemetry"),
    ("Spring Boot", "What is the Zipkin integration?", "Distributed tracing visualization with Zipkin"),
    ("Spring Boot", "What is the OpenTelemetry?", "Vendor-neutral observability standard"),
    ("Spring Boot", "What is the @SpanTag annotation?", "Adds tag to current span"),
    ("Spring Boot", "What is the @NewSpan annotation?", "Creates a new span for method execution"),
    ("Spring Boot", "What is the @ContinueSpan annotation?", "Continues existing span for method"),
    ("Spring Boot", "What is the Spring Cloud Function?", "Serverless function support for Spring Boot"),
    ("Spring Boot", "What is the @EnableBinding annotation?", "Enables message binding (deprecated in SC Stream 4.x)"),
    ("Spring Boot", "What is the Spring Cloud Stream?", "Event-driven microservice framework with message brokers"),
    ("Spring Boot", "What is the @StreamListener annotation?", "Message handler for Spring Cloud Stream"),
    ("Spring Boot", "What is the Spring Cloud Bus?", "Broadcasting configuration changes across services"),
    ("Spring Boot", "What is the Spring Cloud Task?", "Short-lived microservice tasks"),
    ("Spring Boot", "What is the Spring Cloud Data Flow?", "Orchestration for data processing pipelines"),
    ("Spring Boot", "What is the Spring Batch?", "Batch processing framework"),
    ("Spring Boot", "What is the @EnableBatchProcessing?", "Enables Spring Batch configuration"),
    ("Spring Boot", "What is the Job in Spring Batch?", "A batch process with steps"),
    ("Spring Boot", "What is the Step in Spring Batch?", "A phase in a batch job"),
    ("Spring Boot", "What is the ItemReader in Spring Batch?", "Reads input data for batch processing"),
    ("Spring Boot", "What is the ItemProcessor in Spring Batch?", "Processes/transforms items"),
    ("Spring Boot", "What is the ItemWriter in Spring Batch?", "Writes processed items to output"),
    ("Spring Boot", "What is the Tasklet in Spring Batch?", "Simple task for batch step"),
    ("Spring Boot", "What is the Chunk-oriented processing?", "Processing items in configurable chunks"),
    ("Spring Boot", "What is the JobLauncher in Spring Batch?", "Starts batch jobs"),
    ("Spring Boot", "What is the JobRepository in Spring Batch?", "Persists batch job metadata"),
    ("Spring Boot", "What is the @EnableScheduling?", "Enables Spring task scheduling"),
    ("Spring Boot", "What is the @Scheduled annotation?", "Schedules method execution with cron or fixed rate"),
    ("Spring Boot", "What is the cron expression format?", "Seconds Minutes Hours DayOfMonth Month DayOfWeek"),
    ("Spring Boot", "What is the @Async annotation?", "Makes method execute asynchronously"),
    ("Spring Boot", "What is the @EnableAsync annotation?", "Enables async method execution"),
    ("Spring Boot", "What is the ThreadPoolTaskExecutor?", "Spring's thread pool executor for async tasks"),
    ("Spring Boot", "What is the @Cacheable annotation?", "Caches method result"),
    ("Spring Boot", "What is the @CacheEvict annotation?", "Removes entries from cache"),
    ("Spring Boot", "What is the @CachePut annotation?", "Updates cache without affecting method execution"),
    ("Spring Boot", "What is the @Caching annotation?", "Groups multiple cache annotations"),
    ("Spring Boot", "What is the @EnableCaching annotation?", "Enables caching support"),
    ("Spring Boot", "What is the CacheManager interface?", "Manages cache instances"),
    ("Spring Boot", "What is the Redis CacheManager?", "Redis-backed cache manager"),
    ("Spring Boot", "What is the Caffeine cache?", "High-performance JVM cache library"),
    ("Spring Boot", "What is the @EnableWebSecurity?", "Enables Spring Security configuration"),
    ("Spring Boot", "What is the SecurityFilterChain?", "Defines security filter chain"),
    ("Spring Boot", "What is the @EnableMethodSecurity?", "Enables method-level security annotations"),
    ("Spring Boot", "What is the @PreAuthorize annotation?", "Method security based on SpEL expression"),
    ("Spring Boot", "What is the @PostAuthorize annotation?", "Method security check after execution"),
    ("Spring Boot", "What is the @Secured annotation?", "Role-based method security"),
    ("Spring Boot", "What is the @RolesAllowed annotation?", "JSR-250 role-based security"),
    ("Spring Boot", "What is the SecurityContextHolder?", "Stores current security context"),
    ("Spring Boot", "What is the Authentication object?", "Represents authenticated principal"),
    ("Spring Boot", "What is the UserDetailsService?", "Loads user-specific data for authentication"),
    ("Spring Boot", "What is the PasswordEncoder interface?", "Encodes passwords for secure storage"),
    ("Spring Boot", "What is the BCryptPasswordEncoder?", "Password encoder using BCrypt hashing"),
    ("Spring Boot", "What is the JWT authentication flow?", "Token-based auth: login returns JWT, sent in Authorization header"),
    ("Spring Boot", "What is the OAuth2 resource server?", "Validates JWT tokens from authorization server"),
    ("Spring Boot", "What is the OAuth2 client?", "Delegates authentication to external providers"),
    ("Spring Boot", "What is the OAuth2 login?", "Social login with Google, GitHub, Facebook, etc."),
    ("Spring Boot", "What is the @EnableOAuth2Sso annotation?", "Enables single sign-on with OAuth2 (deprecated)"),
    ("Spring Boot", "What is the SAML2 integration?", "SAML-based single sign-on with Spring Security"),
    ("Spring Boot", "What is the CSRF protection in Spring Security?", "Cross-Site Request Forgery prevention"),
    ("Spring Boot", "What is the CORS configuration in Spring Security?", "Cross-Origin Resource Sharing setup"),
    ("Spring Boot", "What is the @EnableGlobalMethodSecurity?", "Enables method-level security (pre/post annotations)"),
    ("Spring Boot", "What is the HttpSecurity configuration?", "Configures HTTP security rules"),
    ("Spring Boot", "What is the WebSecurityCustomizer?", "Configures web security ignoring paths"),
], "Senior", "Java")

# --- PYTHON (+250) ---
gen([
    ("Web", "What is Flask?", "A lightweight WSGI web framework for Python"),
    ("Web", "What is Django?", "A full-featured web framework with ORM and admin"),
    ("Web", "What is the Django ORM?", "Object-relational mapper for database access"),
    ("Web", "What is the Django REST Framework?", "Library for building REST APIs with Django"),
    ("Web", "What is FastAPI?", "A modern async web framework with automatic OpenAPI docs"),
    ("Web", "What is the ASGI standard?", "Asynchronous Server Gateway Interface for Python"),
    ("Web", "What is the WSGI standard?", "Web Server Gateway Interface for synchronous Python web apps"),
    ("Web", "What is uvicorn?", "ASGI server for running async Python apps"),
    ("Web", "What is gunicorn?", "WSGI HTTP server for Python"),
    ("Web", "What is the Jinja2 template engine?", "Template engine used by Flask and Ansible"),
    ("Web", "What is the Mako template engine?", "Template engine with embedded Python code"),
    ("Web", "What is the WebSockets support in FastAPI?", "Built-in WebSocket support with async handlers"),
    ("Web", "What is the Pydantic library?", "Data validation using Python type annotations"),
    ("Web", "What is the BaseModel in Pydantic?", "Base class for data models with validation"),
    ("Web", "What is the @validator decorator in Pydantic?", "Custom field validation"),
    ("Web", "What is the @field_validator in Pydantic v2?", "Field-specific validation"),
    ("Web", "What is the @model_validator in Pydantic v2?", "Model-level validation"),
    ("Web", "What is the Config class in Pydantic?", "Model configuration for ORM mode, extra fields, etc."),
    ("Web", "What is the model_config in Pydantic v2?", "Configuration dictionary for model settings"),
    ("Web", "What is the FastAPI Dependency Injection?", "Built-in DI system with Depends()"),
    ("Web", "What is the Depends() function in FastAPI?", "Declares dependency for path operation"),
    ("Web", "What is the BackgroundTasks in FastAPI?", "Runs tasks after HTTP response is sent"),
    ("Web", "What is the APIRouter in FastAPI?", "Modular routing with tags and prefix"),
    ("Web", "What is the HTTPException in FastAPI?", "Standard HTTP error response"),
    ("Web", "What is the WebSocket disconnect handling?", "Catching WebSocketDisconnect exception"),
    ("Web", "What is the SQLAlchemy library?", "Database ORM and toolkit for Python"),
    ("Web", "What is the SQLAlchemy Core?", "Low-level SQL expression language"),
    ("Web", "What is the SQLAlchemy ORM?", "High-level ORM with unit of work pattern"),
    ("Web", "What is the declarative base in SQLAlchemy?", "Base class for ORM model definitions"),
    ("Web", "What is the session in SQLAlchemy?", "Unit of work for database operations"),
    ("Web", "What is the relationship in SQLAlchemy?", "Defines database relationships between models"),
    ("Web", "What is the backref in SQLAlchemy?", "Creates reverse relationship automatically"),
    ("Web", "What is the eager loading in SQLAlchemy?", "joinedload, subqueryload, selectinload strategies"),
    ("Web", "What is the Alembic library?", "Database migration tool for SQLAlchemy"),
    ("Web", "What is the revision in Alembic?", "Migration script with upgrade/downgrade functions"),
    ("Web", "What is the auto-generation in Alembic?", "Comparing schema to generate migrations automatically"),
    ("Web", "What is the Celery library?", "Distributed task queue for async job processing"),
    ("Web", "What is the Celery worker?", "Processes tasks from message broker"),
    ("Web", "What is the Celery beat?", "Periodic task scheduler for Celery"),
    ("Web", "What is the Redis as Celery broker?", "Message broker using Redis"),
    ("Web", "What is the RabbitMQ as Celery broker?", "Message broker using RabbitMQ"),
    ("Web", "What is the task in Celery?", "A unit of work decorated with @app.task"),
    ("Web", "What is the delay() in Celery?", "Sends task to broker for async execution"),
    ("Web", "What is the apply_async() in Celery?", "Sends task with more options like countdown, eta"),
    ("Web", "What is the task result in Celery?", "Use backend (Redis/DB) to store and retrieve results"),
    ("Web", "What is the chain in Celery?", "Tasks executed sequentially, passing results"),
    ("Web", "What is the group in Celery?", "Tasks executed in parallel"),
    ("Web", "What is the chord in Celery?", "Group with a callback after all tasks complete"),
    ("Web", "What is the Flower monitoring tool?", "Web-based monitoring for Celery"),
    ("Web", "What is the pytest-celery library?", "Fixtures for testing Celery tasks"),
    ("Web", "What is the Motor library?", "Async MongoDB driver for Python"),
    ("Web", "What is the Beanie ODM?", "Async ODM for MongoDB with Pydantic models"),
    ("Web", "What is the MongoDB aggregation pipeline?", "Data processing pipeline for MongoDB"),
    ("Web", "What is the Redis-py library?", "Python client for Redis"),
    ("Web", "What is the aioredis library?", "Async Redis client (merged into redis-py)"),
    ("Web", "What is the Elasticsearch DSL library?", "Python DSL for Elasticsearch queries"),
    ("Web", "What is the Neo4j Python driver?", "Graph database driver for Neo4j"),
    ("Web", "What is the APScheduler library?", "Advanced Python scheduler with cron support"),
    ("Web", "What is the Sentry SDK?", "Error tracking and performance monitoring"),
    ("Web", "What is the Prometheus Python client?", "Exposes custom metrics for Prometheus"),
    ("Web", "What is the OpenTelemetry Python SDK?", "OpenTelemetry instrumentation for Python"),
    ("Web", "What is the loguru library?", "Modern logging library with structured logging"),
    ("Web", "What is the structlog library?", "Structured logging for Python"),
    ("Web", "What is the rich library?", "Rich text formatting in terminal"),
    ("Web", "What is the typer library?", "CLI framework based on type hints"),
    ("Web", "What is the click library?", "Command-line interface creation toolkit"),
    ("Web", "What is the argparse vs click vs typer?", "argparse: stdlib; click: decorator-based; typer: type-hint-based"),
    ("Web", "What is the invoke library?", "Task execution and CLI framework"),
    ("Web", "What is the fabric library?", "Remote server automation and deployment"),
    ("Web", "What is the paramiko library?", "SSH protocol implementation for Python"),
    ("Web", "What is the ansible library?", "Configuration management and automation"),
    ("Web", "What is the tox tool?", "Virtualenv management and test automation"),
    ("Web", "What is the nox tool?", "Flexible test automation similar to tox"),
    ("Web", "What is the pre-commit tool?", "Git hooks framework for code quality"),
    ("Web", "What is the pre-commit hooks?", "Automated checks before commit: linting, formatting"),
    ("Web", "What is the commitizen tool?", "Standardized commit message format"),
    ("Web", "What is the semantic-release tool?", "Automated versioning and changelog generation"),
    ("Web", "What is the poetry vs pipenv vs pip?", "poetry: modern with lockfile; pipenv: Pipfile-based; pip: basic"),
    ("Web", "What is the pyenv tool?", "Python version management tool"),
    ("Web", "What is the conda environment?", "Cross-platform package and environment manager"),
    ("Web", "What is the miniconda vs anaconda?", "miniconda: minimal installer; anaconda: full distribution"),
    ("Web", "What is the pip freeze command?", "Outputs installed packages in requirements format"),
    ("Web", "What is the requirements.txt file?", "Lists project dependencies for pip"),
    ("Web", "What is the setup.py file?", "Package metadata and dependencies for legacy packaging"),
    ("Web", "What is the setup.cfg file?", "Package metadata in INI format"),
    ("Web", "What is the pyproject.toml file?", "Modern Python project configuration (PEP 517/518)"),
    ("Web", "What is the build system in pyproject.toml?", "Specifies build backend like setuptools, poetry, flit"),
    ("Web", "What is the setuptools package?", "Legacy but still common Python build system"),
    ("Web", "What is the wheel package?", "Built package distribution format"),
    ("Web", "What is the egg format?", "Legacy Python package format (deprecated)"),
    ("Web", "What is the sdist (source distribution)?", "Source code distribution for Python packages"),
    ("Web", "What is the PyPI?", "Python Package Index for package distribution"),
    ("Web", "What is the twine tool?", "Uploads packages to PyPI securely"),
    ("Web", "What is the hatch tool?", "Modern Python project management tool"),
    ("Web", "What is the flit tool?", "Simple Python packaging tool"),
    ("Web", "What is the pbr library?", "Setuptools extension for managed packages"),
    ("Web", "What is the versioneer tool?", "Auto-versioning from git tags"),
    ("Web", "What is the bumpversion tool?", "Bumps version numbers in files"),
    ("Web", "What is the Sphinx documentation tool?", "Documentation generator for Python projects"),
    ("Web", "What is the reStructuredText markup?", "Docstring format used by Sphinx"),
    ("Web", "What is the Read the Docs?", "Hosted documentation service for open source"),
    ("Web", "What is the mkdocs tool?", "Documentation generator using Markdown"),
    ("Web", "What is the pdoc tool?", "Simple API documentation generator"),
    ("Web", "What is the doctest module?", "Tests embedded in documentation strings"),
    ("Web", "What is the unittest module?", "Built-in unit testing framework"),
    ("Web", "What is the pytest vs unittest?", "pytest: simpler and more powerful; unittest: stdlib xUnit-style"),
    ("Web", "What is the nose2 test runner?", "Successor to nose test runner"),
    ("Web", "What is the hypothesis library?", "Property-based testing for Python"),
    ("Web", "What is the faker library?", "Generates fake data for testing"),
    ("Web", "What is the factory_boy library?", "Fixtures replacement with factories"),
    ("Web", "What is the model_bakery library?", "Django model fixtures generator"),
    ("Web", "What is the mixer library?", "Django model data generator"),
    ("Web", "What is the coverage.py tool?", "Code coverage measurement"),
    ("Web", "What is the pytest-cov plugin?", "Coverage reporting for pytest"),
    ("Web", "What is the pytest-xdist plugin?", "Parallel test execution for pytest"),
    ("Web", "What is the pytest-sugar plugin?", "Enhanced pytest output formatting"),
    ("Web", "What is the pytest-html plugin?", "HTML test report generation"),
    ("Web", "What is the pytest-benchmark plugin?", "Benchmarking tests in pytest"),
    ("Web", "What is the pytest-asyncio plugin?", "Async test support for pytest"),
    ("Web", "What is the pytest-mock plugin?", "Mocking support for pytest"),
    ("Web", "What is the pytest-django plugin?", "Django test fixtures for pytest"),
    ("Web", "What is the VCR.py library?", "Record and replay HTTP interactions"),
    ("Web", "What is the responses library?", "Mock HTTP requests for testing"),
    ("Web", "What is the httpretty library?", "HTTP request mocking tool"),
    ("Web", "What is the requests-mock library?", "Mocking for requests library"),
    ("Web", "What is the tox.ini file?", "Tox configuration for multi-env testing"),
    ("Web", "What is the setup.cfg for pytest?", "pytest configuration in setup.cfg or pyproject.toml"),
    ("Web", "What is the conftest.py file?", "Pytest fixtures and hooks for test modules"),
    ("Web", "What is the pytest marks?", "Metadata for tests like @pytest.mark.slow"),
    ("Web", "What is the pytest fixtures scope?", "function, class, module, session scopes"),
    ("Web", "What is the pytest parametrize?", "Runs test with multiple input combinations"),
    ("Web", "What is the pytest yield fixtures?", "Fixtures with setup and teardown using yield"),
    ("Web", "What is the pytest autouse fixtures?", "Fixtures applied automatically to all tests"),
    ("Web", "What is the pytest tmp_path fixture?", "Temporary directory for test files"),
    ("Web", "What is the pytest monkeypatch fixture?", "Monkey patching for test isolation"),
    ("Web", "What is the pytest capsys fixture?", "Captures stdout/stderr in tests"),
    ("Web", "What is the pytest caplog fixture?", "Captures log output in tests"),
    ("Web", "What is the pytest request fixture?", "Provides test request context to fixtures"),
    ("Web", "What is the pytest test discovery?", "Auto-discovery of test files and functions"),
    ("Web", "What is the pytest naming conventions?", "test_ prefix for files, functions, and methods"),
    ("Web", "What is the pytest --tb flag?", "Traceback format: short, long, native, line"),
    ("Web", "What is the pytest -k flag?", "Filter tests by keyword expression"),
    ("Web", "What is the pytest -m flag?", "Run tests with specific mark"),
    ("Web", "What is the pytest --lf flag?", "Run last failed tests first"),
    ("Web", "What is the pytest --ff flag?", "Run failed tests first"),
    ("Web", "What is the pytest --co flag?", "Collect tests without running them"),
    ("Web", "What is the pytest --durations flag?", "Reports slowest test durations"),
    ("Web", "What is the pytest --strict-markers flag?", "Errors on unknown markers"),
    ("Web", "What is the pytest --disable-warnings flag?", "Suppresses warning output"),
    ("Web", "What is the Tox parallel execution?", "Running tox environments in parallel"),
    ("Web", "What is the Nox sessions?", "Named test environments in Nox"),
    ("Web", "What is the pre-commit-config.yaml?", "Pre-commit hook configuration"),
    ("Web", "What is the pre-commit run --all-files?", "Runs hooks on all files"),
    ("Web", "What is the mypy strict mode?", "Enables all strict type-checking options"),
    ("Web", "What is the mypy.ini file?", "Mypy configuration file"),
    ("Web", "What is the pyright tool?", "Fast TypeScript-based Python type checker"),
    ("Web", "What is the pyre tool?", "Python type checker from Meta"),
    ("Web", "What is the pytype tool?", "Google's Python type checker"),
    ("Web", "What is the type annotation in Python?", "Type hints for function parameters and return values"),
    ("Web", "What is the typing module typing_extensions?", "Backports of newer typing features"),
    ("Web", "What is the Literal type?", "Type restricted to specific literal values"),
    ("Web", "What is the TypedDict type?", "Dictionary with specific key-value type constraints"),
    ("Web", "What is the Final type?", "Marks variable as constant (should not be reassigned)"),
    ("Web", "What is the @final decorator?", "Marks method or class as not overridable"),
    ("Web", "What is the @override decorator?", "Indicates method overrides parent method"),
    ("Web", "What is the match statement (Python 3.10)?", "Structural pattern matching with case clauses"),
    ("Web", "What is the pattern matching guard?", "if condition in pattern match case"),
    ("Web", "What is the or pattern in match?", "| operator for multiple patterns in one case"),
    ("Web", "What is the as pattern in match?", "Captures matched value to variable"),
    ("Web", "What is the sequence pattern in match?", "Matching on list/tuple structure"),
    ("Web", "What is the mapping pattern in match?", "Matching on dictionary key-value structure"),
    ("Web", "What is the class pattern in match?", "Matching on class instance attributes"),
    ("Web", "What is the wildcard pattern _ in match?", "Matches anything without binding"),
    ("Web", "What is the exception groups (Python 3.11)?", "Raising and catching multiple exceptions"),
    ("Web", "What is the ExceptionGroup?", "Group of exceptions raised together"),
    ("Web", "What is the except* syntax?", "Catching specific exceptions from ExceptionGroup"),
    ("Web", "What is the Self type?", "Type hint for returning the current class type"),
    ("Web", "What is the type statement (Python 3.12)?", "Type alias declaration with type keyword"),
    ("Web", "What is the override decorator (Python 3.12)?", "Explicit method override marker"),
    ("Web", "What is the @deprecated decorator?", "Marks function as deprecated with warning"),
    ("Web", "What is the Python 3.13 free-threaded mode?", "Python without the GIL (experimental)"),
    ("Web", "What is the Python 3.13 JIT compiler?", "Experimental JIT compilation in CPython"),
    ("Web", "What is the __future__ module?", "Imports future language features"),
    ("Web", "What is the __pycache__ directory?", "Cached bytecode files directory"),
    ("Web", "What is the PYTHONPATH variable?", "Python module search path"),
    ("Web", "What is the sys.path list?", "Python import search paths"),
    ("Web", "What is the site-packages directory?", "Third-party package installation location"),
    ("Web", "What is the user site-packages directory?", "Per-user package installation location"),
    ("Web", "What is the editable install (pip install -e)?", "Installs package in development mode"),
    ("Web", "What is the namespace package?", "Package split across multiple directories"),
    ("Web", "What is the __init__.py file?", "Marks directory as Python package"),
    ("Web", "What is the __main__.py file?", "Entry point for python -m execution"),
    ("Web", "What is the __name__ == '__main__' idiom?", "Checks if script is executed directly"),
    ("Web", "What is the sys.exit() function?", "Exits Python with status code"),
    ("Web", "What is the atexit module?", "Registers cleanup functions on exit"),
    ("Web", "What is the signal module?", "Unix signal handling"),
    ("Web", "What is the traceback module?", "Extracts and formats stack traces"),
    ("Web", "What is the warnings module?", "Warning message control"),
    ("Web", "What is the abc module?", "Abstract Base Classes support"),
    ("Web", "What is the enum module?", "Enumeration type support"),
    ("Web", "What is the dataclasses module?", "Data classes with auto-generated methods"),
    ("Web", "What is the @dataclass decorator?", "Generates __init__, __repr__, __eq__ etc."),
    ("Web", "What is the field() function in dataclasses?", "Configures individual data class fields"),
    ("Web", "What is the frozen dataclass?", "Immutable data class with frozen=True"),
    ("Web", "What is the slots dataclass?", "Data class with __slots__ optimization"),
    ("Web", "What is the kw_only dataclass?", "Keyword-only field initialization"),
    ("Web", "What is the order dataclass?", "Generates comparison methods"),
    ("Web", "What is the unsafe_hash dataclass?", "Generates __hash__ even with mutable fields"),
    ("Web", "What is the @property decorator?", "Getter method with attribute access syntax"),
    ("Web", "What is the @setter decorator?", "Setter for property decorator"),
    ("Web", "What is the @deleter decorator?", "Deleter for property decorator"),
    ("Web", "What is the descriptor protocol?", "Objects with __get__, __set__, __delete__"),
    ("Web", "What is the weakref module?", "Weak references to objects"),
    ("Web", "What is the weakref.ref function?", "Creates weak reference"),
    ("Web", "What is the weakref.WeakValueDictionary?", "Dictionary mapping keys to weakly referenced values"),
    ("Web", "What is the weakref.WeakKeyDictionary?", "Dictionary with weak references to keys"),
    ("Web", "What is the copy module?", "Shallow and deep copy operations"),
    ("Web", "What is the copy.copy vs copy.deepcopy?", "copy: shallow; deepcopy: recursive copy"),
    ("Web", "What is the pprint module?", "Pretty-printing data structures"),
    ("Web", "What is the reprlib module?", "Alternate repr() implementation with size limits"),
    ("Web", "What is the contextvars module?", "Context variables for async task-local storage"),
    ("Web", "What is the asyncio.run() function?", "Entry point for running async programs"),
    ("Web", "What is the asyncio.create_task()?", "Schedules coroutine as task"),
    ("Web", "What is the asyncio.gather()?", "Runs awaitables concurrently"),
    ("Web", "What is the asyncio.wait()?", "Waits for awaitables with timeout"),
    ("Web", "What is the asyncio.as_completed()?", "Yields awaitables as they complete"),
    ("Web", "What is the asyncio.shield()?", "Protects awaitable from cancellation"),
    ("Web", "What is the asyncio.timeout()?", "Async context manager for timeout"),
    ("Web", "What is the asyncio.CancelledError?", "Raised when task is cancelled"),
    ("Web", "What is the asyncio.Queue?", "Async queue for coroutine communication"),
    ("Web", "What is the asyncio.Lock?", "Async mutual exclusion lock"),
    ("Web", "What is the asyncio.Event?", "Async event signaling"),
    ("Web", "What is the asyncio.Semaphore?", "Async semaphore for limiting concurrency"),
    ("Web", "What is the asyncio.Condition?", "Async condition variable"),
    ("Web", "What is the asyncio.subprocess module?", "Async subprocess execution"),
    ("Web", "What is the asyncio streams API?", "High-level async TCP networking"),
    ("Web", "What is the asyncio start_server?", "Async TCP server"),
    ("Web", "What is the asyncio open_connection?", "Async TCP client connection"),
    ("Web", "What is the asyncio run_coroutine_threadsafe?", "Sends coroutine to event loop in another thread"),
    ("Web", "What is the asyncio all_tasks()?", "Returns all pending tasks"),
    ("Web", "What is the asyncio current_task()?", "Returns currently running task"),
    ("Web", "What is the asyncio to_thread()?", "Runs blocking function in thread pool"),
    ("Web", "What is the asyncio run_in_executor()?", "Runs function in thread or process executor"),
    ("Web", "What is the asyncio get_running_loop()?", "Returns currently running event loop"),
    ("Web", "What is the asyncio new_event_loop()?", "Creates new event loop instance"),
    ("Web", "What is the asyncio set_event_loop()?", "Sets event loop for current context"),
    ("Web", "What is the asyncio ProactorEventLoop?", "Windows I/O completion port event loop"),
    ("Web", "What is the asyncio SelectorEventLoop?", "Selector-based event loop (Unix default)"),
    ("Web", "What is the aiofiles library?", "Async file I/O operations"),
    ("Web", "What is the aiosqlite library?", "Async SQLite database access"),
    ("Web", "What is the asyncpg library?", "Async PostgreSQL driver"),
    ("Web", "What is the aiomysql library?", "Async MySQL driver"),
    ("Web", "What is the aioredis library?", "Async Redis client"),
    ("Web", "What is the aioamqp library?", "Async RabbitMQ client"),
    ("Web", "What is the websockets library?", "Async WebSocket server and client"),
    ("Web", "What is the sanic framework?", "Async web framework inspired by Flask"),
    ("Web", "What is the aiohttp client session?", "Async HTTP client with session management"),
    ("Web", "What is the aiohttp web application?", "Async HTTP server framework"),
    ("Web", "What is the Starlette framework?", "ASGI framework that powers FastAPI"),
    ("Web", "What is the Quart framework?", "Async reimplementation of Flask"),
    ("Web", "What is the Bocadillo framework?", "Async web framework (deprecated)"),
    ("Web", "What is the Vibora framework?", "Async web framework (no longer maintained)"),
    ("Web", "What is the responder framework?", "Async web framework by Kenneth Reitz"),
    ("Web", "What is the hug framework?", "REST API framework with versioning"),
    ("Web", "What is the falcon framework?", "Minimalist WSGI framework for APIs"),
    ("Web", "What is the connexion library?", "OpenAPI-first REST framework"),
    ("Web", "What is the apistar framework?", "API framework with type checking (deprecated)"),
    ("Web", "What is the masonite framework?", "Modern MVC framework for Python"),
    ("Web", "What is the cherrypy framework?", "Minimalist web framework with built-in server"),
    ("Web", "What is the bottle framework?", "Single-file micro web framework"),
    ("Web", "What is the pyramid framework?", "Scalable web framework for large apps"),
    ("Web", "What is the web2py framework?", "Full-stack web framework (no longer maintained)"),
    ("Web", "What is the tornado framework?", "Non-blocking web server and framework"),
    ("Web", "What is the twisted framework?", "Event-driven networking engine"),
    ("Web", "What is the gevent library?", "Coroutine-based concurrency with monkey patching"),
    ("Web", "What is the eventlet library?", "Concurrent networking with green threads"),
    ("Web", "What is the greenlet library?", "Lightweight coroutines for C extensions"),
], "Senior", "Python")

# --- GENERAL (+550) ---
gen([
    ("System Design", "What is the Twitter-like system design?", "Feed generation, fanout, timeline service"),
    ("System Design", "What is the URL shortener design?", "Base62 encoding, redirect, analytics service"),
    ("System Design", "What is the chat system design?", "WebSocket, message persistence, presence service"),
    ("System Design", "What is the video streaming design?", "Transcoding, CDN, adaptive bitrate streaming"),
    ("System Design", "What is the e-commerce system design?", "Product catalog, cart, order, payment service"),
    ("System Design", "What is the ride-sharing system design?", "Geospatial queries, matching, pricing service"),
    ("System Design", "What is the notification system design?", "Push, email, SMS, template service"),
    ("System Design", "What is the payment system design?", "Idempotency, reconciliation, fraud detection"),
    ("System Design", "What is the search engine design?", "Crawler, indexer, query parser, ranking"),
    ("System Design", "What is the rate limiter design?", "Token bucket, distributed rate limiting"),
    ("System Design", "What is the distributed cache design?", "Eviction policy, replication, partitioning"),
    ("System Design", "What is the distributed ID generator design?", "Snowflake, UUID, database sequence"),
    ("System Design", "What is the Snowflake ID format?", "41-bit timestamp, 10-bit worker, 12-bit sequence"),
    ("System Design", "What is the distributed logging system?", "ELK stack, log aggregation, structured logging"),
    ("System Design", "What is the distributed monitoring system?", "Metrics collection, alerting, dashboards"),
    ("System Design", "What is the ELK stack?", "Elasticsearch, Logstash, Kibana for logging"),
    ("System Design", "What is the Prometheus monitoring?", "Time-series database with pull-based metrics"),
    ("System Design", "What is the Grafana visualization?", "Dashboard and visualization for metrics"),
    ("System Design", "What is the Thanos project?", "Long-term storage and global view for Prometheus"),
    ("System Design", "What is the Cortex project?", "Horizontal scaling for Prometheus"),
    ("System Design", "What is the Jaeger tracing?", "Distributed tracing with OpenTracing support"),
    ("System Design", "What is the Apache Kafka architecture?", "Topics, partitions, brokers, consumer groups"),
    ("System Design", "What is the Kafka topic partitioning?", "Parallelism through ordered partitions"),
    ("System Design", "What is the Kafka consumer group?", "Consumers coordinate to read partitions"),
    ("System Design", "What is the Kafka offset management?", "Tracking position of consumer in partition"),
    ("System Design", "What is the Kafka replication?", "Partition replicas for fault tolerance"),
    ("System Design", "What is the Kafka ISR (In-Sync Replicas)?", "Replicas that are fully caught up with leader"),
    ("System Design", "What is the ZooKeeper in Kafka?", "Cluster coordination and metadata management"),
    ("System Design", "What is the KRaft mode in Kafka?", "Kafka without ZooKeeper (Kafka Raft metadata)"),
    ("System Design", "What is the RabbitMQ exchange types?", "Direct, Topic, Fanout, Headers"),
    ("System Design", "What is the RabbitMQ binding?", "Connects queue to exchange with routing key"),
    ("System Design", "What is the RabbitMQ vhost?", "Virtual host for resource isolation"),
    ("System Design", "What is the RabbitMQ confirm mode?", "Publisher confirms for message delivery guarantee"),
    ("System Design", "What is the RabbitMQ dead letter queue?", "Queue for undelivered messages"),
    ("System Design", "What is the Amazon SQS?", "Managed message queue service"),
    ("System Design", "What is the Amazon SNS?", "Managed pub/sub notification service"),
    ("System Design", "What is the Google Pub/Sub?", "Managed message and event ingestion service"),
    ("System Design", "What is the Azure Service Bus?", "Managed enterprise message broker"),
    ("System Design", "What is the NATS messaging system?", "High-performance messaging for cloud-native apps"),
    ("System Design", "What is the Pulsar messaging system?", "Multi-tenant, high-throughput messaging platform"),
    ("System Design", "What is the Redis Streams?", "Append-only log data structure in Redis"),
    ("System Design", "What is the Redis Pub/Sub?", "Simple publish/subscribe messaging in Redis"),
    ("System Design", "What is the Redis as cache?", "In-memory cache with eviction policies"),
    ("System Design", "What is the Redis persistence options?", "RDB snapshots and AOF append-only log"),
    ("System Design", "What is the Redis sentinel?", "High availability for Redis"),
    ("System Design", "What is the Redis cluster?", "Automatic sharding and replication in Redis"),
    ("System Design", "What is the Memcached vs Redis?", "Memcached: simple cache; Redis: data structure server"),
    ("System Design", "What is the Content Delivery Network (CDN)?", "Edge servers caching static content"),
    ("System Design", "What is the CDN cache hit ratio?", "Percentage of requests served from edge cache"),
    ("System Design", "What is the CDN origin pull?", "CDN fetches content from origin on cache miss"),
    ("System Design", "What is the CDN edge push?", "Content proactively pushed to edge servers"),
    ("System Design", "What is the CloudFront?", "AWS CDN service"),
    ("System Design", "What is the CloudFlare?", "CDN and DDoS protection service"),
    ("System Design", "What is the Akamai CDN?", "Large-scale CDN with edge computing"),
    ("System Design", "What is the Blue-Green deployment?", "Two identical environments for zero-downtime deployment"),
    ("System Design", "What is the Canary deployment?", "Gradual rollout to small subset of users"),
    ("System Design", "What is the Rolling deployment?", "Gradually replacing instances"),
    ("System Design", "What is the A/B testing?", "Comparing two versions of app with user segments"),
    ("System Design", "What is the Feature flags?", "Toggle features on/off without deployment"),
    ("System Design", "What is the LaunchDarkly?", "Feature flag management platform"),
    ("System Design", "What is the dark launch?", "Releasing feature to production without user visibility"),
    ("System Design", "What is the Chaos engineering?", "Deliberately introducing failures to test resilience"),
    ("System Design", "What is the Chaos Monkey?", "Netflix tool that randomly terminates instances"),
    ("System Design", "What is the Litmus tool?", "Cloud-native chaos engineering framework"),
    ("System Design", "What is the Gremlin platform?", "Chaos engineering as a service"),
    ("System Design", "What is the Chaos Mesh?", "Kubernetes-native chaos engineering platform"),
    ("System Design", "What is the circuit breaker metrics?", "Monitoring open/closed/half-open state"),
    ("System Design", "What is the retry with exponential backoff?", "Increasing delay between retries"),
    ("System Design", "What is the jitter in retries?", "Randomizing retry intervals to avoid thundering herd"),
    ("System Design", "What is the timeout pattern?", "Maximum wait time for operation completion"),
    ("System Design", "What is the deadline pattern?", "Absolute time limit for operation"),
    ("System Design", "What is the graceful degradation?", "Reducing functionality instead of full failure"),
    ("System Design", "What is the graceful shutdown?", "Completing in-flight requests before stopping"),
    ("System Design", "What is the health check types?", "Liveness: is alive; Readiness: can serve traffic"),
    ("System Design", "What is the liveness probe?", "Checks if container is running"),
    ("System Design", "What is the readiness probe?", "Checks if container can accept traffic"),
    ("System Design", "What is the startup probe?", "Checks if container has started up"),
    ("System Design", "What is the Kubernetes pod lifecycle?", "Pending, Running, Succeeded, Failed, Unknown"),
    ("System Design", "What is the Kubernetes node?", "A machine in the cluster running pods"),
    ("System Design", "What is the Kubernetes cluster?", "Set of nodes managed by control plane"),
    ("System Design", "What is the Kubernetes control plane?", "Manages cluster: API server, scheduler, controller manager, etcd"),
    ("System Design", "What is the kube-apiserver?", "Kubernetes API entry point"),
    ("System Design", "What is the kube-scheduler?", "Assigns pods to nodes"),
    ("System Design", "What is the kube-controller-manager?", "Runs controller processes"),
    ("System Design", "What is the etcd in Kubernetes?", "Distributed key-value store for cluster state"),
    ("System Design", "What is the kubelet?", "Node agent managing pods"),
    ("System Design", "What is the kube-proxy?", "Network proxy on each node"),
    ("System Design", "What is the Kubernetes ReplicaSet?", "Ensures desired number of pod replicas"),
    ("System Design", "What is the Kubernetes DaemonSet?", "Runs pod on every node"),
    ("System Design", "What is the Kubernetes StatefulSet?", "Stateful application with stable identity"),
    ("System Design", "What is the Kubernetes Job?", "Runs pod to completion"),
    ("System Design", "What is the Kubernetes CronJob?", "Scheduled job execution"),
    ("System Design", "What is the Kubernetes persistent volume?", "Storage resource in the cluster"),
    ("System Design", "What is the Kubernetes persistent volume claim?", "Storage request by a pod"),
    ("System Design", "What is the Kubernetes storage class?", "Storage provisioning and policy"),
    ("System Design", "What is the Kubernetes Horizontal Pod Autoscaler?", "Scales pods based on metrics"),
    ("System Design", "What is the Kubernetes Vertical Pod Autoscaler?", "Adjusts pod resource requests"),
    ("System Design", "What is the Kubernetes cluster autoscaler?", "Adjusts cluster node count"),
    ("System Design", "What is the Helm package manager?", "Kubernetes package manager with charts"),
    ("System Design", "What is the Helm chart?", "Package of Kubernetes manifests"),
    ("System Design", "What is the Kustomize tool?", "Native Kubernetes configuration customization"),
    ("System Design", "What is the Istio architecture?", "Data plane (Envoy) and control plane (Pilot, Mixer, Citadel)"),
    ("System Design", "What is the Envoy proxy?", "High-performance sidecar proxy"),
    ("System Design", "What is the service mesh traffic management?", "Routing, retries, timeouts, circuit breaking"),
    ("System Design", "What is the service mesh security?", "mTLS, authorization policies"),
    ("System Design", "What is the service mesh observability?", "Metrics, logs, traces from mesh"),
    ("System Design", "What is the Linkerd service mesh?", "Lightweight service mesh for Kubernetes"),
    ("System Design", "What is the Consul service mesh?", "Service mesh from HashiCorp"),
    ("System Design", "What is the NGINX ingress controller?", "Kubernetes ingress with NGINX"),
    ("System Design", "What is the Traefik ingress controller?", "Dynamic reverse proxy and ingress"),
    ("System Design", "What is the HAProxy?", "High-performance TCP/HTTP load balancer"),
    ("System Design", "What is the AWS ALB (Application Load Balancer)?", "Layer 7 load balancer with path routing"),
    ("System Design", "What is the AWS NLB (Network Load Balancer)?", "Layer 4 load balancer for extreme performance"),
    ("System Design", "What is the AWS ELB (Elastic Load Balancer)?", "AWS managed load balancer service"),
    ("System Design", "What is the GCP Cloud Load Balancing?", "Google's global load balancing service"),
    ("System Design", "What is the Azure Load Balancer?", "Azure's layer 4 load balancer"),
    ("System Design", "What is the Azure Application Gateway?", "Azure's layer 7 load balancer with WAF"),
    ("System Design", "What is the DNS round-robin?", "Simple load balancing via multiple A records"),
    ("System Design", "What is the GeoDNS?", "DNS resolution based on client location"),
    ("System Design", "What is the Anycast routing?", "Multiple servers share same IP, routed to nearest"),
    ("System Design", "What is the split DNS?", "Different DNS responses for internal vs external"),
    ("System Design", "What is the private DNS?", "DNS resolution for internal network"),
    ("System Design", "What is the mTLS (Mutual TLS)?", "Both client and server authenticate via certificates"),
    ("System Design", "What is the Let's Encrypt?", "Free automated certificate authority"),
    ("System Design", "What is the ACME protocol?", "Automated Certificate Management Environment"),
    ("System Design", "What is the certificate rotation?", "Replacing certificates before expiry"),
    ("System Design", "What is the certificate pinning?", "Associating host with expected certificate"),
    ("System Design", "What is the OAuth 2.0 grant types?", "Authorization Code, Implicit, Client Credentials, ROPC"),
    ("System Design", "What is the OAuth 2.0 Authorization Code flow?", "Most secure flow with authorization code"),
    ("System Design", "What is the OAuth 2.0 PKCE extension?", "Proof Key for Code Exchange for public clients"),
    ("System Design", "What is the OAuth 2.0 refresh token?", "Token to obtain new access tokens without re-authentication"),
    ("System Design", "What is the OpenID Connect (OIDC)?", "Identity layer on top of OAuth 2.0"),
    ("System Design", "What is the SAML vs OAuth?", "SAML: enterprise SSO with XML; OAuth: delegated access with JSON"),
    ("System Design", "What is the LDAP protocol?", "Lightweight Directory Access Protocol"),
    ("System Design", "What is the Active Directory?", "Microsoft's directory service with LDAP and Kerberos"),
    ("System Design", "What is the Kerberos authentication?", "Network authentication using tickets"),
    ("System Design", "What is the biometric authentication?", "Authentication using fingerprints, face, or voice"),
    ("System Design", "What is the MFA (Multi-Factor Authentication)?", "Multiple authentication factors for security"),
    ("System Design", "What is the TOTP (Time-based One-Time Password)?", "Time-synchronized one-time passwords"),
    ("System Design", "What is the HOTP (HMAC-based One-Time Password)?", "Counter-based one-time passwords"),
    ("System Design", "What is the WebAuthn standard?", "Passwordless authentication with public key cryptography"),
    ("System Design", "What is the FIDO2 standard?", "Passwordless authentication framework"),
    ("System Design", "What is the passkeys?", "Device-based FIDO2 credentials for passwordless auth"),
    ("System Design", "What is the RBAC (Role-Based Access Control)?", "Permissions assigned to roles, roles to users"),
    ("System Design", "What is the ABAC (Attribute-Based Access Control)?", "Access based on user, resource, and environment attributes"),
    ("System Design", "What is the ACL (Access Control List)?", "List of permissions attached to an object"),
    ("System Design", "What is the encryption at rest?", "Encrypting stored data"),
    ("System Design", "What is the encryption in transit?", "Encrypting data during transmission (TLS)"),
    ("System Design", "What is the encryption in use?", "Encrypting data during processing"),
    ("System Design", "What is the envelope encryption?", "Encrypting data key with master key"),
    ("System Design", "What is the KMS (Key Management Service)?", "Managed key storage and rotation"),
    ("System Design", "What is the HSM (Hardware Security Module)?", "Hardware device for key management"),
    ("System Design", "What is the Vault by HashiCorp?", "Secret management and encryption service"),
    ("System Design", "What is the AWS KMS?", "AWS managed key management service"),
    ("System Design", "What is the GCP Cloud KMS?", "Google's key management service"),
    ("System Design", "What is the Azure Key Vault?", "Azure's secret and key management service"),
    ("System Design", "What is the SOC 2 compliance?", "Service Organization Control for security and availability"),
    ("System Design", "What is the PCI DSS compliance?", "Payment Card Industry Data Security Standard"),
    ("System Design", "What is the HIPAA compliance?", "Health data privacy and security standard"),
    ("System Design", "What is the GDPR compliance?", "EU data protection and privacy regulation"),
    ("System Design", "What is the ISO 27001?", "Information security management standard"),
    ("System Design", "What is the penetration testing?", "Simulated attacks to find security vulnerabilities"),
    ("System Design", "What is the SAST (Static Application Security Testing)?", "Source code security analysis"),
    ("System Design", "What is the DAST (Dynamic Application Security Testing)?", "Runtime application security testing"),
    ("System Design", "What is the dependency scanning?", "Checking dependencies for known vulnerabilities"),
    ("System Design", "What is the container scanning?", "Scanning container images for vulnerabilities"),
    ("System Design", "What is the SBOM (Software Bill of Materials)?", "Inventory of software components and dependencies"),
    ("System Design", "What is the WAF (Web Application Firewall)?", "Filters malicious HTTP traffic"),
    ("System Design", "What is the DDoS mitigation?", "Protecting against distributed denial of service attacks"),
    ("System Design", "What is the rate limiting at API gateway?", "Limiting requests per client at edge"),
    ("System Design", "What is the API key authentication?", "Simple API key in header for service identification"),
    ("System Design", "What is the HMAC authentication?", "Signed requests using hash-based message authentication"),
    ("System Design", "What is the basic authentication?", "Base64-encoded username:password in Authorization header"),
    ("System Design", "What is the digest authentication?", "Challenge-response authentication with MD5 hash"),
    ("System Design", "What is the IP whitelisting?", "Allowing access only from specific IP addresses"),
    ("System Design", "What is the IP blacklisting?", "Blocking access from specific IP addresses"),
    ("System Design", "What is the Geo-blocking?", "Restricting access based on geographic location"),
    ("System Design", "What is the virtual private cloud (VPC)?", "Isolated private network in cloud"),
    ("System Design", "What is the subnet in VPC?", "IP address range within VPC"),
    ("System Design", "What is the security group?", "Stateful firewall for AWS resources"),
    ("System Design", "What is the NACL (Network ACL)?", "Stateless firewall at subnet level"),
    ("System Design", "What is the VPN (Virtual Private Network)?", "Encrypted tunnel to private network"),
    ("System Design", "What is the site-to-site VPN?", "VPN connecting two networks"),
    ("System Design", "What is the client VPN?", "VPN for individual client devices"),
    ("System Design", "What is the Direct Connect?", "Dedicated network connection to AWS"),
    ("System Design", "What is the ExpressRoute?", "Azure dedicated network connection"),
    ("System Design", "What is the Cloud Interconnect?", "Google dedicated network connection"),
    ("System Design", "What is the Bastion host?", "Jump server for accessing private network"),
    ("System Design", "What is the zero trust security?", "Never trust, always verify access principle"),
    ("System Design", "What is the BeyondCorp?", "Google's zero trust access framework"),
    ("System Design", "What is the Zero Trust Network Access (ZTNA)?", "Remote access with zero trust principles"),
    ("System Design", "What is the WebAssembly (Wasm)?", "Binary instruction format for browser and server"),
    ("System Design", "What is the WebAssembly System Interface (WASI)?", "System interface for Wasm outside browser"),
    ("System Design", "What is the edge computing?", "Processing data near the source instead of cloud"),
    ("System Design", "What is the AWS Lambda@Edge?", "Lambda functions at CloudFront edge locations"),
    ("System Design", "What is the Cloudflare Workers?", "JavaScript execution at Cloudflare edge"),
    ("System Design", "What is the Vercel Edge Functions?", "Edge computing on Vercel platform"),
    ("System Design", "What is the Deno Deploy?", "Edge computing platform for Deno"),
    ("System Design", "What is the Fastly Compute@Edge?", "Edge computing platform on Fastly"),
    ("System Design", "What is the serverless framework?", "Framework for building serverless applications"),
    ("System Design", "What is the AWS SAM?", "Serverless Application Model for AWS"),
    ("System Design", "What is the Serverless Framework (serverless.com)?", "Multi-cloud serverless framework"),
    ("System Design", "What is the AWS Step Functions?", "Workflow orchestration for serverless"),
    ("System Design", "What is the AWS EventBridge?", "Event bus for serverless event-driven architectures"),
    ("System Design", "What is the AWS SQS Lambda trigger?", "Lambda invoked by SQS messages"),
    ("System Design", "What is the AWS SNS Lambda trigger?", "Lambda invoked by SNS notifications"),
    ("System Design", "What is the DynamoDB Streams Lambda trigger?", "Lambda invoked by DynamoDB changes"),
    ("System Design", "What is the S3 Event Lambda trigger?", "Lambda invoked by S3 events"),
    ("System Design", "What is the cold start in Lambda?", "Delay when Lambda instance is created"),
    ("System Design", "What is the Lambda warm start?", "Reusing existing Lambda instance"),
    ("System Design", "What is the Lambda provisioned concurrency?", "Pre-warmed Lambda instances"),
    ("System Design", "What is the Lambda reserved concurrency?", "Guaranteed concurrency for function"),
    ("System Design", "What is the Lambda layer?", "Shared code and dependencies for Lambda"),
    ("System Design", "What is the Lambda environment variables?", "Configuration via encrypted environment variables"),
    ("System Design", "What is the Lambda function URL?", "HTTPS endpoint for Lambda function"),
    ("System Design", "What is the Lambda destination?", "Async invocation result routing"),
    ("System Design", "What is the Lambda SnapStart?", "Faster cold starts with snapshot restore"),
    ("System Design", "What is the API Gateway REST API?", "RESTful API creation and management"),
    ("System Design", "What is the API Gateway HTTP API?", "Low-cost API Gateway option"),
    ("System Design", "What is the API Gateway WebSocket API?", "WebSocket API management"),
    ("System Design", "What is the API Gateway caching?", "Response caching at API level"),
    ("System Design", "What is the API Gateway throttling?", "Rate limiting at API level"),
    ("System Design", "What is the API Gateway usage plan?", "API access tiers and quotas"),
    ("System Design", "What is the API Gateway Lambda authorizer?", "Custom authorization with Lambda"),
    ("System Design", "What is the API Gateway Cognito authorizer?", "Auth with Amazon Cognito"),
    ("System Design", "What is the Cognito user pool?", "User directory for authentication"),
    ("System Design", "What is the Cognito identity pool?", "AWS credentials for authenticated users"),
    ("System Design", "What is the Cognito OIDC identity provider?", "Federated identity with OIDC"),
    ("System Design", "What is the Amazon DynamoDB?", "Managed NoSQL key-value and document database"),
    ("System Design", "What is the DynamoDB partition key?", "Hash key for data distribution"),
    ("System Design", "What is the DynamoDB sort key?", "Range key for ordering within partition"),
    ("System Design", "What is the DynamoDB secondary index?", "Alternate query patterns with GSI or LSI"),
    ("System Design", "What is the DynamoDB GSI (Global Secondary Index)?", "Index with different partition key"),
    ("System Design", "What is the DynamoDB LSI (Local Secondary Index)?", "Index with same partition, different sort key"),
    ("System Design", "What is the DynamoDB auto-scaling?", "Automatic throughput adjustment"),
    ("System Design", "What is the DynamoDB on-demand mode?", "Pay-per-request without capacity planning"),
    ("System Design", "What is the DynamoDB DAX (Accelerator)?", "In-memory cache for DynamoDB"),
    ("System Design", "What is the DynamoDB Transactions?", "ACID transactions across tables"),
    ("System Design", "What is the DynamoDB TTL?", "Automatic item expiration after timestamp"),
    ("System Design", "What is the DynamoDB streams?", "Time-ordered item change log"),
    ("System Design", "What is the DynamoDB single-table design?", "Multiple entities in one table for performance"),
    ("System Design", "What is the Amazon RDS?", "Managed relational database service"),
    ("System Design", "What is the Amazon Aurora?", "MySQL/PostgreSQL-compatible cloud database"),
    ("System Design", "What is the Aurora Serverless?", "Auto-scaling Aurora database"),
    ("System Design", "What is the Amazon ElastiCache?", "Managed Redis and Memcached"),
    ("System Design", "What is the Amazon OpenSearch?", "Managed Elasticsearch service"),
    ("System Design", "What is the Amazon MQ?", "Managed ActiveMQ and RabbitMQ"),
    ("System Design", "What is the MSK (Amazon Managed Streaming for Kafka)?", "Managed Apache Kafka service"),
    ("System Design", "What is the AWS CloudFormation?", "Infrastructure as Code with templates"),
    ("System Design", "What is the AWS CDK (Cloud Development Kit)?", "Infrastructure as Code with programming languages"),
    ("System Design", "What is the Pulumi tool?", "Infrastructure as Code with real languages"),
    ("System Design", "What is the Crossplane tool?", "Control plane for managing cloud resources"),
    ("System Design", "What is the ArgoCD tool?", "GitOps continuous delivery for Kubernetes"),
    ("System Design", "What is the Flux CD tool?", "GitOps operator for Kubernetes"),
    ("System Design", "What is the Spinnaker tool?", "Multi-cloud continuous delivery platform"),
    ("System Design", "What is the Harness platform?", "CI/CD platform with AI-driven deployments"),
    ("System Design", "What is the GitOps workflow?", "Git as single source of truth for infrastructure"),
    ("System Design", "What is the Infrastructure as Code (IaC)?", "Managing infrastructure through code"),
    ("System Design", "What is the immutable infrastructure?", "Replacing rather than modifying servers"),
    ("System Design", "What is the cattle vs pets analogy?", "Servers as disposable cattle vs unique pets"),
    ("System Design", "What is the Phoenix server pattern?", "Regularly recreating servers"),
    ("System Design", "What is the configuration drift?", "Servers deviating from desired state"),
    ("System Design", "What is the idempotent provisioning?", "Multiple runs produce same state"),
    ("System Design", "What is the declarative vs imperative IaC?", "Declarative: desired state; Imperative: step-by-step"),
    ("System Design", "What is the Terraform state file?", "Tracks managed resource state"),
    ("System Design", "What is the Terraform remote state?", "State stored in shared backend like S3"),
    ("System Design", "What is the Terraform module?", "Reusable infrastructure configuration"),
    ("System Design", "What is the Terraform provider?", "Plugin for interacting with cloud APIs"),
    ("System Design", "What is the Terraform workspace?", "Isolated environments in Terraform"),
    ("System Design", "What is the Terraform plan?", "Preview of changes before applying"),
    ("System Design", "What is the Terraform apply?", "Applies changes to infrastructure"),
    ("System Design", "What is the Terraform destroy?", "Destroys managed infrastructure"),
    ("System Design", "What is the AWS Organizations?", "Central management for multiple AWS accounts"),
    ("System Design", "What is the AWS Control Tower?", "Automated multi-account AWS setup"),
    ("System Design", "What is the AWS Landing Zone?", "Best-practice multi-account foundation"),
    ("System Design", "What is the AWS Well-Architected Framework?", "Five pillars: operational excellence, security, reliability, performance efficiency, cost optimization"),
    ("System Design", "What is the cost optimization pillar?", "Efficient resource usage and cost management"),
    ("System Design", "What is the operational excellence pillar?", "Running and monitoring systems for business value"),
    ("System Design", "What is the reliability pillar?", "System recovery from failures and demand scaling"),
    ("System Design", "What is the performance efficiency pillar?", "Using resources efficiently for requirements"),
    ("System Design", "What is the security pillar?", "Protecting data and systems"),
    ("System Design", "What is the sustainability pillar?", "Minimizing environmental impact of cloud workloads"),
    ("System Design", "What is the Google Cloud Architecture Framework?", "Six pillars for GCP best practices"),
    ("System Design", "What is the Azure Well-Architected Framework?", "Five pillars for Azure best practices"),
    ("System Design", "What is the TOGAF framework?", "Enterprise architecture methodology"),
    ("System Design", "What is the Zachman framework?", "Enterprise architecture ontology framework"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 13 added {len(new)} questions.")