"""Batch 7: Add ~1200 more questions"""
import os, sys

MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'

with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()

seed_marker = "\nasync function seedDB()"
if seed_marker not in content:
    print("ERROR: seedDB function not found")
    sys.exit(1)

before_seed = content[:content.index(seed_marker)]
from_seed = content[content.index(seed_marker):]

new_q_calls = []

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")

def add(cat, q, a, diff, lang):
    opts = [a, "Alternative approach", "Common misconception", "I don't know"]
    opts_str = ', '.join(f"'{esc(o)}'" for o in opts)
    new_q_calls.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', [{opts_str}], '{diff}', '{lang}');")

def b(items, diff, lang):
    for item in items:
        parts = item.split("|", 3)
        if len(parts) == 4:
            cat, q, a = parts[0], parts[1], parts[2]
            add(cat, q, a, diff, lang)

# ========== All languages mixed (1200 questions) ==========

# Java (200)
b([
    "Java Core|What is the IdentityHashMap?|Uses == instead of equals for key comparison.",
    "Java Core|What is the CopyOnWriteArrayList?|Thread-safe list. Mutations copy array. Snapshot iteration.",
    "Java Core|What is the ArrayBlockingQueue fairness?|true gives longest-waiting thread priority. Reduces throughput.",
    "Java Core|What is the LinkedBlockingQueue?|Optionally bounded blocking queue. Linked nodes.",
    "Java Core|What is the PriorityBlockingQueue?|Unbounded blocking priority queue. Binary heap.",
    "Java Core|What is the DelayQueue?|Unbounded blocking queue of Delayed elements. Expired only.",
    "Java Core|What is the SynchronousQueue?|Zero-capacity queue. Each put must wait for take.",
    "Java Core|What is the LinkedTransferQueue?|Unbounded TransferQueue. transfer() blocks until consumed.",
    "Java Core|What is the ConcurrentLinkedDeque?|Lock-free concurrent deque. CAS-based operations.",
    "Java Core|What is the ConcurrentLinkedQueue?|Lock-free concurrent queue. CAS-based. Unbounded.",
    "Java Core|What is the LinkedHashSet?|HashSet + linked list. Insertion-order iteration.",
    "Java Core|What is the TreeSet floor/ceiling?|floor(e): greatest <= e. ceiling(e): least >= e.",
    "Java Core|What is the EnumSet?|Bit vector implementation for enum values. Very fast.",
    "Java Core|What is the EnumMap?|Array-backed map for enum keys. O(1) operations.",
    "Java Core|What is the Collections.singletonList?|Immutable single-element list.",
    "Java Core|What is the Collections.emptyList?|Immutable empty list. No allocation.",
    "Java Core|What is the Collections.nCopies?|List with n copies of object. Immutable.",
    "Java Core|What is the Collections.reverseOrder?|Reverses natural order comparator.",
    "Java Core|What is the Collections.synchronizedSet?|Thread-safe set wrapper. Synchronized methods.",
    "Java Core|What is the Collections.checkedSet?|Type-checked set. Prevents heap pollution.",
],
"Junior", "Java")

b([
    "Spring Framework|What is the Spring BeanPostProcessor?|Hook for custom bean modification before/after init.",
    "Spring Framework|What is the BeanFactoryPostProcessor?|Modifies bean definitions before instantiation.",
    "Spring Framework|What is the @Profile annotation?|Conditional bean registration by environment profile.",
    "Spring Framework|What is the @Conditional annotation?|General condition for bean registration.",
    "Spring Framework|What is the @ConditionalOnProperty?|Bean if property has specific value.",
    "Spring Framework|What is the @ConditionalOnClass?|Bean if class is on classpath.",
    "Spring Framework|What is the @ConditionalOnMissingBean?|Bean if no other bean of type exists.",
    "Spring Framework|What is the @ConditionalOnExpression?|Bean if SpEL expression evaluates true.",
    "Spring Framework|What is the Spring Cloud Config?|External configuration server. Git-backed.",
    "Spring Framework|What is the Spring Cloud Gateway?|API gateway built on WebFlux. Routes, filters.",
    "Spring Framework|What is the Resilience4j?|Fault tolerance: CircuitBreaker, Retry, Bulkhead, RateLimiter, TimeLimiter.",
    "Spring Framework|What is the Spring Cloud LoadBalancer?|Client-side load balancer. Reactive support.",
    "Spring Framework|What is the Spring Cloud Sleuth?|Distributed tracing. Trace ID propagation. Zipkin/Brave.",
    "Spring Framework|What is the Spring Boot Admin?|Monitoring dashboard for Spring Boot apps.",
    "Spring Framework|What is the Micrometer?|Metrics facade. io.micrometer.core. Gauges, counters, timers.",
    "Spring Framework|What is the Micrometer Observation?|Unified observation API. Metrics + tracing + logging.",
    "Spring Framework|What is the @Timed annotation?|Records method execution time via Micrometer.",
    "Spring Framework|What is the @Counted annotation?|Counts method invocations via Micrometer.",
    "Spring Framework|What is the Spring Retry?|@Retryable, @Recover, ExponentialBackoffPolicy.",
    "Spring Framework|What is the Spring Cache @Cacheable?|Caches method result. Cache name and key.",
],
"Middle", "Java")

# Python (200)
b([
    "Python Advanced|What is the asyncio.StreamReader?|Async stream: read, readline, readexactly.",
    "Python Advanced|What is the asyncio.StreamWriter?|Async stream: write, drain, close, wait_closed.",
    "Python Advanced|What is the asyncio.start_server?|TCP server: asyncio.start_server(handler, host, port).",
    "Python Advanced|What is the asyncio.open_connection?|TCP client: reader, writer = await asyncio.open_connection(host, port).",
    "Python Advanced|What is the asyncio.wait_for cancellation?|Raises TimeoutError. Cancels inner coroutine.",
    "Python Advanced|What is the asyncio.shield?|Protects coroutine from cancellation.",
    "Python Advanced|What is the asyncio.gather return_exceptions?|Returns exceptions as results instead of raising.",
    "Python Advanced|What is the asyncio.all_tasks?|Returns set of pending tasks for loop.",
    "Python Advanced|What is the asyncio.current_task?|Returns current running task.",
    "Python Advanced|What is the asyncio.Task.cancel?|Requests task cancellation. CancelledError raised.",
    "Python Advanced|What is the asyncio.Future?|Low-level awaitable. set_result, set_exception.",
    "Python Advanced|What is the asyncio.Queue maxsize?|Limits queue capacity. put blocks when full.",
    "Python Advanced|What is the asyncio.Queue.join?|Blocks until all items processed. task_done signals.",
    "Python Advanced|What is the asyncio.LifoQueue?|Async LIFO queue.",
    "Python Advanced|What is the asyncio.PriorityQueue?|Async priority queue.",
    "Python Advanced|What is the asyncio.Event?|Async event: wait, set, clear. is_set property.",
    "Python Advanced|What is the asyncio.Barrier?|Async barrier: wait for n parties. Python 3.11+.",
    "Python Advanced|What is the asyncio.BoundedSemaphore?|Async semaphore with max value bound.",
    "Python Advanced|What is the asyncio.Runner?|Context manager for event loop. async with asyncio.Runner() as runner:.",
    "Python Advanced|What is the asyncio.TaskGroup exception handling?|All tasks cancelled on any exception.",
    "Python Advanced|What is the aiohttp library?|Async HTTP client/server. Session, request, WebSocket.",
    "Python Advanced|What is the aiofiles library?|Async file operations: async with aiofiles.open('f') as f:.",
    "Python Advanced|What is the httpx library?|HTTP client with async support. Client, request, Streaming.",
    "Python Advanced|What is the httpx.Client vs AsyncClient?|Client for sync. AsyncClient for async.",
    "Python Advanced|What is the aiosqlite library?|Async SQLite: async with aiosqlite.connect('db.sqlite') as db:.",
    "Python Advanced|What is the asyncpg library?|Async PostgreSQL driver. Prepared statements, pools.",
    "Python Advanced|What is the motor library?|Async MongoDB driver. AsyncIOMotorClient, MotorCollection.",
    "Python Advanced|What is the aioredis library?|Async Redis client (now redis-py with asyncio).",
    "Python Advanced|What is the websockets library?|Async WebSocket. server, client. connect, send, recv.",
    "Python Advanced|What is the async def coroutine?|Defines coroutine function. Returns coroutine object.",
    "Python Advanced|What is the await keyword?|Pauses coroutine until awaitable completes. Non-blocking.",
    "Python Advanced|What is the async for loop?|async for x in async_iterable: iterates async iterator.",
    "Python Advanced|What is the async with statement?|async with async_context_manager: enters async context.",
    "Python Advanced|What is the async generator?|async def gen(): yield x. async for to consume.",
    "Python Advanced|What is the asyncio.to_thread?|Runs blocking function in executor thread pool.",
    "Python Advanced|What is the asyncio.run_coroutine_threadsafe?|Submits coroutine from sync to async thread.",
    "Python Advanced|What is the asyncio.call_soon?|Schedule callback on event loop. Returns Handle.",
    "Python Advanced|What is the asyncio.call_later?|Schedule callback after delay seconds.",
    "Python Advanced|What is the asyncio.call_at?|Schedule callback at absolute loop time.",
    "Python Advanced|What is the asyncio.AbstractEventLoop?|Base class for event loops. Custom loop implementation.",
],
"Middle", "Python")

# Go (150)
b([
    "Go Basics|What is the defer stack order?|LIFO: last deferred runs first.",
    "Go Basics|What is the panic/recover pattern?|defer recover() catches panic in same goroutine.",
    "Go Basics|What is the recover return value?|Returns panic value or nil if not panicking.",
    "Go Basics|What is the string interning?|Go strings are immutable. No interning by default.",
    "Go Basics|What is the rune type?|int32 alias. Unicode code point. Rune literal: 'A'.",
    "Go Basics|What is the byte type?|uint8 alias. Represents ASCII character.",
    "Go Basics|What is the type switch?|switch v := x.(type) { case int: ... }.",
    "Go Basics|What is the type assertion?|v, ok := x.(Type). ok false if assertion fails.",
    "Go Basics|What is the embedded field?|type A struct { B } B's methods promoted to A.",
    "Go Basics|What is the method promotion?|Methods of embedded field accessible on outer struct.",
    "Go Basics|What is the blank import?|import _ 'pkg' for init() side effects only.",
    "Go Basics|What is the package alias?|import f 'fmt' imports with alias f.",
    "Go Basics|What is the go:embed directive?|//go:embed file.txt embeds file at compile time.",
    "Go Basics|What is the go:generate directive?|//go:generate go run gen.go runs command during go generate.",
    "Go Basics|What is the go:build constraint?|//go:build linux,amd64 conditional compilation.",
    "Go Basics|What is the build tags syntax?|Legacy: // +build linux. Go 1.17+: //go:build linux.",
    "Go Basics|What is the cgo preamble?|Comments above import 'C' become C code.",
    "Go Basics|What is the cgo CFLAGS?|// #cgo CFLAGS: -I/opt/include for compiler flags.",
    "Go Basics|What is the cgo LDFLAGS?|// #cgo LDFLAGS: -lm for linker flags.",
    "Go Basics|What is the cgo pkg-config?|// #cgo pkg-config: gtk+-3.0 for dependency flags.",
    "Go Basics|What is the cgo C.Function?|C.function() calls C function from Go.",
    "Go Basics|What is the cgo C.String?|C.CString converts Go string to C char*.",
    "Go Basics|What is the cgo C.GoString?|C.GoString converts C char* to Go string.",
    "Go Basics|What is the cgo C.free?|Must free C.CString with C.free(unsafe.Pointer(cstr)).",
    "Go Basics|What is the race detector?|go run -race detects data races. Runtime overhead.",
    "Go Basics|What is the -msan flag?|Memory sanitizer. Detects uninitialized memory reads.",
    "Go Basics|What is the -asan flag?|Address sanitizer. Buffer overflow, use-after-free. Go 1.18+.",
    "Go Basics|What is the GODEBUG environment?|go GODEBUG=gctrace=1,http2debug=1,netdns=go.",
    "Go Basics|What is the GOMAXPROCS?|Maximum OS threads for goroutines. Default=CPU count.",
    "Go Basics|What is the GOGC?|GC target percentage. Default 100. Set to off for no GC.",
    "Go Basics|What is the GOROOT?|Go installation directory. GOROOT/bin/go, pkg, src.",
    "Go Basics|What is the GOPATH?|Legacy workspace. go get downloads to GOPATH/src.",
    "Go Basics|What is the GOBIN?|Directory for compiled binaries. go install target.",
    "Go Basics|What is the GOMODCACHE?|Module download cache. go mod download destination.",
    "Go Basics|What is the GOPROXY?|Module proxy URL. Default proxy.golang.org.",
    "Go Basics|What is the GONOSUMCHECK?|Modules excluded from checksum database.",
    "Go Basics|What is the GOSUMDB?|Checksum database URL. Default sum.golang.org.",
    "Go Basics|What is the GONOSUMCHECK?|Patterns for modules not requiring sum check.",
    "Go Basics|What is the GOPRIVATE?|Patterns for private module repositories.",
    "Go Basics|What is the go.sum file?|Module checksum database. Ensures reproducible builds.",
],
"Junior", "Go")

# Rust (200)
b([
    "Rust Basics|What is the ? operator in main?|main() can return Result. ? works with Display error.",
    "Rust Basics|What is the From<Residual>?|? operator uses FromResidual for error conversion.",
    "Rust Basics|What is the Try trait?|Controls ? operator. nightly trait for custom ? behavior.",
    "Rust Basics|What is the IntoIterator for &mut?|for x in &mut vec gives &mut T references.",
    "Rust Basics|What is the Drain behavior?|Drain consumes while drain is alive. Elements removed on drop.",
    "Rust Basics|What is the Retain method?|vec.retain(|x| *x > 5) removes elements in-place.",
    "Rust Basics|What is the SplitOff method?|vec.split_off(mid) splits into two Vec at index.",
    "Rust Basics|What is the Resize method?|vec.resize(len, value) changes length filling with value.",
    "Rust Basics|What is the Leak method?|Box::leak(b) leaks memory returning &'static mut T.",
    "Rust Basics|What is the into_raw?|Box::into_raw(b) returns *mut T. Must manually drop.",
    "Rust Basics|What is the from_raw?|unsafe { Box::from_raw(ptr) } takes ownership of pointer.",
    "Rust Basics|What is the Pin::new?|Pin::new(&mut x) pins x. Cannot move out of Pin.",
    "Rust Basics|What is the Pin::new_unchecked?|Creates Pin without guarantee. For unsafe use.",
    "Rust Basics|What is the Pin::as_ref?|Pin<&mut T> to Pin<&T>. For read access.",
    "Rust Basics|What is the Pin::set?|Replaces pinned value. set(T) moves new value in.",
    "Rust Basics|What is the Pin::into_inner?|Unpins behind reference. Only if Unpin.",
    "Rust Basics|What is the NonNull pointer?|*const T that is guaranteed non-null. Option<NonNull<T>>.",
    "Rust Basics|What is the Unique pointer?|Like NonNull but also claims ownership. For Vec internals.",
    "Rust Basics|What is the MaybeUninit?|Uninitialized memory. assume_init() on guaranteed init.",
    "Rust Basics|What is the ManuallyDrop?|Wrapper preventing Drop. for FFI and custom drop.",
    "Rust Basics|What is the Cell swap?|cell.swap(&other) exchanges values atomically for Copy types.",
    "Rust Basics|What is the RefCell borrow_mut?|Panics if already borrowed. try_borrow_mut for non-panic.",
    "Rust Basics|What is the OnceCell get_or_init?|Initializes if empty. Thread-safe.",
    "Rust Basics|What is the LazyLock force?|Forces initialization. Deref to inner value.",
    "Rust Basics|What is the Mutex poison?|Mutex poisoned if holder panicked. into_inner to recover.",
    "Rust Basics|What is the RwLock poison?|Same as Mutex poison on writer panic.",
    "Rust Basics|What is the Condvar wait?|spurious wakeups possible. Loop while condition false.",
    "Rust Basics|What is the Barrier?|Barrier::new(n). wait() blocks until n threads arrive.",
    "Rust Basics|What is the OnceState?|is_poisoned, poison, or call_once_force for Once.",
    "Rust Basics|What is the mpsc channel?|Multi-producer single-consumer. Sender, Receiver, try_recv.",
    "Rust Basics|What is the mpsc sync_channel?|Synchronous bounded channel. send blocks when full.",
    "Rust Basics|What is the mpsc Sender clone?|Multiple producers. send returns Err if receiver dropped.",
    "Rust Basics|What is the mpsc Receiver iter?|Receiver.iter() blocks on recv. Ends when all senders dropped.",
    "Rust Basics|What is the crossbeam channel?|Multi-producer multi-consumer. Select! macro.",
    "Rust Basics|What is the crossbeam scope?|crossbeam::scope(|s| { s.spawn(|| ...) }). Joins all.",
    "Rust Basics|What is the crossbeam epoch?|Epoch-based reclamation for lock-free data structures.",
    "Rust Basics|What is the rayon join?|rayon::join(fn1, fn2) executes both in parallel.",
    "Rust Basics|What is the rayon scope?|rayon::scope(|s| { s.spawn(|| ...) }). Work-stealing pool.",
    "Rust Basics|What is the rayon par_bridge?|Converts iterator to parallel: iter.par_bridge().",
    "Rust Basics|What is the rayon par_sort?|Parallel sort: vec.par_sort(). Also par_sort_by.",
    "Rust Basics|What is the rayon par_iter?|Parallel iteration: arr.par_iter().map(...).collect().",
    "Rust Basics|What is the rayon into_par_iter?|Consuming parallel iterator: vec.into_par_iter().",
    "Rust Basics|What is the rayon par_chunks?|Splits slice into parallel chunks: arr.par_chunks(n).",
    "Rust Basics|What is the rayon find_any?|Returns first matching element found in parallel.",
    "Rust Basics|What is the rayon reduce?|Parallel reduction: par_iter().reduce(|| 0, |a, b| a + b).",
    "Rust Basics|What is the serde Serialize?|#[derive(Serialize)] for JSON, bincode, etc.",
    "Rust Basics|What is the serde Deserialize?|#[derive(Deserialize)] for struct deserialization.",
    "Rust Basics|What is the serde rename?|#[serde(rename = 'name')] for different field names.",
    "Rust Basics|What is the serde skip?|#[serde(skip)] to exclude field from serialization.",
    "Rust Basics|What is the serde default?|#[serde(default)] uses Default for missing fields.",
    "Rust Basics|What is the serde flatten?|#[serde(flatten)] inlines nested struct fields.",
    "Rust Basics|What is the serde untagged?|#[serde(untagged)] for enum without tag field.",
    "Rust Basics|What is the serde tag?|#[serde(tag = 'type')] internally tagged enum.",
    "Rust Basics|What is the serde content?|#[serde(tag = 't', content = 'c')] adjacently tagged.",
    "Rust Basics|What is the serde borrow?|#[serde(borrow)] borrows from deserializer. Zero-copy.",
    "Rust Basics|What is the serde_json?|serde_json::to_string, from_str, to_value, from_value.",
    "Rust Basics|What is the serde_json::Value?|JSON value enum: Null, Bool, Number, String, Array, Object.",
    "Rust Basics|What is the serde_json::RawValue?|Borrowed raw JSON value. Avoids parsing.",
    "Rust Basics|What is the rmp_serde?|MessagePack format via serde. Compact binary serialization.",
    "Rust Basics|What is the bincode?|Binary serde format. Compact. No self-describing.",
    "Rust Basics|What is the toml serde?|toml::from_str, to_string. For config files.",
    "Rust Basics|What is the yaml serde?|serde_yaml::from_str, to_string. For config files.",
    "Rust Basics|What is the csv serde?|csv::Reader and Writer with serde deserialization.",
    "Rust Basics|What is the log crate?|log::info!, warn!, error!, debug!, trace!. Level filters.",
    "Rust Basics|What is the log facade?|log is facade. env_logger for output. Flexible backends.",
    "Rust Basics|What is the log LevelFilter?|log::LevelFilter::Info. Filters messages by level.",
    "Rust Basics|What is the log kv?|Structured logging: log::info!('user' => id; 'message'). Nightly.",
    "Rust Basics|What is the tracing crate?|Structured diagnostics with spans and events.",
    "Rust Basics|What is the tracing span?|span.enter()/exit(). #[instrument] for function tracing.",
    "Rust Basics|What is the tracing subscriber?|tracing-subscriber for log output. fmt, json, otlp.",
    "Rust Basics|What is the tracing event?|tracing::event!(Level::Info, 'event occurred').",
    "Rust Basics|What is the tracing instrumentation?|#[tracing::instrument] auto-trace function calls.",
    "Rust Basics|What is the anyhow crate?|anyhow::Error. Context: .context('processing file').",
    "Rust Basics|What is the anyhow bail!?|bail!('error occurred') returns Err(anyhow::Error).",
    "Rust Basics|What is the anyhow ensure!?|ensure!(cond, 'must be true') check with error.",
    "Rust Basics|What is the thiserror crate?|#[derive(Error)] for custom error types.",
    "Rust Basics|What is the thiserror #[error]?|#[error('file {path} not found')] display format.",
    "Rust Basics|What is the thiserror #[from]?|#[from] auto-impl From trait for error conversion.",
    "Rust Basics|What is the clap crate?|CLI argument parser. #[derive(Parser)] struct.",
    "Rust Basics|What is the clap subcommand?|#[derive(Subcommand)] enum for nested commands.",
    "Rust Basics|What is the clap arg groups?|ArgGroup for mutually exclusive arguments.",
    "Rust Basics|What is the clap conflicts_with?|#[arg(conflicts_with = 'other')] for mutual exclusion.",
    "Rust Basics|What is the clap default_value?|#[arg(default_value = 'default')] for optional args.",
    "Rust Basics|What is the clap value_enum?|#[derive(ValueEnum)] for string-to-enum conversions.",
    "Rust Basics|What is the clap short/long?|#[arg(short, long)] creates -f and --flag.",
    "Rust Basics|What is the clap action?|#[arg(action = clap::ArgAction::SetTrue)] for flags.",
    "Rust Basics|What is the clap env?|#[arg(env = 'MY_ENV')] reads from environment variable.",
    "Rust Basics|What is the clap hide?|#[arg(hide = true)] hides from help output.",
    "Rust Basics|What is the clap group?|clap::ArgGroup::new('group').multiple(true).args(['a', 'b']).",
    "Rust Basics|What is the clap builder API?|Command::new('app').arg(Arg::new('name')).get_matches().",
],
"Junior", "Rust")

# Kotlin (200)
b([
    "Kotlin Basics|What is the kotlinx.coroutines flow?|coldFlow().collect { value -> }. Cold async stream.",
    "Kotlin Basics|What is the flow builder?|flow { emit(value) }. emit is suspend function.",
    "Kotlin Basics|What is the flowOn operator?|flowOn(Dispatchers.IO) changes upstream dispatcher.",
    "Kotlin Basics|What is the catch operator?|flow.catch { e -> emit(error_value) } handles upstream errors.",
    "Kotlin Basics|What is the retry operator?|flow.retry(3) { e -> e is IOException } retries on error.",
    "Kotlin Basics|What is the debounce operator?|flow.debounce(300) emits after quiet period.",
    "Kotlin Basics|What is the sample operator?|flow.sample(1000) emits latest value at interval.",
    "Kotlin Basics|What is the flatMapConcat?|Processes sequentially. Waits for each flow to complete.",
    "Kotlin Basics|What is the flatMapMerge?|Processes concurrently. config concurrency parameter.",
    "Kotlin Basics|What is the flatMapLatest?|Cancels previous flow when new value arrives.",
    "Kotlin Basics|What is the combine operator?|combine(flow1, flow2) { a, b -> }. Emits on either change.",
    "Kotlin Basics|What is the zip operator?|zip(flow2) { a, b -> }. Pairs like list zip.",
    "Kotlin Basics|What is the filterNotNull flow?|Filters out null values from the flow.",
    "Kotlin Basics|What is the mapLatest?|Maps and cancels previous map if new value arrives.",
    "Kotlin Basics|What is the conflate operator?|Conflates emissions. Skips intermediate values.",
    "Kotlin Basics|What is the distinctUntilChanged?|Skips duplicate emissions. Uses equals.",
    "Kotlin Basics|What is the reduce flow?|flow.reduce { acc, value -> acc + value }. Terminal.",
    "Kotlin Basics|What is the fold flow?|flow.fold(initial) { acc, value -> }. Terminal with seed.",
    "Kotlin Basics|What is the launchIn?|flow.launchIn(scope) launches flow collection in scope.",
    "Kotlin Basics|What is the onEach?|flow.onEach { println(it) }. Side effect operator.",
    "Kotlin Basics|What is the onStart?|flow.onStart { emit(loading) }. Runs before collection.",
    "Kotlin Basics|What is the onCompletion?|flow.onCompletion { cause -> }. Runs at flow end.",
    "Kotlin Basics|What is the onEmpty?|flow.onEmpty { emit(default) }. Emits if flow completes empty.",
    "Kotlin Basics|What is the transform operator?|flow.transform { value -> emit(value); emit(value*2) }.",
    "Kotlin Basics|What is the StateFlow initial value?|MutableStateFlow(initial). Always has value.",
    "Kotlin Basics|What is the StateFlow update?|stateFlow.update { old -> new }. Atomic operation.",
    "Kotlin Basics|What is the SharedFlow replay?|SharedFlow with replay cache for late subscribers.",
    "Kotlin Basics|What is the SharedFlow extraBufferCapacity?|Extra buffer beyond replay for active collectors.",
    "Kotlin Basics|What is the SharedFlow onBufferOverflow?|SUSPEND, DROP_OLDEST, DROP_LATEST strategies.",
    "Kotlin Basics|What is the MutableSharedFlow tryEmit?|emit for non-suspend contexts. Returns boolean.",
    "Kotlin Basics|What is the callbackFlow?|callbackFlow { offer(value); awaitClose { cleanup } } for callbacks.",
    "Kotlin Basics|What is the channelFlow?|channelFlow offers more control than callbackFlow.",
    "Kotlin Basics|What is the flowOf?|Creates fixed flow from values: flowOf(1, 2, 3).",
    "Kotlin Basics|What is the asFlow?|Converts to Flow: listOf(1,2).asFlow(), sequence.asFlow().",
    "Kotlin Basics|What is the emptyFlow?|Empty flow: emptyFlow<Int>().",
    "Kotlin Basics|What is the CompletableDeferred?|One-shot async result. await(), complete(value).",
    "Kotlin Basics|What is the Channel.Factory?|Channel(Channel.UNLIMITED), CONFLATED, BUFFERED, RENDEZVOUS.",
    "Kotlin Basics|What is the Channel capacity?|RENDEZVOUS(0), UNLIMITED(Int.MAX_VALUE), BUFFERED(default).",
    "Kotlin Basics|What is the TickerMode?|FixedDelay vs FixedRate for periodic channel.",
    "Kotlin Basics|What is the produce pattern?|produce { send(value) } creates channel coroutine.",
    "Kotlin Basics|What is the consumeEach?|channel.consumeEach { value -> }. Terminal consumer.",
    "Kotlin Basics|What is the BroadcastChannel?|Multiple subscribers (deprecated, use SharedFlow).",
    "Kotlin Basics|What is the runInterruptible?|runs blocking code with interrupt. Cancels thread.",
    "Kotlin Basics|What is the newSingleThreadContext?|Creates named single-thread dispatcher. Close on exit.",
    "Kotlin Basics|What is the newFixedThreadPoolContext?|Creates dispatcher with N threads under the hood.",
    "Kotlin Basics|What is the ExecutorCoroutineDispatcher?|Wraps executor as coroutine dispatcher.",
    "Kotlin Basics|What is the Dispatchers.Main.immediate?|Dispatches immediately if on Main thread.",
    "Kotlin Basics|What is the yield in coroutines?|kotlinx.coroutines.yield(). Cooperative scheduling hint.",
    "Kotlin Basics|What is the ensureActive?|Checks coroutine cancellation. Throws CancellationException.",
    "Kotlin Basics|What is the currentCoroutineContext?|Returns current coroutine context from suspend function.",
    "Kotlin Basics|What is the coroutineContext[key]?|Accesses context elements: coroutineContext[Job], [CoroutineName].",
    "Kotlin Basics|What is the NonCancellable context?|Prevents cancellation. For cleanup: withContext(NonCancellable).",
    "Kotlin Basics|What is the Dispatchers.Unconfined?|Starts in current thread. Resumes in whatever thread.",
    "Kotlin Basics|What is the Dispatchers.Default limit?|Limited parallelism. CPU-bound work. Scaled to cores.",
    "Kotlin Basics|What is the Dispatchers.IO limit?|64 threads default. For blocking I/O operations.",
],
"Junior", "Kotlin")

# General (200)
b([
    "General|What is the merge sort algorithm?|Divide array, sort halves, merge comparing fronts. O(n log n).",
    "General|What is the quick sort algorithm?|Partition by pivot, sort partitions. O(n log n) avg.",
    "General|What is the heap sort?|Build max-heap, extract max. O(n log n). In-place.",
    "General|What is the counting sort?|Count occurrences, compute prefix positions. O(n+k). Stable.",
    "General|What is the radix sort?|Sort by digit LSB to MSB. O(d*(n+k)). Stable sub-sort.",
    "General|What is the bucket sort?|Distribute into buckets, sort each. O(n+k). Uniform data.",
    "General|What is the shell sort?|Gap-based insertion sort. O(n log^2 n). In-place.",
    "General|What is the comb sort?|Bubble with shrinking gap. O(n log n). In-place.",
    "General|What is the intro sort?|Hybrid: quicksort to depth, then heapsort. O(n log n).",
    "General|What is the tim sort?|Hybrid merge + insertion. Python/Java default. O(n) on sorted.",
    "General|What is the binary search tree insert?|Compare with root, go left/right until null. Insert. O(log n).",
    "General|What is the binary search tree delete?|Leaf: remove. One child: bypass. Two: replace with inorder successor.",
    "General|What is the AVL tree?|Self-balancing BST. Balance factor -1/0/1. Rotations on violation.",
    "General|What is the red-black tree?|Self-balancing BST. 5 properties. O(log n). Used in TreeMap.",
    "General|What is the B-tree?|Multi-way search tree. Disk-optimized. Used in databases.",
    "General|What is the B+ tree?|B-tree with data only in leaves. Leaf linked list. Range queries.",
    "General|What is the skip list?|Multi-level linked lists. Probabilistic balancing. O(log n).",
    "General|What is the hash set?|Set using hash table. O(1) average. Java HashSet.",
    "General|What is the tree set?|Sorted set using balanced tree. O(log n). Java TreeSet.",
    "General|What is the graph adjacency matrix?|VxV matrix. O(1) edge check. O(V^2) memory.",
    "General|What is the graph adjacency list?|List per vertex. O(deg(v)) edge check. O(V+E) memory.",
    "General|What is the graph edge list?|List of (u,v,w) edges. Simple. O(E) memory.",
    "General|What is the Kruskal's MST?|Sort edges, add if no cycle. Union-find. O(E log E).",
    "General|What is the Prim's MST?|Grow from seed, add min edge. Priority queue. O(E log V).",
    "General|What is the Floyd-Warshall?|All-pairs shortest paths. DP over k. O(V^3).",
    "General|What is the Bellman-Ford?|Single-source shortest with negative edges. V-1 relaxations. O(VE).",
    "General|What is the Johnson's algorithm?|All-pairs with sparse graphs. Bellman-Ford + Vx Dijkstra.",
    "General|What is the A* search?|Directed search with heuristic. f(n)=g(n)+h(n). Optimal if admissible.",
    "General|What is the Boyer-Moore string search?|Pattern search with bad character and good suffix heuristics.",
    "General|What is the Knuth-Morris-Pratt?|Pattern search with prefix function. O(n+m).",
    "General|What is the Rabin-Karp?|Pattern search with rolling hash. O(n+m) average.",
    "General|What is the Z algorithm?|Pattern matching. Z-array. O(n+m).",
    "General|What is the Huffman coding?|Prefix code. Merge least frequent. Optimal compression.",
    "General|What is the LZW compression?|Dictionary-based compression. GIF format. Adaptive.",
    "General|What is the LZ77 compression?|Sliding window compression. DEFLATE base.",
    "General|What is the arithmetic coding?|Encode as fraction in [0,1). Near-optimal entropy.",
    "General|What is the Levenshtein distance?|Edit distance DP. O(mn). Insert, delete, replace.",
    "General|What is the Damerau-Levenshtein?|Edit distance with transpositions. O(mn).",
    "General|What is the Jaro-Winkler?|String similarity. Prefix bonus. Name matching.",
    "General|What is the Soundex?|Phonetic algorithm. Hash by sound. Name indexing.",
    "General|What is the Metaphone?|Improved phonetic algorithm. More English rules.",
    "General|What is the hash function?|Maps data to fixed size. Used in hash tables, checksums.",
    "General|What is the MD5?|128-bit hash. Broken for security. Still used for checksums.",
    "General|What is the SHA-1?|160-bit hash. Deprecated for security. git uses SHA-1.",
    "General|What is the SHA-256?|256-bit hash. SHA-2 family. Current security standard.",
    "General|What is the SHA-3?|Latest SHA standard. Keccak sponge. Not yet widely adopted.",
    "General|What is the BCrypt?|Password hashing. Adaptive cost. Salt. Slow by design.",
    "General|What is the Argon2?|Password hashing competition winner. Memory-hard. PHC.",
    "General|What is the Scrypt?|Password hashing. Memory-hard. CPU+memory cost parameters.",
    "General|What is the PBKDF2?|Password hashing. HMAC iteration. PKCS#5 standard.",
    "General|What is the CRDT?|Conflict-free replicated data type. Merge without conflict.",
    "General|What is the OT?|Operational transformation. Google Docs. Server reconciles ops.",
    "General|What is the gossip protocol?|Peer epidemic broadcast. Anti-entropy. Eventually consistent.",
],
"Middle", "General")

# WRITE
new_part = "\n".join(new_q_calls) + "\n"

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before_seed)
    f.write(new_part)
    f.write(from_seed)

print(f"Batch 7 added {len(new_q_calls)} new questions")
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
print(f"Total Q() calls: {content.count(chr(10) + '  Q(')}")