"""Batch 15: ~2000 fresh questions in new topic areas (no repeats)"""
import json
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    opts = [a, 'Common misconception', 'Alternative approach', 'I don\'t know']
    # strict JSON verification
    obj = {"category": cat, "question": q, "short_answer": a, "options": opts, "difficulty": diff, "language": lang}
    json.dumps(obj, ensure_ascii=False)
    # ensure all 4 options are non-null strings
    assert all(isinstance(o, str) and len(o) > 0 for o in opts), f"Options validation failed for: {q[:50]}"
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(opts[0])}', '{esc(opts[1])}', '{esc(opts[2])}', '{esc(opts[3])}'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# === JAVA: NEW TOPICS ===
# Topic: Java Security (JCA, JCE, JAAS)
gen([
    ("Security", "What is the Java Cryptography Architecture (JCA)?", "A framework for cryptographic operations with pluggable providers"),
    ("Security", "What is the Java Cryptography Extension (JCE)?", "Extends JCA with encryption, key exchange, and MAC algorithms"),
    ("Security", "What is a MessageDigest in Java?", "Computes hash digests like SHA-256 using one-way hash function"),
    ("Security", "What is the KeyGenerator class?", "Generates symmetric cryptographic keys"),
    ("Security", "What is the KeyPairGenerator class?", "Generates asymmetric key pairs (public/private)"),
    ("Security", "What is the Cipher class?", "Provides encryption and decryption functionality"),
    ("Security", "What is the difference between ECB, CBC, and GCM modes?", "ECB: no IV; CBC: chained blocks; GCM: authenticated encryption"),
    ("Security", "What is the IvParameterSpec class?", "Specifies initialization vector for cipher modes"),
    ("Security", "What is the SecretKeySpec class?", "Creates a secret key from raw bytes"),
    ("Security", "What is the KeyStore class?", "Database for cryptographic keys and certificates"),
    ("Security", "What is the Java Authentication and Authorization Service (JAAS)?", "Pluggable authentication and authorization framework"),
    ("Security", "What is the Subject class in JAAS?", "Represents an authenticated entity with principals and credentials"),
    ("Security", "What is the LoginContext in JAAS?", "Entry point for JAAS authentication"),
    ("Security", "What is the Principal interface?", "Represents a named entity like user or role"),
    ("Security", "What is the javax.net.ssl.SSLContext?", "Implements SSL/TLS protocol engine"),
    ("Security", "What is the TrustManager in Java?", "Determines whether to trust remote certificates"),
    ("Security", "What is the HostnameVerifier interface?", "Validates hostname against certificate"),
    ("Security", "What is the SecureRandom class?", "Cryptographically strong random number generator"),
    ("Security", "What is the SignedObject class?", "Creates signed objects for tamper-proof data transfer"),
    ("Security", "What is the java.security.Permission class?", "Represents access permission to system resources"),
], "Middle", "Java")

# Topic: Java Internationalization
gen([
    ("i18n", "What is internationalization (i18n) in Java?", "Designing applications to support multiple locales without code changes"),
    ("i18n", "What is the Locale class?", "Represents a specific geographic, political, or cultural region"),
    ("i18n", "What is the ResourceBundle class?", "Loads locale-specific resources like strings from properties files"),
    ("i18n", "What is the PropertyResourceBundle?", "ResourceBundle backed by .properties files"),
    ("i18n", "What is the ListResourceBundle?", "ResourceBundle implemented as Java class with getContents()"),
    ("i18n", "What is the NumberFormat class?", "Formats numbers according to locale conventions"),
    ("i18n", "What is the DateFormat class?", "Formats dates and times according to locale"),
    ("i18n", "What is the SimpleDateFormat class?", "Date formatting with custom patterns"),
    ("i18n", "What is the DateTimeFormatter class?", "Thread-safe date/time formatter from Java 8"),
    ("i18n", "What is the Collator class?", "Locale-sensitive string comparison for sorting"),
    ("i18n", "What is the BreakIterator class?", "Detects text boundaries for characters, words, sentences, lines"),
    ("i18n", "What is the Normalizer class?", "Unicode normalization forms (NFC, NFD, NFKC, NFKD)"),
    ("i18n", "What is the Charset class?", "Maps between Unicode characters and byte sequences"),
    ("i18n", "What is the MessageFormat class?", "Formats messages with placeholders and plural forms"),
    ("i18n", "What is the ChoiceFormat class?", "Formats numbers with grammatical agreement choices"),
    ("i18n", "What is the Bidi class?", "Handles bidirectional text (left-to-right and right-to-left)"),
    ("i18n", "What is the CompactNumberFormat class?", "Formats numbers in compact form like 1K, 1M (Java 12)"),
    ("i18n", "What is the Currency class?", "Represents currency with code, symbol, and fraction digits"),
    ("i18n", "What is the TimeZone class?", "Represents time zone offset and daylight saving rules"),
    ("i18n", "What is the ZoneId class?", "Java 8 time zone identifier like America/New_York"),
], "Middle", "Java")

# Topic: Java Logging
gen([
    ("Logging", "What is the java.util.logging (JUL) framework?", "Built-in logging API with Logger, Handler, Formatter, Filter"),
    ("Logging", "What are logging levels in JUL?", "SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST"),
    ("Logging", "What is a Logger in JUL?", "Named entity that logs messages at specified levels"),
    ("Logging", "What is a Handler in JUL?", "Sends log records to destinations (Console, File, Socket)"),
    ("Logging", "What is a Formatter in JUL?", "Formats log records: SimpleFormatter, XMLFormatter"),
    ("Logging", "What is the SLF4J facade?", "Simple Logging Facade for Java - abstraction over logging frameworks"),
    ("Logging", "What is Logback?", "Successor to Log4j with faster performance and native SLF4J support"),
    ("Logging", "What is Log4j 2?", "Modern logging framework with async loggers and plugins"),
    ("Logging", "What is Log4j 2 configuration?", "XML, JSON, YAML, or properties config with appenders and loggers"),
    ("Logging", "What is the MDC in logging?", "Mapped Diagnostic Context for adding contextual data to log entries"),
    ("Logging", "What is the NDC in logging?", "Nested Diagnostic Context for hierarchical logging context"),
    ("Logging", "What is Log4j 2 Async Logger?", "Lock-free async logging using LMAX Disruptor for high throughput"),
    ("Logging", "What is structured logging?", "Logging in JSON format for machine parsing and querying"),
    ("Logging", "What is the Logstash encoder?", "Encodes logs as JSON for ingestion by ELK stack"),
    ("Logging", "What is the @Slf4j annotation from Lombok?", "Generates SLF4J Logger field at compile time"),
    ("Logging", "What is the Logback configuration file?", "logback.xml with appenders, encoders, and loggers"),
    ("Logging", "What is the Log4j 2 configuration file?", "log4j2.xml with appenders, filters, and loggers"),
    ("Logging", "What is the rolling file appender?", "Rotates log files based on time, size, or both"),
    ("Logging", "What is the difference between Logger.getLogger and LogManager.getLogger?", "LogManager provides centralized logger management"),
    ("Logging", "What is the TTL for log messages in JUL?", "LogRecords have sequence numbers and timestamps"),
], "Middle", "Java")

# Topic: Java Build Tools
gen([
    ("Build Tools", "What is Maven?", "Build automation and dependency management tool using POM.xml"),
    ("Build Tools", "What is the POM.xml file?", "Project Object Model with coordinates, dependencies, and build config"),
    ("Build Tools", "What are Maven coordinates?", "groupId, artifactId, version uniquely identify a project"),
    ("Build Tools", "What is the Maven repository?", "Stores build artifacts: local, central (Maven Central), remote"),
    ("Build Tools", "What is Maven dependency scope?", "compile, provided, runtime, test, system, import"),
    ("Build Tools", "What is Maven transitive dependency?", "Dependencies of your dependencies are automatically included"),
    ("Build Tools", "What is Maven dependency exclusion?", "Excluding specific transitive dependencies"),
    ("Build Tools", "What is Maven lifecycle?", "Default (build), Clean, Site lifecycles with sequential phases"),
    ("Build Tools", "What are Maven build phases?", "validate, compile, test, package, verify, install, deploy"),
    ("Build Tools", "What are Maven plugins?", "Goals bound to lifecycle phases (maven-compiler-plugin, surefire)"),
    ("Build Tools", "What is Maven Surefire plugin?", "Runs unit tests during the test phase"),
    ("Build Tools", "What is Maven Failsafe plugin?", "Runs integration tests during verify phase"),
    ("Build Tools", "What is Maven Shade plugin?", "Creates uber JAR with all dependencies bundled"),
    ("Build Tools", "What is Maven Assembly plugin?", "Creates distributions with custom formats"),
    ("Build Tools", "What is Maven Archetype plugin?", "Generates project skeletons from templates"),
    ("Build Tools", "What is Maven Wrapper?", "Ensures correct Maven version for the project"),
    ("Build Tools", "What is Gradle?", "Groovy/Kotlin DSL-based build tool with incremental builds"),
    ("Build Tools", "What is Gradle build.gradle?", "Groovy DSL build configuration file"),
    ("Build Tools", "What is Gradle build.gradle.kts?", "Kotlin DSL build configuration file"),
    ("Build Tools", "What is Gradle settings.gradle?", "Project settings and module declarations"),
    ("Build Tools", "What is Gradle task?", "Atomic unit of work in Gradle build"),
    ("Build Tools", "What is Gradle dependency configuration?", "implementation, api, compileOnly, runtimeOnly, testImplementation"),
    ("Build Tools", "What is Gradle incremental build?", "Only executes tasks whose inputs changed"),
    ("Build Tools", "What is Gradle build cache?", "Reuses task outputs across builds for speed"),
    ("Build Tools", "What is Gradle composite build?", "Replaces binary dependencies with source projects"),
    ("Build Tools", "What is Gradle multi-project build?", "Build with multiple subprojects in settings.gradle"),
    ("Build Tools", "What is Gradle Wrapper (gradlew)?", "Script that downloads and runs the specified Gradle version"),
    ("Build Tools", "What is the difference between Maven and Gradle?", "Maven: XML-based, fixed lifecycle; Gradle: DSL, flexible, faster"),
    ("Build Tools", "What is the Gradle daemon?", "Long-lived background process for faster builds"),
    ("Build Tools", "What is the mvnw (Maven Wrapper)?", "Script for reproducible Maven builds with pinned version"),
], "Middle", "Java")

# Topic: Java Reflection & Proxies
gen([
    ("Reflection", "What is the Class class in Java?", "Runtime representation of a type with metadata inspection"),
    ("Reflection", "What is the getClass() method?", "Returns the Class object of an instance"),
    ("Reflection", "What is the .class syntax?", "Class literal to obtain Class object at compile time"),
    ("Reflection", "What is Class.forName()?", "Dynamically loads a class by fully qualified name"),
    ("Reflection", "What is the getDeclaredFields() method?", "Returns all fields declared in the class"),
    ("Reflection", "What is the getDeclaredMethods() method?", "Returns all methods declared in the class"),
    ("Reflection", "What is the getDeclaredConstructors() method?", "Returns all constructors declared in the class"),
    ("Reflection", "What is the setAccessible() method?", "Suppresses Java access control checks for private members"),
    ("Reflection", "What is the Field class?", "Provides metadata and access to a class field"),
    ("Reflection", "What is the Method class?", "Provides metadata and invocation of a method"),
    ("Reflection", "What is the Constructor class?", "Provides metadata and instantiation via a constructor"),
    ("Reflection", "What is the Array class in reflection?", "Dynamically creates and manipulates arrays"),
    ("Reflection", "What is the Proxy class?", "Creates dynamic proxy instances at runtime"),
    ("Reflection", "What is the InvocationHandler interface?", "Handles method calls on dynamic proxy instances"),
    ("Reflection", "What is the java.lang.reflect.Proxy.newProxyInstance()?", "Creates proxy implementing specified interfaces"),
    ("Reflection", "What is a dynamic proxy use case?", "AOP, declarative transactions, remote method invocation"),
    ("Reflection", "What is the AnnotatedElement interface?", "Provides reflection methods for annotations"),
    ("Reflection", "What is the getAnnotation() method?", "Returns annotation of specified type if present"),
    ("Reflection", "What is the getAnnotationsByType() method?", "Returns all annotations of specified type (repeatable)"),
    ("Reflection", "What is the ParameterizedType interface?", "Represents parameterized types like List<String>"),
], "Senior", "Java")

# === PYTHON: NEW TOPICS ===
# Topic: Data Science
gen([
    ("Data Science", "What is NumPy?", "Python library for numerical computing with multidimensional arrays"),
    ("Data Science", "What is a NumPy array?", "Homogeneous n-dimensional array with vectorized operations"),
    ("Data Science", "What is the shape attribute in NumPy?", "Tuple of array dimensions"),
    ("Data Science", "What is the reshape() method in NumPy?", "Changes array dimensions without changing data"),
    ("Data Science", "What is broadcasting in NumPy?", "Performs operations on arrays of different shapes automatically"),
    ("Data Science", "What is the numpy.dot() function?", "Computes dot product of two arrays"),
    ("Data Science", "What is the numpy.linalg module?", "Linear algebra operations like matrix inversion, eigenvalues"),
    ("Data Science", "What is Pandas?", "Data manipulation library with DataFrame and Series structures"),
    ("Data Science", "What is a Pandas DataFrame?", "2D labeled data structure with columns of different types"),
    ("Data Science", "What is a Pandas Series?", "1D labeled array for time series or column data"),
    ("Data Science", "What is the read_csv() function in Pandas?", "Reads CSV files into DataFrame"),
    ("Data Science", "What is the groupby() method in Pandas?", "Groups data by column values for aggregation"),
    ("Data Science", "What is the merge() in Pandas?", "Combines DataFrames with SQL-like joins"),
    ("Data Science", "What is the pivot_table() in Pandas?", "Creates spreadsheet-style pivot tables"),
    ("Data Science", "What is the apply() method in Pandas?", "Applies function along axis of DataFrame"),
    ("Data Science", "What is Matplotlib?", "Python plotting library for static and interactive visualizations"),
    ("Data Science", "What is the pyplot interface?", "MATLAB-like plotting API in Matplotlib"),
    ("Data Science", "What is a seaborn library?", "Statistical data visualization library based on Matplotlib"),
    ("Data Science", "What is the scikit-learn library?", "Machine learning library with classification, regression, clustering"),
    ("Data Science", "What is the train_test_split() function?", "Splits data into training and testing sets"),
    ("Data Science", "What is the StandardScaler in sklearn?", "Standardizes features by removing mean and scaling to unit variance"),
    ("Data Science", "What is PCA in sklearn?", "Principal Component Analysis for dimensionality reduction"),
    ("Data Science", "What is cross-validation in sklearn?", "Model validation by partitioning data into folds"),
    ("Data Science", "What is the confusion_matrix() function?", "Evaluates classification performance with true/false positives"),
    ("Data Science", "What is the RandomForestClassifier?", "Ensemble classifier using multiple decision trees"),
    ("Data Science", "What is the SciPy library?", "Scientific computing with optimization, integration, and statistics"),
    ("Data Science", "What is the scipy.optimize module?", "Optimization algorithms like minimize, curve_fit"),
    ("Data Science", "What is the scipy.stats module?", "Statistical distributions and hypothesis tests"),
    ("Data Science", "What is the scipy.interpolate module?", "Interpolation methods for 1D and 2D data"),
    ("Data Science", "What is the scipy.integrate module?", "Numerical integration methods like quad and odeint"),
], "Middle", "Python")

# Topic: Web Scraping
gen([
    ("Web Scraping", "What is BeautifulSoup?", "Python library for parsing HTML and XML documents"),
    ("Web Scraping", "What is the BeautifulSoup constructor?", "Parses HTML/XML string or file into a parse tree"),
    ("Web Scraping", "What is the find() method in BeautifulSoup?", "Finds first tag matching specified criteria"),
    ("Web Scraping", "What is the find_all() method?", "Finds all tags matching specified criteria as list"),
    ("Web Scraping", "What is the select() method in BeautifulSoup?", "Finds elements using CSS selectors"),
    ("Web Scraping", "What is the get_text() method?", "Extracts all text content from tag and descendants"),
    ("Web Scraping", "What is the attrs property in BeautifulSoup?", "Dictionary of HTML attributes for a tag"),
    ("Web Scraping", "What is the parent and children traversal?", "Navigating the parse tree up and down"),
    ("Web Scraping", "What is the next_sibling and previous_sibling?", "Navigating between sibling nodes in parse tree"),
    ("Web Scraping", "What is the Scrapy framework?", "High-performance web scraping and crawling framework"),
    ("Web Scraping", "What is a Scrapy spider?", "Class defining how to scrape a site with start URLs and parse"),
    ("Web Scraping", "What is the Scrapy Item?", "Container for scraped data with typed fields"),
    ("Web Scraping", "What is the Scrapy Item Pipeline?", "Processes scraped items for cleaning, validation, storage"),
    ("Web Scraping", "What is the Scrapy middleware?", "Extensions that process requests/responses in the pipeline"),
    ("Web Scraping", "What is the Scrapy selector?", "XPath and CSS selector engine for extracting data"),
    ("Web Scraping", "What is the requests library?", "HTTP library with session management and authentication"),
    ("Web Scraping", "What is the requests.Session()?", "Persists cookies and connection pooling across requests"),
    ("Web Scraping", "What is the requests.get() parameters?", "params dict for query string, headers dict for custom headers"),
    ("Web Scraping", "What is the response.status_code?", "HTTP status code from requests response"),
    ("Web Scraping", "What is the response.json() method?", "Parses JSON response body into Python dict/list"),
    ("Web Scraping", "What is the response.text property?", "Response body as decoded string"),
    ("Web Scraping", "What is the response.content property?", "Response body as raw bytes"),
    ("Web Scraping", "What is the requests exception handling?", "RequestException, ConnectionError, Timeout, HTTPError"),
    ("Web Scraping", "What is the Selenium library?", "Browser automation for dynamic JavaScript-rendered content"),
    ("Web Scraping", "What is the WebDriver in Selenium?", "Controls browser programmatically"),
    ("Web Scraping", "What is the find_element() in Selenium?", "Finds single element by strategy (By.ID, By.CSS_SELECTOR)"),
    ("Web Scraping", "What is the find_elements() in Selenium?", "Finds all matching elements as list"),
    ("Web Scraping", "What is the headless mode in Selenium?", "Runs browser without GUI for automation"),
    ("Web Scraping", "What is the Playwright library?", "Cross-browser automation with async API"),
    ("Web Scraping", "What is the Pyppeteer library?", "Python port of Puppeteer for headless Chrome automation"),
], "Middle", "Python")

# Topic: Python Networking
gen([
    ("Networking", "What is the socket module?", "Low-level networking interface for TCP and UDP communication"),
    ("Networking", "What is a TCP socket?", "Reliable, connection-oriented socket type SOCK_STREAM"),
    ("Networking", "What is a UDP socket?", "Connectionless, unreliable socket type SOCK_DGRAM"),
    ("Networking", "What is the socket.bind() method?", "Binds socket to a specific address and port"),
    ("Networking", "What is the socket.listen() method?", "Puts TCP socket in server mode to accept connections"),
    ("Networking", "What is the socket.accept() method?", "Accepts incoming TCP connection, returns (conn, addr)"),
    ("Networking", "What is the socket.connect() method?", "Connects TCP socket to a remote address"),
    ("Networking", "What is the socket.send() and socket.recv()?", "Sends and receives data on connected socket"),
    ("Networking", "What is the socket.sendto() and socket.recvfrom()?", "Sends and receives UDP datagrams with address info"),
    ("Networking", "What is the selectors module?", "High-level I/O multiplexing for monitoring multiple sockets"),
    ("Networking", "What is the socketserver module?", "Framework for creating network servers with threading/forking"),
    ("Networking", "What is the asyncore module?", "Async socket handler (deprecated, use asyncio)"),
    ("Networking", "What is the dnspython library?", "DNS toolkit for Python with DNS queries and zone transfers"),
    ("Networking", "What is the scapy library?", "Packet manipulation tool for network analysis"),
    ("Networking", "What is the pcap library?", "Packet capture library for network monitoring"),
    ("Networking", "What is the netifaces library?", "Network interface information: IPs, gateways, MAC addresses"),
    ("Networking", "What is the Twisted networking engine?", "Event-driven networking framework for protocols"),
    ("Networking", "What is the Twisted Reactor?", "Event loop that drives Twisted applications"),
    ("Networking", "What is the Twisted Protocol class?", "Defines how data is processed over a connection"),
    ("Networking", "What is the Twisted Factory class?", "Creates protocol instances for each connection"),
    ("Networking", "What is the gevent library?", "Coroutine-based networking with monkey-patching for async I/O"),
    ("Networking", "What is gevent monkey-patching?", "Replaces blocking stdlib functions with non-blocking versions"),
    ("Networking", "What is the python-socks library?", "SOCKS proxy client for TCP connections"),
    ("Networking", "What is the paramiko for SSH?", "SSHv2 protocol implementation with client and server"),
    ("Networking", "What is the asyncssh library?", "Async SSH client and server implementation"),
    ("Networking", "What is the netmiko library?", "Multi-vendor SSH library for network devices"),
    ("Networking", "What is the napalm library?", "Network automation library for configuration and validation"),
    ("Networking", "What is the ZeroMQ (pyzmq)?", "High-performance messaging library with socket abstraction"),
    ("Networking", "What is the zmq.PUB/SUB pattern?", "Publish-subscribe messaging pattern in ZeroMQ"),
    ("Networking", "What is the zmq.REQ/REP pattern?", "Request-reply messaging pattern in ZeroMQ"),
    ("Networking", "What is the zmq.PUSH/PULL pattern?", "Pipeline messaging pattern for task distribution"),
    ("Networking", "What is the AEAD in TLS?", "Authenticated Encryption with Associated Data for TLS 1.3"),
    ("Networking", "What is the httpx library?", "Modern async-capable HTTP client with HTTP/2 support"),
    ("Networking", "What is the httpx.Client?", "HTTP client with connection pooling and cookie persistence"),
    ("Networking", "What is the httpx.AsyncClient?", "Async HTTP client with async/await support"),
    ("Networking", "What is the MQTT protocol?", "Lightweight publish-subscribe messaging for IoT"),
    ("Networking", "What is the paho-mqtt library?", "MQTT client library for Python"),
    ("Networking", "What is the WebSocket protocol?", "Full-duplex communication over a single TCP connection"),
    ("Networking", "What is the websockets library?", "Async WebSocket server and client for Python"),
], "Middle", "Python")

# Topic: Python Metaprogramming
gen([
    ("Metaprogramming", "What is a metaclass in Python?", "A class of a class that controls class creation behavior"),
    ("Metaprogramming", "What is the type() function as metaclass?", "type is the default metaclass in Python"),
    ("Metaprogramming", "What is the __new__ method in metaclass?", "Called when creating a new class in metaclass"),
    ("Metaprogramming", "What is the __init__ method in metaclass?", "Called after class creation for initialization"),
    ("Metaprogramming", "What is the __call__ method in metaclass?", "Called when the class is instantiated, controls instance creation"),
    ("Metaprogramming", "What is the ABCMeta metaclass?", "Metaclass for defining Abstract Base Classes"),
    ("Metaprogramming", "What is the Singleton metaclass?", "Metaclass that ensures only one instance of a class exists"),
    ("Metaprogramming", "What is the __prepare__ method in metaclass?", "Returns namespace dict for class body execution"),
    ("Metaprogramming", "What is the __init_subclass__ hook?", "Called when a subclass is created"),
    ("Metaprogramming", "What is the __set_name__ descriptor?", "Called when descriptor is assigned to a class attribute"),
    ("Metaprogramming", "What is the __class_getitem__ method?", "Supports generic type parameters like List[int]"),
    ("Metaprogramming", "What is the __subclasshook__ method?", "Customizes issubclass() behavior for ABCs"),
    ("Metaprogramming", "What is the __instancecheck__ method?", "Customizes isinstance() behavior for a class"),
    ("Metaprogramming", "What is the __subclasscheck__ method?", "Customizes issubclass() behavior for a class"),
    ("Metaprogramming", "What is the __init_subclass__ in a mixin?", "Adds behavior when a class inherits from the mixin"),
    ("Metaprogramming", "What is the inspect.getsource() function?", "Returns source code of a function, class, or module"),
    ("Metaprogramming", "What is the inspect.signature() function?", "Inspects function parameters and return annotation"),
    ("Metaprogramming", "What is the dis module?", "Disassembles Python bytecode for analysis"),
    ("Metaprogramming", "What is the ast module?", "Abstract Syntax Tree parsing and manipulation"),
    ("Metaprogramming", "What is the ast.parse() function?", "Parses Python source code into AST"),
    ("Metaprogramming", "What is the ast.NodeTransformer class?", "Transforms AST nodes for code modification"),
    ("Metaprogramming", "What is the ast.NodeVisitor class?", "Visits AST nodes without modification"),
    ("Metaprogramming", "What is the compile() builtin with AST?", "Compiles AST or source code into code object"),
    ("Metaprogramming", "What is the code object in Python?", "Compiled bytecode representation of executable code"),
    ("Metaprogramming", "What is the FunctionType constructor?", "Creates a function from code object and globals at runtime"),
    ("Metaprogramming", "What is the exec() with custom namespace?", "Executes code with controlled globals and locals"),
    ("Metaprogramming", "What is the eval() with restricted globals?", "Evaluates expression with limited namespace"),
    ("Metaprogramming", "What is the __import__ function?", "Low-level import mechanism for dynamic loading"),
    ("Metaprogramming", "What is the importlib module?", "Implementations of import protocol for custom importers"),
    ("Metaprogramming", "What is the importlib.import_module()?", "Programmatic import by module name string"),
], "Senior", "Python")

# === TYPESCRIPT: NEW TOPICS ===
# Topic: TypeScript Configuration
gen([
    ("Config", "What is the tsconfig.json strict mode?", "Enables all strict type-checking options for code safety"),
    ("Config", "What is the strictNullChecks option?", "Makes null and undefined distinct types requiring explicit handling"),
    ("Config", "What is the noImplicitAny option?", "Errors on parameters and variables without explicit type"),
    ("Config", "What is the strictPropertyInitialization option?", "Ensures class properties are initialized in constructor"),
    ("Config", "What is the noUnusedLocals option?", "Errors on declared but unused local variables"),
    ("Config", "What is the noUnusedParameters option?", "Errors on declared but unused function parameters"),
    ("Config", "What is the noImplicitReturns option?", "Errors on functions with missing return paths"),
    ("Config", "What is the noFallthroughCasesInSwitch option?", "Errors on unintentional switch case fallthrough"),
    ("Config", "What is the exactOptionalPropertyTypes option?", "Prevents undefined assignment to optional properties"),
    ("Config", "What is the noPropertyAccessFromIndexSignature option?", "Requires bracket notation for index signatures"),
    ("Config", "What is the skipLibCheck option?", "Skips type checking of declaration files for faster compilation"),
    ("Config", "What is the forceConsistentCasingInFileNames option?", "Ensures consistent file name casing across imports"),
    ("Config", "What is the resolveJsonModule option?", "Allows importing JSON files as modules with types"),
    ("Config", "What is the allowSyntheticDefaultImports option?", "Allows default imports from modules without default export"),
    ("Config", "What is the esModuleInterop option?", "Emits helper for CommonJS and ES modules interoperability"),
    ("Config", "What is the isolatedModules option?", "Treats each file as a separate module for transpilers"),
    ("Config", "What is the preserveConstEnums option?", "Preserves const enum declarations in output JavaScript"),
    ("Config", "What is the sourceMap option?", "Generates .map files for debugging TypeScript in browser"),
    ("Config", "What is the declaration option?", "Generates .d.ts declaration files for library consumers"),
    ("Config", "What is the declarationMap option?", "Generates .d.ts.map files for declaration navigation"),
    ("Config", "What is the composite option?", "Enables project references with incremental builds"),
    ("Config", "What is the incremental option?", "Saves information for faster subsequent compilations"),
    ("Config", "What is the tsBuildInfoFile option?", "Specifies file path for incremental build info"),
    ("Config", "What is the inlineSourceMap option?", "Embeds source maps directly in output files, not separate files"),
    ("Config", "What is the inlineSources option?", "Embeds source code in source maps"),
    ("Config", "What is the emitDeclarationOnly option?", "Only emits declaration files, not JavaScript output"),
    ("Config", "What is the outDir option?", "Redirects output JavaScript to specified directory"),
    ("Config", "What is the rootDir option?", "Common root for source files for output structure"),
    ("Config", "What is the baseUrl option?", "Base directory for non-relative module name resolution"),
    ("Config", "What is the paths option?", "Maps module imports to relative paths"),
], "Middle", "TypeScript")

# Topic: TypeScript Build Tools
gen([
    ("Build Tools", "What is ts-node?", "TypeScript execution engine for Node.js with JIT compilation"),
    ("Build Tools", "What is tsx (TypeScript Execute)?", "Enhanced ts-node with ES modules support and faster startup"),
    ("Build Tools", "What is esbuild?", "Extremely fast JavaScript bundler with TypeScript support"),
    ("Build Tools", "What is esbuild loader?", "Configures how file types are processed (ts, tsx, css)"),
    ("Build Tools", "What is the esbuild build API?", "Programmatic API for bundling and transforming code"),
    ("Build Tools", "What is SWC (Speedy Web Compiler)?", "Rust-based TypeScript/JavaScript compiler for bundlers"),
    ("Build Tools", "What is the @swc/core package?", "SWC compiler bindings for Node.js"),
    ("Build Tools", "What is the @swc/jest transformer?", "SWC integration for Jest to replace ts-jest"),
    ("Build Tools", "What is Vite?", "Fast dev server with HMR and optimized production builds"),
    ("Build Tools", "What is the Vite TypeScript plugin?", "@vitejs/plugin-react-swc or @vitejs/plugin-react for TS support"),
    ("Build Tools", "What is Webpack ts-loader?", "TypeScript loader for Webpack with full type checking"),
    ("Build Tools", "What is the Webpack fork-ts-checker-plugin?", "Runs TypeScript type checker in separate process for speed"),
    ("Build Tools", "What is the awesome-typescript-loader?", "Alternative Webpack TypeScript loader (less maintained)"),
    ("Build Tools", "What is Rollup with TypeScript?", "Tree-shaking bundler with @rollup/plugin-typescript"),
    ("Build Tools", "What is the Parcel bundler?", "Zero-config bundler with built-in TypeScript support"),
    ("Build Tools", "What is the tsc --noEmit flag?", "Type-checks code without emitting output files"),
    ("Build Tools", "What is the tsc --watch flag?", "Watches files and recompiles on changes"),
    ("Build Tools", "What is the tsc --build flag?", "Builds project references for composite projects"),
    ("Build Tools", "What is the tsc --init flag?", "Creates tsconfig.json with recommended defaults"),
    ("Build Tools", "What is the tsc --project flag?", "Specifies tsconfig.json location"),
], "Middle", "TypeScript")

# Topic: TypeScript Linting & Testing
gen([
    ("Linting", "What is ESLint?", "Pluggable JavaScript/TypeScript linter for code quality"),
    ("Linting", "What is @typescript-eslint/parser?", "ESLint parser that converts TypeScript to ESTree"),
    ("Linting", "What is @typescript-eslint/eslint-plugin?", "ESLint rules specific to TypeScript"),
    ("Linting", "What is the @typescript-eslint/no-explicit-any rule?", "Warns against using any type"),
    ("Linting", "What is the @typescript-eslint/strict-boolean-expressions rule?", "Enforces strict boolean expressions"),
    ("Linting", "What is the @typescript-eslint/no-unnecessary-condition rule?", "Warns on always-true or always-false conditions"),
    ("Linting", "What is the @typescript-eslint/prefer-nullish-coalescing rule?", "Prefers ?? over || for null/undefined"),
    ("Linting", "What is the @typescript-eslint/prefer-optional-chain rule?", "Prefers ?. over && for optional access"),
    ("Linting", "What is the eslint-config-prettier?", "Disables ESLint rules that conflict with Prettier"),
    ("Linting", "What is the eslint-plugin-prettier?", "Runs Prettier as an ESLint rule"),
    ("Linting", "What is the eslint-config-standard-with-typescript?", "StandardJS config adapted for TypeScript"),
    ("Linting", "What is the eslint-plugin-import?", "Linting for ES module import/export syntax"),
    ("Linting", "What is the eslint-plugin-unicorn?", "Collection of advanced ESLint rules"),
    ("Linting", "What is the eslint-plugin-sonarjs?", "Detects code smells and bugs in JavaScript/TypeScript"),
    ("Linting", "What is the eslint-plugin-security?", "Detects potential security vulnerabilities"),
    ("Testing", "What is Vitest?", "Fast Vite-native unit test framework with Jest-compatible API"),
    ("Testing", "What is the vitest.config.ts?", "Vitest configuration file with test options"),
    ("Testing", "What is the vi.mock() in Vitest?", "Mocks modules for testing"),
    ("Testing", "What is the vi.fn() in Vitest?", "Creates mock function"),
    ("Testing", "What is the vi.spyOn() in Vitest?", "Spies on object methods"),
    ("Testing", "What is the vitest --coverage flag?", "Generates test coverage report with c8 or istanbul"),
    ("Testing", "What is the vitest --ui flag?", "Launches Vitest UI dashboard"),
    ("Testing", "What is Jest?", "Popular JavaScript testing framework with assertions and mocking"),
    ("Testing", "What is ts-jest?", "TypeScript preprocessor for Jest with type checking"),
    ("Testing", "What is the jest.config.ts?", "Jest configuration in TypeScript format"),
    ("Testing", "What is the jest.mock() function?", "Auto-mocks a module for testing"),
    ("Testing", "What is the jest.fn() function?", "Creates a mock function"),
    ("Testing", "What is the jest.spyOn() function?", "Spies on method calls and returns"),
    ("Testing", "What is the describe/it pattern in Jest?", "Describe groups tests, it defines individual test"),
    ("Testing", "What is the expect() matchers in Jest?", "toBe, toEqual, toBeTruthy, toContain, toThrow"),
], "Middle", "TypeScript")

# === GO: NEW TOPICS ===
# Topic: Go Web Frameworks
gen([
    ("Web Frameworks", "What is Gin?", "High-performance HTTP web framework with Martini-like API"),
    ("Web Frameworks", "What is gin.Default()?", "Creates Gin router with Logger and Recovery middleware"),
    ("Web Frameworks", "What is gin.Context?", "Request context with params, body, and response methods"),
    ("Web Frameworks", "What is the gin.HandlerFunc?", "Function type for Gin request handlers"),
    ("Web Frameworks", "What is gin.RouterGroup?", "Route groups with common prefix and middleware"),
    ("Web Frameworks", "What is c.JSON() in Gin?", "Serializes response as JSON with status code"),
    ("Web Frameworks", "What is c.BindJSON() in Gin?", "Binds request body to struct as JSON"),
    ("Web Frameworks", "What is c.Param() in Gin?", "Extracts URL path parameters"),
    ("Web Frameworks", "What is c.Query() in Gin?", "Extracts URL query parameters"),
    ("Web Frameworks", "What is Gin middleware?", "Functions that execute before handler for logging, auth, etc."),
    ("Web Frameworks", "What is Echo?", "Fast and minimalist web framework with middleware chaining"),
    ("Web Frameworks", "What is echo.New()?", "Creates Echo instance with default settings"),
    ("Web Frameworks", "What is echo.Context?", "Request context with unified API for input/output"),
    ("Web Frameworks", "What is c.Bind() in Echo?", "Binds request body to struct based on Content-Type"),
    ("Web Frameworks", "What is echo.Group()?", "Route grouping with prefix and middleware in Echo"),
    ("Web Frameworks", "What is Fiber?", "Express.js-inspired web framework with zero allocation"),
    ("Web Frameworks", "What is fiber.Ctx?", "Request context in Fiber with method chaining"),
    ("Web Frameworks", "What is fiber.New()?", "Creates new Fiber app instance"),
    ("Web Frameworks", "What is c.JSON() in Fiber?", "JSON response in Fiber"),
    ("Web Frameworks", "What is c.SendString() in Fiber?", "Plain text response in Fiber"),
], "Middle", "Go")

# Topic: Go ORMs & Databases
gen([
    ("Databases", "What is GORM?", "Popular ORM library for Go with conventions-over-configuration"),
    ("Databases", "What is GORM model?", "Struct with gorm.Model embedded for ID, CreatedAt, UpdatedAt, DeletedAt"),
    ("Databases", "What is gorm.DB.AutoMigrate()?", "Auto-creates tables and indexes matching model structs"),
    ("Databases", "What is db.Create() in GORM?", "Inserts record into database"),
    ("Databases", "What is db.First() in GORM?", "Returns first matching record ordered by primary key"),
    ("Databases", "What is db.Find() in GORM?", "Returns all matching records as slice"),
    ("Databases", "What is db.Where() in GORM?", "Adds WHERE condition to query"),
    ("Databases", "What is db.Preload() in GORM?", "Eager loads associations to avoid N+1 queries"),
    ("Databases", "What is db.Joins() in GORM?", "LEFT JOIN or INNER JOIN with related tables"),
    ("Databases", "What is GORM association tags?", "belongsTo, hasOne, hasMany, many2many tags on struct fields"),
    ("Databases", "What is db.Transaction() in GORM?", "Runs callback within database transaction"),
    ("Databases", "What is GORM hooks?", "BeforeSave, AfterSave, BeforeCreate, AfterCreate lifecycle hooks"),
    ("Databases", "What is Ent (Entgo)?", "Entity framework with code generation for Go"),
    ("Databases", "What is Ent schema?", "Go struct defining entity fields and edges (relationships)"),
    ("Databases", "What is Ent client?", "Generated client with Create, Query, Update, Delete methods"),
    ("Databases", "What is Ent graph traversal?", "Chained queries for traversing entity relationships"),
    ("Databases", "What is Ent migration?", "Auto-migration or versioned migration for schema changes"),
    ("Databases", "What is sqlx?", "Extensions to database/sql with struct scanning and named params"),
    ("Databases", "What is sqlx.Get()?", "Queries single row and scans to struct"),
    ("Databases", "What is sqlx.Select()?", "Queries multiple rows and scans to slice of structs"),
], "Middle", "Go")

# Topic: Go gRPC & Protobuf
gen([
    ("gRPC", "What is gRPC?", "High-performance RPC framework using Protocol Buffers and HTTP/2"),
    ("gRPC", "What is Protocol Buffers?", "Interface definition language for serializing structured data"),
    ("gRPC", "What is the .proto file?", "Service and message definitions for gRPC and Protobuf"),
    ("gRPC", "What is protoc?", "Protocol Buffers compiler that generates code from .proto files"),
    ("gRPC", "What is protoc-gen-go?", "Go code generator plugin for Protocol Buffers"),
    ("gRPC", "What is protoc-gen-go-grpc?", "Go gRPC code generator for server and client stubs"),
    ("gRPC", "What is a gRPC Unary RPC?", "Single request, single response like traditional RPC"),
    ("gRPC", "What is a gRPC Server Streaming RPC?", "Single request, stream of responses"),
    ("gRPC", "What is a gRPC Client Streaming RPC?", "Stream of requests, single response"),
    ("gRPC", "What is a gRPC Bidirectional Streaming RPC?", "Both sides send stream of messages"),
    ("gRPC", "What is the grpc.Server in Go?", "Creates gRPC server with interceptors and options"),
    ("gRPC", "What is the grpc.Dial() in Go?", "Creates client connection to gRPC server"),
    ("gRPC", "What is a gRPC interceptor?", "Middleware for server and client to handle cross-cutting concerns"),
    ("gRPC", "What is the gRPC metadata?", "Key-value pairs transmitted with RPC calls as HTTP/2 headers"),
    ("gRPC", "What is gRPC deadline/timeout?", "Maximum time limit for RPC completion on client side"),
    ("gRPC", "What is gRPC error handling?", "Status codes with gRPC-specific error details"),
    ("gRPC", "What is the google.golang.org/grpc package?", "Official Go implementation of gRPC"),
    ("gRPC", "What is the gRPC health check?", "Standard health checking protocol for gRPC services"),
    ("gRPC", "What is the gRPC reflection?", "Server endpoint that lists available services and methods"),
    ("gRPC", "What is the grpcurl tool?", "Command-line tool for interacting with gRPC servers"),
], "Senior", "Go")

# === RUST: NEW TOPICS ===
# Topic: Rust Web Frameworks
gen([
    ("Web Frameworks", "What is Axum?", "Web framework using tower service infrastructure"),
    ("Web Frameworks", "What is the Router in Axum?", "Defines routes with methods, handlers, and middleware"),
    ("Web Frameworks", "What is axum::routing::get?", "Handler for GET requests on specified path"),
    ("Web Frameworks", "What is axum::extract?", "Extractors for request parts: Query, Path, Json, State"),
    ("Web Frameworks", "What is axum::Json<T>?", "JSON request body extractor and response type"),
    ("Web Frameworks", "What is axum::Extension<T>?", "Shared state via extension middleware"),
    ("Web Frameworks", "What is axum::middleware?", "Middleware layers for request processing"),
    ("Web Frameworks", "What is Actix-web?", "Actor-based, high-performance web framework"),
    ("Web Frameworks", "What is actix_web::HttpServer?", "HTTP server with multi-threaded worker model"),
    ("Web Frameworks", "What is actix_web::App?", "Application builder with routes and middleware"),
    ("Web Frameworks", "What is actix_web::HttpRequest?", "Request object with headers, params, and body extractors"),
    ("Web Frameworks", "What is actix_web::HttpResponse?", "Response builder with status, headers, and body"),
    ("Web Frameworks", "What is actix_web::web::Data<T>?", "Shared application state accessible in handlers"),
    ("Web Frameworks", "What is actix_web::web::Json<T>?", "JSON extractor for request body deserialization"),
    ("Web Frameworks", "What is actix_web::middleware::Logger?", "HTTP request logging middleware"),
    ("Web Frameworks", "What is Rocket?", "Weeb framework with focus on usability and type safety"),
    ("Web Frameworks", "What is Rocket route attribute?", "#[get('/path')], #[post('/path')], etc."),
    ("Web Frameworks", "What is Rocket State?", "Managed state accessible from request handlers"),
    ("Web Frameworks", "What is Rocket Form?", "Form data extractor with auto-validation"),
    ("Web Frameworks", "What is Rocket fairing?", "Application lifecycle callbacks similar to middleware"),
], "Middle", "Rust")

# Topic: Rust Databases (Diesel, SQLx, SeaORM)
gen([
    ("Databases", "What is Diesel?", "Safe, extensible ORM and query builder for Rust"),
    ("Databases", "What is Diesel schema?", "Table schema definition (auto-generated by diesel print-schema)"),
    ("Databases", "What is Diesel model?", "Rust struct mapping to database table with Queryable, Insertable"),
    ("Databases", "What is diesel::QueryDsl?", "Trait providing query methods like .filter(), .order(), .limit()"),
    ("Databases", "What is diesel::RunQueryDsl?", "Trait executing queries: .load(), .get_result(), .execute()"),
    ("Databases", "What is diesel::Insertable?", "Trait for structs that can be inserted into a table"),
    ("Databases", "What is diesel::Queryable?", "Trait for structs that can be loaded from query results"),
    ("Databases", "What is diesel::AsChangeset?", "Trait for structs that can update table rows"),
    ("Databases", "What is diesel migration?", "SQL-based versioned schema changes with up.sql and down.sql"),
    ("Databases", "What is diesel migration run?", "Applies pending migrations"),
    ("Databases", "What is diesel migration revert?", "Rolls back the last migration"),
    ("Databases", "What is diesel migration generate?", "Creates new migration with timestamp"),
    ("Databases", "What is SQLx?", "Async SQL database driver with compile-time query checking"),
    ("Databases", "What is sqlx::query_as::<T>()?", "Queries and maps results to struct with FromRow"),
    ("Databases", "What is sqlx::PgPool?", "PostgreSQL connection pool for async queries"),
    ("Databases", "What is sqlx::migrate!()", "Compile-time migration runner macro"),
    ("Databases", "What is sqlx::FromRow derive?", "Derives row mapping for query results"),
    ("Databases", "What is SeaORM?", "Async ORM for Rust with ActiveRecord-like API"),
    ("Databases", "What is SeaORM entity?", "Struct and related impl for table mapping"),
    ("Databases", "What is SeaORM query?", "Entity::find(), .filter(), .all(), .one() API"),
], "Middle", "Rust")

# Topic: Rust WebAssembly
gen([
    ("WebAssembly", "What is WebAssembly?", "Binary instruction format for high-performance web apps"),
    ("WebAssembly", "What is wasm-pack?", "Tool to build Rust-generated WebAssembly packages"),
    ("WebAssembly", "What is wasm-bindgen?", "Facilitates JS-Rust interop for WebAssembly"),
    ("WebAssembly", "What is the #[wasm_bindgen] attribute?", "Exposes Rust functions and types to JavaScript"),
    ("WebAssembly", "What is the wasm_bindgen::JsValue?", "Represents arbitrary JavaScript values in Rust"),
    ("WebAssembly", "What is the web-sys crate?", "Web API bindings for Rust (DOM, fetch, console)"),
    ("WebAssembly", "What is the js-sys crate?", "Bindings for JavaScript standard built-in objects"),
    ("WebAssembly", "What is wasm-bindgen-futures?", "Bridge between JS Promises and Rust Futures"),
    ("WebAssembly", "What is the console_error_panic_hook?", "Panics in Rust/Wasm print to browser console"),
    ("WebAssembly", "What is the wasm-pack build command?", "Builds Rust project as npm package for WebAssembly"),
    ("WebAssembly", "What is the wasm-pack test command?", "Runs tests in browser or Node.js with Wasm"),
    ("WebAssembly", "What is wasm-pack publish?", "Publishes Wasm package to npm registry"),
    ("WebAssembly", "What is Yew?", "Rust framework for building WebAssembly frontends"),
    ("WebAssembly", "What is Yew function component?", "Stateless component with properties in Yew"),
    ("WebAssembly", "What is Yew hooks?", "use_state, use_effect, use_reducer hooks similar to React"),
    ("WebAssembly", "What is the Leptos framework?", "Fine-grained reactive WASM framework for Rust"),
    ("WebAssembly", "What is the Sycamore framework?", "Reactive library for WebAssembly frontends in Rust"),
    ("WebAssembly", "What is the Dioxus framework?", "React-like framework for multi-platform Rust apps"),
    ("WebAssembly", "What is wasmtime?", "Standalone WebAssembly runtime outside the browser"),
    ("WebAssembly", "What is WASI (WebAssembly System Interface)?", "Standard system interface for Wasm outside the browser"),
], "Senior", "Rust")

# === REACT: NEW TOPICS ===
# Topic: React Native
gen([
    ("React Native", "What is React Native?", "Framework for building native mobile apps using React"),
    ("React Native", "What is the bridge in React Native?", "Communication channel between JS and native modules"),
    ("React Native", "What is the new architecture (Fabric/TurboModules)?", "JSI-based native module and renderer system"),
    ("React Native", "What is the View component?", "Basic UI building block for layout in React Native"),
    ("React Native", "What is the Text component?", "Displays text content in React Native"),
    ("React Native", "What is the ScrollView component?", "Scrollable container for content in React Native"),
    ("React Native", "What is the FlatList component?", "Virtualized scrolling list for performant long lists"),
    ("React Native", "What is the SectionList component?", "Virtualized list with section headers in React Native"),
    ("React Native", "What is the Image component?", "Displays images from local or remote sources"),
    ("React Native", "What is the TouchableOpacity component?", "Pressable wrapper with opacity feedback"),
    ("React Native", "What is the Pressable component?", "Advanced press handler with state feedback"),
    ("React Native", "What is the StyleSheet.create()?", "Creates optimized style object in React Native"),
    ("React Native", "What is the Flexbox in React Native?", "Layout system using flex property for responsive design"),
    ("React Native", "What is the SafeAreaView component?", "Renders content within safe area boundaries"),
    ("React Native", "What is the React Navigation library?", "Routing and navigation for React Native apps"),
    ("React Native", "What is the navigation stack?", "Push/pop screen navigation pattern"),
    ("React Native", "What is the navigation tab?", "Bottom or top tab navigator for section switching"),
    ("React Native", "What is the navigation drawer?", "Side drawer navigator with overlay"),
    ("React Native", "What is the Expo framework?", "Managed React Native workflow with built-in tools"),
    ("React Native", "What is Expo Go?", "Sandboxed app for testing Expo projects on device"),
    ("React Native", "What is Expo EAS Build?", "Cloud build service for React Native apps"),
    ("React Native", "What is expo-dev-client?", "Custom dev client for bare workflow projects"),
    ("React Native", "What is the AsyncStorage API?", "Unencrypted persistent key-value storage in React Native"),
    ("React Native", "What is the NetInfo library?", "Network connectivity detection in React Native"),
    ("React Native", "What is the react-native-camera?", "Camera component for photo and video capture"),
    ("React Native", "What is react-native-maps?", "Map components for iOS and Android"),
    ("React Native", "What is react-native-push-notification?", "Local and remote push notifications"),
    ("React Native", "What is react-native-firebase?", "Firebase SDK integration for React Native"),
    ("React Native", "What is react-native-vector-icons?", "Custom icon sets for React Native apps"),
    ("React Native", "What is the Hermes engine?", "JavaScript engine optimized for React Native"),
], "Middle", "React")

# Topic: Storybook
gen([
    ("Storybook", "What is Storybook?", "Frontend workshop for building UI components in isolation"),
    ("Storybook", "What is a Story?", "Function that renders a component state for a specific scenario"),
    ("Storybook", "What is the Component Story Format (CSF)?", "Standard format for writing stories as ES modules"),
    ("Storybook", "What is the meta default export?", "Component metadata: title, component, decorators, args"),
    ("Storybook", "What are Args in Storybook?", "Input arguments passed to component stories"),
    ("Storybook", "What is the args object in CSF?", "Default arguments for all stories of a component"),
    ("Storybook", "What are decorators in Storybook?", "Wrapper components that provide context to stories"),
    ("Storybook", "What is the Storybook controls addon?", "Interactive controls to modify component args at runtime"),
    ("Storybook", "What is the Storybook actions addon?", "Logs event handler calls for debugging"),
    ("Storybook", "What is the Storybook viewport addon?", "Tests responsive layouts at various screen sizes"),
    ("Storybook", "What is the Storybook a11y addon?", "Accessibility testing and violation reporting"),
    ("Storybook", "What is the Storybook interaction addon?", "Visual testing of user interactions and assertions"),
    ("Storybook", "What is the Storybook test runner?", "Automates interaction tests across all stories"),
    ("Storybook", "What is the Storybook docs addon?", "Auto-generates documentation from stories"),
    ("Storybook", "What is the Storybook canvas?", "Main preview area where components are rendered"),
    ("Storybook", "What is the Storybook sidebar?", "Navigation tree organized by component hierarchy"),
    ("Storybook", "What is the Storybook toolbar?", "Top menu with zoom, grid, background, viewport toggles"),
    ("Storybook", "What is the main.js config?", "Storybook configuration file for addons and stories paths"),
    ("Storybook", "What is the preview.js config?", "Global decorators, parameters, and args configuration"),
    ("Storybook", "What is the manager.js config?", "Addons panel configuration and theme customization"),
], "Middle", "React")

# Topic: Animation Libraries
gen([
    ("Animation", "What is Framer Motion?", "Animation library for React with declarative API"),
    ("Animation", "What is the motion component?", "Animation-enabled HTML/React element in Framer Motion"),
    ("Animation", "What is the animate prop?", "Defines target animation values for motion components"),
    ("Animation", "What is the initial prop?", "Starting state before animation in Framer Motion"),
    ("Animation", "What is the exit prop?", "Animation state for unmounting with AnimatePresence"),
    ("Animation", "What is AnimatePresence?", "Enables exit animations when components unmount"),
    ("Animation", "What is the transition prop?", "Configures timing, easing, and delay for animations"),
    ("Animation", "What is the variants API?", "Named animation states that can be referenced by name"),
    ("Animation", "What is the whileHover prop?", "Animation state triggered on hover"),
    ("Animation", "What is the whileTap prop?", "Animation state triggered on press/tap"),
    ("Animation", "What is the useAnimation hook?", "Controls animation imperatively with start/stop"),
    ("Animation", "What is the useMotionValue hook?", "Reactive value for performance-driven animations"),
    ("Animation", "What is the useTransform hook?", "Transforms one motion value to another"),
    ("Animation", "What is the useScroll hook?", "Reactive scroll position and progress in Framer Motion"),
    ("Animation", "What is the useViewportScroll hook?", "Deprecated, use useScroll with page offset"),
    ("Animation", "What is the layout animations?", "Animate layout changes with layout prop"),
    ("Animation", "What is the gesture recognition?", "Drag, hover, tap, pan gesture support"),
    ("Animation", "What is the drag prop?", "Enables drag behavior on motion component"),
    ("Animation", "What is the react-spring library?", "Physics-based animation library for React"),
    ("Animation", "What is the useSpring hook?", "Creates animated value with spring physics"),
    ("Animation", "What is the animated component?", "Animation-enabled wrapper in react-spring"),
    ("Animation", "What is the useTrail hook?", "Staggered animation for multiple elements"),
    ("Animation", "What is the useTransition hook (react-spring)?", "Mount/unmount animations with lifecycle"),
    ("Animation", "What is the useChain hook?", "Orchestrates multiple animations in sequence"),
    ("Animation", "What is the GSAP library?", "High-performance animation library for the web"),
    ("Animation", "What is the gsap.to() method?", "Animates target to specified values"),
    ("Animation", "What is the gsap.from() method?", "Animates from specified values to current state"),
    ("Animation", "What is the gsap.fromTo() method?", "Animates between explicit from and to values"),
    ("Animation", "What is the gsap.timeline()?", "Sequences multiple animations with precise control"),
    ("Animation", "What is the gsap ScrollTrigger plugin?", "Animations triggered by scroll position"),
], "Senior", "React")

# === KOTLIN: NEW TOPICS ===
# Topic: Ktor
gen([
    ("Ktor", "What is Ktor?", "Async web framework for Kotlin built on coroutines"),
    ("Ktor", "What is the embeddedServer() in Ktor?", "Starts a Ktor server with specified engine and config"),
    ("Ktor", "What are Ktor engines?", "Netty, Jetty, Tomcat, CIO for server and client"),
    ("Ktor", "What is the routing block in Ktor?", "Defines routes with HTTP method and path"),
    ("Ktor", "What is the get() handler in Ktor?", "Handles GET requests for a path"),
    ("Ktor", "What is the post() handler in Ktor?", "Handles POST requests for a path"),
    ("Ktor", "What is the call object in Ktor?", "Represents HTTP request and response for handling"),
    ("Ktor", "What is call.respond() in Ktor?", "Sends response with content and status code"),
    ("Ktor", "What is call.respondText() in Ktor?", "Sends plain text response"),
    ("Ktor", "What is call.respondBytes() in Ktor?", "Sends binary response"),
    ("Ktor", "What is content negotiation in Ktor?", "Serializes/deserializes content based on Content-Type"),
    ("Ktor", "What is kotlinx.serialization in Ktor?", "JSON serialization plugin for content negotiation"),
    ("Ktor", "What is the Ktor client?", "HTTP client with coroutines support and engine switching"),
    ("Ktor", "What is the HttpClient in Ktor?", "Creates HTTP client with configurable engine and plugins"),
    ("Ktor", "What is the Ktor client get() method?", "Performs HTTP GET request with URL"),
    ("Ktor", "What is Ktor authentication?", "Built-in auth: Basic, Digest, JWT, OAuth, Form"),
    ("Ktor", "What is the authenticate block in Ktor?", "Wraps routes requiring authentication"),
    ("Ktor", "What is Ktor JWT authentication?", "JWT token verification with issuer, audience, and secret"),
    ("Ktor", "What is Ktor session management?", "Cookie or header-based session storage and retrieval"),
    ("Ktor", "What is Ktor file upload?", "Multi-part form data handling for file uploads"),
    ("Ktor", "What is the Ktor status pages plugin?", "Custom error page rendering per status code"),
    ("Ktor", "What is the Ktor call logging plugin?", "Logs incoming requests and outgoing responses"),
    ("Ktor", "What is the Ktor compression plugin?", "Compresses responses with gzip or deflate"),
    ("Ktor", "What is the Ktor CORS plugin?", "Configures Cross-Origin Resource Sharing headers"),
    ("Ktor", "What is the Ktor HSTS plugin?", "Enforces HTTPS with Strict-Transport-Security header"),
    ("Ktor", "What is the Ktor locations plugin?", "Type-safe URL routing with path parameters (deprecated in 3.x)"),
    ("Ktor", "What is the Ktor resource routing?", "Type-safe routing using annotation-based resources"),
    ("Ktor", "What is the Ktor testing?", "Test host for integration testing Ktor applications"),
    ("Ktor", "What is testApplication in Ktor?", "Creates test application context with mock request"),
    ("Ktor", "What is the Ktor client test engine?", "Mock engine for testing HTTP client code"),
], "Senior", "Kotlin")

# Topic: Kotlin Multiplatform
gen([
    ("Multiplatform", "What is Kotlin Multiplatform (KMP)?", "Share code across JVM, JS, and Native targets"),
    ("Multiplatform", "What is the expect/actual mechanism?", "Declare platform-agnostic API (expect) with platform implementations (actual)"),
    ("Multiplatform", "What is the expect keyword?", "Declares a function or class without implementation"),
    ("Multiplatform", "What is the actual keyword?", "Provides platform-specific implementation of expect declaration"),
    ("Multiplatform", "What is the commonMain source set?", "Shared code across all platforms in KMP"),
    ("Multiplatform", "What is the platform-specific source sets?", "jvmMain, jsMain, nativeMain for platform code"),
    ("Multiplatform", "What is the Kotlin Multiplatform plugin?", "kotlin(\"multiplatform\") in Gradle for KMP projects"),
    ("Multiplatform", "What is the shared module in KMP?", "Module with commonMain and platform source sets"),
    ("Multiplatform", "What is Kotlin/JS?", "Kotlin compiler target for JavaScript and TypeScript"),
    ("Multiplatform", "What is the Kotlin JS DCE (Dead Code Elimination)?", "Removes unused functions in JS production builds"),
    ("Multiplatform", "What is @JsExport annotation?", "Exposes Kotlin declarations to JavaScript in Kotlin/JS"),
    ("Multiplatform", "What is the @JsName annotation?", "Customizes JavaScript name for Kotlin declarations"),
    ("Multiplatform", "What is Kotlin/Native?", "Kotlin compiler target for native binaries (iOS, Linux, Windows)"),
    ("Multiplatform", "What is the Kotlin/Native memory model?", "Automatic memory management with reference counting"),
    ("Multiplatform", "What is the new Kotlin/Native memory manager?", "Stable memory manager with garbage collection like JVM"),
    ("Multiplatform", "What is Kotlin/Wasm?", "Kotlin compiler target for WebAssembly"),
    ("Multiplatform", "What is the @OptionalExpectation annotation?", "Marks expect annotation class as optional for platforms"),
    ("Multiplatform", "What is the kotlinx.coroutines in KMP?", "Async programming across all platforms"),
    ("Multiplatform", "What is the kotlinx.serialization in KMP?", "JSON serialization across all platforms"),
    ("Multiplatform", "What is the kotlinx.datetime library?", "Multiplatform date and time library"),
], "Senior", "Kotlin")

# Topic: Kotlin Compose Multiplatform
gen([
    ("Compose Multiplatform", "What is Compose Multiplatform?", "Jetpack Compose UI framework for desktop and web"),
    ("Compose Multiplatform", "What is the Compose Desktop?", "Desktop application development with Compose UI"),
    ("Compose Multiplatform", "What is the Compose Web?", "Web application development with Compose for HTML Canvas"),
    ("Compose Multiplatform", "What is the application() function?", "Entry point for Compose Desktop application"),
    ("Compose Multiplatform", "What is the Window composable?", "Creates a OS window with title and state"),
    ("Compose Multiplatform", "What is the MenuBar composable?", "Describes native window menu bar"),
    ("Compose Multiplatform", "What is the androidx.compose.material3?", "Material Design 3 components for Desktop"),
    ("Compose Multiplatform", "What is the Desktop theme in Compose?", "MaterialTheme for desktop with typography and colors"),
    ("Compose Multiplatform", "What is the use of Swing interop?", "Embedding Swing components in Compose Desktop"),
    ("Compose Multiplatform", "What is the WindowState in Desktop?", "Manages window position, size, and state"),
    ("Compose Multiplatform", "What is the Canvas composable in Compose?", "Low-level drawing with drawScope"),
    ("Compose Multiplatform", "What is the PointerInput in Compose?", "Custom gesture handling with pointer events"),
    ("Compose Multiplatform", "What is the DragGestureDetector?", "Detects drag gestures in Compose"),
    ("Compose Multiplatform", "What is the Compose snapshot system?", "State observation for recomposition"),
    ("Compose Multiplatform", "What is the recomposition count?", "Number of times composable re-executed"),
    ("Compose Multiplatform", "What is the @Stable annotation?", "Marks type as stable for smart recomposition"),
    ("Compose Multiplatform", "What is the @Immutable annotation?", "Marks type as immutable for optimization"),
    ("Compose Multiplatform", "What is the CompositionLocal?", "Implicitly propagated values down the composition"),
    ("Compose Multiplatform", "What is the Layout composable?", "Custom layout with measured and placed children"),
    ("Compose Multiplatform", "What is the SubcomposeLayout?", "Layout that subcomposes based on constraints"),
], "Senior", "Kotlin")

# === GENERAL: NEW TOPICS ===
# Topic: Networking & Protocols
gen([
    ("Networking", "What is the TCP three-way handshake?", "SYN, SYN-ACK, ACK for connection establishment"),
    ("Networking", "What is TCP congestion control?", "Slow start, congestion avoidance, fast retransmit, fast recovery"),
    ("Networking", "What is the sliding window in TCP?", "Flow control mechanism for unacknowledged data"),
    ("Networking", "What is TCP vs UDP?", "TCP: reliable, ordered, connection-oriented; UDP: fast, connectionless"),
    ("Networking", "What is HTTP/1.1?", "Text-based protocol with persistent connections and pipelining"),
    ("Networking", "What is HTTP/2?", "Binary protocol with multiplexing, header compression, server push"),
    ("Networking", "What is HTTP/3?", "Uses QUIC over UDP for reduced latency and improved reliability"),
    ("Networking", "What is QUIC protocol?", "Google-developed transport protocol over UDP with TLS 1.3 built-in"),
    ("Networking", "What is WebSocket?", "Full-duplex communication over a single TCP connection"),
    ("Networking", "What is the WebSocket handshake?", "Upgrade from HTTP to WebSocket via 101 Switching Protocols"),
    ("Networking", "What is Server-Sent Events (SSE)?", "Unidirectional server-to-client streaming over HTTP"),
    ("Networking", "What is the DNS resolution process?", "Recursive lookup: cache, resolver, root, TLD, authoritative servers"),
    ("Networking", "What are DNS record types?", "A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, PTR"),
    ("Networking", "What is the DHCP protocol?", "Dynamically assigns IP addresses to network devices"),
    ("Networking", "What is the ARP protocol?", "Resolves IP addresses to MAC addresses on local network"),
    ("Networking", "What is NAT (Network Address Translation)?", "Maps private IPs to public IP for internet access"),
    ("Networking", "What is IPv4 vs IPv6?", "IPv4: 32-bit; IPv6: 128-bit with larger address space"),
    ("Networking", "What is subnetting?", "Divides IP network into smaller subnetworks"),
    ("Networking", "What is CIDR notation?", "Classless Inter-Domain Routing with prefix length suffix"),
    ("Networking", "What is the OSI model layers?", "Physical, Data Link, Network, Transport, Session, Presentation, Application"),
], "Senior", "General")

# Topic: Security
gen([
    ("Security", "What is the OWASP Top 10?", "Most critical web application security risks list"),
    ("Security", "What is SQL injection prevention?", "Parameterized queries, prepared statements, ORM frameworks"),
    ("Security", "What is XSS (Cross-Site Scripting)?", "Injecting malicious scripts into web pages viewed by others"),
    ("Security", "What is XSS prevention?", "Output encoding, Content Security Policy, input validation"),
    ("Security", "What is CSRF (Cross-Site Request Forgery)?", "Forces user to execute unwanted actions on authenticated app"),
    ("Security", "What is CSRF prevention?", "Anti-CSRF tokens, SameSite cookies, origin/referrer headers"),
    ("Security", "What is Clickjacking?", "Hides malicious UI under legitimate UI via iframes"),
    ("Security", "What is Clickjacking prevention?", "X-Frame-Options header, CSP frame-ancestors directive"),
    ("Security", "What is Session fixation?", "Attacker sets victim's session ID to a known value"),
    ("Security", "What is Session fixation prevention?", "Regenerate session ID after authentication"),
    ("Security", "What is Path traversal?", "Accessing files outside web root using ../ sequences"),
    ("Security", "What is Path traversal prevention?", "Validate and sanitize file paths, use allowlists"),
    ("Security", "What is SSRF (Server-Side Request Forgery)?", "Attacker makes server make requests to internal systems"),
    ("Security", "What is SSRF prevention?", "Allowlist destinations, disable unnecessary redirects"),
    ("Security", "What is XXE (XML External Entity)?", "Attacks using XML entity expansion or external entity loading"),
    ("Security", "What is XXE prevention?", "Disable DTD processing, use JSON instead of XML"),
    ("Security", "What is Insecure Deserialization?", "Attacker manipulates serialized objects for code execution"),
    ("Security", "What is Deserialization prevention?", "Integrity checks, type restrictions, use safe formats"),
    ("Security", "What is the principle of least privilege?", "Grant minimum permissions necessary for function"),
    ("Security", "What is defense in depth?", "Multiple layers of security controls throughout the system"),
], "Senior", "General")

# Topic: Cloud (AWS)
gen([
    ("Cloud", "What is Amazon S3?", "Object storage service with unlimited scalability"),
    ("Cloud", "What is S3 bucket?", "Container for objects stored in Amazon S3"),
    ("Cloud", "What is S3 storage classes?", "Standard, Intelligent-Tiering, One Zone-IA, Glacier, Deep Archive"),
    ("Cloud", "What is S3 versioning?", "Preserves multiple versions of objects for recovery"),
    ("Cloud", "What is S3 lifecycle policy?", "Automates object transitions between storage classes"),
    ("Cloud", "What is S3 presigned URL?", "Time-limited URL for temporary object access"),
    ("Cloud", "What is Amazon EC2?", "Virtual servers in the cloud with customizable instances"),
    ("Cloud", "What is EC2 instance types?", "General purpose, Compute optimized, Memory optimized, Storage optimized"),
    ("Cloud", "What is EC2 security group?", "Virtual firewall for EC2 instance traffic control"),
    ("Cloud", "What is EC2 auto scaling?", "Automatically adjusts instance count based on demand"),
    ("Cloud", "What is EC2 load balancer?", "Distributes traffic across EC2 instances"),
    ("Cloud", "What is Amazon VPC?", "Isolated virtual network in AWS cloud"),
    ("Cloud", "What is VPC peering?", "Connecting VPCs for private communication"),
    ("Cloud", "What is AWS IAM?", "Identity and Access Management for AWS resources"),
    ("Cloud", "What is IAM role?", "Set of permissions assumed by users, services, or apps"),
    ("Cloud", "What is IAM policy?", "JSON document defining resource permissions"),
    ("Cloud", "What is AWS CloudWatch?", "Monitoring and observability for AWS resources"),
    ("Cloud", "What is CloudWatch alarm?", "Triggers actions based on metric thresholds"),
    ("Cloud", "What is AWS CloudTrail?", "Audits API calls across AWS accounts"),
    ("Cloud", "What is AWS Config?", "Continuously assesses and audits resource configurations"),
], "Senior", "General")

# Topic: Git
gen([
    ("Git", "What is git rebase?", "Reapplies commits on top of another base commit"),
    ("Git", "What is git rebase vs merge?", "Rebase: linear history; Merge: preserves branch topology"),
    ("Git", "What is git interactive rebase?", "Rewrites commit history: squash, reword, drop, reorder"),
    ("Git", "What is git cherry-pick?", "Applies specific commit from one branch to another"),
    ("Git", "What is git stash?", "Temporarily saves uncommitted changes"),
    ("Git", "What is git stash pop?", "Applies and removes the latest stash"),
    ("Git", "What is git bisect?", "Binary search to find the commit that introduced a bug"),
    ("Git", "What is git revert?", "Creates new commit that undoes a previous commit"),
    ("Git", "What is git reset --soft?", "Moves HEAD, keeps changes staged"),
    ("Git", "What is git reset --mixed?", "Moves HEAD, unstages changes (default)"),
    ("Git", "What is git reset --hard?", "Moves HEAD, discards all changes"),
    ("Git", "What is git log --oneline?", "Compact commit history with one line per commit"),
    ("Git", "What is git log --graph?", "ASCII graph of branch and merge history"),
    ("Git", "What is git blame?", "Shows who last modified each line of a file"),
    ("Git", "What is git reflog?", "Records local reference updates for recovery"),
    ("Git", "What is git fetch vs pull?", "fetch: downloads without merging; pull: downloads and merges"),
    ("Git", "What is git remote add?", "Adds remote repository reference"),
    ("Git", "What is git submodule?", "Embeds another repository within a repository"),
    ("Git", "What is git worktree?", "Checks out multiple branches simultaneously"),
    ("Git", "What is git tag?", "Marks specific commit with a named reference"),
    ("Git", "What is git describe?", "Gives human-readable name for commit relative to tags"),
    ("Git", "What is git clean?", "Removes untracked files from working directory"),
    ("Git", "What is git archive?", "Creates archive (zip/tar) of repository"),
    ("Git", "What is git hooks?", "Scripts triggered by git events: pre-commit, post-commit, pre-push"),
    ("Git", "What is git pre-commit hook?", "Runs checks before commit is recorded"),
    ("Git", "What is git post-receive hook?", "Runs after push to repository"),
    ("Git", "What is Git LFS (Large File Storage)?", "Replaces large files with text pointers in repository"),
    ("Git", "What is git filter-branch?", "Rewrites history with custom filter (deprecated by git filter-repo)"),
    ("Git", "What is git filter-repo?", "Modern tool for rewriting git history"),
    ("Git", "What is the .gitignore file?", "Specifies intentionally untracked files to ignore"),
], "Middle", "General")

# Topic: Linux
gen([
    ("Linux", "What is the Linux kernel?", "Core of the OS managing hardware, processes, and resources"),
    ("Linux", "What is init system (systemd)?", "PID 1 that manages services and boot process"),
    ("Linux", "What is systemctl?", "Controls systemd services (start, stop, enable, status)"),
    ("Linux", "What is journalctl?", "Queries systemd journal logs"),
    ("Linux", "What are Linux file permissions?", "rwx for owner, group, others with numeric mode"),
    ("Linux", "What is chmod 755?", "Owner: rwx; Group: r-x; Others: r-x"),
    ("Linux", "What is chown?", "Changes file owner and group"),
    ("Linux", "What is umask?", "Default permission mask for new files/directories"),
    ("Linux", "What is the /proc filesystem?", "Virtual filesystem exposing kernel and process info"),
    ("Linux", "What is the /sys filesystem?", "Virtual filesystem for kernel object configuration"),
    ("Linux", "What is the /dev filesystem?", "Device files for hardware access"),
    ("Linux", "What is LVM (Logical Volume Manager)?", "Flexible disk management with volume groups and snapshots"),
    ("Linux", "What is the Linux process states?", "Running, Sleeping, Uninterruptible Sleep, Zombie, Stopped"),
    ("Linux", "What is the kill command?", "Sends signals to processes: SIGTERM (15), SIGKILL (9)"),
    ("Linux", "What is the ps command?", "Lists running processes with various output formats"),
    ("Linux", "What is the top/htop command?", "Interactive process viewer with resource usage"),
    ("Linux", "What is the netstat command?", "Network connections, routing tables, and interface stats"),
    ("Linux", "What is the ss command?", "Modern replacement for netstat with socket statistics"),
    ("Linux", "What is iptables/nftables?", "Packet filtering and NAT configuration"),
    ("Linux", "What is SELinux?", "Mandatory Access Control security module"),
    ("Linux", "What is AppArmor?", "Mandatory Access Control per-program profiles"),
    ("Linux", "What is cgroups?", "Control groups for resource limiting and accounting"),
    ("Linux", "What is namespaces in Linux?", "Isolates processes: PID, Network, Mount, User, IPC, UTS"),
    ("Linux", "What is the strace command?", "Traces system calls and signals of a process"),
    ("Linux", "What is the ltrace command?", "Traces library calls of a process"),
    ("Linux", "What is the perf command?", "Performance profiling with hardware counters"),
    ("Linux", "What is the dd command?", "Low-level data copy and conversion"),
    ("Linux", "What is the rsync command?", "Fast incremental file transfer and synchronization"),
    ("Linux", "What is the scp command?", "Secure file copy over SSH"),
    ("Linux", "What is the cron daemon?", "Time-based job scheduler in Unix-like systems"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 15 added {len(new)} questions.")