"""Batch 5: Add ~1000 more questions"""
import os, sys

MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'

with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()

seed_marker = "\nasync function seedDB()"
if seed_marker not in content:
    print("ERROR: seedDB function not found")
    sys.exit(1)

before_seed = content[:content.index(seed_marker)]
from_seed = content[content.index(seed_marker):]

new_q_calls = []

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")

def add(cat, q, a, diff, lang):
    opts = [a, "Alternative approach", "Common misconception", "I don't know"]
    opts_str = ', '.join(f"'{esc(o)}'" for o in opts)
    new_q_calls.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', [{opts_str}], '{diff}', '{lang}');")

def b(cat, items, diff, lang):
    for item in items:
        if isinstance(item, tuple):
            q, a = item
        else:
            q, a = item.split("|", 1)
        add(cat, q.strip(), a.strip(), diff, lang)

# ========== Java (300) ==========
j5 = [
    "Explain the Java Security Manager|Sandbox for untrusted code. Deprecated Java 17. Removed Java 18.",
    "What is a MethodHandle?|java.lang.invoke.MethodHandle. Typed, direct executable reference. Faster than reflection.",
    "What is a VarHandle?|Variable handle for atomic operations on fields. Memory ordering modes.",
    "What is the jdk.incubator.vector module?|SIMD vector operations. FloatVector, IntVector. Species for lane count.",
    "What is the jdk.incubator.concurrent module?|Structured concurrency, scoped values. Incubator features.",
    "What is the Foreign Function API?|java.lang.foreign.*. Linker, SymbolLookup, MemorySegment. Replace JNI.",
    "What is the MemorySegment?|Off-heap memory region. Spatial and temporal bounds. Arena for lifecycle.",
    "What is the Arena API?|Controls MemorySegment lifecycle. Confined, shared, automatic arenas.",
    "What is the SymbolLookup?|Looks up symbols in native libraries. loaderLookup for JNI libraries.",
    "What is the Linker interface?|Links Java methods to native functions. downcallHandle, upcallStub.",
    "What is a value class?|Inline class without identity. Stack-allocated. Project Valhalla preview.",
    "What are primitive classes?|User-defined primitives with no identity. ValueType in JVM.",
    "What are specialized generics?|Generics over primitives. ArrayList<int> without boxing. Valhalla.",
    "What is the keySet view in Map?|Returns Set view of keys. Changes reflected in map.",
    "What is the entrySet view?|Set<Map.Entry<K,V>> view. Modifying entries affects map.",
    "What is the values view?|Collection<V> view of map values. Modifications reflected.",
    "What is the Map.Entry interface?|Key-value pair. getKey, getValue, setValue.",
    "What is the Map.Entry.comparingByKey?|Comparator for Map.Entry by key.",
    "What is the Map.Entry.comparingByValue?|Comparator for Map.Entry by value.",
    "What is the Iterable.forEach?|forEach(Consumer) default method. forEach(System.out::println).",
    "What is the Collection.removeIf?|Removes all elements matching predicate.",
    "What is the List.replaceAll?|Replaces each element with unary operator result.",
    "What is the List.sort?|Sorts list in-place with comparator.",
    "What is the Map.compute?|Computes new value for key. If absent, function receives null.",
    "What is the Map.computeIfAbsent?|Computes value only if key absent. Useful for lazy init.",
    "What is the Map.computeIfPresent?|Computes value only if key present.",
    "What is the Map.merge?|Merges value with existing using remapping function.",
    "What is the Map.putIfAbsent?|Puts value only if key absent. Returns old or null.",
    "What is the Map.replace?|Replaces entry only if present. Key+oldValue overload.",
    "What is the Map.getOrDefault?|Returns default if key absent.",
    "What is the Stream.Builder?|Mutable builder for streams. accept, add, build.",
    "What is the IntStream.range?|range(0, 10) is 0-9. rangeClosed(0, 10) is 0-10.",
    "What is the IntStream.iterate?|iterate(seed, hasNext, next) for finite streams.",
    "What is the LongStream.range?|Same as IntStream but for longs.",
    "What is the DoubleStream.generate?|Infinite double stream from DoubleSupplier.",
    "What is the Optional.stream?|Converts Optional to Stream of 0 or 1 elements. Java 9+.",
    "What is the Optional.ifPresentOrElse?|ifPresent then consumer, else runnable. Java 9+.",
    "What is the Optional.or?|Returns Optional from supplier if empty. Java 9+.",
    "What is the Optional.orElseThrow?|Throws NoSuchElementException if empty. Java 10+.",
    "What is the Collectors.filtering?|Filters before collecting. Java 9+.",
    "What is the Collectors.flatMapping?|flatMaps before collecting. Java 9+.",
    "What is the Stream.iterate with predicate?|iterate(seed, hasNext, next) finite stream. Java 9+.",
    "What is the Stream.dropWhile?|Drops elements while true, then passes rest. Java 9+.",
    "What is the Stream.takeWhile?|Takes elements while true, then stops. Java 9+.",
    "What is the Stream.ofNullable?|Single element stream or empty. Java 9+.",
    "What is the List.of?|Creates unmodifiable list. Nulls forbidden. Java 9+.",
    "What is the Set.of?|Creates unmodifiable set. No duplicates. Java 9+.",
    "What is the Map.of?|Creates unmodifiable map up to 10 entries. Java 9+.",
    "What is the Map.ofEntries?|Creates unmodifiable map with varargs of Map.entry. Java 9+.",
    "What is the Optional.stream?|Converts to Stream. 0 or 1 elements.",
    "What is the Collectors.teeing?|Collects to two collectors and merges. Java 12+.",
    "What is the String.isBlank?|Returns true if string empty or whitespace. Java 11+.",
    "What is the String.lines?|Splits string into Stream of lines. Java 11+.",
    "What is the String.strip?|Removes leading/trailing whitespace. Java 11+.",
    "What is the String.repeat?|Repeats string n times. Java 11+.",
    "What is the String.indent?|Indents each line by n spaces. Java 12+.",
    "What is the String.transform?|Applies function to string. Java 12+.",
    "What is the String.formatted?|Instance-level format: 'Hello %s'.formatted(name). Java 13+.",
    "What is the String.stripIndent?|Strips common leading whitespace. Text block helper. Java 14+.",
    "What is the String.translateEscapes?|Unescapes Java escape sequences. Java 14+.",
    "What is the text block syntax?|\"\"\" multi-line string \"\"\". Preserves indentation. Java 13+.",
]
b("Java Core", j5, "Junior", "Java")

j5m = [
    "Explain JVM TI (Tool Interface)|Native programming interface for JVM agents. Events for class load, breakpoints, heap.",
    "What is the Attach API?|com.sun.tools.attach. Attach agent to running JVM. VirtualMachine.",
    "What is the JMX architecture?|MBean server. Platform MBeans. Remote via RMI/JMXMP. jconsole tool.",
    "What is the MBean pattern?|Standard MBean: interface + implementation. MXBean for complex types.",
    "What is the NotificationEmitter?|MBeans emit notifications. NotificationListener interface.",
    "What is the ServiceLoader?|SPI discovery. META-INF/services. Provides implementations on demand.",
    "What is the ServiceLoader.Stream?|Lazy stream of service providers. Java 9+.",
    "What is the Multi-Release JAR?|MR-JAR: different class versions per Java version. META-INF/versions.",
    "What is the jlink plugin?|Creates custom runtime. Plugins: compress, strip-debug, include-locales.",
    "What is the jdeps module graph?|jdeps --module-path outputs module dependency graph as Dot/GraphML.",
    "What is the jfr command?|Java Flight Recorder: jfr dump, jfr print, jfr configure.",
    "What is the jcmd DiagnosticCommand?|jcmd PID help. Thread.print, GC.heap_dump, VM.flags.",
    "What is the JVMCI?|JVM Compiler Interface. Custom JIT compiler via Graal JIT.",
    "What is the graal JIT?|JIT compiler written in Java. Isolated from HotSpot. JVMCI enabled.",
    "What is the Epsilon GC?|No-op GC. No memory reclamation. For short-lived apps, testing.",
    "What is the SerialGC young collection?|Single-threaded. Copy live objects from Eden+S0 to S1.",
    "What is the ParallelGC old collection?|Multi-threaded mark-sweep-compact. Compacts old gen.",
    "What is the G1 remembered set?|Per-region set of cards with incoming references. Refines concurrently.",
    "What is the G1 concurrent marking?|SATB (Snapshot-At-The-Beginning) algorithm. Concurrent phase.",
    "What is the ZGC load barrier?|Read barrier checks pointer coloring. Remap/relocate on access.",
    "What is the ZGC relocation set?|Set of regions being compacted. Concurrent relocation thread.",
    "What is the Shenandoah Brooks pointer?|Forwarding pointer stored before object. Indicates moved state.",
    "What is the Shenandoah evacuation?|Concurrent copy of live objects. Brooks pointer updated.",
    "What is the Shenandoah update refs?|Scans heap to update references to moved objects. Concurrent.",
    "What is the heap profiling with JFR?|JFR events: AllocationRequiringGC, OldObjectSample, GarbageCollection.",
    "What is the object sample interval?|-XX:ObjectSampleAgeSampleInterval for JFR OldObjectSample.",
    "What is the GC stats via jstat?|jstat -gcutil PID: S0/S1/Eden/Old/Meta usage and GC counts.",
    "What is the VM info via jinfo?|jinfo PID: JVM flags. -flag to get/set specific flag.",
    "What is the VM flags via jcmd?|jcmd PID VM.flags prints all flag values.",
    "What is the native memory tracking?|-XX:NativeMemoryTracking=summary/detail. jcmd VM.native_memory.",
]
b("JVM Internals", j5m, "Middle", "Java")

# ========== Python (300) ==========
p5 = [
    "What is the @property setter?|@name.setter decorator for property write access.",
    "What is the @property deleter?|@name.deleter decorator for property deletion.",
    "What is the __slots__ in inheritance?|Subclass must define its own __slots__. Parent slots still work.",
    "What is the __init_subclass__ hook?|Called when subclass created. For registration patterns.",
    "What is the __set_name__ hook?|Descriptor protocol: called when descriptor assigned to class attr.",
    "What is the __subclasshook__?|ABC method for issubclass customization. Virtual subclasses.",
    "What is the __instancecheck__?|Customizes isinstance behavior on a class.",
    "What is the __subclasscheck__?|Customizes issubclass behavior on a class.",
    "What is the __class_getitem__?|For parameterized generics: list[int] invokes this.",
    "What is the __mro_entries__?|MRO entry manipulation in class creation.",
    "What is the __prepare__?|Metaclass method: returns namespace dict for class body.",
    "What is the __init_subclass__ vs metaclass?|__init_subclass__ simpler than metaclass for class registration.",
    "What is the ABCMeta?|Metaclass for ABCs. Registers abstract methods. Prevents instantiation.",
    "What is the @abstractmethod?|Marks method as abstract. Subclass must override.",
    "What is the @abstractclassmethod?|Combined abstract and classmethod (legacy, use @abstractmethod with @classmethod).",
    "What is the @abstractstaticmethod?|Combined abstract and staticmethod (legacy).",
    "What is the @abstractproperty?|Abstract property. Use @abstractmethod + @property instead.",
    "What is the @final decorator?|typing.final marks method as not-overridable. Python 3.8+.",
    "What is the @runtime_checkable protocol?|Makes Protocol checkable with isinstance at runtime.",
    "What is the @dataclass frozen?|@dataclass(frozen=True) creates immutable instances.",
    "What is the @dataclass order?|@dataclass(order=True) generates comparison methods.",
    "What is the @dataclass kw_only?|@dataclass(kw_only=True) fields become keyword-only. Python 3.10+.",
    "What is the @dataclass slots?|@dataclass(slots=True) generates __slots__. Python 3.10+.",
    "What is the field descriptor?|field(default=0, repr=False) customizes dataclass field behavior.",
    "What is the InitVar in dataclass?|Init-only variable. Passed to __post_init__ but not stored.",
    "What is the __post_init__?|Dataclass hook after __init__. For validation and derived fields.",
    "What is the @enum.unique?|Decorator ensuring no duplicate enum values.",
    "What is the Enum auto()?|enum.auto() auto-assigns values. Starts at 1.",
    "What is the IntEnum?|Enum that also inherits int. Comparable to ints.",
    "What is the StrEnum?|Enum that also inherits str. Python 3.11+.",
    "What is the Flag enum?|Enum for bit flags. |, &, ^, ~ operators. NamedFlag for ease.",
    "What is the IntFlag?|Integer flag enum. Bit operations return IntFlag.",
    "What is the Enum member order?|Enum members ordered by definition order. __members__ preserves.",
    "What is the Enum aliases?|Multiple names for same value. @unique prevents.",
    "What is the __init_subclass__ in Enum?|Hook when Enum subclass created. For custom Enum patterns.",
    "What is the functools.cache?|Simpler alias for lru_cache(maxsize=None). Python 3.9+.",
    "What is the functools.cached_property?|Property evaluated once then cached. Python 3.8+.",
    "What is the functools.singledispatchmethod?|Single dispatch on method first argument. Python 3.8+.",
    "What is the functools.total_ordering?|Generates comparison methods from __eq__ and one __lt__/__le__/__gt__/__ge__.",
    "What is the functools.reduce?|Apply function cumulatively: reduce(add, [1,2,3]) => 6.",
    "What is the itertools.chain?|Chain iterables: chain([1,2], [3,4]) => 1,2,3,4.",
    "What is the itertools.combinations?|All r-length combinations: combinations('ABC', 2) => AB, AC, BC.",
    "What is the itertools.permutations?|All r-length permutations: permutations('ABC', 2) => 6 orderings.",
    "What is the itertools.product?|Cartesian product: product('AB', '12') => A1, A2, B1, B2.",
    "What is the itertools.groupby?|Groups consecutive keys: groupby(sorted(data), key_func).",
    "What is the itertools.cycle?|Cycles through iterable infinitely: cycle('ABC') => A, B, C, A, B, C.",
    "What is the itertools.repeat?|Repeats element: repeat(10, 3) => 10, 10, 10.",
    "What is the itertools.count?|Counts from start: count(10, 2) => 10, 12, 14.",
    "What is the itertools.accumulate?|Running accumulation: accumulate([1,2,3]) => 1, 3, 6.",
    "What is the itertools.compress?|Filters with selectors: compress('ABCD', [1,0,1,0]) => A, C.",
    "What is the itertools.dropwhile?|Drops while predicate true, then yields rest.",
    "What is the itertools.takewhile?|Yields while predicate true, then stops.",
    "What is the itertools.filterfalse?|Yields elements where predicate is false.",
    "What is the itertools.starmap?|Maps with *args unpacking: starmap(pow, [(2,3)]) => 8.",
    "What is the itertools.tee?|Creates n independent iterators from single iterable.",
    "What is the itertools.zip_longest?|Zips with fillvalue for shorter iterables.",
    "What is the itertools.islice?|Slice iterable: islice(range(10), 2, 8, 2).",
    "What is the itertools.pairwise?|Successive overlapping pairs: pairwise('ABCD') => AB, BC, CD. Python 3.10+.",
    "What is the operator module?|Functional operators: operator.add, operator.itemgetter, operator.attrgetter.",
    "What is the contextlib.contextmanager?|Creates context manager from generator with yield.",
    "What is the contextlib.suppress?|Suppress specific exceptions: with suppress(FileNotFoundError):.",
    "What is the contextlib.redirect_stdout?|Redirect stdout: with redirect_stdout(f):.",
    "What is the contextlib.closing?|Calls close() on exit: with closing(conn):.",
    "What is the contextlib.nullcontext?|No-op context manager. For conditional context usage.",
    "What is the contextlib.ExitStack?|Dynamically manages multiple context managers.",
    "What is the contextlib.AbstractContextManager?|ABC for context managers.",
    "What is the contextlib.AsyncContextManager?|ABC for async context managers.",
    "What is the asyncio.gather?|Runs awaitables concurrently. Returns list of results.",
    "What is the asyncio.wait?|Waits for awaitables with configurable return_when condition.",
    "What is the asyncio.as_completed?|Returns futures as they complete. Iterator of coroutines.",
    "What is the asyncio.create_task?|Creates asyncio Task from coroutine. Runs concurrently.",
    "What is the asyncio.ensure_future?|Wraps awaitable in Task if not already. Legacy, prefer create_task.",
    "What is the asyncio.sleep?|Non-blocking sleep: await asyncio.sleep(0.1).",
    "What is the asyncio.wait_for?|Coroutine with timeout: await asyncio.wait_for(coro, timeout=5).",
    "What is the asyncio.timeout?|Async context manager for timeout. Python 3.11+.",
    "What is the asyncio.Lock?|Async mutex: async with lock: for async critical section.",
    "What is the asyncio.Semaphore?|Async semaphore: limit concurrent tasks.",
    "What is the asyncio.Event?|Async event: wait() until set(). For notification pattern.",
    "What is the asyncio.Condition?|Async condition variable. notify, wait.",
    "What is the asyncio.Queue?|Async queue. await queue.get(), await queue.put().",
    "What is the asyncio.subprocess?|Async subprocess: await asyncio.create_subprocess_exec.",
    "What is the asyncio.run?|Entry point for async: asyncio.run(main()). Event loop management.",
    "What is the asyncio.get_event_loop?|Returns running event loop. Called from coroutine.",
    "What is the asyncio.get_running_loop?|Returns running loop or raises RuntimeError.",
    "What is the asyncio.TaskGroup?|Structured concurrency: async with TaskGroup() as tg: tg.create_task(). Python 3.11+.",
    "What is the asyncio.timeout_at?|Timeout at absolute time. Python 3.11+.",
    "What is the asyncio.to_thread?|Runs sync function in thread pool. await asyncio.to_thread(blocking_fn). Python 3.9+.",
]
b("Python Advanced", p5, "Middle", "Python")

# ========== Rust (250) ==========
r5 = [
    "What is the Result.is_ok?|Returns true if Result is Ok.",
    "What is the Result.is_err?|Returns true if Result is Err.",
    "What is the Result.ok?|Converts Result to Option. Ok(v) => Some(v), Err => None.",
    "What is the Result.err?|Converts to Option. Err(e) => Some(e), Ok => None.",
    "What is the Result.map?|Maps Ok value: result.map(|v| v * 2).",
    "What is the Result.map_err?|Maps Err value: result.map_err(|e| e.to_string()).",
    "What is the Result.and_then?|Chains Result-returning function: result.and_then(|v| Ok(v * 2)).",
    "What is the Result.or_else?|Chains on error: result.or_else(|_| Ok(default)).",
    "What is the Result.unwrap_or?|Returns value or default: result.unwrap_or(0).",
    "What is the Result.unwrap_or_else?|Returns value or computed: result.unwrap_or_else(|| compute()).",
    "What is the Result.expect?|Panics with message if Err: result.expect('should never fail').",
    "What is the Result.transpose?|Transposes Result<Option<T>> to Option<Result<T>>.",
    "What is the Option.is_some?|Returns true if Option is Some.",
    "What is the Option.is_none?|Returns true if Option is None.",
    "What is the Option.map?|Maps inner value: opt.map(|v| v * 2).",
    "What is the Option.and_then?|Chains Option-returning function.",
    "What is the Option.or_else?|Returns alternative if None.",
    "What is the Option.unwrap?|Panics if None. Use with caution.",
    "What is the Option.unwrap_or?|Returns default if None: opt.unwrap_or(0).",
    "What is the Option.expect?|Panics with message if None.",
    "What is the Option.take?|Takes value, replaces with None. Returns Some(v) or None.",
    "What is the Option.replace?|Replace value, returns old: opt.replace(new_val).",
    "What is the Option.filter?|Some(v) if predicate true, else None.",
    "What is the Option.flatten?|Converts Option<Option<T>> to Option<T>.",
    "What is the Option.as_ref?|Converts Option<T> to Option<&T>.",
    "What is the Option.as_mut?|Converts Option<T> to Option<&mut T>.",
    "What is the Option.map_or?|Maps or returns default.",
    "What is the Option.map_or_else?|Maps or computes default.",
    "What is the Iterator.any?|Returns true if any element satisfies predicate.",
    "What is the Iterator.all?|Returns true if all elements satisfy predicate.",
    "What is the Iterator.find?|Returns first Some matching predicate.",
    "What is the Iterator.position?|Index of first matching element.",
    "What is the Iterator.rposition?|Index from end of first matching.",
    "What is the Iterator.max?|Maximum element by Ord.",
    "What is the Iterator.min?|Minimum element by Ord.",
    "What is the Iterator.sum?|Sum of elements by Sum trait.",
    "What is the Iterator.product?|Product of elements by Product trait.",
    "What is the Iterator.partition?|Splits into two collections by predicate.",
    "What is the Iterator.try_fold?|Fold that short-circuits on error/None.",
    "What is the Iterator.try_for_each?|For_each that short-circuits.",
    "What is the Iterator.scan?|Stateful map: scan(init, |state, x| option).",
    "What is the Iterator.inspect?|Calls closure on each element without consuming.",
    "What is the Iterator.copied?|Copies elements from &T to T.",
    "What is the Iterator.cloned?|Clones elements from &T to T.",
    "What is the Iterator.cycle?|Repeats iterator infinitely.",
    "What is the Iterator.intersperse?|Inserts separator between elements. Nightly.",
    "What is the Iterator.map_while?|Maps while predicate true. Collects until None.",
    "What is the Iterator.flatten?|Flattens nested iterators.",
    "What is the Iterator.flat_map?|Maps to iterator then flattens.",
    "What is the Iterator.filter_map?|Filter + map in one step: filter_map(|x| x.parse().ok()).",
]
b("Rust Advanced", r5, "Middle", "Rust")

# ========== Go (200) ==========
g5 = [
    "What is the encoding/json.MarshalIndent?|Pretty-prints JSON with indent prefix and indentation.",
    "What is the json.RawMessage?|Deferred JSON decoding. Store as raw bytes until needed.",
    "What is the json.Encoder?|Encodes directly to writer. SetIndent for pretty print.",
    "What is the json.Decoder?|Decodes from reader. Use for streaming JSON.",
    "What is the json.Decoder.Token?|Reads JSON tokens sequentially. For streaming parsing.",
    "What is the json.Decoder.More?|Returns true if more tokens remain.",
    "What is the json.Decoder.Buffered?|Returns buffered bytes remaining.",
    "What is the json.Compact?|Removes whitespace from JSON.",
    "What is the json.Indent?|Adds indentation to JSON.",
    "What is the json.HTMLEscape?|Escapes HTML characters in JSON.",
    "What is the json.Valid?|Checks if bytes are valid JSON.",
    "What is the fmt.Stringer interface?|String() string method. Similar to toString.",
    "What is the error interface?|Error() string method. All errors implement it.",
    "What is the errors.New?|Creates simple error: errors.New('not found').",
    "What is the errors.Unwrap?|Returns wrapped error for Is/As matching.",
    "What is the errors.Is?|Checks if error chain contains target: errors.Is(err, io.EOF).",
    "What is the errors.As?|Finds error in chain matching type: var e *MyError; errors.As(err, &e).",
    "What is the errors.Join?|Joins multiple errors. errors.Is checks each. Go 1.20+.",
    "What is the fmt.Errorf %w verb?|Wraps error: fmt.Errorf('context: %w', err).",
    "What is the hash.Hash interface?|Hash: Write, Sum, Reset. Implemented by SHA256, MD5.",
    "What is the crypto/sha256.New?|sha256.New() returns hash.Hash for SHA-256.",
    "What is the crypto/hmac.New?|HMAC: hmac.New(sha256.New, key).",
    "What is the crypto/rand.Read?|Fills buffer with random bytes. Cryptographically secure.",
    "What is the crypto/rsa.GenerateKey?|Generates RSA key pair. rand.Reader as randomness source.",
    "What is the crypto/x509.CreateCertificate?|Creates X.509 certificate from template.",
    "What is the crypto/tls.Config?|TLS config: Certificates, RootCAs, InsecureSkipVerify.",
    "What is the net.Dial?|Dial connects to address: net.Dial('tcp', 'host:port').",
    "What is the net.Listen?|Listen on address: net.Listen('tcp', ':8080').",
    "What is the net.LookupHost?|DNS lookup: net.LookupHost('example.com') returns IPs.",
    "What is the net.LookupAddr?|Reverse DNS lookup: addr to hostname.",
    "What is the net.Interfaces?|Returns system network interfaces.",
    "What is the net.InterfaceAddrs?|Returns addresses of specific interface.",
    "What is the net.SplitHostPort?|Splits host:port into host and port strings.",
    "What is the net.JoinHostPort?|Joins host and port: net.JoinHostPort('host', '8080').",
    "What is the net.Conn interface?|Read, Write, Close, LocalAddr, RemoteAddr, SetDeadline.",
    "What is the net.Listener interface?|Accept, Close, Addr. Accept blocks for new connection.",
    "What is the net.Resolver?|Custom DNS resolver. Dial, LookupHost, LookupAddr.",
    "What is the net.Dialer?|Custom dialer with Timeout, KeepAlive, Control.",
    "What is the net/http.Transport?|HTTP transport: proxy, TLS config, connection pooling.",
    "What is the http.Client.Timeout?|Client-level timeout for entire request lifecycle.",
]
b("Go Advanced", g5, "Middle", "Go")

# ========== React (200) ==========
rx5 = [
    "What is React.memo with comparison?|React.memo(Comp, (prev, next) => prev.id === next.id).",
    "What is the useRef as instance variable?|const countRef = useRef(0). Like instance field in class.",
    "What is the forwardRef with generics?|const Comp = forwardRef<HTMLDivElement, Props>((props, ref) => ...).",
    "What is the useImperativeHandle with deps?|useImperativeHandle(ref, () => ({}), [dep1, dep2]).",
    "What is the useLayoutEffect for measurements?|useLayoutEffect for reading DOM layout before paint.",
    "What is the useDebugValue with formatter?|useDebugValue(value, v => JSON.stringify(v)).",
    "What is the useSyncExternalStore with selector?|useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot).",
    "What is the useTransition with timeoutMs?|startTransition({ timeoutMs: 3000 }) for timeout fallback.",
    "What is the useDeferredValue with initial?|useDeferredValue(value, { initialValue: null }).",
    "What is the useId with prefix?|useId() returns `:r1:`. Works for accessibility attributes.",
    "What is the createPortal second argument?|createPortal(children, domNode). domNode must be valid DOM.",
    "What is the flushSync with callbacks?|flushSync(() => setState(...)). Forces synchronous commit.",
    "What is the act function in tests?|await act(async () => { render(<App />) }) ensures updates processed.",
    "What is the renderHook from testing library?|const { result } = renderHook(() => useCustomHook(x)).",
    "What is the waitFor utility?|await waitFor(() => expect(screen.getByText('done')).toBeInTheDocument()).",
    "What is the screen utility?|screen.getByText, screen.getByRole, screen.getByTestId.",
    "What is the userEvent?|import userEvent from '@testing-library/user-event'. await user.click(btn).",
    "What is the findBy queries?|screen.findByText('Done') returns promise. Combines waitFor + getBy.",
    "What is the queryBy vs getBy?|queryBy returns null if not found. getBy throws if not found.",
    "What is the within utility?|within(element).getByText('Nested'). Scopes queries to element.",
    "What is the cleanup in tests?|afterEach(cleanup). Automatically in new testing library.",
    "What is the jest.fn?|const mock = jest.fn(). mockReturnValue, mockResolvedValue.",
    "What is the jest.spyOn?|jest.spyOn(obj, 'method'). mockImplementation, mockRestore.",
    "What is the jest.mock?|jest.mock('module'). Manual mock or __mocks__ directory.",
    "What is the MSW library?|Mock Service Worker. Intercepts network in tests. Handlers for routes.",
    "What is the MSW server setup?|setupServer(...handlers). beforeAll listen, afterEach reset, afterAll close.",
    "What is the MSW handler pattern?|rest.get('/api/user', (req, res, ctx) => res(ctx.json({}))).",
    "What is the Cypress component test?|cy.mount(<Component />). cy.get('button').click().",
    "What is the Playwright component test?|test('click', async ({ mount }) => { const c = await mount(<Comp />) }).",
    "What is the Storybook?|Component explorer. Stories for each state. Addons for testing, docs.",
    "What is the Storybook CSF format?|Component Story Format. export default { title, component }. export const Basic = {}.",
    "What is the Storybook args?|export const Primary = { args: { variant: 'primary' } }.",
    "What is the chromatic?|Visual regression testing. Screenshots per story. Git integration.",
    "What is the bundle analysis?|webpack-bundle-analyzer or vite-bundle-visualizer. Identify large deps.",
    "What is the tree shaking?|Dead code elimination. ESM imports help. Side-effect-free packages.",
    "What is the code splitting by route?|React.lazy per route. const Home = lazy(() => import('./Home')).",
    "What is the code splitting by component?|Lazy load heavy components: const Chart = lazy(() => import('./Chart')).",
    "What is the preloading with React.lazy?|Preload: const Comp = lazy(() => import('./Comp')). Not loaded until rendered.",
    "What is the dynamic import syntax?|import('./Module').then(mod => mod.default). For non-React code.",
    "What is the preload/prefetch hints?|<link rel='preload' href='chunk.js' as='script'>. Browser hints.",
]
b("React Advanced", rx5, "Middle", "React")

# ========== Kotlin (200) ==========
k5 = [
    "What is the File.readText?|Reads file to string: File('path').readText().",
    "What is the File.writeText?|Writes string to file: File('path').writeText('content').",
    "What is the File.appendText?|Appends string to file.",
    "What is the File.readLines?|Reads file lines to List<String>.",
    "What is the File.forEachLine?|Iterates file lines lazily.",
    "What is the File.useLines?|Auto-closes file after processing lines.",
    "What is the File.inputStream?|Opens file as InputStream. Use .use { } for auto-close.",
    "What is the File.bufferedReader?|Buffered reader for file. use { reader -> reader.readText() }.",
    "What is the File.bufferedWriter?|Buffered writer for file. use { it.write('data') }.",
    "What is the File.extension?|Returns file extension: 'file.txt'.extension => 'txt'.",
    "What is the File.nameWithoutExtension?|'file.txt'.nameWithoutExtension => 'file'.",
    "What is the File.resolve?|Resolves child path: File('dir').resolve('file.txt').",
    "What is the File.resolveSibling?|Resolves sibling path relative to parent.",
    "What is the File.startsWith?|Checks if path starts with another path.",
    "What is the File.endsWith?|Checks if path ends with another path.",
    "What is the File.invariantSeparatorsPath?|Path with '/' separators regardless of platform.",
    "What is the File.toRelativeString?|Relative path from base to this file.",
    "What is the File.isRooted?|Checks if path is absolute/rooted.",
    "What is the File.normalize?|Resolves . and .. in path.",
    "What is the File.toFile?|Converts String or Path to java.io.File.",
    "What is the File.walk?|Walks directory tree: file.walk().filter { it.extension == 'kt' }.toList().",
    "What is the File.walkTopDown?|Walks directory top-down. Default walk order.",
    "What is the File.walkBottomUp?|Walks directory bottom-up. Children before parent.",
    "What is the File.copyTo?|Copies file to target. overwrite parameter.",
    "What is the File.copyRecursively?|Copies directory tree recursively.",
    "What is the File.deleteRecursively?|Deletes directory and contents.",
    "What is the File.mkdir?|Creates single directory.",
    "What is the File.mkdirs?|Creates directory with parents.",
    "What is the File.createNewFile?|Creates file atomically. Returns boolean.",
    "What is the File.createTempFile?|Creates temp file in specified/auto dir.",
    "What is the File.createTempDir?|Creates temp directory.",
    "What is the File.exists?|Checks if file or directory exists.",
    "What is the File.isFile/isDirectory?|Checks file/directory type.",
    "What is the File.isHidden?|Checks if file is hidden on platform.",
    "What is the File.canRead/canWrite/canExecute?|Permission checks.",
    "What is the File.setReadable/setWritable/setExecutable?|Permission setters.",
    "What is the File.lastModified?|Returns last modified timestamp.",
    "What is the File.setLastModified?|Sets last modified timestamp.",
    "What is the File.length?|Returns file size in bytes.",
    "What is the File.freeSpace/totalSpace?|Disk space information.",
    "What is the File.toPath?|Converts to java.nio.file.Path.",
    "What is the File.toURI?|Converts to URI with file scheme.",
    "What is the File.list?|Lists directory contents as String array.",
    "What is the File.listFiles?|Lists directory contents as File array.",
    "What is the File.listRoots?|Lists filesystem roots (C:\\, /). Static method.",
    "What is the File.parent?|Parent directory File.",
    "What is the File.name?|File name as string.",
    "What is the File.absolutePath?|Absolute path string.",
    "What is the File.canonicalPath?|Canonical path (resolves symlinks, . and ..).",
    "What is the File.toPath vs toFile?|toPath returns nio Path. toFile works on String/Path receivers.",
    "What is the URI?|java.net.URI for uniform resource identifiers. Scheme, host, path, query.",
    "What is the URL?|java.net.URL for network resource. openStream, openConnection.",
    "What is the HttpURLConnection?|URL-based HTTP. connect, responseCode, inputStream.",
    "What is the URLEncoder/URLDecoder?|Percent-encoding for URLs. encode, decode with charset.",
    "What is the InetAddress?|IP address: getByName, getLocalHost, isReachable.",
    "What is the NetworkInterface?|Network interface info: getByName, getNetworkInterfaces.",
    "What is the Socket and ServerSocket?|TCP socket: Socket(host, port). ServerSocket(port).",
    "What is the DatagramSocket?|UDP socket: send, receive packets.",
    "What is the MulticastSocket?|Multicast UDP: joinGroup, leaveGroup.",
    "What is the ProcessBuilder?|OS process: ProcessBuilder('ls', '-la'). redirectOutput.",
    "What is the Runtime.exec?|Execute command: Runtime.getRuntime().exec('cmd'). Legacy.",
    "What is the Timer and TimerTask?|Scheduled tasks: Timer().schedule(task, delay, period).",
    "What is the UUID.randomUUID?|Generates random UUID: UUID.randomUUID().toString().",
    "What is the Currency?|Currency info: getInstance(Locale), symbol, currencyCode.",
    "What is the Locale?|Locale for i18n: Locale.US, Locale('fr', 'FR').",
    "What is the ResourceBundle?|i18n resources: ResourceBundle.getBundle('Messages', locale).",
    "What is the MessageFormat?|Formats with placeholders: MessageFormat.format('Hello {0}', name).",
    "What is the BreakIterator?|Text boundary detection: word, line, sentence, character.",
    "What is the Collator?|Locale-aware string comparison: Collator.getInstance(locale).",
    "What is the SimpleDateFormat?|Date format: SimpleDateFormat('yyyy-MM-dd'). Thread-unsafe.",
    "What is the NumberFormat?|Number formatting: NumberFormat.getCurrencyInstance(Locale.US).",
    "What is the DecimalFormat?|Pattern-based number formatting: DecimalFormat('#,##0.00').",
    "What is the ChoiceFormat?|Pluralization format: ChoiceFormat for 0#none|1#one|2#{0,number}.",
    "What is the Bidi?|Bidirectional text: Bidi(text, Bidi.DIRECTION_DEFAULT_LEFT_TO_RIGHT).",
    "What is the Normalizer?|Unicode normalization: Normalizer.normalize(text, Form.NFC).",
    "What is the Charset?|Character encoding: Charset.forName('UTF-8'), availableCharsets.",
    "What is the CharsetEncoder/Decoder?|Convert bytes to/from chars: encoder.encode(charBuffer).",
]
b("Kotlin Advanced", k5, "Junior", "Kotlin")

# ========== General (200) ==========
g5g = [
    "What is a linear regression?|Statistical method: y = mx + b. Minimize MSE.",
    "What is logistic regression?|Binary classification: sigmoid(w*x + b). Probability output.",
    "What is a decision tree?|Tree with feature-split nodes. Entropy/Gini for splits.",
    "What is random forest?|Ensemble of decision trees. Bagging. Reduces overfitting.",
    "What is a neural network?|Layers of neurons. Activation functions. Backpropagation.",
    "What is gradient descent?|Optimization: follow negative gradient to minimize loss.",
    "What is stochastic gradient descent?|Update weights per sample. Noisy but fast convergence.",
    "What is a convolutional neural network?|Conv layers for spatial features. Image processing.",
    "What is a recurrent neural network?|Hidden state for sequential data. LSTM for long memory.",
    "What is a transformer?|Self-attention mechanism. Positional encoding. BERT, GPT.",
    "What is attention mechanism?|Query, Key, Value attention. Weighted sum based on relevance.",
    "What is the training/validation/test split?|Train: learn. Validation: tune hyperparams. Test: evaluate.",
    "What is cross-validation?|k-fold: split into k parts. Train on k-1, test on 1. Repeat.",
    "What is overfitting?|Model fits training noise. Poor generalization. Regularization helps.",
    "What is underfitting?|Model too simple. High bias. More capacity needed.",
    "What is regularization?|L1 (Lasso): absolute penalty. L2 (Ridge): squared penalty.",
    "What is dropout?|Randomly zero neurons during training. Prevents co-adaptation.",
    "What is batch normalization?|Normalize layer inputs. Faster training. Reduces internal covariate shift.",
    "What is a confusion matrix?|TP, FP, TN, FN counts. Accuracy, precision, recall, F1 derived.",
    "What is precision?|TP / (TP + FP). Of positive predictions, how many correct.",
    "What is recall?|TP / (TP + FN). Of actual positives, how many found.",
    "What is F1 score?|Harmonic mean of precision and recall. 2 * (P * R) / (P + R).",
    "What is ROC curve?|TPR vs FPR at various thresholds. AUC is area under curve.",
    "What is a ROC AUC?|Probability that classifier ranks random positive higher than negative.",
    "What is bias-variance tradeoff?|Bias: error from wrong assumptions. Variance: error from sensitivity.",
    "What is PCA?|Principal Component Analysis. Dimensionality reduction. Eigenvectors of covariance.",
    "What is t-SNE?|Non-linear dimensionality reduction. Preserves local structure. Visualization.",
    "What is k-means?|Unsupervised clustering. Assign to nearest centroid. Update centroids.",
    "What is hierarchical clustering?|Agglomerative: merge closest clusters. Dendrogram visualization.",
    "What is DBSCAN?|Density-based clustering. Core points. Noise points. Handles arbitrary shapes.",
    "What is a support vector machine?|Max-margin classifier. Kernel trick for non-linear.",
    "What is a kernel method?|Implicit high-dimensional mapping. RBF, polynomial, linear kernels.",
    "What is naive Bayes?|Conditional independence assumption. P(class|features) proportional.",
    "What is k-nearest neighbors?|Majority vote of k nearest samples. Non-parametric.",
    "What is an ensemble method?|Combine multiple models. Bagging, boosting, stacking.",
    "What is bagging?|Bootstrap samples. Train models independently. Average predictions.",
    "What is boosting?|Sequential models. Correct previous errors. AdaBoost, XGBoost.",
    "What is XGBoost?|Gradient boosted trees. Regularization. Parallel/GPU. Kaggle favorite.",
    "What is LightGBM?|Gradient boosting with GOSS and EFB. Leaf-wise growth. Faster.",
    "What is CatBoost?|Gradient boosting with categorical feature handling. Ordered boosting.",
    "What is a recommender system?|Collaborative filtering. Matrix factorization. User-item interactions.",
    "What is collaborative filtering?|Similar users/items. User-based: find similar users. Item-based: similar items.",
    "What is matrix factorization?|Decompose user-item matrix into latent factors. SVD, NMF.",
    "What is content-based filtering?|Recommend based on item features. User profiles from history.",
    "What is reinforcement learning?|Agent learns from rewards. State, action, reward. Policy optimization.",
    "What is Q-learning?|Off-policy RL. Q(s,a) = reward + gamma * max Q(s',a'). Bellman equation.",
    "What is a Markov decision process?|(S, A, P, R, gamma). State transitions with Markov property.",
    "What is Monte Carlo method?|Estimate via random sampling. Simulation-based approximation.",
    "What is a genetic algorithm?|Evolutionary: selection, crossover, mutation. Fitness-based.",
    "What is simulated annealing?|Probabilistic optimization. Accept worse solutions with decreasing probability.",
]
b("General", g5g, "Middle", "General")

# WRITE
new_part = "\n".join(new_q_calls) + "\n"

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before_seed)
    f.write(new_part)
    f.write(from_seed)

total_new = len(new_q_calls)
print(f"Batch 5 added {total_new} new questions")

with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
total = content.count("\n  Q(")
print(f"Total Q() calls: {total}")