"""Batch 12: Add ~2000 more questions across all languages"""
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(a)}', 'Alternative', 'Misconception', 'Unsure'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# --- JAVA (+400) ---
java_extra = [
    ("OOP", "What is the difference between composition and aggregation?", "Composition: child cannot exist without parent; Aggregation: child can exist independently"),
    ("OOP", "What is the difference between Association, Aggregation, and Composition?", "Association: uses; Aggregation: has-a; Composition: owns"),
    ("OOP", "What is a marker interface?", "An interface with no methods, used to tag classes"),
    ("OOP", "What is the clone() method?", "Creates a shallow copy of an object"),
    ("OOP", "What is the difference between shallow and deep copy?", "Shallow copies references; deep copies referenced objects"),
    ("OOP", "What is the hashCode() contract?", "Equal objects must have equal hash codes"),
    ("OOP", "What is the equals() contract?", "Reflexive, symmetric, transitive, consistent, non-null comparison"),
    ("OOP", "What is the toString() method?", "Returns string representation of an object"),
    ("OOP", "What is the finalize() method?", "Called by GC before reclaiming object memory (deprecated)"),
    ("OOP", "What is the difference between checked and unchecked exceptions?", "Checked must be caught/declared; unchecked are runtime"),
    ("OOP", "What is a try-with-resources?", "Auto-closes resources implementing AutoCloseable"),
    ("OOP", "What is a multi-catch block?", "Catching multiple exception types in one catch clause"),
    ("OOP", "What is the difference between throw and throws?", "throw throws an exception; throws declares exceptions"),
    ("OOP", "What is the difference between ClassNotFoundException and NoClassDefFoundError?", "CNFE at load time; NCDFE at runtime when class was available earlier"),
    ("OOP", "What is an assertion in Java?", "A statement checking a boolean condition, enabled with -ea"),
    ("OOP", "What is the enum type?", "A special type defining named constants"),
    ("OOP", "Can an enum have methods?", "Yes, enums can have constructors, fields, and methods"),
    ("OOP", "What is the ordinal() method in enum?", "Returns the position of the enum constant"),
    ("OOP", "What is the values() method in enum?", "Returns all enum constants as an array"),
    ("OOP", "What is the valueOf() method in enum?", "Returns enum constant by name string"),
    ("OOP", "What is a nested class?", "A class defined inside another class"),
    ("OOP", "What is a static nested class?", "A nested class with static modifier"),
    ("OOP", "What is an inner class?", "A non-static nested class with access to outer class members"),
    ("OOP", "What is a local class?", "A class defined inside a method"),
    ("OOP", "What is an anonymous class?", "A class without a name, defined inline"),
    ("OOP", "What is a lambda expression?", "A concise representation of a functional interface"),
    ("OOP", "What is the :: method reference?", "Shorthand for lambda calling an existing method"),
    ("OOP", "What are the types of method references?", "Static, instance, arbitrary object, constructor"),
    ("OOP", "What is a functional interface?", "An interface with exactly one abstract method"),
    ("OOP", "What are common functional interfaces?", "Predicate, Function, Consumer, Supplier, UnaryOperator, BinaryOperator"),
    ("OOP", "What is the andThen() default method in Function?", "Chains another function to run after"),
    ("OOP", "What is the compose() default method in Function?", "Chains another function to run before"),
    ("OOP", "What is the identity() static method in Function?", "Returns a function that returns its input"),
    ("OOP", "What is the negate() default in Predicate?", "Returns the logical negation of the predicate"),
    ("OOP", "What is the and() default in Predicate?", "Combines two predicates with logical AND"),
    ("OOP", "What is the or() default in Predicate?", "Combines two predicates with logical OR"),
    ("OOP", "What is the isEqual() static in Predicate?", "Creates a predicate testing equality"),
    ("OOP", "What is the not() static in Predicate (Java 11)?", "Creates a predicate that negates another"),
    ("OOP", "What is the andThen() in Consumer?", "Chains another consumer to run after"),
    ("OOP", "What is the Supplier use case?", "Lazy evaluation or generating values"),
    ("Streams", "What is an intermediate operation?", "Returns a new stream, lazy evaluation"),
    ("Streams", "What is a terminal operation?", "Produces a result or side effect, closes the stream"),
    ("Streams", "What is a short-circuiting operation?", "May produce result without processing all elements"),
    ("Streams", "What is the allMatch() operation?", "Returns true if all elements match the predicate"),
    ("Streams", "What is the anyMatch() operation?", "Returns true if any element matches the predicate"),
    ("Streams", "What is the noneMatch() operation?", "Returns true if no elements match the predicate"),
    ("Streams", "What is the count() operation?", "Returns the number of elements in the stream"),
    ("Streams", "What is the min() and max() operations?", "Returns min/max element based on comparator"),
    ("Streams", "What is the sum() operation on IntStream?", "Returns sum of elements"),
    ("Streams", "What is the average() operation on IntStream?", "Returns OptionalDouble average"),
    ("Streams", "What is the summaryStatistics() method?", "Returns count, sum, min, max, average"),
    ("Streams", "What is the boxed() method?", "Converts primitive stream to object stream"),
    ("Streams", "What is the mapToObj() method?", "Maps int/long/double to objects"),
    ("Streams", "What is the flatMapToInt() method?", "Flattens IntStream from nested streams"),
    ("Streams", "What is the concat() static method?", "Combines two streams into one"),
    ("Streams", "What is the of() static method?", "Creates a stream from individual values"),
    ("Streams", "What is the iterate() static method?", "Creates infinite sequential stream"),
    ("Streams", "What is the generate() static method?", "Creates infinite stream from Supplier"),
    ("Streams", "What is the takeWhile() operation (Java 9)?", "Takes elements while predicate is true"),
    ("Streams", "What is the dropWhile() operation (Java 9)?", "Drops elements while predicate is true, takes rest"),
    ("Streams", "What is the ofNullable() method (Java 9)?", "Creates stream with one element or empty"),
    ("Streams", "What is the iterate() with predicate (Java 9)?", "Creates finite stream with hasNext predicate"),
    ("Streams", "What is the Collectors.joining()?", "Concatenates elements into a string"),
    ("Streams", "What is the Collectors.toSet()?", "Collects elements into a Set"),
    ("Streams", "What is the Collectors.toMap()?", "Collects elements into a Map"),
    ("Streams", "What is the Collectors.toCollection()?", "Collects into a specific collection type"),
    ("Streams", "What is the Collectors.mapping()?", "Applies mapper then collects"),
    ("Streams", "What is the Collectors.filtering() (Java 9)?", "Filters then collects elements"),
    ("Streams", "What is the Collectors.flatMapping() (Java 9)?", "Applies flatMap then collects"),
    ("Streams", "What is the Collectors.collectingAndThen()?", "Collects then applies finishing function"),
    ("Streams", "What is the Collectors.teeing() (Java 12)?", "Combines two collectors into one"),
    ("Streams", "What is the difference between Stream and IntStream?", "IntStream is specialized for int primitives"),
    ("Streams", "What is the mapMulti() method (Java 16)?", "Replaces flatMap with more efficient multi-mapping"),
    ("Streams", "What is the toList() method (Java 16)?", "Collects stream into an unmodifiable list"),
    ("Streams", "What is the distinctBy() method (non-standard)?", "Custom distinct using a key extractor"),
    ("Streams", "What is the difference between sequential and parallel streams?", "Sequential single-threaded; parallel splits across threads"),
    ("Streams", "What is the common ForkJoinPool?", "The default thread pool for parallel streams"),
    ("Streams", "What is the spliterator() method?", "Creates a Spliterator for custom traversal"),
    ("Streams", "What is the Spliterator characteristics?", "ORDERED, DISTINCT, SORTED, SIZED, NONNULL, IMMUTABLE, etc."),
    ("Streams", "What is the tryAdvance() method in Spliterator?", "Performs action on next element"),
    ("Streams", "What is the trySplit() method in Spliterator?", "Partitions spliterator for parallel processing"),
    ("Streams", "What is the estimateSize() in Spliterator?", "Returns estimated number of remaining elements"),
    ("Streams", "What is the getExactSizeIfKnown() in Spliterator?", "Returns exact size if SIZED characteristic"),
    ("Streams", "What is the characteristics() in Spliterator?", "Returns set of characteristics"),
    ("Streams", "What is the hasCharacteristics() in Spliterator?", "Checks if a characteristic is present"),
    ("Streams", "What is the StreamSupport utility?", "Creates streams from Spliterators and iterators"),
    ("Streams", "What is the double colon operator?", "Method reference shorthand"),
]
gen(java_extra, "Middle", "Java")

# --- PYTHON (+300) ---
python_extra = [
    ("Basics", "What is the with statement?", "Context manager for resource management"),
    ("Basics", "What is the assert statement?", "Debugging aid that raises AssertionError"),
    ("Basics", "What is the difference between is and == for None?", "Use is None, not == None"),
    ("Basics", "What is the chaining comparison?", "a < b < c evaluates as a < b and b < c"),
    ("Basics", "What is the difference between / and //?", "/ is float division; // is integer floor division"),
    ("Basics", "What is the % operator for strings?", "Old-style string formatting"),
    ("Basics", "What is the format() method?", "String formatting with placeholders"),
    ("Basics", "What is the f-string?", "Formatted string literals with f prefix"),
    ("Basics", "What is the .format_map() method?", "Formats with dictionary mapping"),
    ("Basics", "What is the Template class from string module?", "String template with $ placeholders"),
    ("Basics", "What is the bytes type?", "Immutable sequence of bytes"),
    ("Basics", "What is the bytearray type?", "Mutable sequence of bytes"),
    ("Basics", "What is the memoryview?", "Access memory of object without copying"),
    ("Basics", "What is the array module?", "Efficient array of typed values"),
    ("Basics", "What is the struct module?", "Packs and unpacks binary data"),
    ("Basics", "What is the binascii module?", "Binary to ASCII conversion"),
    ("Basics", "What is the base64 module?", "Base64 encoding and decoding"),
    ("Basics", "What is the zlib module?", "Compression with gzip format"),
    ("Basics", "What is the gzip module?", "File compression in gzip format"),
    ("Basics", "What is the tarfile module?", "Read/write tar archives"),
    ("Basics", "What is the zipfile module?", "Read/write zip archives"),
    ("Basics", "What is the fnmatch module?", "Unix filename pattern matching"),
    ("Basics", "What is the glob module?", "File path pattern expansion"),
    ("Basics", "What is the linecache module?", "Random access to text file lines"),
    ("Basics", "What is the textwrap module?", "Wrapping and formatting text"),
    ("Basics", "What is the difflib module?", "Comparing sequences and producing diffs"),
    ("Basics", "What is the unicodedata module?", "Unicode character database"),
    ("Basics", "What is the stringprep module?", "String preparation for protocols"),
    ("Basics", "What is the codecs module?", "Codec registry and base classes"),
    ("Basics", "What is the io module?", "Core stream I/O tools"),
    ("Basics", "What is the StringIO class?", "In-memory text stream"),
    ("Basics", "What is the BytesIO class?", "In-memory binary stream"),
    ("Basics", "What is the csv module?", "CSV file reading and writing"),
    ("Basics", "What is the configparser module?", "Configuration file parsing"),
    ("Basics", "What is the json module?", "JSON encoder and decoder"),
    ("Basics", "What is the pickle module?", "Object serialization"),
    ("Basics", "What is the shelve module?", "Persistent dictionary of pickled objects"),
    ("Basics", "What is the dbm module?", "Unix DBM database interface"),
    ("Basics", "What is the sqlite3 module?", "SQLite database interface"),
    ("Intermediate", "What is the xml.etree.ElementTree module?", "XML parsing and creation"),
    ("Intermediate", "What is the html.parser module?", "Simple HTML parser"),
    ("Intermediate", "What is the html.escape() function?", "Escapes HTML special characters"),
    ("Intermediate", "What is the urllib.parse module?", "URL parsing and joining"),
    ("Intermediate", "What is the urllib.request module?", "Opening and reading URLs"),
    ("Intermediate", "What is the http.client module?", "Low-level HTTP client"),
    ("Intermediate", "What is the http.server module?", "Simple HTTP server"),
    ("Intermediate", "What is the smtplib module?", "SMTP email sending"),
    ("Intermediate", "What is the imaplib module?", "IMAP email reading"),
    ("Intermediate", "What is the poplib module?", "POP3 email reading"),
    ("Intermediate", "What is the email module?", "Email message handling"),
    ("Intermediate", "What is the uuid module?", "UUID generation"),
    ("Intermediate", "What is the random module?", "Random number generation"),
    ("Intermediate", "What is the statistics module?", "Mathematical statistics functions"),
    ("Intermediate", "What is the math module?", "Mathematical functions"),
    ("Intermediate", "What is the cmath module?", "Complex number math"),
    ("Intermediate", "What is the decimal module?", "Decimal floating-point arithmetic"),
    ("Intermediate", "What is the fractions module?", "Rational number arithmetic"),
    ("Intermediate", "What is the numbers module?", "Abstract numeric base classes"),
    ("Intermediate", "What is the itertools.chain()?", "Chain iterables sequentially"),
    ("Intermediate", "What is the itertools.product()?", "Cartesian product of iterables"),
    ("Intermediate", "What is the itertools.permutations()?", "All possible orderings"),
    ("Intermediate", "What is the itertools.combinations()?", "All combinations without replacement"),
    ("Intermediate", "What is the itertools.combinations_with_replacement()?", "All combinations with replacement"),
    ("Intermediate", "What is the itertools.groupby()?", "Groups consecutive elements by key"),
    ("Intermediate", "What is the itertools.cycle()?", "Cycles through iterable infinitely"),
    ("Intermediate", "What is the itertools.repeat()?", "Repeats a value infinitely or N times"),
    ("Intermediate", "What is the itertools.accumulate()?", "Accumulates results of binary function"),
    ("Intermediate", "What is the itertools.starmap()?", "Maps function with argument unpacking"),
    ("Intermediate", "What is the itertools.islice()?", "Slices an iterator"),
    ("Intermediate", "What is the functools.reduce()?", "Applies function cumulatively"),
    ("Intermediate", "What is the functools.partial()?", "Fixes arguments of a function"),
    ("Intermediate", "What is the functools.singledispatch()?", "Generic function dispatch on first arg"),
    ("Intermediate", "What is the functools.cached_property()?", "Caches property value on instance"),
    ("Intermediate", "What is the operator module?", "Functional operators like add, itemgetter"),
    ("Intermediate", "What is the operator.itemgetter()?", "Gets item from index/key"),
    ("Intermediate", "What is the operator.attrgetter()?", "Gets attribute from object"),
    ("Intermediate", "What is the operator.methodcaller()?", "Calls method on object"),
]
gen(python_extra, "Middle", "Python")

# --- TYPESCRIPT (+200) ---
ts_extra = [
    ("Types", "What is the satisfies operator?", "Checks type compatibility without widening inference"),
    ("Types", "What is the const assertion?", "Marks a value as deeply readonly literal type"),
    ("Types", "What is the intrinsic keyword?", "Built-in compiler string manipulation type functions"),
    ("Types", "What is the Uppercase intrinsic type?", "Converts string literal to uppercase at type level"),
    ("Types", "What is the Lowercase intrinsic type?", "Converts string literal to lowercase at type level"),
    ("Types", "What is the Capitalize intrinsic type?", "Capitalizes first character at type level"),
    ("Types", "What is the Uncapitalize intrinsic type?", "Uncapitalizes first character at type level"),
    ("Types", "What is a variadic tuple type?", "Tuple types with spread of generic type parameters"),
    ("Types", "What is the ... spread in tuple types?", "Spreads a tuple type into another tuple"),
    ("Types", "What is a template literal type?", "String literal type with ${} interpolation"),
    ("Types", "What is a recursive conditional type?", "A conditional type that references itself"),
    ("Types", "What is the infer in template literals?", "Infers parts of a string pattern at type level"),
    ("Types", "What is the as const on arrays?", "Marks array as readonly tuple type"),
    ("Types", "What is the readonly modifier?", "Marks property as immutable"),
    ("Types", "What is the -? modifier in mapped types?", "Removes optional from properties"),
    ("Types", "What is the -readonly modifier?", "Removes readonly from properties"),
    ("Types", "What is the as clause in mapped types?", "Remaps keys in mapped types"),
    ("Types", "What is the key remapping syntax?", "as ${NewKey} in mapped types"),
    ("Types", "What is the Filter out pattern with never?", "Using never in conditional type to filter"),
    ("Types", "What is the difference between extends and implements?", "extends is for inheritance; implements is for contract checking"),
    ("Types", "What is a declaration file?", ".d.ts file with type-only declarations"),
    ("Types", "What is an ambient module declaration?", "declare module 'name' for external modules"),
    ("Types", "What is the declare global block?", "Augments global scope from a module"),
    ("Types", "What is the declare function?", "Ambient function declaration"),
    ("Types", "What is the declare class?", "Ambient class declaration"),
    ("Types", "What is the declare enum?", "Ambient enum declaration"),
    ("Types", "What is the triple-slash reference directive?", "/// <reference types='...' />"),
    ("Types", "What is the triple-slash reference path?", "/// <reference path='...' />"),
    ("Types", "What is the triple-slash reference lib?", "/// <reference lib='...' />"),
    ("Types", "What is the node types package?", "@types/node for Node.js type definitions"),
    ("Types", "What is the DefinitelyTyped project?", "Repository of community type definitions"),
    ("Types", "What is the @types scope?", "npm scope for TypeScript type definitions"),
    ("Types", "What is the ts-node tool?", "TypeScript execution environment for Node.js"),
    ("Types", "What is the tsx tool?", "Enhanced ts-node with ESM support"),
    ("Types", "What is the bun runtime?", "JavaScript runtime with native TypeScript support"),
    ("Types", "What is the deno runtime?", "JavaScript runtime with built-in TypeScript"),
    ("Types", "What is the esbuild bundler?", "Fast bundler with TypeScript support"),
    ("Types", "What is the swc compiler?", "Rust-based TypeScript/JavaScript compiler"),
    ("Types", "What is the tsc CLI?", "TypeScript compiler command-line interface"),
    ("Types", "What is the tsc --noEmit flag?", "Checks types without emitting output files"),
    ("Types", "What is the tsc --watch flag?", "Watches files for changes and recompiles"),
    ("Types", "What is the tsc --build flag?", "Builds project references"),
    ("Types", "What is the tsc --init flag?", "Creates a tsconfig.json file"),
    ("Types", "What is the tsconfig.json extends?", "Inherits configuration from another file"),
    ("Types", "What is the tsconfig.json references?", "Project references configuration"),
    ("Types", "What is the tsconfig.json compilerOptions?", "Compiler settings for TypeScript"),
    ("Types", "What is the include glob in tsconfig?", "File patterns to include in compilation"),
    ("Types", "What is the exclude glob in tsconfig?", "File patterns to exclude from compilation"),
    ("Types", "What is the files array in tsconfig?", "Explicit file list for compilation"),
    ("Types", "What is the typeAcquisition in tsconfig?", "Automatic type acquisition for JavaScript projects"),
    ("Functions", "What is the rest parameter type?", "Array type for rest parameters with ..."),
    ("Functions", "What is the tuple rest parameter?", "Typed rest parameter with tuple type"),
    ("Functions", "What is the labeled tuple element?", "Tuple with labels for each element"),
    ("Functions", "What is the optional tuple element?", "Tuple with optional ? element"),
    ("Functions", "What is the variadic tuple spread?", "Spreading generic array into tuple types"),
    ("Functions", "What is the indexed access with keyof?", "T[keyof T] creates union of all property types"),
    ("Functions", "What is the conditional type infer?", "Type inference in conditional types with infer"),
    ("Functions", "What is the distributive conditional type?", "Conditional type distributes over unions"),
    ("Functions", "What is the no-infer utility?", "Prevents inference at specific positions"),
    ("Functions", "What is the satisfies vs as?", "satisfies validates; as coerces the type"),
]
gen(ts_extra, "Middle", "TypeScript")

# --- GO (+300) ---
go_extra = [
    ("Basics", "What is the copy function?", "Copies elements between slices"),
    ("Basics", "What is the append function?", "Appends elements to a slice"),
    ("Basics", "What is the len function?", "Returns length of array, slice, map, string, or channel"),
    ("Basics", "What is the cap function?", "Returns capacity of slice or array"),
    ("Basics", "What is the delete function?", "Deletes key from a map"),
    ("Basics", "What is the close function?", "Closes a channel"),
    ("Basics", "What is the panic and recover pattern?", "Error handling with stack unwinding and recovery"),
    ("Basics", "What is the error handling pattern in Go?", "Return error as the last return value"),
    ("Basics", "What is the errors.New function?", "Creates a simple error"),
    ("Basics", "What is the fmt.Errorf function?", "Creates formatted error with %w for wrapping"),
    ("Basics", "What is the errors.Is function?", "Checks if error wraps a target error"),
    ("Basics", "What is the errors.As function?", "Finds first error matching target type in chain"),
    ("Basics", "What is the errors.Unwrap function?", "Returns next error in chain"),
    ("Basics", "What is error wrapping?", "Adding context to errors with %w verb"),
    ("Basics", "What is a sentinel error?", "A predefined error value for comparison"),
    ("Basics", "What is the custom error type?", "A struct implementing the error interface"),
    ("Basics", "What is the log package?", "Simple logging with timestamp"),
    ("Basics", "What is the log.Fatal function?", "Logs and calls os.Exit(1)"),
    ("Basics", "What is the log.Panic function?", "Logs and panics"),
    ("Basics", "What is the fmt.Print vs fmt.Println?", "Println adds newline"),
    ("Basics", "What is the fmt.Sprintf function?", "Formats string without printing"),
    ("Basics", "What is the fmt.Scanf function?", "Reads formatted input"),
    ("Basics", "What is the bufio.Scanner?", "Buffered scanner for reading lines"),
    ("Basics", "What is the bufio.Writer?", "Buffered writer"),
    ("Basics", "What is the ioutil.ReadFile (deprecated)?", "Reads entire file (use os.ReadFile)"),
    ("Basics", "What is the ioutil.WriteFile (deprecated)?", "Writes data to file (use os.WriteFile)"),
    ("Basics", "What is the ioutil.ReadDir (deprecated)?", "Reads directory (use os.ReadDir)"),
    ("Basics", "What is the os.ReadFile function?", "Reads entire file in Go 1.16+"),
    ("Basics", "What is the os.WriteFile function?", "Writes data to file in Go 1.16+"),
    ("Basics", "What is the os.ReadDir function?", "Reads directory entries in Go 1.16+"),
    ("Basics", "What is the os.Create function?", "Creates or truncates a file"),
    ("Basics", "What is the os.Open function?", "Opens a file for reading"),
    ("Basics", "What is the os.OpenFile function?", "Opens a file with specific flags"),
    ("Basics", "What is the os.Stat function?", "Returns file info"),
    ("Basics", "What is the os.IsNotExist function?", "Checks if error is file not exists"),
    ("Basics", "What is the os.Mkdir function?", "Creates a directory"),
    ("Basics", "What is the os.MkdirAll function?", "Creates directory and all parents"),
    ("Basics", "What is the os.Remove function?", "Removes file or empty directory"),
    ("Basics", "What is the os.RemoveAll function?", "Removes file or directory and children"),
    ("Basics", "What is the os.Rename function?", "Renames or moves a file"),
    ("Basics", "What is the os.Getenv function?", "Gets environment variable value"),
    ("Basics", "What is the os.Setenv function?", "Sets environment variable"),
    ("Basics", "What is the os.Getwd function?", "Gets current working directory"),
    ("Basics", "What is the os.Chdir function?", "Changes current working directory"),
    ("Basics", "What is the os.Exit function?", "Exits program with status code"),
    ("Basics", "What is the os.Args variable?", "Command-line arguments"),
    ("Basics", "What is the os.Stdin/os.Stdout/os.Stderr?", "Standard I/O file descriptors"),
    ("Basics", "What is the flag package?", "Command-line flag parsing"),
    ("Basics", "What is the flag.String function?", "Defines a string flag"),
    ("Intermediate", "What is the encoding/csv package?", "CSV reading and writing"),
    ("Intermediate", "What is the encoding/xml package?", "XML parsing and generation"),
    ("Intermediate", "What is the regexp package?", "Regular expression engine"),
    ("Intermediate", "What is the regexp.Compile function?", "Parses and compiles regex"),
    ("Intermediate", "What is the regexp.MatchString function?", "Checks if string matches pattern"),
    ("Intermediate", "What is the regexp.FindString function?", "Finds first match as string"),
    ("Intermediate", "What is the regexp.FindAllString function?", "Finds all matches"),
    ("Intermediate", "What is the regexp.ReplaceAllString function?", "Replaces regex matches"),
    ("Intermediate", "What is the text/template package?", "Text template engine"),
    ("Intermediate", "What is the html/template package?", "HTML template engine with escaping"),
    ("Intermediate", "What is the crypto/md5 package?", "MD5 hash function"),
    ("Intermediate", "What is the crypto/sha256 package?", "SHA-256 hash function"),
    ("Intermediate", "What is the crypto/rand package?", "Cryptographically secure random"),
    ("Intermediate", "What is the crypto/aes package?", "AES encryption"),
    ("Intermediate", "What is the crypto/rsa package?", "RSA encryption"),
    ("Intermediate", "What is the crypto/tls package?", "TLS implementation"),
    ("Intermediate", "What is the crypto/x509 package?", "X.509 certificate parsing"),
    ("Intermediate", "What is the crypto/hmac package?", "HMAC implementation"),
    ("Intermediate", "What is the encoding/hex package?", "Hex encoding and decoding"),
    ("Intermediate", "What is the encoding/base64 package?", "Base64 encoding and decoding"),
    ("Intermediate", "What is the compress/gzip package?", "Gzip compression"),
    ("Intermediate", "What is the archive/tar package?", "Tar archive reading and writing"),
    ("Intermediate", "What is the archive/zip package?", "ZIP archive reading and writing"),
    ("Intermediate", "What is the net package?", "Network primitives"),
    ("Intermediate", "What is the net.Dial function?", "Connects to a network address"),
    ("Intermediate", "What is the net.Listen function?", "Listens on a network address"),
    ("Intermediate", "What is the net/http HandleFunc?", "Registers handler for HTTP pattern"),
    ("Intermediate", "What is the net/http FileServer?", "Serves static files"),
    ("Intermediate", "What is the net/http NotFoundHandler?", "Returns 404"),
    ("Intermediate", "What is the net/http RedirectHandler?", "Returns redirect"),
    ("Intermediate", "What is the net/http StripPrefix?", "Strips prefix before serving"),
    ("Intermediate", "What is the net/http TimeoutHandler?", "Wraps handler with timeout"),
    ("Intermediate", "What is the net/http MaxBytesHandler?", "Limits request body size"),
    ("Intermediate", "What is the net/http NotFound function?", "Writes 404 response"),
    ("Intermediate", "What is the net/http Error function?", "Writes error response"),
    ("Intermediate", "What is the net/http Get function?", "HTTP GET request"),
    ("Intermediate", "What is the net/http Post function?", "HTTP POST request"),
    ("Intermediate", "What is the net/http PostForm function?", "HTTP POST with form data"),
    ("Intermediate", "What is the net/http Head function?", "HTTP HEAD request"),
    ("Intermediate", "What is the http.NewRequest function?", "Creates custom HTTP request"),
    ("Intermediate", "What is the http.Client.Do method?", "Executes an HTTP request"),
    ("Intermediate", "What is the http.Transport type?", "HTTP transport configuration"),
    ("Intermediate", "What is the http.Cookie type?", "HTTP cookie"),
]
gen(go_extra, "Middle", "Go")

# --- RUST (+200) ---
rust_extra = [
    ("Basics", "What is the dbg! macro?", "Prints debug info and returns the value"),
    ("Basics", "What is the todo! macro?", "Placeholder for incomplete code, panics"),
    ("Basics", "What is the unimplemented! macro?", "Placeholder for unimplemented code, panics"),
    ("Basics", "What is the unreachable! macro?", "Marks code as unreachable, panics"),
    ("Basics", "What is the include! macro?", "Includes file content at compile time"),
    ("Basics", "What is the stringify! macro?", "Converts expression to string literal"),
    ("Basics", "What is the concat! macro?", "Concatenates literals at compile time"),
    ("Basics", "What is the env! macro?", "Reads environment variable at compile time"),
    ("Basics", "What is the option_env! macro?", "Reads optional env variable at compile time"),
    ("Basics", "What is the cfg! macro?", "Checks configuration flag at compile time"),
    ("Basics", "What is the column! macro?", "Returns current column number"),
    ("Basics", "What is the file! macro?", "Returns current file path"),
    ("Basics", "What is the line! macro?", "Returns current line number"),
    ("Basics", "What is the module_path! macro?", "Returns current module path"),
    ("Basics", "What is the matches! macro?", "Checks if value matches a pattern"),
    ("Basics", "What is the assert! macro?", "Runtime assertion"),
    ("Basics", "What is the assert_eq! macro?", "Assert two values are equal"),
    ("Basics", "What is the assert_ne! macro?", "Assert two values are not equal"),
    ("Basics", "What is the debug_assert! macro?", "Assert only in debug builds"),
    ("Basics", "What is the write! macro?", "Writes formatted string to a buffer"),
    ("Basics", "What is the writeln! macro?", "Writes formatted line to a buffer"),
    ("Basics", "What is the format! macro?", "Creates formatted String"),
    ("Basics", "What is the panic! macro?", "Panics with error message"),
    ("Basics", "What is the compile_error! macro?", "Causes compile-time error"),
    ("Basics", "What is the core::mem::replace function?", "Replaces value, returns old"),
    ("Basics", "What is the core::mem::swap function?", "Swaps two values"),
    ("Basics", "What is the core::mem::take function?", "Takes value, replaces with default"),
    ("Basics", "What is the core::mem::drop function?", "Explicitly drops a value"),
    ("Basics", "What is the core::mem::forget function?", "Prevents drop without running destructor"),
    ("Basics", "What is the core::mem::size_of function?", "Returns size of a type in bytes"),
    ("Basics", "What is the core::mem::align_of function?", "Returns alignment of a type"),
    ("Basics", "What is the core::mem::needs_drop function?", "Checks if type needs dropping"),
    ("Basics", "What is the core::mem::ManuallyDrop?", "Wrapper preventing automatic drop"),
    ("Basics", "What is the core::mem::MaybeUninit?", "Wrapper for potentially uninitialized data"),
    ("Basics", "What is the std::convert::From trait?", "Infallible type conversion"),
    ("Basics", "What is the std::convert::Into trait?", "Infallible consuming conversion"),
    ("Basics", "What is the std::convert::TryFrom trait?", "Fallible type conversion"),
    ("Basics", "What is the std::convert::TryInto trait?", "Fallible consuming conversion"),
    ("Basics", "What is the std::convert::AsRef trait?", "Reference-to-reference conversion"),
    ("Basics", "What is the std::convert::AsMut trait?", "Mutable reference conversion"),
    ("Intermediate", "What is the std::rc::Rc type?", "Reference-counted shared ownership"),
    ("Intermediate", "What is the std::rc::Weak type?", "Weak reference to an Rc"),
    ("Intermediate", "What is the std::sync::Arc type?", "Atomic reference-counted shared ownership"),
    ("Intermediate", "What is the std::sync::Weak type?", "Weak reference to an Arc"),
    ("Intermediate", "What is the std::cell::Cell type?", "Interior mutability for Copy types"),
    ("Intermediate", "What is the std::cell::RefCell type?", "Interior mutability with runtime borrow checking"),
    ("Intermediate", "What is the std::cell::Ref type?", "Immutable borrow guard from RefCell"),
    ("Intermediate", "What is the std::cell::RefMut type?", "Mutable borrow guard from RefCell"),
    ("Intermediate", "What is the std::cell::OnceCell type?", "Write-once cell for single initialization"),
    ("Intermediate", "What is the std::cell::LazyCell type?", "Lazily initialized cell"),
    ("Intermediate", "What is the std::sync::OnceLock type?", "Thread-safe write-once cell"),
    ("Intermediate", "What is the std::sync::LazyLock type?", "Thread-safe lazy initialization"),
    ("Intermediate", "What is the std::sync::Mutex type?", "Mutual exclusion lock"),
    ("Intermediate", "What is the std::sync::MutexGuard type?", "Lock guard for Mutex"),
    ("Intermediate", "What is the std::sync::RwLock type?", "Reader-writer lock"),
    ("Intermediate", "What is the std::sync::RwLockReadGuard?", "Read lock guard"),
    ("Intermediate", "What is the std::sync::RwLockWriteGuard?", "Write lock guard"),
    ("Intermediate", "What is the std::sync::Barrier type?", "Synchronization barrier for threads"),
    ("Intermediate", "What is the std::sync::Condvar type?", "Condition variable for thread notification"),
    ("Intermediate", "What is the std::sync::mpsc::channel", "Multi-producer single-consumer channel"),
    ("Intermediate", "What is the std::sync::mpsc::Sender", "Sending end of MPSC channel"),
    ("Intermediate", "What is the std::sync::mpsc::Receiver", "Receiving end of MPSC channel"),
    ("Intermediate", "What is the std::sync::mpsc::sync_channel", "Bounded synchronous channel"),
    ("Intermediate", "What is the std::thread::scope function?", "Scoped threads with borrowed data"),
    ("Intermediate", "What is the std::thread::sleep function?", "Sleeps current thread"),
    ("Intermediate", "What is the std::thread::yield_now function?", "Yields CPU to other threads"),
    ("Intermediate", "What is the std::thread::current function?", "Returns current thread handle"),
    ("Intermediate", "What is the std::thread::park function?", "Blocks thread until unparked"),
    ("Intermediate", "What is the std::thread::unpark function?", "Unparks a parked thread"),
    ("Intermediate", "What is the std::time::Duration type?", "Time duration representation"),
    ("Intermediate", "What is the std::time::Instant type?", "Monotonic clock measurement"),
    ("Intermediate", "What is the std::time::SystemTime type?", "System clock time"),
    ("Intermediate", "What is the std::path::Path type?", "Filesystem path slice"),
    ("Intermediate", "What is the std::path::PathBuf type?", "Owned filesystem path"),
    ("Intermediate", "What is the std::ffi::OsStr type?", "OS string slice"),
    ("Intermediate", "What is the std::ffi::OsString type?", "Owned OS string"),
    ("Intermediate", "What is the std::ffi::CStr type?", "C string slice"),
    ("Intermediate", "What is the std::ffi::CString type?", "Owned C string"),
    ("Intermediate", "What is the std::net::TcpListener type?", "TCP socket listener"),
    ("Intermediate", "What is the std::net::TcpStream type?", "TCP connection stream"),
    ("Intermediate", "What is the std::net::UdpSocket type?", "UDP socket"),
    ("Intermediate", "What is the std::net::IpAddr type?", "IP address (v4 or v6)"),
    ("Intermediate", "What is the std::net::SocketAddr type?", "Socket address with IP and port"),
    ("Intermediate", "What is the std::process::Command type?", "External process execution"),
    ("Intermediate", "What is the std::process::Child type?", "Child process handle"),
    ("Intermediate", "What is the std::process::Output type?", "Captured process output"),
    ("Intermediate", "What is the std::env::args function?", "Command-line arguments"),
    ("Intermediate", "What is the std::env::var function?", "Environment variable value"),
    ("Intermediate", "What is the std::env::set_var function?", "Sets environment variable"),
    ("Intermediate", "What is the std::env::current_dir function?", "Current working directory"),
    ("Intermediate", "What is the std::env::temp_dir function?", "Temporary directory path"),
    ("Intermediate", "What is the std::env::home_dir function?", "Home directory path (deprecated)"),
    ("Intermediate", "What is the std::fs::read function?", "Reads file into bytes"),
    ("Intermediate", "What is the std::fs::read_to_string function?", "Reads file into string"),
    ("Intermediate", "What is the std::fs::write function?", "Writes bytes to file"),
    ("Intermediate", "What is the std::fs::read_dir function?", "Reads directory entries"),
    ("Intermediate", "What is the std::fs::create_dir function?", "Creates directory"),
    ("Intermediate", "What is the std::fs::create_dir_all function?", "Creates directory tree"),
    ("Intermediate", "What is the std::fs::remove_dir function?", "Removes empty directory"),
    ("Intermediate", "What is the std::fs::remove_dir_all function?", "Removes directory tree"),
    ("Intermediate", "What is the std::fs::remove_file function?", "Removes file"),
    ("Intermediate", "What is the std::fs::rename function?", "Renames file or directory"),
    ("Intermediate", "What is the std::fs::copy function?", "Copies file"),
    ("Intermediate", "What is the std::fs::hard_link function?", "Creates hard link"),
    ("Intermediate", "What is the std::fs::symlink function?", "Creates symbolic link"),
    ("Intermediate", "What is the std::fs::metadata function?", "File metadata"),
    ("Intermediate", "What is the std::fs::canonicalize function?", "Absolute path resolution"),
    ("Intermediate", "What is the std::io::stdin function?", "Standard input handle"),
    ("Intermediate", "What is the std::io::stdout function?", "Standard output handle"),
    ("Intermediate", "What is the std::io::stderr function?", "Standard error handle"),
    ("Intermediate", "What is the std::io::Read trait?", "Read bytes from a source"),
    ("Intermediate", "What is the std::io::Write trait?", "Write bytes to a sink"),
    ("Intermediate", "What is the std::io::Seek trait?", "Seek within a stream"),
    ("Intermediate", "What is the std::io::BufRead trait?", "Buffered reading with line methods"),
    ("Intermediate", "What is the std::io::BufReader type?", "Buffered reader wrapping a reader"),
    ("Intermediate", "What is the std::io::BufWriter type?", "Buffered writer wrapping a writer"),
    ("Intermediate", "What is the std::io::Cursor type?", "In-memory buffered reader/writer"),
    ("Intermediate", "What is the std::io::Lines type?", "Iterator over file lines"),
    ("Intermediate", "What is the std::io::Error type?", "I/O error representation"),
    ("Intermediate", "What is the std::io::Result type?", "Alias for Result<T, io::Error>"),
    ("Intermediate", "What is the std::io::ErrorKind enum?", "Categorizes I/O errors"),
    ("Intermediate", "What is the ? operator in I/O?", "Propagates errors in functions returning Result"),
    ("Intermediate", "What is the std::fmt::Display trait?", "User-facing display formatting"),
    ("Intermediate", "What is the std::fmt::Debug trait?", "Debug formatting with {:?}"),
    ("Intermediate", "What is the std::fmt::Write trait?", "Formatting for types implementing write_str"),
]
gen(rust_extra, "Middle", "Rust")

# --- REACT (+200) ---
react_extra = [
    ("Hooks", "What is the useMemo dependency array?", "List of values that trigger re-computation"),
    ("Hooks", "What is the useCallback dependency array?", "List of values that trigger re-creation"),
    ("Hooks", "What is the useEffect cleanup?", "Returned function runs on unmount or before re-run"),
    ("Hooks", "What is the useRef current property?", "The mutable current value of the ref"),
    ("Hooks", "What is the useReducer dispatch?", "Function that dispatches an action to the reducer"),
    ("Hooks", "What is the initialState in useReducer?", "The initial state value"),
    ("Hooks", "What is the init function in useReducer?", "Lazy initialization function for useReducer"),
    ("Hooks", "What is the useContext value?", "The current value from the nearest Provider"),
    ("Hooks", "What is the useLayoutEffect vs useEffect?", "useLayoutEffect fires synchronously before paint"),
    ("Hooks", "What is the useTransition startTransition?", "Marks state update as non-urgent"),
    ("Hooks", "What is the useDeferredValue defer?", "Delays re-render of a value"),
    ("Hooks", "What is the useId for accessibility?", "Generates unique IDs for aria attributes"),
    ("Hooks", "What is the useSyncExternalStore subscribe?", "Subscription function for external store"),
    ("Hooks", "What is the useSyncExternalStore getSnapshot?", "Returns current snapshot of external store"),
    ("Hooks", "What is the useInsertionEffect for CSS?", "Injects style tags before DOM mutations"),
    ("Hooks", "What is the useDebugValue label?", "Custom label shown in React DevTools"),
    ("Hooks", "What is the useCallback vs useMemo?", "useCallback memoizes function; useMemo memoizes value"),
    ("Hooks", "What is the useRef vs useState?", "useRef persists without re-render; useState triggers re-render"),
    ("Hooks", "What is the useEffect infinite loop?", "Caused by missing dependency array or updating dependencies"),
    ("Hooks", "What is the useEffect cleanup for subscriptions?", "Prevents memory leaks from subscriptions"),
    ("Components", "What is a pure component?", "Component that renders same output for same props/state"),
    ("Components", "What is React.PureComponent?", "Class component with shallow prop/state comparison"),
    ("Components", "What is the shouldComponentUpdate method?", "Controls whether component re-renders"),
    ("Components", "What is the getDerivedStateFromProps method?", "Updates state based on props changes"),
    ("Components", "What is the getSnapshotBeforeUpdate method?", "Captures DOM info before update"),
    ("Components", "What is the componentDidUpdate method?", "Called after component updates"),
    ("Components", "What is the componentWillUnmount method?", "Cleanup before component unmounts"),
    ("Components", "What is the componentDidCatch method?", "Catches errors in child component tree"),
    ("Components", "What is the getDerivedStateFromError method?", "Updates state after error is caught"),
    ("Components", "What is the static getDerivedStateFromProps?", "Static lifecycle for deriving state from props"),
    ("Components", "What is the UNSAFE_componentWillMount?", "Deprecated lifecycle, use constructor"),
    ("Components", "What is the UNSAFE_componentWillReceiveProps?", "Deprecated lifecycle, use getDerivedStateFromProps"),
    ("Components", "What is the UNSAFE_componentWillUpdate?", "Deprecated lifecycle"),
    ("Components", "What is the React.createElement function?", "Creates React element (JSX compiles to this)"),
    ("Components", "What is the React.cloneElement function?", "Clones element with new props"),
    ("Components", "What is the React.isValidElement function?", "Checks if value is a React element"),
    ("Components", "What is the React.Children utility?", "Utility for working with children prop"),
    ("Components", "What is the React.Children.map function?", "Maps over children with flattening"),
    ("Components", "What is the React.Children.forEach function?", "Iterates over children"),
    ("Components", "What is the React.Children.count function?", "Counts number of children"),
    ("Components", "What is the React.Children.only function?", "Ensures single child, throws otherwise"),
    ("Components", "What is the React.Children.toArray function?", "Converts children to flat array"),
    ("Components", "What is the React.Fragment component?", "Groups children without adding DOM node"),
    ("Components", "What is the React.StrictMode component?", "Checks for potential problems in dev"),
    ("Components", "What is the React.Suspense component?", "Shows fallback while children load"),
    ("Components", "What is the React.Profiler component?", "Measures rendering performance"),
    ("Components", "What is the React.lazy function?", "Lazy loads a component"),
    ("Components", "What is the React.memo HOC?", "Memoizes functional component"),
    ("Components", "What is the React.forwardRef?", "Forwards ref to child component"),
    ("Components", "What is the React.createRef?", "Creates a ref object"),
    ("Components", "What is the React.createContext?", "Creates a context for prop drilling avoidance"),
    ("Components", "What is the React.use hooks?", "React 19 hooks for data loading"),
    ("Components", "What is the React.use() in Server Components?", "Reads context or resource in RSC"),
    ("JSX", "What is the JSX transform?", "Automatic runtime for JSX compilation"),
    ("JSX", "What is the jsxRuntime option?", "Configures classic or automatic JSX transform"),
    ("JSX", "What is the importSource option?", "Specifies JSX import source"),
    ("JSX", "What is the jsxImportSource pragma?", "/** @jsxImportSource @emotion/react */"),
    ("JSX", "What is the jsx pragma?", "/** @jsx jsx */ for custom JSX factory"),
    ("JSX", "What is the React 17 JSX transform?", "No need to import React for JSX"),
    ("JSX", "What is the boolean attribute shorthand?", "{true} can be written as just prop name"),
    ("JSX", "What is the spread attributes syntax?", "{...props} spreads object as props"),
    ("JSX", "What is the conditional className?", "Using template literals or clsx library"),
    ("JSX", "What is the inline style camelCase?", "CSS properties in camelCase for style prop"),
    ("JSX", "What is the dangerouslySetInnerHTML?", "Renders HTML string (XSS risk)"),
    ("JSX", "What is the suppressHydrationWarning?", "Suppresses SSR mismatch warnings"),
    ("JSX", "What is the htmlFor attribute?", "JSX equivalent of HTML for attribute"),
    ("JSX", "What is the checked attribute?", "For controlled checkbox/radio inputs"),
    ("JSX", "What is the defaultValue attribute?", "Default value for uncontrolled inputs"),
    ("JSX", "What is the defaultChecked attribute?", "Default checked for uncontrolled inputs"),
    ("JSX", "What is the onDoubleClick event?", "Double-click event handler"),
    ("JSX", "What is the onContextMenu event?", "Right-click context menu event"),
    ("JSX", "What is the onWheel event?", "Mouse wheel event"),
    ("JSX", "What is the onPointerDown event?", "Pointer event for mouse/touch/pen"),
    ("JSX", "What is the synthetic event?", "Cross-browser wrapper around native events"),
    ("JSX", "What is the event pooling (React 16)?", "Synthetic events are pooled and nullified"),
    ("JSX", "What is the event.persist() method?", "Removes synthetic event from pooling"),
]
gen(react_extra, "Middle", "React")

# --- KOTLIN (+200) ---
kotlin_extra = [
    ("Collections", "What is the Sequence in Kotlin?", "A lazy collection for efficient chaining"),
    ("Collections", "What is the difference between Sequence and Iterable?", "Sequence is lazy; Iterable processes eagerly"),
    ("Collections", "What is the generateSequence function?", "Creates infinite sequence"),
    ("Collections", "What is the sequenceOf function?", "Creates sequence from elements"),
    ("Collections", "What is the asSequence function?", "Converts iterable to sequence"),
    ("Collections", "What is the toList() terminal on sequence?", "Evaluates sequence to list"),
    ("Collections", "What is the constrainsOne typealias?", "Typealias for List<List<T>>"),
    ("Collections", "What is the MutableList interface?", "A modifiable list"),
    ("Collections", "What is the MutableSet interface?", "A modifiable set"),
    ("Collections", "What is the MutableMap interface?", "A modifiable map"),
    ("Collections", "What is the getOrElse on Map?", "Returns value or computed default"),
    ("Collections", "What is the getOrDefault on Map?", "Returns value or default"),
    ("Collections", "What is the getOrPut on MutableMap?", "Returns or computes and stores value"),
    ("Collections", "What is the plus operator for collections?", "Creates new collection with added element"),
    ("Collections", "What is the minus operator for collections?", "Creates new collection without element"),
    ("Collections", "What is the contains operator (in)?", "Checks if element is in collection"),
    ("Collections", "What is the slice function?", "Returns elements at specified indices"),
    ("Collections", "What is the subList function?", "Returns view of portion of list"),
    ("Collections", "What is the reversed function?", "Returns reversed collection"),
    ("Collections", "What is the shuffle function?", "Randomly shuffles collection"),
    ("Coroutines", "What is the supervisorScope builder?", "Scope where child failures isolate"),
    ("Coroutines", "What is the supervisorJob?", "Job where child failure doesn't cancel parent"),
    ("Coroutines", "What is the NonCancellable context?", "Context that cannot be cancelled"),
    ("Coroutines", "What is the Dispatchers.Unconfined?", "Dispatcher not confined to any thread"),
    ("Coroutines", "What is the newSingleThreadContext?", "Creates single-threaded coroutine context"),
    ("Coroutines", "What is the newFixedThreadPoolContext?", "Creates fixed thread pool context"),
    ("Coroutines", "What is the ExecutorCoroutineDispatcher?", "Dispatcher backed by an executor"),
    ("Coroutines", "What is the asCoroutineDispatcher extension?", "Converts executor to dispatcher"),
    ("Coroutines", "What is the runBlocking function?", "Blocks thread to run coroutines"),
    ("Coroutines", "What is the delay function?", "Non-blocking suspend delay"),
    ("Coroutines", "What is the yield in coroutines?", "Suspends and yields thread"),
    ("Coroutines", "What is the ensureActive function?", "Checks coroutine cancellation"),
    ("Coroutines", "What is the currentCoroutineContext function?", "Returns current coroutine context"),
    ("Coroutines", "What is the coroutineContext property?", "Accesses context inside coroutine"),
    ("Coroutines", "What is the isActive property?", "Checks if coroutine is still active"),
    ("Coroutines", "What is the CompletableDeferred?", "A Deferred that can be completed externally"),
    ("Coroutines", "What is the Job.cancelAndJoin function?", "Cancels and waits for completion"),
    ("Coroutines", "What is the Job.children property?", "Returns children of a job"),
    ("Coroutines", "What is the Job.attachChild function?", "Attaches child to a job"),
    ("Coroutines", "What is the Channel.Factory.CONFLATED?", "Channel that keeps only the latest value"),
    ("Coroutines", "What is the Channel.Factory.BUFFERED?", "Buffered channel with default capacity"),
    ("Coroutines", "What is the Channel.Factory.RENDEZVOUS?", "Channel with zero buffer"),
    ("Coroutines", "What is the Channel.Factory.UNLIMITED?", "Channel with unlimited buffer"),
    ("Coroutines", "What is the BroadcastChannel?", "Channel that broadcasts to multiple subscribers"),
    ("Coroutines", "What is the ConflatedBroadcastChannel?", "Broadcast channel keeping latest value"),
    ("Coroutines", "What is the produce in coroutines?", "Creates coroutine producing to channel"),
    ("Coroutines", "What is the actor in coroutines?", "Creates coroutine processing channel messages"),
    ("Coroutines", "What is the ticker flow?", "Produces Unit values at fixed intervals"),
    ("Coroutines", "What is the callbackFlow builder?", "Converts callback-based API to flow"),
    ("Coroutines", "What is the channelFlow builder?", "Flow builder using a channel internally"),
    ("Coroutines", "What is the flatMapConcat in flow?", "Concatenates inner flows sequentially"),
    ("Coroutines", "What is the flatMapMerge in flow?", "Merges inner flows concurrently"),
    ("Coroutines", "What is the flatMapLatest in flow?", "Switches to latest inner flow"),
    ("Coroutines", "What is the combine in flow?", "Combines two flows with a transform"),
    ("Coroutines", "What is the zip in flow?", "Zips two flows element-wise"),
    ("Coroutines", "What is the merge in flow?", "Merges multiple flows into one"),
    ("Coroutines", "What is the buffer in flow?", "Buffers upstream emissions"),
    ("Coroutines", "What is the conflate in flow?", "Keeps only the latest emitted value"),
    ("Coroutines", "What is the collectLatest in flow?", "Cancels previous collector when new value emitted"),
    ("Coroutines", "What is the transform in flow?", "Maps and filters elements"),
    ("Coroutines", "What is the mapLatest in flow?", "Maps with cancellation of previous mapping"),
    ("Coroutines", "What is the retryWhen in flow?", "Retries with custom condition"),
    ("Coroutines", "What is the catch in flow?", "Catches upstream exceptions"),
    ("Coroutines", "What is the onCompletion in flow?", "Callback when flow completes"),
    ("Coroutines", "What is the onStart in flow?", "Callback when flow starts"),
    ("Coroutines", "What is the onEach in flow?", "Performs action on each element"),
    ("Coroutines", "What is the distinctUntilChanged in flow?", "Emits only when value changes"),
    ("Coroutines", "What is the scan in flow?", "Accumulates values like fold but emits each step"),
    ("Coroutines", "What is the reduce in flow?", "Accumulates values to single result"),
    ("Coroutines", "What is the fold in flow?", "Accumulates with initial value"),
    ("Coroutines", "What is the count in flow?", "Counts elements matching predicate"),
    ("Coroutines", "What is the first in flow?", "Returns first element"),
    ("Coroutines", "What is the last in flow?", "Returns last element"),
    ("Coroutines", "What is the single in flow?", "Expects exactly one element"),
    ("Coroutines", "What is the toList in flow?", "Collects flow to list"),
    ("Coroutines", "What is the toSet in flow?", "Collects flow to set"),
    ("Coroutines", "What is the launchIn in flow?", "Launches flow collection in scope"),
    ("Coroutines", "What is the flowWith function?", "Wraps flow with context switch"),
    ("Coroutines", "What is the flowOn operator?", "Changes dispatcher for upstream"),
    ("Coroutines", "What is the withContext in flow?", "Switches context in flow building"),
    ("Coroutines", "What is the Mutex.withLock function?", "Locks mutex, executes block, unlocks"),
    ("Coroutines", "What is the Semaphore in coroutines?", "Limits concurrent coroutine access"),
    ("Coroutines", "What is the ThreadLocal.asContextElement?", "Converts thread local to context element"),
]
gen(kotlin_extra, "Middle", "Kotlin")

# --- GENERAL (+200) ---
general_extra = [
    ("System Design", "What is the single point of failure?", "A component whose failure causes system failure"),
    ("System Design", "What is high availability?", "System remains operational despite failures"),
    ("System Design", "What is fault tolerance?", "System continues functioning after component failure"),
    ("System Design", "What is disaster recovery?", "Restoring system after catastrophic failure"),
    ("System Design", "What is the RTO (Recovery Time Objective)?", "Maximum acceptable downtime after disaster"),
    ("System Design", "What is the RPO (Recovery Point Objective)?", "Maximum acceptable data loss in time"),
    ("System Design", "What is the SLA (Service Level Agreement)?", "Contract defining expected service level"),
    ("System Design", "What is the SLO (Service Level Objective)?", "Target service level metric"),
    ("System Design", "What is the SLI (Service Level Indicator)?", "Actual measured service level metric"),
    ("System Design", "What is the CAP theorem tradeoffs?", "Consistency, Availability, Partition tolerance tradeoff"),
    ("System Design", "What is the PACELC theorem?", "Extends CAP: if partition, trade CA else trade LC"),
    ("System Design", "What is eventual consistency?", "All replicas eventually converge to same value"),
    ("System Design", "What is strong consistency?", "All reads return latest write immediately"),
    ("System Design", "What is read-after-write consistency?", "User sees their own writes immediately"),
    ("System Design", "What is quorum consensus?", "Minimum votes needed for read/write in distributed system"),
    ("System Design", "What is the gossip protocol?", "Peer-to-peer information dissemination"),
    ("System Design", "What is the Paxos algorithm?", "Consensus algorithm for distributed systems"),
    ("System Design", "What is the Raft algorithm?", "Understandable consensus algorithm with leader election"),
    ("System Design", "What is the two-phase commit (2PC)?", "Distributed transaction commit protocol"),
    ("System Design", "What is the three-phase commit (3PC)?", "Non-blocking distributed commit protocol"),
    ("System Design", "What is the Saga pattern in microservices?", "Sequence of local transactions with compensation"),
    ("System Design", "What is choreography in microservices?", "Services communicate via events without coordinator"),
    ("System Design", "What is orchestration in microservices?", "Central coordinator manages service interactions"),
    ("System Design", "What is the service mesh?", "Infrastructure layer for service-to-service communication"),
    ("System Design", "What is Istio?", "A popular service mesh platform"),
    ("System Design", "What is Envoy proxy?", "High-performance sidecar proxy for service mesh"),
    ("System Design", "What is the sidecar pattern?", "A helper container alongside the main container"),
    ("System Design", "What is the ambassador pattern?", "A sidecar for cross-cutting proxy concerns"),
    ("System Design", "What is the adapter pattern in containers?", "Adapts container interfaces"),
    ("System Design", "What is the init container pattern?", "Runs setup tasks before main container starts"),
    ("System Design", "What is the leader election pattern?", "Selecting one instance as leader in distributed system"),
    ("System Design", "What is the heartbeat pattern?", "Periodic signals to check system health"),
    ("System Design", "What is the health check endpoint?", "Endpoint for monitoring system health"),
    ("System Design", "What is the circuit breaker state machine?", "Closed, Open, Half-Open states"),
    ("System Design", "What is the bulkhead pattern?", "Isolating components to prevent cascading failures"),
    ("System Design", "What is the rate limiting algorithm?", "Token bucket, leaky bucket, sliding window"),
    ("System Design", "What is the token bucket algorithm?", "Tokens refill at fixed rate, consumed per request"),
    ("System Design", "What is the leaky bucket algorithm?", "Requests processed at fixed rate, excess queued"),
    ("System Design", "What is the sliding window log algorithm?", "Timestamps of requests within time window"),
    ("System Design", "What is the sliding window counter algorithm?", "Approximate count with weighted previous window"),
    ("System Design", "What is consistent hashing?", "Minimizes rehashing when nodes change"),
    ("System Design", "What is the virtual nodes in consistent hashing?", "Each physical node has multiple virtual nodes"),
    ("System Design", "What is the hash ring?", "Circular space for consistent hashing"),
    ("System Design", "What is data partitioning?", "Splitting data across multiple databases"),
    ("System Design", "What is horizontal partitioning (sharding)?", "Splitting rows across databases"),
    ("System Design", "What is vertical partitioning?", "Splitting columns across databases"),
    ("System Design", "What is the directory-based sharding?", "Lookup service maps keys to shards"),
    ("System Design", "What is the range-based sharding?", "Partitioning by value ranges"),
    ("System Design", "What is the hash-based sharding?", "Partitioning by hash of key"),
    ("System Design", "What is the rebalancing in sharding?", "Moving data when adding/removing shards"),
    ("System Design", "What is the hot spot in sharding?", "Uneven load distribution across shards"),
    ("System Design", "What is the database replication?", "Copying data across database nodes"),
    ("System Design", "What is the synchronous replication?", "Master waits for replica confirmation"),
    ("System Design", "What is the asynchronous replication?", "Master does not wait for replica"),
    ("System Design", "What is the semi-synchronous replication?", "Master waits for at least one replica"),
    ("System Design", "What is the multi-master replication?", "Multiple nodes accept writes"),
    ("System Design", "What is the master-slave replication?", "Single master for writes, slaves for reads"),
    ("System Design", "What is the failover in replication?", "Promoting replica when master fails"),
    ("System Design", "What is the split-brain problem?", "Multiple nodes believe they are master"),
    ("System Design", "What is the read replica?", "Replica serving read-only queries"),
    ("System Design", "What is the write-ahead log (WAL)?", "Log for crash recovery before data write"),
    ("System Design", "What is the checkpoint in databases?", "Flushing dirty pages to disk"),
    ("System Design", "What is the MVCC (Multi-Version Concurrency Control)?", "Each transaction sees a consistent snapshot"),
    ("System Design", "What is the isolation level in databases?", "Read Uncommitted, Read Committed, Repeatable Read, Serializable"),
    ("System Design", "What is the phantom read?", "New rows appear in subsequent queries"),
    ("System Design", "What is the dirty read?", "Reading uncommitted data"),
    ("System Design", "What is the non-repeatable read?", "Same row shows different values on re-read"),
    ("System Design", "What is the serializable isolation?", "Highest isolation level preventing all anomalies"),
    ("System Design", "What is the optimistic locking?", "Assume no conflict, check at commit"),
    ("System Design", "What is the pessimistic locking?", "Lock data before modification"),
    ("System Design", "What is the deadlock detection?", "Identifying circular wait conditions"),
    ("System Design", "What is the deadlock prevention?", "Ensuring circular waits cannot occur"),
    ("System Design", "What is the wait-die scheme?", "Older transaction waits, younger dies"),
    ("System Design", "What is the wound-wait scheme?", "Older wounds younger, younger waits"),
    ("System Design", "What is the timestamp ordering protocol?", "Transactions ordered by timestamps"),
    ("System Design", "What is the optimistic concurrency control?", "Validate at commit time with three phases"),
    ("System Design", "What is the B-tree index?", "Balanced tree index for range queries"),
    ("System Design", "What is the hash index?", "Index using hash function for equality queries"),
    ("System Design", "What is the bitmap index?", "Index using bitmaps for low-cardinality columns"),
    ("System Design", "What is the GiST index?", "Generalized Search Tree for custom data types"),
    ("System Design", "What is the GIN index?", "Generalized Inverted Index for composite values"),
    ("System Design", "What is the BRIN index?", "Block Range Index for large sorted tables"),
    ("System Design", "What is the covering index?", "Index containing all columns needed by query"),
    ("System Design", "What is the composite index?", "Index on multiple columns"),
    ("System Design", "What is the index selectivity?", "Ratio of unique indexed values to total rows"),
    ("System Design", "What is the clustered index?", "Index that determines physical order of rows"),
    ("System Design", "What is the non-clustered index?", "Index separate from data rows"),
    ("System Design", "What is the full-text search index?", "Index for text search queries"),
    ("System Design", "What is the spatial index?", "Index for geographic and geometric queries"),
    ("System Design", "What is the partial index?", "Index on a subset of rows"),
    ("System Design", "What is the expression index?", "Index on the result of an expression"),
    ("System Design", "What is the unique index?", "Index enforcing uniqueness constraint"),
    ("System Design", "What is the primary index?", "Index on primary key columns"),
    ("System Design", "What is the secondary index?", "Index on non-primary key columns"),
    ("System Design", "What is the index-only scan?", "Query satisfied entirely by index"),
    ("System Design", "What is the bitmap scan?", "Combining multiple indexes with bitwise operations"),
    ("System Design", "What is the sequential scan?", "Reading entire table row by row"),
    ("System Design", "What is the query planner?", "Chooses most efficient query execution plan"),
    ("System Design", "What is the EXPLAIN command?", "Shows query execution plan"),
    ("System Design", "What is the ANALYZE command?", "Updates table statistics for query planner"),
    ("System Design", "What is the VACUUM command?", "Reclaims storage from dead tuples"),
    ("System Design", "What is the auto-vacuum?", "Automatic VACUUM process in PostgreSQL"),
    ("System Design", "What is the connection pooling?", "Reusing database connections to reduce overhead"),
    ("System Design", "What is PgBouncer?", "Lightweight PostgreSQL connection pooler"),
    ("System Design", "What is the N+1 query problem?", "N additional queries for N entities' relations"),
    ("System Design", "What is eager loading?", "Loading related data in a single query"),
    ("System Design", "What is lazy loading?", "Loading related data on demand"),
    ("System Design", "What is the entity-relationship model?", "Conceptual data model with entities and relationships"),
    ("System Design", "What is the normalization?", "Reducing data redundancy in database design"),
    ("System Design", "What is the first normal form (1NF)?", "Atomic columns, no repeating groups"),
    ("System Design", "What is the second normal form (2NF)?", "1NF + no partial dependencies"),
    ("System Design", "What is the third normal form (3NF)?", "2NF + no transitive dependencies"),
    ("System Design", "What is the BCNF?", "3NF + every determinant is a candidate key"),
    ("System Design", "What is the denormalization?", "Adding redundancy for query performance"),
    ("System Design", "What is the star schema?", "Fact table with dimension tables for analytics"),
    ("System Design", "What is the snowflake schema?", "Star schema with normalized dimensions"),
    ("System Design", "What is the data warehouse?", "Central repository for analytics and reporting"),
    ("System Design", "What is the data lake?", "Storage for raw data in native format"),
    ("System Design", "What is the ETL pipeline?", "Extract, Transform, Load data process"),
    ("System Design", "What is the OLTP vs OLAP?", "OLTP: transactional; OLAP: analytical processing"),
    ("System Design", "What is the materialized view?", "Pre-computed query result stored as table"),
    ("System Design", "What is the Common Table Expression (CTE)?", "Temporary query result within WITH clause"),
    ("System Design", "What is the recursive CTE?", "CTE that references itself"),
    ("System Design", "What is the window function?", "Aggregate over partition without collapsing rows"),
    ("System Design", "What is the ROW_NUMBER function?", "Sequential row number within partition"),
    ("System Design", "What is the RANK function?", "Row rank with gaps for ties"),
    ("System Design", "What is the DENSE_RANK function?", "Row rank without gaps"),
    ("System Design", "What is the NTILE function?", "Divides rows into N buckets"),
    ("System Design", "What is the LAG function?", "Access previous row within partition"),
    ("System Design", "What is the LEAD function?", "Access next row within partition"),
    ("System Design", "What is the FIRST_VALUE function?", "First value in window frame"),
    ("System Design", "What is the LAST_VALUE function?", "Last value in window frame"),
    ("System Design", "What is the NTH_VALUE function?", "Nth value in window frame"),
    ("System Design", "What is the window frame clause?", "ROWS BETWEEN or RANGE BETWEEN for window"),
]
gen(general_extra, "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 12 added {len(new)} questions.")