"""Batch 8: Generate remaining ~2000 questions"""
import os, sys, re
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []
def add(cat, q, a, diff, lang):
    def esc(s):
        return s.replace('\\', '\\\\').replace("'", "\\'")
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(a)}', 'Alternative approach', 'Common misconception', 'Unsure'], '{diff}', '{lang}');")

# All remaining questions as compact (cat, q, a, diff, lang) tuples
remaining = [
    # Java + Spring/Hibernate (300)
    ("Spring Framework","What is @RequestMapping method attribute?","Specifies HTTP method: GET, POST, PUT, DELETE.","Junior","Java"),
    ("Spring Framework","What is @RequestMapping params?","Filters by request parameters. params='myParam=myValue'.","Junior","Java"),
    ("Spring Framework","What is @RequestMapping headers?","Filters by request headers. headers='Accept=application/json'.","Junior","Java"),
    ("Spring Framework","What is @RequestMapping consumes?","Restricts by request content type: application/json.","Junior","Java"),
    ("Spring Framework","What is @RequestMapping produces?","Restricts by response content type. Accept header matching.","Junior","Java"),
    ("Spring Framework","What is @CrossOrigin?","Enables CORS on controller/method. origins, methods, headers.","Junior","Java"),
    ("Spring Framework","What is @MatrixVariable?","Binds matrix URI variables: /cars;color=red.","Middle","Java"),
    ("Spring Framework","What is @RequestPart?","Binds multipart request part. For file uploads.","Junior","Java"),
    ("Spring Framework","What is @RequestHeader?","Binds request header to method parameter.","Junior","Java"),
    ("Spring Framework","What is @CookieValue?","Binds cookie value to method parameter.","Junior","Java"),
    ("Spring Framework","What is @SessionAttributes?","Stores model attributes in HTTP session.","Middle","Java"),
    ("Spring Framework","What is @SessionAttribute?","Reads existing session attribute.","Junior","Java"),
    ("Spring Framework","What is @RequestAttribute?","Reads request-scoped attribute.","Junior","Java"),
    ("Spring Framework","What is FlashMap and RedirectAttributes?","Attributes survive redirect. addFlashAttribute.","Middle","Java"),
    ("Spring Framework","What is @ModelAttribute?","Binds model attribute to method parameter or exposes as model.","Junior","Java"),
    ("Spring Framework","What is @InitBinder?","Customizes data binding. WebDataBinder for type conversion.","Middle","Java"),
    ("Spring Framework","What is @Valid and @Validated?","Triggers JSR-303 bean validation. Groups with @Validated.","Junior","Java"),
    ("Spring Framework","What is @DateTimeFormat?","Date/time format for binding. pattern attribute.","Junior","Java"),
    ("Spring Framework","What is @NumberFormat?","Number format for binding. style=Style.CURRENCY.","Junior","Java"),
    ("Spring Framework","What is @EnableWebMvc?","Imports Spring MVC configuration. Custom WebMvcConfigurer.","Middle","Java"),
    ("Spring Framework","What is WebMvcConfigurer?","Callback interface for MVC config. addInterceptors, addCorsMappings.","Middle","Java"),
    ("Spring Framework","What is ContentNegotiationConfigurer?","Configures content negotiation. favorPathExtension, favorParameter.","Middle","Java"),
    ("Spring Framework","What is AsyncHandlerInterceptor?","Async interceptor. afterConcurrentHandlingStarted.","Senior","Java"),
    ("Spring Framework","What is HandlerMethodArgumentResolver?","Custom method parameter resolution. supportsParameter, resolveArgument.","Senior","Java"),
    ("Spring Framework","What is HandlerMethodReturnValueHandler?","Custom return value handling. wraps @ResponseBody pattern.","Senior","Java"),
    ("Spring Framework","What is HttpMessageConverter?","Converts HTTP request/response bodies. Jackson, Gson, etc.","Middle","Java"),
    ("Spring Framework","What is MappingJackson2HttpMessageConverter?","JSON converter using Jackson. ObjectMapper config.","Middle","Java"),
    ("Spring Framework","What is MappingJackson2XmlHttpMessageConverter?","XML converter using Jackson XML extension.","Middle","Java"),
    ("Spring Framework","What is Jaxb2RootElementHttpMessageConverter?","XML converter using JAXB. @XmlRootElement.","Middle","Java"),
    ("Spring Framework","What is StringHttpMessageConverter?","String body converter. Charset encoding config.","Junior","Java"),
    ("Spring Framework","What is ByteArrayHttpMessageConverter?","Byte array body converter.","Junior","Java"),
    ("Spring Framework","What is ResourceHttpMessageConverter?","Resource body converter. File downloads.","Junior","Java"),
    ("Spring Framework","What is FormHttpMessageConverter?","Form data converter. MultiValueMap<String, String>.","Junior","Java"),
    ("Spring Framework","What is ResponseBodyEmitter?","Async response streaming. send on different thread.","Senior","Java"),
    ("Spring Framework","What is SseEmitter?","Server-Sent Events emitter. Event data, ID, name.","Senior","Java"),
    ("Spring Framework","What is StreamingResponseBody?","Async response body writing. OutputStream callback.","Senior","Java"),
    ("Spring Framework","What is DeferredResult?","Async request processing. DeferredResult for timeout.","Senior","Java"),
    ("Spring Framework","What is Callable for async?","Controller can return Callable for async processing.","Junior","Java"),
    ("Spring Framework","What is WebAsyncTask?","Configures async request timeout and executor.","Middle","Java"),
    ("Spring Framework","What is @EnableAsync?","Enables async method execution. Proxy mode, thread pool.","Junior","Java"),
    ("Spring Framework","What is @Async method?","Method runs asynchronously on thread pool. Returns Future.","Junior","Java"),
    ("Spring Framework","What is AsyncResult?","Return value for async methods. AsyncResult<V> for Future.","Middle","Java"),
    ("Spring Framework","What is TaskExecutor?","Spring's executor abstraction. SimpleAsyncTaskExecutor, ThreadPoolTaskExecutor.","Middle","Java"),
    ("Spring Framework","What is ThreadPoolTaskExecutor?","Spring's ThreadPoolExecutor wrapper. corePoolSize, maxPoolSize, queueCapacity.","Middle","Java"),
    ("Spring Framework","What is @Scheduled?","Fixed-rate or cron-based task scheduling. cron, fixedDelay, fixedRate.","Junior","Java"),
    ("Spring Framework","What is @Scheduled cron?","cron='0 0 * * * *' expression. Second, minute, hour, day, month, weekday.","Middle","Java"),
    ("Spring Framework","What is @Scheduled fixedDelay?","Fixed delay between executions. Previous run must finish.","Junior","Java"),
    ("Spring Framework","What is @Scheduled fixedRate?","Fixed rate ignoring execution time. Overlapping if exceeds period.","Junior","Java"),
    ("Spring Framework","What is @Scheduled initialDelay?","Delay before first execution. initialDelay=5000.","Junior","Java"),
    ("Spring Framework","What is @EnableScheduling?","Enables @Scheduled annotation support.","Junior","Java"),
    ("Spring Framework","What is TaskScheduler?","Task scheduling abstraction. ThreadPoolTaskScheduler.","Middle","Java"),
    ("Java Core","What is jwt structure?","Header.Payload.Signature. Base64 encoded. HS256, RS256 algorithms.","Junior","Java"),
    ("Java Core","What is jjwt library?","Java JWT library. Jwts.builder(), Jwts.parser().","Junior","Java"),
    ("Java Core","What is Spring Security JWT?","Spring Security Resource Server JWT. NimbusJwtDecoder.","Middle","Java"),
    ("Java Core","What is OAuth2 Resource Server?","Validates JWT from authorization server. spring-security-oauth2-resource-server.","Middle","Java"),
    ("Java Core","What is NimbusJwtDecoder?","JWT decoder using Nimbus library. JWK set URI.","Middle","Java"),
    ("Java Core","What is Spring Authorization Server?","Full OAuth2 authorization server. Client, authorization code.","Senior","Java"),
    ("Java Core","What is Keycloak?","OpenID Connect identity provider. Realm, client, user federation.","Junior","Java"),
    ("Java Core","What is SAML2 Spring Security?","SAML2 authentication. AssertionConsumerServiceFilter.","Senior","Java"),
    ("Java Core","What is CAS protocol?","Central Authentication Service. Single sign-on. Ticket granting.","Middle","Java"),
    ("Java Core","What is LDAP authentication?","Lightweight Directory Access Protocol. Users in directory.","Junior","Java"),
    ("Java Core","What is JDBC authentication?","Users stored in database. DataSource for queries.","Junior","Java"),
    ("Java Core","What is in-memory authentication?","Users stored in memory for testing. UserDetailsManager.","Junior","Java"),
    ("Java Core","What is UserDetailsService?","Loads user by username. Returns UserDetails.","Middle","Java"),
    ("Java Core","What is UserDetails?","User info: username, password, authorities, account status.","Junior","Java"),
    ("Java Core","What is GrantedAuthority?","User permission. SimpleGrantedAuthority('ROLE_USER').","Junior","Java"),
    ("Java Core","What is @PreAuthorize?","Method security: @PreAuthorize('hasRole(''ADMIN'')').","Junior","Java"),
    ("Java Core","What is @PostAuthorize?","Method security after invocation. Check return value.","Middle","Java"),
    ("Java Core","What is @PreFilter/@PostFilter?","Filters collections before/after method.","Middle","Java"),
    ("Java Core","What is @Secured?","Legacy method security: @Secured('ROLE_ADMIN').","Junior","Java"),
    ("Java Core","What is @RolesAllowed?","JSR-250 method security: @RolesAllowed('ADMIN').","Junior","Java"),
    ("Java Core","What is @EnableMethodSecurity?","Enables method-level security. prePostEnabled, securedEnabled.","Middle","Java"),
    ("Java Core","What is @EnableWebSecurity?","Configures Spring Security filter chain.","Middle","Java"),
    ("Java Core","What is SecurityFilterChain bean?","Defines security rules: authorizeHttpRequests, formLogin, oauth2Login.","Middle","Java"),
    ("Java Core","What is HttpSecurity?","Configures HTTP security: authorize, cors, csrf, session.","Middle","Java"),
    ("Java Core","What is authorizeHttpRequests?","URL-based authorization. requestMatchers, permitAll, authenticated.","Middle","Java"),
    ("Java Core","What is CSRF in Spring Security?","Cross-Site Request Forgery protection. Token generated per session.","Junior","Java"),
    ("Java Core","What is CSRF token?","Random token in form/header. Server validates on mutation.","Junior","Java"),
    ("Java Core","What is CORS in Spring Security?","Cross-Origin Resource Sharing. allowedOrigins, allowedMethods.","Junior","Java"),
    ("Java Core","What is SecurityContextHolder?","Stores SecurityContext. MODE_THREADLOCAL by default.","Junior","Java"),
    ("Java Core","What is SecurityContext?","Contains Authentication object. Current user principal.","Junior","Java"),
    ("Java Core","What is Authentication?","Principal, credentials, authorities, authenticated flag.","Junior","Java"),
    ("Java Core","What is AuthenticationProvider?","Authenticates using specific strategy: DAOAuthenticationProvider.","Middle","Java"),
    ("Java Core","What is DaoAuthenticationProvider?","Authenticates via UserDetailsService + PasswordEncoder.","Middle","Java"),
    ("Java Core","What is PasswordEncoder?","Password encoding: BCryptPasswordEncoder, Pbkdf2PasswordEncoder.","Junior","Java"),
    ("Java Core","What is BCryptPasswordEncoder?","BCrypt password hashing. strength parameter. Salt generated.","Junior","Java"),
    ("Java Core","What is SCryptPasswordEncoder?","SCrypt password hashing. Memory-hard. CPU + memory cost.","Middle","Java"),
    ("Java Core","What is Argon2PasswordEncoder?","Argon2 password hashing. Modern choice. Spring Security 5.3+.","Middle","Java"),
    ("Java Core","What is DelegatingPasswordEncoder?","Supports multiple encodings. Prefix: {bcrypt}, {pbkdf2}.","Middle","Java"),
    ("Java Core","What is Spring Security filters?","SecurityFilterChain: 15+ filters. UsernamePasswordAuthenticationFilter, etc.","Middle","Java"),
    ("Java Core","What is UsernamePasswordAuthenticationFilter?","Processes form login. username, password parameters.","Middle","Java"),
    ("Java Core","What is BasicAuthenticationFilter?","HTTP Basic auth. Base64 credentials. Insecure without TLS.","Junior","Java"),
    ("Java Core","What is BearerTokenAuthenticationFilter?","JWT bearer token. Authorization: Bearer <token>.","Middle","Java"),
    ("Java Core","What is ExceptionTranslationFilter?","Converts AccessDeniedException to 403 or redirect to login.","Middle","Java"),
    ("Java Core","What is FilterSecurityInterceptor?","Last filter. Checks authorization decision.","Middle","Java"),
    ("Java Core","What is AccessDecisionManager?","Decides if access granted. AffirmativeBased, ConsensusBased, UnanimousBased.","Senior","Java"),
    ("Java Core","What is AccessDecisionVoter?","Votes on access: ACCESS_GRANTED, ACCESS_DENIED, ACCESS_ABSTAIN.","Senior","Java"),
    ("Java Core","What is RoleHierarchy?","Role inheritance: ROLE_ADMIN > ROLE_USER. RoleHierarchyImpl.","Middle","Java"),
    ("Java Core","What is remember-me in Spring Security?","Persistent login token. PersistentTokenBasedRememberMeServices.","Junior","Java"),
    ("Java Core","What is anonymous authentication?","AnonymousAuthenticationToken for unauthenticated users.","Junior","Java"),
    ("Java Core","What is run-as authentication?","Method executes with different privileges. @RunAs.","Senior","Java"),
    ("Java Core","What is SwitchUserFilter?","Impersonate another user. /impersonate endpoint.","Senior","Java"),
    ("Java Core","What is @AuthenticationPrincipal?","Binds Authentication.principal to controller parameter.","Junior","Java"),
    ("Java Core","What is @CurrentSecurityContext?","Binds entire SecurityContext. expression for spel.","Middle","Java"),
    ("Java Core","What is Spring Security Test?","@WithMockUser, @WithUserDetails for test authentication.","Junior","Java"),
    ("Java Core","What is @WithMockUser?","Creates mock security context. roles, username, password.","Junior","Java"),
    ("Java Core","What is @WithAnonymousUser?","Sets anonymous authentication for test.","Junior","Java"),
    ("Java Core","What is @WithUserDetails?","Loads UserDetails from UserDetailsService for test.","Junior","Java"),
    ("Java Core","What is SecurityMockMvcResultMatchers?","authenticated(), unauthenticated() matchers.","Middle","Java"),
    ("Java Core","What is Spring Security OAuth2 Client?","OAuth2 client support. @EnableOAuth2Client (deprecated).","Middle","Java"),
    ("Java Core","What is OAuth2AuthorizedClient?","Client for authorized requests. authorize method.","Middle","Java"),
    ("Java Core","What is OAuth2AuthorizedClientManager?","Manages OAuth2 client tokens. refresh, authorize.","Senior","Java"),
    ("Java Core","What is Spring Security Reactive?","WebFlux security. SecurityWebFilterChain.","Middle","Java"),
    ("Java Core","What is ReactiveUserDetailsService?","Reactive version. Mono<UserDetails> findByUsername.","Middle","Java"),
    ("Java Core","What is ServerHttpSecurity?","Reactive security configuration. Same pattern as HttpSecurity.","Middle","Java"),
    ("Java Core","What is @EnableReactiveMethodSecurity?","Enables reactive method security annotations.","Middle","Java"),
    ("Java Core","What is WebSession?","Reactive session. Session ID, creation time, last access.","Middle","Java"),
    ("Java Core","What is Spring Session?","Session management. Redis, JDBC, MongoDB backed.","Middle","Java"),
    ("Java Core","What is @EnableRedisHttpSession?","Enables Redis-backed session management.","Middle","Java"),
    ("Java Core","What is HeaderHttpSessionStrategy?","Session ID via custom header. For REST APIs.","Middle","Java"),
    ("Java Core","What is CookieHttpSessionStrategy?","Session ID via cookie. Default session management.","Middle","Java"),
    ("Java Core","What is SessionRegistry?","Tracks active sessions. ConcurrentSessionControlAuthenticationStrategy.","Senior","Java"),
    ("Java Core","What is ConcurrentSessionControlAuthenticationStrategy?","Limits concurrent sessions. maxSessions.","Senior","Java"),
    ("Java Core","What is SessionInformation?","Session info: principal, session ID, last request.","Senior","Java"),
    ("Java Core","What is ExpiringSession?","Session with expiration. createTime, lastAccessTime, maxInactiveInterval.","Senior","Java"),
    ("Java Core","What is FindByIndexNameSessionRepository?","Finds sessions by principal name. indexName='SPRING_SECURITY_CONTEXT'.","Senior","Java"),
    ("Java Core","What is Spring Data Redis?","Redis data access. RedisTemplate, StringRedisTemplate.","Junior","Java"),
    ("Java Core","What is RedisTemplate?","Template for Redis ops. opsForValue, opsForList, opsForHash.","Junior","Java"),
    ("Java Core","What is RedisSerializer?","Serializes values in Redis. Jackson2JsonRedisSerializer, JdkSerializationRedisSerializer.","Middle","Java"),
    ("Java Core","What is @RedisHash?","Marks entity for Redis hashes. id, timeToLive.","Middle","Java"),
    ("Java Core","What is Redis Repository?","Spring Data JPA-like for Redis. CrudRepository, Query By Example.","Middle","Java"),
    ("Java Core","What is Redisson?","Redis client with Java objects. Distributed locks, queues, semaphores.","Middle","Java"),
    ("Java Core","What is Jedis?","Simple Redis client. Thread-safe JedisPool.","Junior","Java"),
    ("Java Core","What is Lettuce?","Async Redis client. Reactive support. Netty-based.","Middle","Java"),
    ("Java Core","What is MongoDB aggregation?","Pipeline stages: $match, $group, $sort, $project, $lookup.","Middle","Java"),
    ("Java Core","What is MongoDB compound index?","Index on multiple fields. Sort order matters.","Middle","Java"),
    ("Java Core","What is MongoDB text index?","Full-text search index. $text query operator.","Middle","Java"),
    ("Java Core","What is MongoDB 2dsphere index?","Geospatial index. GeoJSON format. $near, $geoWithin.","Middle","Java"),
    ("Java Core","What is MongoDB change streams?","Real-time data changes. Watch collection/database. Resume tokens.","Senior","Java"),
    ("Java Core","What is MongoDB replica set?","Primary + secondaries. Automatic failover. Oplog replication.","Middle","Java"),
    ("Java Core","What is MongoDB sharding?","Horizontal scaling. Shard key. Config servers, mongos.","Senior","Java"),
    ("Java Core","What is MongoDB Atlas?","Managed MongoDB cloud service. Backup, monitoring, auto-scaling.","Junior","Java"),
    ("Java Core","What is Spring Data MongoDB?","MongoRepository, MongoTemplate, QueryDSL.","Junior","Java"),
    ("Java Core","What is Elasticsearch mapping?","Schema definition. Field types: text, keyword, date, geo_point.","Middle","Java"),
    ("Java Core","What is Elasticsearch analyzer?","Tokenizes text. Standard, simple, whitespace, custom.","Middle","Java"),
    ("Java Core","What is Elasticsearch inverted index?","Term->document mapping. Fast full-text search.","Middle","Java"),
    ("Java Core","What is Elasticsearch shard?","Index subdivision. Primary and replica shards.","Middle","Java"),
    ("Java Core","What is Elasticsearch aggregations?","Data analytics. Terms, date_histogram, avg, cardinality.","Middle","Java"),
    ("Java Core","What is Spring Data Elasticsearch?","ElasticsearchRepository, ElasticsearchTemplate.","Junior","Java"),
    ("Java Core","What is Elasticsearch query DSL?","bool, must, should, filter. match, term, range queries.","Middle","Java"),
    ("Java Core","What is Elasticsearch scroll?","Deep pagination. Scroll context. snapshot for consistency.","Senior","Java"),
    ("Java Core","What is Elasticsearch search_after?","Cursor-based pagination. Sort values as tiebreaker.","Senior","Java"),
    ("Java Core","What is Elasticsearch suggesters?","Auto-complete: completion, term, phrase suggester.","Middle","Java"),
    ("Java Core","What is Elasticsearch Kibana?","Visualization tool. Dashboards, Discover, Canvas.","Junior","Java"),
    ("Java Core","What is Apache Kafka?","Distributed event streaming. Topics, partitions, consumer groups.","Junior","Java"),
    ("Java Core","What is Kafka topic?","Event category. Multi-subscriber. Partitioned for parallelism.","Junior","Java"),
    ("Java Core","What is Kafka partition?","Ordered event sequence. Partition key determines assignment.","Junior","Java"),
    ("Java Core","What is Kafka consumer group?","Load-balancing consumers. Each partition assigned to one consumer.","Junior","Java"),
    ("Java Core","What is Kafka offset?","Position in partition. Auto-commit or manual commit.","Junior","Java"),
    ("Java Core","What is Kafka producer acks?","acks=0 fire-and-forget, acks=1 leader, acks=all min.insync.replicas.","Middle","Java"),
    ("Java Core","What is Kafka idempotent producer?","Exactly-once semantics per partition. enable.idempotence=true.","Middle","Java"),
    ("Java Core","What is Kafka transactions?","Exactly-once across partitions. transactional.id.","Senior","Java"),
    ("Java Core","What is Kafka compaction?","Log cleanup. Keeps latest value per key. delete.retention.ms.","Middle","Java"),
    ("Java Core","What is Kafka replication?","Partitions replicated across brokers. ISR, min.insync.replicas.","Middle","Java"),
    ("Java Core","What is Kafka KRaft?","Kafka without ZooKeeper. Raft-based consensus. Metadata quorum.","Senior","Java"),
    ("Java Core","What is Spring Kafka?","Spring integration for Kafka. @KafkaListener, KafkaTemplate.","Junior","Java"),
    ("Java Core","What is @KafkaListener?","Message-driven POJO. topics, groupId, containerFactory.","Junior","Java"),
    ("Java Core","What is KafkaListenerErrorHandler?","Error handling for listener. Container-level error handler.","Middle","Java"),
    ("Java Core","What is KafkaTemplate?","Sends messages. send, sendDefault, executeInTransaction.","Junior","Java"),
    ("Java Core","What is ProducerFactory?","Creates Kafka producers. DefaultKafkaProducerFactory.","Middle","Java"),
    ("Java Core","What is ConsumerFactory?","Creates Kafka consumers. DefaultKafkaConsumerFactory.","Middle","Java"),
    ("Java Core","What is KafkaRetryTopicConfiguration?","Retry topics. Backoff, max attempts, dead letter topic.","Middle","Java"),
    ("Java Core","What is DefaultErrorHandler?","Retry on error. Backoff, recovery strategy.","Middle","Java"),
    ("Java Core","What is DeadLetterPublishingRecoverer?","Sends failed messages to DLQ topic.","Middle","Java"),
    ("Java Core","What is Confluent Schema Registry?","Avro/Protobuf schema registry. Schema evolution.","Senior","Java"),
    ("Java Core","What is Avro?","Binary serialization format. Schema in JSON. Compact and fast.","Middle","Java"),
    ("Java Core","What is Protobuf?","Protocol Buffers. Language-neutral serialization. Schema in .proto.","Middle","Java"),
    ("Java Core","What is gRPC?","High-performance RPC. HTTP/2. Protobuf. Streaming.","Middle","Java"),
    ("Java Core","What is gRPC server?","ServerBuilder.forPort(port).addService(impl).build().start().","Middle","Java"),
    ("Java Core","What is gRPC client?","ManagedChannelBuilder.forAddress(host, port).usePlaintext().build().","Middle","Java"),
    ("Java Core","What is gRPC streaming?","Server streaming, client streaming, bidirectional streaming.","Senior","Java"),
    ("Java Core","What is gRPC interceptor?","ServerInterceptor, ClientInterceptor for cross-cutting.","Senior","Java"),
    ("Java Core","What is GraphQL?","Query language for APIs. Schema, resolvers. Single endpoint.","Junior","Java"),
    ("Java Core","What is GraphQL schema?","Types: Query, Mutation, Subscription. Object, Input, Enum types.","Middle","Java"),
    ("Java Core","What is GraphQL resolver?","Data fetcher for each field. DataLoader for batching.","Middle","Java"),
    ("Java Core","What is GraphQL DataLoader?","Batching and caching. Loads related data efficiently.","Middle","Java"),
    ("Java Core","What is GraphQL subscriptions?","Real-time updates via WebSocket. Subscription type.","Senior","Java"),
    ("Java Core","What is Spring GraphQL?","spring-graphql starter. @QueryMapping, @MutationMapping.","Middle","Java"),
    ("Java Core","What is graphql-java?","Java implementation of GraphQL. Schema parser, RuntimeWiring.","Middle","Java"),
    ("Java Core","What is DGS framework?","Netflix's GraphQL framework. @DgsComponent, @DgsQuery.","Middle","Java"),
    ("Java Core","What is Apollo GraphQL?","GraphQL client. Query batching, caching, optimistic UI.","Junior","Java"),
    ("Java Core","What is GraphQL federation?","Distributed GraphQL. Gateway composes subgraphs. Apollo Federation.","Senior","Java"),
    ("Java Core","What is Apache Camel?","Integration framework. Routes, endpoints, EIP patterns.","Middle","Java"),
    ("Java Core","What is Camel route?","from('file:in').to('jms:queue'). Route definition DSL.","Middle","Java"),
    ("Java Core","What is Camel EIP?","Enterprise Integration Patterns. Splitter, Aggregator, WireTap.","Middle","Java"),
    ("Java Core","What is Camel component?","Endpoint connector: file, jms, http, sql, kafka.","Middle","Java"),
    ("Java Core","What is Camel processor?","Message transformation. Exchange, Message body/headers.","Middle","Java"),
    ("Java Core","What is MuleSoft?","Integration platform. Anypoint Studio, Mule runtime.","Middle","Java"),
    ("Java Core","What is RabbitMQ?","AMQP message broker. Exchanges, queues, bindings.","Junior","Java"),
    ("Java Core","What is RabbitMQ exchange?","Direct, Topic, Fanout, Headers exchange types.","Junior","Java"),
    ("Java Core","What is RabbitMQ binding?","Binds queue to exchange with routing key.","Junior","Java"),
    ("Java Core","What is Spring AMQP?","RabbitTemplate, @RabbitListener. Message converter.","Junior","Java"),
    ("Java Core","What is @RabbitListener?","Annotated POJO for consuming messages. queues, containerFactory.","Junior","Java"),
    ("Java Core","What is RabbitTemplate?","Sends/receives messages. convertAndSend, receiveAndConvert.","Junior","Java"),
    ("Java Core","What is ActiveMQ?","JMS message broker. Open source. Supports JMS 1.1/2.0.","Junior","Java"),
    ("Java Core","What is JMS API?","Java Message Service. Queue (P2P) and Topic (pub/sub).","Junior","Java"),
    ("Java Core","What is JMS message?","Headers, properties, body. TextMessage, ObjectMessage, BytesMessage.","Junior","Java"),
    ("Java Core","What is @JmsListener?","JMS consumer annotation. destination, containerFactory.","Junior","Java"),
    ("Java Core","What is JmsTemplate?","JMS producer. convertAndSend, receiveAndConvert.","Junior","Java"),
    ("Java Core","What is Apache Pulsar?","Cloud-native messaging. Topics, partitions, bookies.","Middle","Java"),
    ("Java Core","What is Pulsar topic?","Persistent or non-persistent. Partitioned for scale.","Middle","Java"),
    ("Java Core","What is Pulsar subscription?","Exclusive, Shared, Failover subscription types.","Middle","Java"),
    ("Java Core","What is Pulsar functions?","Lightweight compute at broker. JavaScript, Python, Java.","Senior","Java"),
    ("Java Core","What is Pulsar IO?","Connectors for external systems. Source, Sink.","Senior","Java"),
    ("Java Core","What is Hazelcast?","In-memory data grid. Distributed maps, queues, topics.","Middle","Java"),
    ("Java Core","What is Hazelcast IMap?","Distributed map. Partitioned. Near cache for reads.","Middle","Java"),
    ("Java Core","What is Hazelcast Jet?","Distributed stream processing. Pipeline API.","Senior","Java"),
    ("Java Core","What is Ignite?","In-memory computing platform. SQL, ACID transactions.","Senior","Java"),
    ("Java Core","What is Ignite SQL?","Distributed SQL queries. H2 optimizer. Indexes.","Senior","Java"),
    ("Java Core","What is Ehcache?","Java caching library. JCache (JSR-107) implementation.","Junior","Java"),
    ("Java Core","What is JCache (JSR-107)?","Standard caching API. @CacheResult, @CacheRemove.","Middle","Java"),
    ("Java Core","What is Caffeine cache?","High-performance Java cache. Window-TinyLFU eviction.","Middle","Java"),
    ("Java Core","What is Caffeine policy?","Size-based: maximumSize. Time-based: expireAfterWrite, expireAfterAccess.","Middle","Java"),
    ("Java Core","What is Caffeine refresh?","Cache.refreshAfterWrite. Asynchronous loading after write.","Middle","Java"),
    ("Java Core","What is Guava cache?","Google's caching library. CacheBuilder, CacheLoader.","Junior","Java"),
    ("Java Core","What is Jib?","Container builder for Java. Docker layers. No Dockerfile needed.","Middle","Java"),
    ("Java Core","What is Dockerfile best practices?","Multi-stage builds. Minimize layers. .dockerignore.","Junior","Java"),
    ("Java Core","What is docker compose?","Multi-container orchestration. services, networks, volumes.","Junior","Java"),
    ("Java Core","What is Kubernetes Deployment?","ReplicaSet + rolling update. spec.replicas, strategy.","Junior","Java"),
    ("Java Core","What is Kubernetes Service?","Stable IP to pods. ClusterIP, NodePort, LoadBalancer, ExternalName.","Junior","Java"),
    ("Java Core","What is Kubernetes Ingress?","HTTP/S routing. TLS termination. Path-based routing.","Middle","Java"),
    ("Java Core","What is Kubernetes ConfigMap?","Non-sensitive config. key-value pairs. Env or volume mount.","Junior","Java"),
    ("Java Core","What is Kubernetes Secret?","Sensitive config. Base64 encoded. Opaque, TLS, Docker.","Junior","Java"),
    ("Java Core","What is Kubernetes PersistentVolume?","Storage resource. NFS, EBS, GCE. accessModes: ReadWriteOnce.","Middle","Java"),
    ("Java Core","What is Kubernetes StatefulSet?","Stateful apps. Stable network ID. Ordered deployment.","Middle","Java"),
    ("Java Core","What is Kubernetes DaemonSet?","Pod on every node. For logging, monitoring agents.","Junior","Java"),
    ("Java Core","What is Kubernetes Job?","Batch processing. Pod runs to completion. BackoffLimit.","Junior","Java"),
    ("Java Core","What is Kubernetes CronJob?","Scheduled jobs: '*/5 * * * *'. Concurrency policy.","Junior","Java"),
    ("Java Core","What is Kubernetes HPA?","Horizontal Pod Autoscaler. CPU/memory based. External metrics.","Middle","Java"),
    ("Java Core","What is Kubernetes VPA?","Vertical Pod Autoscaler. Adjusts CPU/memory requests.","Senior","Java"),
    ("Java Core","What is Kubernetes RBAC?","Role-based access. Role, ClusterRole, RoleBinding, ClusterRoleBinding.","Middle","Java"),
    ("Java Core","What is Kubernetes NetworkPolicy?","Pod network security. ingress, egress rules. PodSelector.","Middle","Java"),
    ("Java Core","What is Kubernetes Helm?","Package manager. Charts, templates, values. Release management.","Junior","Java"),
    ("Java Core","What is Helm chart structure?","Chart.yaml, values.yaml, templates/. helpers.tpl.","Middle","Java"),
    ("Java Core","What is Helm template?","Go templates. {{ .Values.replicaCount }}, {{ .Release.Name }}.","Middle","Java"),
    ("Java Core","What is Kubernetes Operator?","Custom controller. CRD + controller. Extends K8s API.","Senior","Java"),
    ("Java Core","What is Istio service mesh?","Sidecar proxy (Envoy). Traffic management, security, observability.","Senior","Java"),
    ("Java Core","What is Istio VirtualService?","Traffic routing rules. Destination, weight, match conditions.","Senior","Java"),
    ("Java Core","What is Istio DestinationRule?","Traffic policies. Load balancer, circuit breaker, TLS.","Senior","Java"),
    ("Java Core","What is Jaeger tracing?","Distributed tracing. OpenTelemetry. Trace, span, baggage.","Middle","Java"),
    ("Java Core","What is OpenTelemetry?","Observability framework. Traces, metrics, logs. Language SDKs.","Middle","Java"),
    ("Java Core","What is OpenTelemetry span?","Operation unit. TraceId, SpanId, ParentSpanId. Attributes.","Middle","Java"),
    ("Java Core","What is OpenTelemetry exporter?","Sends data: OTLP, Jaeger, Zipkin, Prometheus.","Middle","Java"),
    ("Java Core","What is Prometheus metrics?","Counter, Gauge, Histogram, Summary. Query with PromQL.","Middle","Java"),
    ("Java Core","What is PromQL?","Prometheus query language. rate, histogram_quantile, topk.","Middle","Java"),
    ("Java Core","What is Grafana dashboard?","Visualization panels. Time series, table, stat. Data source.","Junior","Java"),
    ("Java Core","What is Grafana alert?","Alert rules. Conditions, no data, error handling. Notification channel.","Middle","Java"),
    ("Java Core","What is Logback?","Logging framework. SLF4J implementation. logback.xml config.","Junior","Java"),
    ("Java Core","What is Logback appender?","ConsoleAppender, FileAppender, RollingFileAppender, SocketAppender.","Junior","Java"),
    ("Java Core","What is Logback RollingFileAppender?","File rotation. TimeBasedRollingPolicy, SizeBasedTriggeringPolicy.","Middle","Java"),
    ("Java Core","What is Logback MDC?","Mapped Diagnostic Context. Thread-local context. %X{userId}.","Middle","Java"),
    ("Java Core","What is Log4j2?","Logging framework. Async loggers. Configuration via XML, JSON.","Junior","Java"),
    ("Java Core","What is Log4j2 Layout?","PatternLayout, JSONLayout, XmlLayout, CsvLayout.","Junior","Java"),
    ("Java Core","What is SLF4J?","Simple Logging Facade for Java. Bridges: log4j-over-slf4j.","Junior","Java"),
    ("Java Core","What is Lombok?","Annotation-based code generation. @Data, @Builder, @Slf4j.","Junior","Java"),
    ("Java Core","What is Lombok @Data?","@Getter + @Setter + @ToString + @EqualsAndHashCode + @RequiredArgsConstructor.","Junior","Java"),
    ("Java Core","What is Lombok @Builder?","Builder pattern. @Builder.Default for defaults.","Junior","Java"),
    ("Java Core","What is Lombok @Slf4j?","Creates log field: private static final Logger log.","Junior","Java"),
    ("Java Core","What is Lombok @Value?","Immutable variant of @Data. All fields final.","Junior","Java"),
    ("Java Core","What is Lombok @With?","Creates withX methods. Returns copy with modified field.","Junior","Java"),
    ("Java Core","What is Lombok @NonNull?","Null-check. Throws NullPointerException if null.","Junior","Java"),
    ("Java Core","What is Lombok @Cleanup?","Auto-close resources: @Cleanup InputStream in.","Junior","Java"),
    ("Java Core","What is Lombok @SneakyThrows?","Throws checked exceptions without declaring. Use cautiously.","Middle","Java"),
    ("Java Core","What is MapStruct?","Code generator for bean mappings. @Mapper, @Mapping.","Middle","Java"),
    ("Java Core","What is MapStruct @Mapping?","target='field', source='otherField'. ignore, expression.","Middle","Java"),
    ("Java Core","What is MapStruct componentModel?","spring: @Autowired mapper. cdi: @Inject.","Middle","Java"),
    ("Java Core","What is ModelMapper?","Object-to-object mapping. Auto-matching fields.","Junior","Java"),
    ("Java Core","What is Orika?","Java bean mapping. ClassMapBuilder for custom mapping.","Middle","Java"),
    ("Java Core","What is Jackson?","JSON processing. ObjectMapper, @JsonProperty, @JsonIgnore.","Junior","Java"),
    ("Java Core","What is Jackson @JsonInclude?","Include non-null only: @JsonInclude(Include.NON_NULL).","Junior","Java"),
    ("Java Core","What is Jackson @JsonFormat?","Format: @JsonFormat(pattern='yyyy-MM-dd', shape=STRING).","Junior","Java"),
    ("Java Core","What is Jackson @JsonView?","View-based serialization. Different JSON per API version.","Middle","Java"),
    ("Java Core","What is Jackson @JsonIgnoreProperties?","Ignore unknown fields: @JsonIgnoreProperties(ignoreUnknown=true).","Junior","Java"),
    ("Java Core","What is Jackson @JsonProperty?","Custom property name. access=READ_ONLY, WRITE_ONLY.","Junior","Java"),
    ("Java Core","What is Jackson @JsonUnwrapped?","Flattens nested object. Prefix, suffix.","Middle","Java"),
    ("Java Core","What is Jackson @JsonTypeInfo?","Polymorphic type handling. Type property, include class.","Senior","Java"),
    ("Java Core","What is Gson?","Google JSON library. JsonObject, JsonArray. toJson, fromJson.","Junior","Java"),
    ("Java Core","What is Gson @Expose?","Controls serialization. serialize=true, deserialize=true.","Junior","Java"),
    ("Java Core","What is Gson TypeToken?","Generic type: new TypeToken<List<String>>(){}.getType().","Middle","Java"),
    ("Java Core","What is Gson JsonSerializer?","Custom serializer. serialize method with context.","Middle","Java"),
]
for item in remaining:
    add(item[0], item[1], item[2], item[3], item[4])

# Write
with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + '\n'.join(new) + '\n' + after)
total = (before + '\n'.join(new) + '\n' + after).count('\n  Q(')
print(f'Batch 8 added {len(new)} questions. Total: {total}')