"""Batch 17: Final ~850 questions to reach ~9000 total - dense generation"""
import json
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    opts = [a, 'Common misconception', 'Alternative approach', 'I don\'t know']
    obj = {"category": cat, "question": q, "short_answer": a, "options": opts, "difficulty": diff, "language": lang}
    json.dumps(obj, ensure_ascii=False)
    assert all(isinstance(o, str) and len(o) > 0 for o in opts)
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(opts[0])}', '{esc(opts[1])}', '{esc(opts[2])}', '{esc(opts[3])}'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# === JAVA: Architecture, Bytecode, Nashorn, Unsafe ===
gen([
    ("Bytecode", "What is the invokedynamic instruction?", "Dynamic method dispatch for lambdas and dynamic languages"),
    ("Bytecode", "What is the aload instruction?", "Loads reference from local variable onto stack"),
    ("Bytecode", "What is the iload/istore instructions?", "Load/store integer to/from local variable"),
    ("Bytecode", "What is the getfield/putfield instructions?", "Access instance fields on the heap"),
    ("Bytecode", "What is the getstatic/putstatic instructions?", "Access static class fields"),
    ("Bytecode", "What is the invokevirtual instruction?", "Calls instance method with virtual dispatch"),
    ("Bytecode", "What is the invokespecial instruction?", "Calls constructors, private methods, super methods"),
    ("Bytecode", "What is the invokestatic instruction?", "Calls static methods"),
    ("Bytecode", "What is the invokeinterface instruction?", "Calls interface methods with dynamic dispatch"),
    ("Bytecode", "What is the anewarray instruction?", "Creates new array of reference type"),
    ("Bytecode", "What is the multianewarray instruction?", "Creates multi-dimensional array"),
    ("Bytecode", "What is the arraylength instruction?", "Gets length of an array"),
    ("Bytecode", "What is the checkcast instruction?", "Runtime type checking with cast"),
    ("Bytecode", "What is the instanceof instruction?", "Runtime type test returning boolean"),
    ("Bytecode", "What is the jsr/ret instruction?", "Subroutine call (removed in Java 7)"),
    ("Bytecode", "What is ASM library?", "Bytecode manipulation framework for class transformation"),
    ("Bytecode", "What is the ASM ClassReader?", "Reads and parses Java class files"),
    ("Bytecode", "What is the ASM ClassWriter?", "Generates Java class files from scratch"),
    ("Bytecode", "What is the ASM ClassVisitor?", "Visits class elements for transformation"),
    ("Bytecode", "What is the ASM MethodVisitor?", "Visits method instructions for transformation"),
    ("Bytecode", "What is ASM Tree API?", "Object model representation of class structure"),
    ("Bytecode", "What is the cglib library?", "Code generation library for dynamic proxies"),
    ("Bytecode", "What is the ByteBuddy library?", "Runtime bytecode generation with type-safe API"),
    ("Bytecode", "What is ByteBuddy AgentBuilder?", "Java agent for class transformation at load time"),
    ("Bytecode", "What is the instrumentation API?", "Modifies bytecode of classes loaded in JVM"),
    ("Bytecode", "What is java.lang.instrument.ClassFileTransformer?", "Transforms class bytecode before definition"),
    ("Bytecode", "What is the javassist library?", "Bytecode editor with high-level source API"),
    ("Bytecode", "What is javassist CtClass?", "Compile-time class representation for modification"),
    ("Bytecode", "What is javassist CtMethod?", "Method manipulation in javassist"),
    ("Bytecode", "What is the Attach API?", "Attaches agent to running JVM process"),
], "Senior", "Java")

# === PYTHON: Functional programming, Design Patterns in Python, Code Analysis ===
gen([
    ("Functional", "What is the operator.mul function?", "Multiplication operator as function"),
    ("Functional", "What is the operator.itemgetter(1)?", "Gets second item from sequence"),
    ("Functional", "What is the operator.attrgetter('name')?", "Gets attribute by name from object"),
    ("Functional", "What is the operator.methodcaller('foo')?", "Calls method by name on object"),
    ("Functional", "What is the functools.partial method?", "Fixes arguments of a function"),
    ("Functional", "What is the functools.singledispatch method?", "Generic function dispatching on first argument type"),
    ("Functional", "What is the functools.update_wrapper?", "Copies metadata to wrapper function"),
    ("Functional", "What is the itertools.count() function?", "Infinite arithmetic progression iterator"),
    ("Functional", "What is the itertools.cycle() function?", "Infinite cycling iterator over iterable"),
    ("Functional", "What is the itertools.repeat() function?", "Infinite or limited repetition of value"),
    ("Functional", "What is the itertools.chain() function?", "Sequentially chains iterables"),
    ("Functional", "What is the itertools.compress() function?", "Filters by selector iterable"),
    ("Functional", "What is the itertools.dropwhile() function?", "Drops elements while predicate true"),
    ("Functional", "What is the itertools.takewhile() function?", "Takes elements while predicate true"),
    ("Functional", "What is the itertools.filterfalse() function?", "Filters elements where predicate false"),
    ("Functional", "What is the itertools.zip_longest() function?", "Zips with fill value for uneven iterables"),
    ("Functional", "What is the itertools.starmap() function?", "Maps with unpacked argument tuples"),
    ("Functional", "What is the itertools.tee() function?", "Creates independent copies of iterator"),
    ("Functional", "What is the itertools.pairwise() (3.10)?", "Yields successive overlapping pairs"),
    ("Functional", "What is the itertools.batched() (3.12)?", "Yields batches of specified size from iterable"),
    ("Patterns", "What is the Strategy pattern in Python?", "Runtime algorithm selection via callable objects"),
    ("Patterns", "What is the Observer pattern in Python?", "Event notification with callbacks or custom signals"),
    ("Patterns", "What is the Command pattern in Python?", "Encapsulates action as object with execute method"),
    ("Patterns", "What is the Template Method pattern in Python?", "Override algorithm steps in subclass methods"),
    ("Patterns", "What is the Adapter pattern in Python?", "Wraps interface to match expected protocol"),
    ("Patterns", "What is the Facade pattern in Python?", "Simplified interface to complex subsystem"),
    ("Patterns", "What is the Proxy pattern in Python?", "Controls access with wrapper implementing same interface"),
    ("Patterns", "What is the Composite pattern in Python?", "Tree structure with uniform component interface"),
    ("Patterns", "What is the Iterator pattern in Python?", "Sequential access via __iter__ and __next__"),
    ("Patterns", "What is the State pattern in Python?", "Behavior changes with internal state object"),
], "Senior", "Python")

# === TYPESCRIPT: Express.js, NestJS detail, TypeORM ===
gen([
    ("Express", "What is Express.js?", "Minimal web framework for Node.js with middleware routing"),
    ("Express", "What is app.get() in Express?", "Defines GET route handler for path"),
    ("Express", "What is app.post() in Express?", "Defines POST route handler for path"),
    ("Express", "What is Express middleware?", "Functions with req, res, next in request pipeline"),
    ("Express", "What is next() in Express middleware?", "Passes control to next middleware function"),
    ("Express", "What is express.json() middleware?", "Parses JSON request body"),
    ("Express", "What is express.urlencoded() middleware?", "Parses URL-encoded form body"),
    ("Express", "What is express.static() middleware?", "Serves static files from directory"),
    ("Express", "What is the req.params in Express?", "Route parameters from URL pattern"),
    ("Express", "What is the req.query in Express?", "Query string parameters"),
    ("Express", "What is the req.body in Express?", "Parsed request body from body parsers"),
    ("Express", "What is Express error middleware?", "Four-argument (err, req, res, next) handler"),
    ("Express", "What is the express.Router()?", "Modular route handlers with middleware"),
    ("Express", "What is res.json() in Express?", "Sends JSON response"),
    ("Express", "What is res.status() in Express?", "Sets HTTP status code"),
    ("Express", "What is res.send() in Express?", "Sends response of various types"),
    ("Express", "What is res.redirect() in Express?", "Redirects to different URL"),
    ("Express", "What is res.render() in Express?", "Renders template view"),
    ("Express", "What is Express CORS middleware?", "Enables Cross-Origin Resource Sharing"),
    ("Express", "What is Express helmet middleware?", "Security headers middleware"),
    ("TypeORM", "What is TypeORM?", "ORM for TypeScript/JavaScript with Active Record and Data Mapper"),
    ("TypeORM", "What is the @Entity decorator?", "Marks class as database entity"),
    ("TypeORM", "What is the @PrimaryGeneratedColumn?", "Auto-increment primary key column"),
    ("TypeORM", "What is the @Column decorator?", "Defines table column with type and options"),
    ("TypeORM", "What is the @ManyToOne decorator?", "Many-to-one relationship with join column"),
    ("TypeORM", "What is the @OneToMany decorator?", "One-to-many relationship with inverse side"),
    ("TypeORM", "What is the @JoinColumn decorator?", "Specifies foreign key column in relationship"),
    ("TypeORM", "What is the @ManyToMany decorator?", "Many-to-many with junction table"),
    ("TypeORM", "What is the @JoinTable decorator?", "Specifies junction table for many-to-many"),
    ("TypeORM", "What is TypeORM repository pattern?", "EntityRepository for custom queries"),
    ("TypeORM", "What is TypeORM find options?", "where, order, relations, skip, take for queries"),
    ("TypeORM", "What is TypeORM query builder?", "Builds SQL queries with chainable methods"),
    ("TypeORM", "What is TypeORM migrations?", "Version-controlled schema changes"),
    ("TypeORM", "What is TypeORM DataSource?", "Database connection configuration"),
    ("TypeORM", "What is TypeORM Active Record pattern?", "Entity with built-in save, find, remove methods"),
    ("TypeORM", "What is TypeORM Data Mapper pattern?", "Separate repository class for database operations"),
    ("TypeORM", "What is TypeORM subscribers?", "Entity lifecycle event listeners"),
    ("TypeORM", "What is TypeORM migrations:generate?", "Auto-generates migration from entity changes"),
    ("TypeORM", "What is TypeORM migrations:run?", "Applies pending migrations"),
    ("TypeORM", "What is TypeORM synchronize option?", "Auto-syncs database schema (dev only)"),
], "Middle", "TypeScript")

# === GO: Context deep, testing/suite, mock, wire DI ===
gen([
    ("Context", "What is context.Background()?", "Returns empty root context, never cancelled"),
    ("Context", "What is context.TODO()?", "Placeholder context when unclear which context to use"),
    ("Context", "What is context.WithValue()?", "Attaches key-value pair to context"),
    ("Context", "What is context.WithCancel()?", "Creates cancellable context with cancel function"),
    ("Context", "What is context.WithTimeout()?", "Context that cancels after specified duration"),
    ("Context", "What is context.WithDeadline()?", "Context that cancels at specified time"),
    ("Context", "What is the ctx.Done() channel?", "Closed when context is cancelled or times out"),
    ("Context", "What is the ctx.Err() method?", "Returns cancellation reason or nil"),
    ("Context", "What is the ctx.Value() method?", "Retrieves value by key from context"),
    ("Context", "What is context propagation?", "Passing context through API boundaries for tracing"),
    ("Wire", "What is Google Wire?", "Compile-time dependency injection for Go"),
    ("Wire", "What is wire.NewSet()?", "Groups providers into a dependency injection set"),
    ("Wire", "What is wire.Build()?", "Builds injector function from provider sets"),
    ("Wire", "What is wire.Bind()?", "Binds interface to concrete implementation"),
    ("Wire", "What is wire.Struct()?", "Injects all fields of a struct"),
    ("Wire", "What is wire.FieldsOf()?", "Extracts providers from struct fields"),
    ("Wire", "What is wireinject.go?", "Builds injector function with wire.Build()"),
    ("Wire", "What is the wire command?", "Generates injector code from wireinject files"),
    ("Wire", "What is provider set reusability?", "Wire sets composed from other wire sets"),
    ("Wire", "What is wire cleanup function?", "Second return value for closing resources"),
    ("Mock", "What is testify mock?", "Mock objects for interface testing"),
    ("Mock", "What is mock.On() method?", "Sets up expected call with arguments"),
    ("Mock", "What is mock.On().Return()?", "Specifies return values for expected call"),
    ("Mock", "What is mock.AssertExpectations()?", "Verifies all expected calls were made"),
    ("Mock", "What is testify suite?", "TestSuite with setup/teardown lifecycle"),
    ("Mock", "What is suite.SetupTest()?", "Runs before each test in the suite"),
    ("Mock", "What is suite.TearDownTest()?", "Runs after each test in the suite"),
    ("Mock", "What is the mock.Anything constant?", "Matches any argument in mock expectations"),
    ("Mock", "What is the mock.MatchedBy() function?", "Custom argument matcher for mock expectations"),
    ("Mock", "What is mock.Called() inside method?", "Records call and returns configured values"),
], "Senior", "Go")

# === RUST: async deep, Error handling with anyhow/thiserror, Serde deep ===
gen([
    ("Async", "What is tokio::main?", "Macro to mark async main function"),
    ("Async", "What is tokio::spawn()?", "Spawns a task on Tokio runtime"),
    ("Async", "What is tokio::time::sleep()?", "Non-blocking async sleep"),
    ("Async", "What is tokio::sync::Mutex?", "Async-aware mutual exclusion lock"),
    ("Async", "What is tokio::sync::RwLock?", "Async reader-writer lock"),
    ("Async", "What is tokio::sync::mpsc?", "Multi-producer single-consumer channel"),
    ("Async", "What is tokio::sync::oneshot?", "One-shot channel for single value"),
    ("Async", "What is tokio::sync::broadcast?", "Fan-out channel for multiple receivers"),
    ("Async", "What is tokio::sync::watch?", "Change notification channel with latest value"),
    ("Async", "What is tokio::sync::Semaphore?", "Async semaphore for limiting concurrency"),
    ("Async", "What is tokio::sync::Barrier?", "Async barrier for synchronization point"),
    ("Async", "What is tokio::sync::Notify?", "Single-thread notification primitive"),
    ("Async", "What is tokio::select! macro?", "Waits on multiple async branches"),
    ("Async", "What is tokio::join! macro?", "Runs multiple futures concurrently"),
    ("Async", "What is tokio::try_join! macro?", "Runs fallible futures concurrently"),
    ("Async", "What is Tokio TcpListener?", "Async TCP server listener"),
    ("Async", "What is Tokio TcpStream?", "Async TCP connection"),
    ("Async", "What is tokio::fs?", "Async filesystem operations"),
    ("Async", "What is tokio::io::AsyncRead/AsyncWrite?", "Async I/O traits"),
    ("Async", "What is tokio::net::UdpSocket?", "Async UDP socket"),
    ("Error", "What is anyhow::Result<T>?", "Type alias for Result<T, anyhow::Error>"),
    ("Error", "What is anyhow::bail!()?", "Returns early with error message"),
    ("Error", "What is anyhow::Context trait?", "Adds context to errors with .context()"),
    ("Error", "What is anyhow::anyhow!()?", "Creates ad-hoc error with message"),
    ("Error", "What is the thiserror derive?", "Derives std::error::Error for custom types"),
    ("Error", "What is #[error(\"...\")] in thiserror?", "Format string for Display implementation"),
    ("Error", "What is #[from] in thiserror?", "Auto-generates From impl for source error"),
    ("Error", "What is color-eyre?", "Error reporting with colored backtraces"),
    ("Error", "What is howtoreadme?'s human panic?", "Human-readable panic messages"),
    ("Error", "What is the snafu crate?", "Error generation with context fields"),
    ("Serde", "What is serde::Serialize?", "Trait for serializable types"),
    ("Serde", "What is serde::Deserialize?", "Trait for deserializable types"),
    ("Serde", "What is #[serde(rename_all = \"camelCase\")]?", "Renames fields to camelCase in JSON"),
    ("Serde", "What is #[serde(default)]?", "Uses Default when field missing in source"),
    ("Serde", "What is #[serde(skip_serializing_if = \"Option::is_none\")]?", "Skips None Option fields in output"),
    ("Serde", "What is #[serde(flatten)]?", "Flattens nested struct into parent"),
    ("Serde", "What is #[serde(tag = \"type\")]?", "Internally tagged enum representation"),
    ("Serde", "What is #[serde(untagged)]?", "Untagged enum representation"),
    ("Serde", "What is #[serde(deny_unknown_fields)]?", "Errors on unknown fields during deserialization"),
    ("Serde", "What is serde_json::from_str()?", "Deserializes JSON string to Rust type"),
    ("Serde", "What is serde_json::to_string()?", "Serializes Rust type to JSON string"),
    ("Serde", "What is serde_json::Value?", "Dynamic JSON value enum for flexible parsing"),
    ("Serde", "What is serde_yaml?", "YAML serialization with serde"),
    ("Serde", "What is serde_urlencoded?", "URL-encoded form data with serde"),
    ("Serde", "What is bincode?", "Compact binary serialization with serde"),
    ("Serde", "What is messagepack (rmp-serde)?", "MessagePack binary format with serde"),
    ("Serde", "What is serde_json::json! macro?", "Builds serde_json::Value with JSON-like syntax"),
    ("Serde", "What is serde_with crate?", "Customizable serde helpers for common patterns"),
    ("Serde", "What is serde_qs?", "Query string deserialization compatible with serde"),
    ("Serde", "What is serde_bytes?", "Efficient byte buffer serialization for serde"),
], "Senior", "Rust")

# === REACT: Component Libraries detail, Query/SWR, Auth, Forms detail ===
gen([
    ("Chakra UI", "What is Chakra UI?", "Component library with accessibility and styling props"),
    ("Chakra UI", "What is ChakraProvider?", "Wraps app for theme and context"),
    ("Chakra UI", "What is the Box component?", "Layout primitive with style props"),
    ("Chakra UI", "What is the Flex component?", "Flexbox layout container"),
    ("Chakra UI", "What is the Stack component?", "Vertical/horizontal spacing layout"),
    ("Chakra UI", "What is the VStack/HStack?", "Vertical or horizontal stack with spacing"),
    ("Chakra UI", "What is the Button component?", "Clickable button with variants and sizes"),
    ("Chakra UI", "What is the Input component?", "Text input with variants"),
    ("Chakra UI", "What is the FormControl component?", "Form field wrapper with label and error"),
    ("Chakra UI", "What is the useToast hook?", "Trigger notification toasts"),
    ("Chakra UI", "What is the Modal component?", "Dialog overlay with focus trap"),
    ("Chakra UI", "What is the Drawer component?", "Slide-in panel from edge"),
    ("Chakra UI", "What is Chakra color mode?", "Light/dark mode toggle with useColorMode"),
    ("Chakra UI", "What is the Chakra theme?", "Customizable design tokens for colors, fonts, spacing"),
    ("Chakra UI", "What is Chakra extendTheme?", "Extends default theme with custom overrides"),
    ("SWR", "What is SWR?", "React Hooks library for data fetching with stale-while-revalidate"),
    ("SWR", "What is useSWR()?", "Fetch hook with cache, revalidation, deduplication"),
    ("SWR", "What is useSWR key?", "Unique key for cache and request identity"),
    ("SWR", "What is useSWR fetcher?", "Function that returns fetched data (usually fetch)"),
    ("SWR", "What is SWR revalidation?", "Auto-refresh on focus, interval, reconnect"),
    ("SWR", "What is mutate() in SWR?", "Optimistic updates and cache invalidation"),
    ("SWR", "What is useSWRMutation()?", "Mutation hook for data modifications"),
    ("SWR", "What is SWRConfig?", "Global provider for default SWR options"),
    ("SWR", "What is SWR suspense mode?", "Throws promise for React Suspense integration"),
    ("SWR", "What is SWR error handling?", "Error object from useSWR for error display"),
    ("TanStack Query", "What is TanStack Query (React Query)?", "Server state management with caching and sync"),
    ("TanStack Query", "What is useQuery()?", "Reads data from server with caching"),
    ("TanStack Query", "What is useMutation()?", "Creates/updates/deletes data on server"),
    ("TanStack Query", "What is queryClient.invalidateQueries()?", "Invalidates cached queries for refetch"),
    ("TanStack Query", "What is queryClient.setQueryData()?", "Sets cached query data manually"),
    ("TanStack Query", "What is queryClient.prefetchQuery()?", "Fetches data before component renders"),
    ("TanStack Query", "What is the QueryClientProvider?", "Provides query client to component tree"),
    ("TanStack Query", "What is TanStack Query DevTools?", "Development tools for debugging queries"),
    ("TanStack Query", "What is the staleTime option?", "Time before cached data is considered stale"),
    ("TanStack Query", "What is the cacheTime option?", "Time inactive data stays in cache"),
    ("Auth", "What is Clerk?", "Authentication and user management platform"),
    ("Auth", "What is the ClerkProvider?", "Wraps app with Clerk context"),
    ("Auth", "What is useUser() in Clerk?", "Returns authenticated user data"),
    ("Auth", "What is useAuth() in Clerk?", "Access auth helpers and session"),
    ("Auth", "What is SignIn component?", "Pre-built sign-in form from Clerk"),
    ("Auth", "What is SignUp component?", "Pre-built registration form from Clerk"),
    ("Auth", "What is UserButton component?", "User profile button with dropdown"),
    ("Auth", "What is @clerk/nextjs?", "Clerk integration for Next.js with middleware"),
    ("Auth", "What is clerkMiddleware in Next.js?", "Protects routes with authentication"),
    ("Auth", "What is Supabase Auth?", "Open-source authentication with Row Level Security"),
    ("Auth", "What is supabase.auth.signInWithPassword()?", "Email/password authentication"),
    ("Auth", "What is supabase.auth.signUp()?", "User registration with confirmation"),
    ("Auth", "What is supabase.auth.signOut()?", "Ends user session"),
    ("Auth", "What is supabase.auth.getSession()?", "Retrieves current session on load"),
    ("Auth", "What is supabase.auth.onAuthStateChange()?", "Listens to auth state changes"),
], "Senior", "React")

# === KOTLIN: Kotlin DSL, buildSrc, Gradle Kotlin DSL, Compose internals ===
gen([
    ("DSL", "What is a type-safe builder in Kotlin?", "Using lambdas with receiver for DSL construction"),
    ("DSL", "What is the @DslMarker annotation?", "Restricts implicit receiver access in nested DSL scopes"),
    ("DSL", "What is the apply() scope function for DSL?", "Configures receiver object and returns it"),
    ("DSL", "What is the with() scope function for DSL?", "Configures receiver but returns lambda result"),
    ("DSL", "What is invoke convention for DSL?", "Allows object() syntax by implementing invoke operator"),
    ("DSL", "What is operator fun invoke()?", "Makes object callable for DSL syntax"),
    ("DSL", "What is the HTML DSL in Kotlin?", "Type-safe HTML builder with nested tags"),
    ("DSL", "What is the Anko DSL (deprecated)?", "Android UI builder using Kotlin DSL"),
    ("DSL", "What is the Ktor DSL?", "Type-safe routing with DSL blocks"),
    ("DSL", "What is the kotlinx.html library?", "HTML DSL for server-side HTML generation"),
    ("Gradle Kotlin", "What is Gradle Kotlin DSL?", "Gradle build scripts in Kotlin instead of Groovy"),
    ("Gradle Kotlin", "What is the plugins block in Kotlin DSL?", "Declares Gradle plugins with apply false"),
    ("Gradle Kotlin", "What is the dependencies block?", "Declares dependencies with configurations"),
    ("Gradle Kotlin", "What is the repositories block?", "Configure dependency repositories"),
    ("Gradle Kotlin", "What is the tasks.register() method?", "Creates custom task with type"),
    ("Gradle Kotlin", "What is the tasks.named() method?", "Configures existing task"),
    ("Gradle Kotlin", "What is the sourceSets block?", "Configures source set directories"),
    ("Gradle Kotlin", "What is the buildscript block?", "Configures build script classpath"),
    ("Gradle Kotlin", "What is the buildSrc directory?", "Pre-compiled scripts and conventions"),
    ("Gradle Kotlin", "What is version catalog?", "Centralized dependency version management"),
    ("Gradle Kotlin", "What is libs.versions.toml?", "Version catalog TOML file"),
    ("Gradle Kotlin", "What is the convention plugin?", "Reusable plugin for sharing build logic"),
    ("Gradle Kotlin", "What is the allprojects block?", "Configures all projects in multi-module build"),
    ("Gradle Kotlin", "What is the subprojects block?", "Configures only subprojects"),
    ("Gradle Kotlin", "What is build.gradle.kts extensions?", "Inline extension functions in build script"),
    ("Gradle Kotlin", "What is the ConfigurableFileTree?", "File tree configuration for source sets"),
    ("Gradle Kotlin", "What is the Gradle Build Scan?", "Remote build diagnostics and performance analysis"),
    ("Gradle Kotlin", "What is the --scan flag?", "Generates a Gradle Build Scan link"),
    ("Gradle Kotlin", "What is the Build Cache?", "Reuses build outputs across machines"),
    ("Gradle Kotlin", "What is Gradle configuration cache?", "Caches task configuration for faster builds"),
], "Senior", "Kotlin")

# === GENERAL: Docker deep, Algorithms, PostgreSQL detail, Architecture patterns ===
gen([
    ("Docker", "What is a Dockerfile multi-stage build?", "Multiple FROM statements for smaller final images"),
    ("Docker", "What is Docker layer caching?", "Caches instruction layers for faster rebuilds"),
    ("Docker", "What is the .dockerignore file?", "Excludes files from Docker build context"),
    ("Docker", "What is docker build --cache-from?", "Use specific image as cache source"),
    ("Docker", "What is docker build --target?", "Stops build at specific stage"),
    ("Docker", "What is the USER instruction in Dockerfile?", "Changes user for security"),
    ("Docker", "What is the HEALTHCHECK instruction?", "Container health check command"),
    ("Docker", "What is the ENTRYPOINT vs CMD?", "ENTRYPOINT: fixed command; CMD: default arguments"),
    ("Docker", "What is the EXPOSE instruction?", "Documents container listening ports"),
    ("Docker", "What is the VOLUME instruction?", "Creates mount point for persistent data"),
    ("Docker", "What is the WORKDIR instruction?", "Sets working directory for subsequent instructions"),
    ("Docker", "What is the ARG instruction?", "Build-time variable with default value"),
    ("Docker", "What is docker compose up?", "Creates and starts containers from compose file"),
    ("Docker", "What is docker compose down?", "Stops and removes containers"),
    ("Docker", "What is docker compose logs?", "Shows container log output"),
    ("Docker", "What is docker compose exec?", "Runs command in running container"),
    ("Docker", "What is docker compose scale?", "Sets number of container replicas"),
    ("Docker", "What is docker compose profiles?", "Selectively start services by profile"),
    ("Docker", "What is docker compose depends_on?", "Service startup order dependency"),
    ("Docker", "What is Docker Compose healthcheck?", "Service readiness dependency condition"),
    ("Docker", "What is Docker networking?", "bridge, host, overlay, macvlan network drivers"),
    ("Docker", "What is docker network create?", "Creates custom Docker network"),
    ("Docker", "What is the bridge network?", "Default network with isolated container communication"),
    ("Docker", "What is the host network?", "Container shares host network stack"),
    ("Docker", "What is docker run --rm?", "Auto-removes container after exit"),
    ("Docker", "What is docker run -it?", "Interactive terminal for container"),
    ("Docker", "What is docker run -d?", "Detached mode running in background"),
    ("Docker", "What is docker run -p?", "Port mapping from host to container"),
    ("Docker", "What is docker run -v?", "Volume mount for persistent data"),
    ("Docker", "What is docker run --env-file?", "Load environment variables from file"),
    ("Docker", "What is docker exec?", "Runs command in running container"),
    ("Docker", "What is docker logs -f?", "Follow log output in real-time"),
    ("Docker", "What is docker ps -a?", "Shows all containers including stopped"),
    ("Docker", "What is docker images?", "Lists downloaded Docker images"),
    ("Docker", "What is docker rmi?", "Removes Docker image"),
    ("Docker", "What is docker prune?", "Removes unused Docker objects"),
    ("Docker", "What is docker system df?", "Shows Docker disk usage"),
    ("Docker", "What is a Docker registry?", "Stores and distributes Docker images"),
    ("Docker", "What is Docker Hub?", "Public Docker image registry"),
    ("Docker", "What is a private registry?", "Self-hosted Docker image storage"),
    ("Architecture", "What is Event-Driven Architecture?", "Components communicate through events asynchronously"),
    ("Architecture", "What is the Event Bus pattern?", "Central channel for event distribution"),
    ("Architecture", "What is CQRS (Command Query Responsibility Segregation)?", "Separates read and write models"),
    ("Architecture", "What is the Event Store?", "Database specialized for event storage"),
    ("Architecture", "What is Event Sourcing?", "Stores state changes as sequence of events"),
    ("Architecture", "What is the Saga pattern?", "Distributed transaction with compensating actions"),
    ("Architecture", "What is Choreography Saga?", "Each service emits events triggering next step"),
    ("Architecture", "What is Orchestration Saga?", "Central coordinator manages each step"),
    ("Architecture", "What is the Strangler Fig pattern?", "Gradually replaces legacy system piece by piece"),
    ("Architecture", "What is the Anti-Corruption Layer?", "Translates between bounded contexts"),
    ("Architecture", "What is the BFF pattern?", "Backend For Frontend per client type"),
    ("Architecture", "What is the Sidecar pattern?", "Auxiliary service deployed alongside main service"),
    ("Architecture", "What is the Ambassador pattern?", "Sidecar handling cross-cutting network concerns"),
    ("Architecture", "What is the Adapter pattern in microservices?", "Converts interface for legacy integration"),
    ("Architecture", "What is the Repository pattern?", "Mediates between domain and data mapping layers"),
    ("Architecture", "What is the Unit of Work pattern?", "Tracks changes for single transaction commit"),
    ("Architecture", "What is the Specification pattern?", "Encapsulates business rules for querying"),
    ("Architecture", "What is the Domain Event pattern?", "Captures significant domain occurrences"),
    ("Architecture", "What is the Aggregate pattern (DDD)?", "Cluster of domain objects treated as unit"),
    ("Architecture", "What is the Value Object pattern?", "Immutable object defined by attributes"),
    ("Algorithms", "What is the Two-Pointer technique?", "Two pointers for efficient array traversal"),
    ("Algorithms", "What is the Sliding Window technique?", "Subarray/substring problems with window expansion"),
    ("Algorithms", "What is the Fast and Slow Pointer technique?", "Detect cycles in linked lists"),
    ("Algorithms", "What is the Merge Intervals pattern?", "Merge overlapping intervals in sorted order"),
    ("Algorithms", "What is the Cyclic Sort pattern?", "Sort array containing numbers in given range"),
    ("Algorithms", "What is the Topological Sort pattern?", "Linear ordering of directed acyclic graph"),
    ("Algorithms", "What is the Union-Find (Disjoint Set) data structure?", "Manages connected components efficiently"),
    ("Algorithms", "What is the Trie data structure?", "Tree for efficient string prefix operations"),
    ("Algorithms", "What is the Segment Tree?", "Tree for range queries with O(log N) update"),
    ("Algorithms", "What is the Fenwick Tree (Binary Indexed Tree)?", "Tree for prefix sums with O(log N) operations"),
    ("Algorithms", "What is the Bloom Filter?", "Space-efficient probabilistic set membership test"),
    ("Algorithms", "What is the LRU Cache?", "Evicts least recently used item when full"),
    ("Algorithms", "What is the Quicksort algorithm?", "Divide-and-conquer sort with O(N log N) average"),
    ("Algorithms", "What is the Mergesort algorithm?", "Stable O(N log N) sort with O(N) extra space"),
    ("Algorithms", "What is Binary Search?", "O(log N) search on sorted array by halving range"),
    ("Algorithms", "What is Depth-First Search (DFS)?", "Graph traversal exploring as far as possible first"),
    ("Algorithms", "What is Breadth-First Search (BFS)?", "Graph traversal exploring neighbors level by level"),
    ("Algorithms", "What is the Dijkstra algorithm?", "Shortest path in weighted graph with non-negative weights"),
    ("Algorithms", "What is the Bellman-Ford algorithm?", "Shortest path supporting negative edge weights"),
    ("Algorithms", "What is the Floyd-Warshall algorithm?", "All-pairs shortest paths with O(V^3) complexity"),
    ("PostgreSQL", "What is the pg_stat_statements extension?", "Track query execution statistics"),
    ("PostgreSQL", "What is the pg_stat_activity view?", "Current backend activity and queries"),
    ("PostgreSQL", "What is the pg_stat_all_tables view?", "Table-level access statistics"),
    ("PostgreSQL", "What is the pg_stat_all_indexes view?", "Index usage statistics"),
    ("PostgreSQL", "What is the pg_buffercache extension?", "Inspect shared buffer cache contents"),
    ("PostgreSQL", "What is the pg_prewarm extension?", "Preload table data into cache"),
    ("PostgreSQL", "What is the pg_stat_statements normalization?", "Parameterized query fingerprinting"),
    ("PostgreSQL", "What is the auto_explain module?", "Automatic query plan logging"),
    ("PostgreSQL", "What is the pg_hint_plan extension?", "Force specific query plan with hints"),
    ("PostgreSQL", "What is the pg_partman extension?", "Automated table partitioning management"),
    ("PostgreSQL", "What is the postgres_fdw extension?", "Foreign data wrapper for remote PostgreSQL"),
    ("PostgreSQL", "What is the dblink extension?", "Cross-database queries from within PostgreSQL"),
    ("PostgreSQL", "What is the file_fdw extension?", "Read files as foreign tables"),
    ("PostgreSQL", "What is the pageinspect extension?", "Low-level inspection of database pages"),
    ("PostgreSQL", "What is the pgrowlocks extension?", "Show row-level lock information"),
    ("PostgreSQL", "What is the pgstattuple extension?", "Tuple-level statistics for tables"),
    ("PostgreSQL", "What is the pg_visibility extension?", "Visibility map information for tables"),
    ("PostgreSQL", "What is the amcheck extension?", "B-tree index corruption checking"),
    ("PostgreSQL", "What is the pg_walinspect extension?", "WAL (Write-Ahead Log) inspection"),
    ("PostgreSQL", "What is the pg_surgery extension?", "Low-level table record manipulation (careful)"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 17 added {len(new)} questions.")