"""Batch 18: Final ~500 questions to reach ~9000 total"""
import json
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    opts = [a, 'Common misconception', 'Alternative approach', 'I don\'t know']
    obj = {"category": cat, "question": q, "short_answer": a, "options": opts, "difficulty": diff, "language": lang}
    json.dumps(obj, ensure_ascii=False)
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(opts[0])}', '{esc(opts[1])}', '{esc(opts[2])}', '{esc(opts[3])}'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# Java: EJB, RMI, JAXB
gen([
    ("EJB", "What is Enterprise JavaBeans (EJB)?", "Server-side component for distributed business logic"),
    ("EJB", "What is Session Bean?", "EJB that implements business logic per client session"),
    ("EJB", "What is Stateful Session Bean?", "Maintains conversational state across method calls"),
    ("EJB", "What is Stateless Session Bean?", "No conversational state, pooled by container"),
    ("EJB", "What is Singleton Session Bean?", "Single instance shared across all clients"),
    ("EJB", "What is Message-Driven Bean?", "EJB that processes JMS messages asynchronously"),
    ("EJB", "What is the @Stateless annotation?", "Marks class as stateless session bean"),
    ("EJB", "What is the @Stateful annotation?", "Marks class as stateful session bean"),
    ("EJB", "What is the @MessageDriven annotation?", "Marks class as message-driven bean"),
    ("EJB", "What is the EJB container?", "Runtime environment for EJB lifecycle management"),
    ("EJB", "What is JNDI lookup for EJB?", "Locates EJB via Java Naming and Directory Interface"),
    ("EJB", "What is the @EJB annotation?", "Injects EJB reference into another component"),
    ("EJB", "What is the @Remote annotation?", "Marks EJB interface for remote access"),
    ("EJB", "What is the @Local annotation?", "Marks EJB interface for local access"),
    ("EJB", "What is EJB transaction management?", "Container-managed or bean-managed transactions"),
    ("EJB", "What is CMT (Container-Managed Transactions)?", "Container handles transaction boundaries declaratively"),
    ("EJB", "What is BMT (Bean-Managed Transactions)?", "Bean manages transactions via UserTransaction"),
    ("EJB", "What is EJB security?", "Declarative role-based access control via annotations"),
    ("EJB", "What is the @RolesAllowed annotation in EJB?", "Specifies allowed roles for method access"),
    ("EJB", "What is the @RunAs annotation?", "Specifies security identity for EJB execution"),
    ("RMI", "What is Java RMI?", "Remote Method Invocation for distributed Java objects"),
    ("RMI", "What is a Remote interface?", "Interface extending java.rmi.Remote for remote objects"),
    ("RMI", "What is the RemoteException?", "Exception thrown during remote method invocation"),
    ("RMI", "What is UnicastRemoteObject?", "Base class for creating remote server objects"),
    ("RMI", "What is the RMI Registry?", "Naming service for locating remote objects"),
    ("RMI", "What is LocateRegistry.getRegistry()?", "Gets reference to RMI registry on host"),
    ("RMI", "What is Naming.rebind()?", "Binds remote object to name in registry"),
    ("RMI", "What is Naming.lookup()?", "Finds remote object by name in registry"),
    ("RMI", "What is RMI stub?", "Client-side proxy for remote object communication"),
    ("RMI", "What is RMI skeleton?", "Server-side dispatcher (deprecated in Java 8)"),
    ("JAXB", "What is JAXB?", "XML binding for Java objects to XML mapping"),
    ("JAXB", "What is @XmlRootElement?", "Maps class to XML root element"),
    ("JAXB", "What is @XmlElement?", "Maps field to XML element"),
    ("JAXB", "What is @XmlAttribute?", "Maps field to XML attribute"),
    ("JAXB", "What is @XmlTransient?", "Excludes field from XML binding"),
    ("JAXB", "What is JAXBContext.newInstance()?", "Creates JAXB context for class binding"),
    ("JAXB", "What is Marshaller?", "Converts Java objects to XML"),
    ("JAXB", "What is Unmarshaller?", "Converts XML to Java objects"),
    ("JAXB", "What is @XmlAccessorType?", "Configures field access type for XML binding"),
    ("JAXB", "What is @XmlSchema annotation?", "Configures namespace for package-level XML"),
], "Senior", "Java")

# Python: SciPy, NetworkX, NLTK, SymPy
gen([
    ("SciPy", "What is scipy.optimize.minimize()?", "General-purpose optimization to minimize scalar function"),
    ("SciPy", "What is scipy.optimize.curve_fit()?", "Non-linear least squares curve fitting"),
    ("SciPy", "What is scipy.integrate.quad()?", "Numerical integration of 1D function"),
    ("SciPy", "What is scipy.integrate.solve_ivp()?", "Initial value problem for ODE systems"),
    ("SciPy", "What is scipy.interpolate.interp1d()?", "1D interpolation with various methods"),
    ("SciPy", "What is scipy.signal module?", "Signal processing: filtering, convolution, spectral analysis"),
    ("SciPy", "What is scipy.ndimage module?", "Multi-dimensional image processing operations"),
    ("SciPy", "What is scipy.sparse module?", "Sparse matrix representations and algorithms"),
    ("SciPy", "What is scipy.sparse.csr_matrix?", "Compressed Sparse Row matrix format"),
    ("SciPy", "What is scipy.linalg.solve()?", "Solve linear system of equations"),
    ("SciPy", "What is scipy.linalg.eig()?", "Compute eigenvalues and eigenvectors"),
    ("SciPy", "What is scipy.stats.norm?", "Normal (Gaussian) distribution with PDF, CDF, PPF"),
    ("SciPy", "What is scipy.stats.ttest_ind()?", "Independent t-test for two sample means"),
    ("SciPy", "What is scipy.stats.pearsonr()?", "Pearson correlation coefficient with p-value"),
    ("SciPy", "What is scipy.cluster.hierarchy?", "Hierarchical clustering with dendrogram visualization"),
    ("NetworkX", "What is NetworkX?", "Graph analysis library for complex networks"),
    ("NetworkX", "What is nx.Graph()?", "Undirected graph with nodes and edges"),
    ("NetworkX", "What is nx.DiGraph()?", "Directed graph with directed edges"),
    ("NetworkX", "What is nx.add_node() / nx.add_edge()?", "Add nodes and edges to graph"),
    ("NetworkX", "What is nx.shortest_path()?", "Finds shortest path between nodes"),
    ("NetworkX", "What is nx.pagerank()?", "PageRank algorithm for node importance"),
    ("NetworkX", "What is nx.connected_components()?", "Finds connected components in undirected graph"),
    ("NetworkX", "What is nx.degree_centrality()?", "Node centrality based on degree"),
    ("NetworkX", "What is nx.betweenness_centrality()?", "Node centrality based on shortest path betweenness"),
    ("NetworkX", "What is nx.draw()?", "Matplotlib-based graph visualization"),
    ("NLTK", "What is NLTK?", "Natural Language Toolkit for text processing"),
    ("NLTK", "What is nltk.tokenize.word_tokenize()?", "Splits text into word tokens"),
    ("NLTK", "What is nltk.tokenize.sent_tokenize()?", "Splits text into sentence tokens"),
    ("NLTK", "What is nltk.pos_tag()?", "Part-of-speech tagging for words"),
    ("NLTK", "What is nltk.stem.PorterStemmer()?", "Porter stemming algorithm for word normalization"),
    ("NLTK", "What is nltk.stem.WordNetLemmatizer()?", "Lemmatization with WordNet dictionary"),
    ("NLTK", "What is nltk.FreqDist()?", "Frequency distribution for counting items"),
    ("NLTK", "What is nltk.corpus.stopwords?", "Common stop words for filtering"),
    ("NLTK", "What is nltk.ngrams()?", "Generates N-gram sequences from tokens"),
    ("NLTK", "What is nltk.ne_chunk()?", "Named entity recognition chunker"),
    ("SymPy", "What is SymPy?", "Symbolic mathematics library for Python"),
    ("SymPy", "What is sympy.Symbol()?", "Symbolic variable for algebraic expressions"),
    ("SymPy", "What is sympy.diff()?", "Symbolic differentiation of expression"),
    ("SymPy", "What is sympy.integrate()?", "Symbolic integration of expression"),
    ("SymPy", "What is sympy.solve()?", "Solves algebraic equations symbolically"),
    ("SymPy", "What is sympy.lambdify()?", "Converts symbolic expression to numeric function"),
    ("SymPy", "What is sympy.simplify()?", "Simplifies mathematical expression"),
    ("SymPy", "What is sympy.Matrix()?", "Symbolic matrix for linear algebra"),
    ("SymPy", "What is sympy.dsolve()?", "Solves ordinary differential equations symbolically"),
    ("SymPy", "What is sympy.series()?", "Series expansion of function"),
], "Middle", "Python")

# TypeScript: Remix, Astro, Qwik, Solid.js
gen([
    ("Remix", "What is Remix?", "Full-stack web framework built on Web Fetch API"),
    ("Remix", "What is Remix loader?", "Server-side data loading for routes"),
    ("Remix", "What is Remix action?", "Server-side form submission handler"),
    ("Remix", "What is useLoaderData()?", "Accesses data from route loader"),
    ("Remix", "What is Remix nested routes?", "Route hierarchy with Outlet nesting"),
    ("Remix", "What is <Outlet /> in Remix?", "Renders child route content"),
    ("Remix", "What is <Link /> in Remix?", "Client-side navigation component"),
    ("Remix", "What is <Form /> in Remix?", "Progressive enhancement form component"),
    ("Remix", "What is useFetcher() in Remix?", "Imperative data mutation without navigation"),
    ("Remix", "What is Remix error boundaries?", "Route-level error handling with ErrorBoundary"),
    ("Astro", "What is Astro?", "Content-driven web framework with partial hydration"),
    ("Astro", "What is Astro island?", "Interactive component in mostly static page"),
    ("Astro", "What is the Astro frontmatter?", "--- delimited script section at top of .astro file"),
    ("Astro", "What is Astro.props?", "Component props passed from parent"),
    ("Astro", "What is client:load directive?", "Hydrates component immediately on page load"),
    ("Astro", "What is client:visible directive?", "Hydrates component when visible in viewport"),
    ("Astro", "What is client:media directive?", "Hydrates component at specific media query"),
    ("Astro", "What is client:only directive?", "Hydrates component on client only (no SSR)"),
    ("Astro", "What is the Astro Content Collections?", "Type-safe content management with schema"),
    ("Astro", "What is Astro Image optimization?", "Automatic image optimization and responsive images"),
    ("Qwik", "What is Qwik?", "Framework with resumable hydration and fine-grained lazy loading"),
    ("Qwik", "What is Qwik resumability?", "Serializes app state in HTML for instant resume"),
    ("Qwik", "What is $ (dollar) suffix convention?", "Marks code for lazy loading and splitting"),
    ("Qwik", "What is component$() in Qwik?", "Lazy-loadable component definition"),
    ("Qwik", "What is useSignal() in Qwik?", "Reactive state primitive"),
    ("Qwik", "What is $() in Qwik?", "Creates lazy-loadable code boundary"),
    ("Qwik", "What is Qwik City?", "Meta-framework like Next.js for Qwik"),
    ("Qwik", "What is Qwik route loader?", "Server-side data loading for route"),
    ("Qwik", "What is Qwik optimizer?", "Bundle splitting at the function level"),
    ("Qwik", "What is Qwik prefetching?", "Prefetches lazy chunks on user interaction intent"),
    ("Solid.js", "What is Solid.js?", "Reactive UI library without virtual DOM"),
    ("Solid.js", "What is createSignal() in Solid?", "Reactive state with getter and setter"),
    ("Solid.js", "What is createEffect() in Solid?", "Reactive side effect on signal changes"),
    ("Solid.js", "What is createMemo() in Solid?", "Derived reactive value with caching"),
    ("Solid.js", "What is createResource() in Solid?", "Async data loading with signals"),
    ("Solid.js", "What is Solid.js JSX?", "JSX with actual DOM elements (no vDOM diffing)"),
    ("Solid.js", "What is the For component?", "Reactive list iteration in JSX"),
    ("Solid.js", "What is the Show component?", "Conditional rendering component"),
    ("Solid.js", "What is the Switch/Match components?", "Multiple conditional branches in Solid"),
    ("Solid.js", "What is solid-start?", "Meta-framework for Solid.js with SSR and routing"),
], "Middle", "TypeScript")

# Go: chi, gorilla/mux, negroni, templ
gen([
    ("Web Frameworks", "What is gorilla/mux?", "URL router and dispatcher for Go"),
    ("Web Frameworks", "What is mux.NewRouter()?", "Creates new gorilla/mux router"),
    ("Web Frameworks", "What is mux.Vars()?", "Extracts path variables from request"),
    ("Web Frameworks", "What is mux.PathPrefix()?", "Matches path prefix with subrouter"),
    ("Web Frameworks", "What is mux.CORSMethodMiddleware()?", "Enables CORS method handling"),
    ("Web Frameworks", "What is chi router?", "Lightweight Go HTTP router with middleware"),
    ("Web Frameworks", "What is chi.NewRouter()?", "Creates new chi router instance"),
    ("Web Frameworks", "What is chi.URLParam()?", "Extracts URL parameter from context"),
    ("Web Frameworks", "What is chi middleware?", "Built-in: logger, recover, compress, timeout, cors"),
    ("Web Frameworks", "What is chi.RouteContext?", "Context key for accessing route information"),
    ("Web Frameworks", "What is chi.Router.Group()?", "Route grouping with shared middleware"),
    ("Web Frameworks", "What is chi.Router.Route()?", "Subrouter with path prefix"),
    ("Web Frameworks", "What is negroni?", "HTTP middleware library for Go"),
    ("Web Frameworks", "What is negroni.Classic()?", "Standard middleware: Logging, Recovery, Static"),
    ("Web Frameworks", "What is negroni.Wrap()?", "Wraps http.Handler as negroni.Handler"),
    ("Web Frameworks", "What is negroni.HandlerFunc?", "Middleware function signature for negroni"),
    ("Web Frameworks", "What is templ?", "HTML templating with Go syntax and type safety"),
    ("Web Frameworks", "What is templ.Component?", "Renders HTML via Render method"),
    ("Web Frameworks", "What is templ component composition?", "Nesting components with @component syntax"),
    ("Web Frameworks", "What is templ generation?", "CLI that generates Go code from .templ files"),
    ("Web Frameworks", "What is htmx?", "Access AJAX and WebSocket in HTML attributes"),
    ("Web Frameworks", "What is hx-get/hx-post attributes?", "AJAX request on element interaction"),
    ("Web Frameworks", "What is hx-trigger attribute?", "Specifies event triggering the request"),
    ("Web Frameworks", "What is hx-target attribute?", "CSS selector for response insertion target"),
    ("Web Frameworks", "What is hx-swap attribute?", "Content swapping strategy (innerHTML, outerHTML)"),
    ("Web Frameworks", "What is hx-push-url attribute?", "Updates browser URL on AJAX response"),
    ("Web Frameworks", "What is htmx history support?", "Browser back/forward navigation support"),
    ("Web Frameworks", "What is htmx WebSocket support?", "Real-time updates via hx-ws attribute"),
    ("Web Frameworks", "What is htmx server-sent events?", "SSE integration with hx-trigger and EventSource"),
    ("Web Frameworks", "What is htmx boosting?", "Enhancing links and forms with AJAX"),
], "Middle", "Go")

# Rust: Tauri, egui, bevy
gen([
    ("GUI", "What is Tauri?", "Desktop app framework with web frontend and Rust backend"),
    ("GUI", "What is tauri::Builder?", "Application builder for Tauri setup"),
    ("GUI", "What is Tauri command?", "Rust function exposed to frontend via #[tauri::command]"),
    ("GUI", "What is the Tauri invoke()?", "Frontend calls Rust command via invoke()"),
    ("GUI", "What is Tauri events?", "Frontend-backend communication via event system"),
    ("GUI", "What is Tauri window management?", "Create and manage windows from Rust"),
    ("GUI", "What is Tauri file system access?", "Secure file system access with allowlist"),
    ("GUI", "What is Tauri shell access?", "Running shell commands with scope restrictions"),
    ("GUI", "What is Tauri updater?", "Built-in app update mechanism"),
    ("GUI", "What is Tauri bundler?", "Creates platform installers (DMG, MSI, AppImage)"),
    ("GUI", "What is egui?", "Immediate mode GUI library for Rust"),
    ("GUI", "What is egui::Context?", "UI context for adding panels and windows"),
    ("GUI", "What is egui::Window?", "Floating window in egui interface"),
    ("GUI", "What is egui::SidePanel?", "Fixed panel on side of screen"),
    ("GUI", "What is egui::TopBottomPanel?", "Panel at top of bottom of screen"),
    ("GUI", "What is egui::CentralPanel?", "Main content area panel"),
    ("GUI", "What is egui Label/Button/TextEdit?", "Standard UI widgets"),
    ("GUI", "What is egui image rendering?", "Displays images from texture handles"),
    ("GUI", "What is eframe?", "Framework for native egui applications"),
    ("GUI", "What is egui-winit?", "egui backend for winit window management"),
    ("GUI", "What is egui Web support?", "egui runs in browser via WebGL canvas"),
    ("GUI", "What is egui docking?", "Undocked, resizable, draggable window layout"),
    ("GUI", "What is bevy?", "Entity Component System game engine for Rust"),
    ("GUI", "What is Bevy ECS?", "Component, Entity, System architecture"),
    ("GUI", "What is Bevy Commands?", "Spawn/despawn entities, insert/remove components"),
    ("GUI", "What is Bevy Query?", "Queries components from entities by type filter"),
    ("GUI", "What is Bevy App builder?", "Configures plugins, systems, resources, events"),
    ("GUI", "What is Bevy plugin?", "Modular extension adding systems and resources"),
    ("GUI", "What is Bevy Resource?", "Global singleton data shared across systems"),
    ("GUI", "What is Bevy Event system?", "Inter-system communication with events"),
], "Senior", "Rust")

# React: Remix deep, Gatsby, Docusaurus, Framer Motion deep
gen([
    ("Remix", "What is <Scripts /> in Remix?", "Loads client-side JavaScript bundle"),
    ("Remix", "What is <Links /> in Remix?", "Renders link tags for stylesheets"),
    ("Remix", "What is <Meta /> in Remix?", "Renders meta tags for SEO"),
    ("Remix", "What is useMatches() in Remix?", "Access all matched route data"),
    ("Remix", "What is shouldRevalidate in Remix?", "Control when route revalidates"),
    ("Remix", "What is Remix sessions?", "Cookie-based session storage"),
    ("Remix", "What is createCookieSessionStorage()?", "Cookie-based session in Remix"),
    ("Remix", "What is Remix resource routes?", "Routes returning non-HTML responses (API)"),
    ("Remix", "What is Remix route modules?", "Route file conventions with loader, action, component"),
    ("Remix", "What is Remix flat routes?", "Flat file routing instead of nested folders"),
    ("Gatsby", "What is Gatsby?", "React-based static site generator with GraphQL"),
    ("Gatsby", "What is Gatsby Link?", "Client-side navigation component"),
    ("Gatsby", "What is Gatsby GraphQL layer?", "Data layer compiling GraphQL queries at build"),
    ("Gatsby", "What is gatsby-source-filesystem?", "Source plugin for local file system"),
    ("Gatsby", "What is gatsby-transformer-sharp?", "Image transformation plugin"),
    ("Gatsby", "What is gatsby-plugin-image?", "Optimized responsive image component"),
    ("Gatsby", "What is gatsby-node.js?", "Custom APIs for creating pages dynamically"),
    ("Gatsby", "What is Gatsby SSR/DSG/SSG?", "Server-side, Deferred Static, Static Generation"),
    ("Gatsby", "What is Gatsby Cloud?", "Cloud platform for Gatsby builds and hosting"),
    ("Gatsby", "What is Gatsby Content Mesh?", "Unified content API across sources"),
    ("Docusaurus", "What is Docusaurus?", "Documentation site generator by Meta"),
    ("Docusaurus", "What is Docusaurus sidebar?", "Auto-generated navigation from file structure"),
    ("Docusaurus", "What is Docusaurus docs plugin?", "Documentation with versioning and i18n"),
    ("Docusaurus", "What is Docusaurus blog plugin?", "Blog with tags, RSS, and pagination"),
    ("Docusaurus", "What is docusaurus.config.js?", "Site configuration with theme and plugins"),
    ("Docusaurus", "What is Docusaurus MDX?", "MDX (Markdown + JSX) component support"),
    ("Docusaurus", "What is Docusaurus swizzling?", "Theme component customization"),
    ("Docusaurus", "What is Docusaurus search?", "Algolia DocSearch integration"),
    ("Docusaurus", "What is Docusaurus versioning?", "Multi-version documentation management"),
    ("Docusaurus", "What is Docusaurus i18n?", "Multi-language documentation support"),
], "Senior", "React")

# Kotlin: Arrow, MockK, Koin
gen([
    ("Arrow", "What is Arrow (functional library)?", "Functional companion for Kotlin with monads and optics"),
    ("Arrow", "What is Either in Arrow?", "Right-biased type for computations with two outcomes"),
    ("Arrow", "What is Option in Arrow?", "Nullable wrapper with functional combinators"),
    ("Arrow", "What is Validated in Arrow?", "Accumulates errors instead of failing fast"),
    ("Arrow", "What is Try in Arrow?", "Wrapper for computation that may throw"),
    ("Arrow", "What is NonEmptyList in Arrow?", "List guaranteed to have at least one element"),
    ("Arrow", "What is IO in Arrow?", "Lazy, suspendable computation for side effects"),
    ("Arrow", "What is Arrow Fx?", "Functional effect system for Kotlin"),
    ("Arrow", "What is the map() function on Either?", "Transforms right value, left passes through"),
    ("Arrow", "What is flatMap() on Either?", "Chains computations that return Either"),
    ("Arrow", "What is fold() on Either?", "Handles both left and right cases"),
    ("Arrow", "What is Arrow Optics?", "Lens, Prism, Optional for immutable data access"),
    ("Arrow", "What is @optics annotation?", "Generates optics for data classes"),
    ("Arrow", "What is Arrow Meta?", "Compiler plugin for functional programming"),
    ("Arrow", "What is the raise DSL in Arrow?", "Typed errors with stack-safe computations"),
    ("Koin", "What is Koin?", "Lightweight DI framework without reflection"),
    ("Koin", "What is koin { modules { } }?", "DSL for declaring dependency modules"),
    ("Koin", "What is single { } in Koin?", "Singleton definition"),
    ("Koin", "What is factory { } in Koin?", "New instance on every injection"),
    ("Koin", "What is scoped { } in Koin?", "Instance per scope lifecycle"),
    ("Koin", "What is get() in Koin?", "Retrieves dependency by type"),
    ("Koin", "What is by inject() in Koin?", "Lazy delegate for property injection"),
    ("Koin", "What is Koin Android?", "Android integration with ViewModel injection"),
    ("Koin", "What is koinViewModel()?", "ViewModel injection in Koin Android"),
    ("Koin", "What is KoinTest?", "Testing utilities for Koin containers"),
    ("MockK", "What is MockK?", "Mocking library for Kotlin with coroutine support"),
    ("MockK", "What is mockk<T>()?", "Creates mock for type T"),
    ("MockK", "What is every { } returns { }?", "Sets up expectation for mock call"),
    ("MockK", "What is coEvery { } coReturns { }?", "Coroutine-aware mock expectation"),
    ("MockK", "What is verify { } in MockK?", "Verifies mock was called with expected args"),
    ("MockK", "What is confirmVerified()?", "Verifies all recorded calls were verified"),
    ("MockK", "What is relaxUnitFun = true?", "Relaxes unit function responses"),
    ("MockK", "What is spy in MockK?", "Partial mock wrapping real object"),
    ("MockK", "What is slot<T>() in MockK?", "Captures argument values for assertion"),
    ("MockK", "What is mockkStatic()?", "Mocks static/companion object methods"),
], "Senior", "Kotlin")

# General: Docker Compose advanced, K8s troubleshooting, Agile, PromQL, Code Review
gen([
    ("Docker", "What is Docker Compose watch mode?", "Auto-update containers on file changes"),
    ("Docker", "What is Docker Compose build?", "Builds or rebuilds services"),
    ("Docker", "What is Docker Compose secrets?", "Mounts secrets from orchestration platform"),
    ("Docker", "What is Docker Compose configs?", "Configuration files for swarm services"),
    ("Docker", "What is docker compose config?", "Validates and views compose file"),
    ("Docker", "What is docker compose top?", "Shows running processes per service"),
    ("Docker", "What is docker compose images?", "Lists images used by services"),
    ("Docker", "What is docker compose ps?", "Lists containers for services"),
    ("Docker", "What is docker compose events?", "Streaming events from containers"),
    ("Docker", "What is docker compose port?", "Prints public port for service"),
    ("K8s", "What is kubectl get pods?", "Lists all pods in namespace"),
    ("K8s", "What is kubectl describe pod?", "Detailed pod information"),
    ("K8s", "What is kubectl logs -f?", "Stream pod logs"),
    ("K8s", "What is kubectl exec -it?", "Interactive shell in container"),
    ("K8s", "What is kubectl port-forward?", "Forward local port to pod"),
    ("K8s", "What is kubectl apply -f?", "Creates or updates resources from file"),
    ("K8s", "What is kubectl delete pod?", "Deletes pod (recreated if part of Deployment)"),
    ("K8s", "What is kubectl rollout status?", "Check deployment rollout progress"),
    ("K8s", "What is kubectl rollout history?", "Shows revision history of rollout"),
    ("K8s", "What is kubectl rollout undo?", "Rolls back to previous revision"),
    ("K8s", "What is kubectl scale deployment?", "Changes replica count for deployment"),
    ("K8s", "What is kubectl autoscale?", "Creates autoscaler for deployment"),
    ("K8s", "What is kubectl get events?", "Shows cluster events for debugging"),
    ("K8s", "What is kubectl top pod/node?", "Shows resource usage metrics"),
    ("K8s", "What is kubectl drain node?", "Safely evicts pods from node for maintenance"),
    ("K8s", "What is kubectl cordon node?", "Marks node as unschedulable"),
    ("K8s", "What is kubectl taint node?", "Adds taint to repel pods"),
    ("K8s", "What is kubectl get namespaces?", "Lists namespaces in cluster"),
    ("K8s", "What is kubectl config use-context?", "Switches kubectl cluster context"),
    ("K8s", "What is k9s tool?", "Terminal UI for Kubernetes management"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 18 added {len(new)} questions.")