"""Batch 16: ~1300 fresh questions in completely new topic areas"""
import json
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    opts = [a, 'Common misconception', 'Alternative approach', 'I don\'t know']
    obj = {"category": cat, "question": q, "short_answer": a, "options": opts, "difficulty": diff, "language": lang}
    json.dumps(obj, ensure_ascii=False)
    assert all(isinstance(o, str) and len(o) > 0 for o in opts), f"Options validation failed for: {q[:50]}"
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(opts[0])}', '{esc(opts[1])}', '{esc(opts[2])}', '{esc(opts[3])}'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# === JAVA FRESH: JPMS, JavaFX, CDI, JMS, JMX, Web Services ===
gen([
    ("JPMS", "What is the Java Platform Module System (JPMS)?", "Project Jigsaw: modularizes JDK with module-info.java descriptors"),
    ("JPMS", "What is module-info.java?", "Module descriptor declaring name, exports, requires, opens, provides"),
    ("JPMS", "What is the module keyword?", "Declares a named module in module-info.java"),
    ("JPMS", "What is the exports directive?", "Makes package accessible to other modules"),
    ("JPMS", "What is the requires directive?", "Declares dependency on another module"),
    ("JPMS", "What is the requires transitive directive?", "Propagates module dependency to consumers"),
    ("JPMS", "What is the opens directive?", "Allows reflective access to package at runtime"),
    ("JPMS", "What is the provides...with directive?", "Declares service provider for service loader"),
    ("JPMS", "What is the uses directive?", "Declares service interface for service loader"),
    ("JPMS", "What is the ServiceLoader class?", "Loads service implementations via service provider interface"),
    ("JPMS", "What is the unnamed module?", "Classpath code in unnamed module for backward compatibility"),
    ("JPMS", "What is the automatic module?", "JAR without module-info on module path becomes automatic module"),
    ("JPMS", "What is the Module API?", "java.lang.Module for programmatic module access"),
    ("JPMS", "What is the --module-path flag?", "Specifies module search path instead of classpath"),
    ("JPMS", "What is the --add-exports flag?", "Exports package from module at runtime for reflection"),
    ("JPMS", "What is the --add-opens flag?", "Opens package for deep reflection at runtime"),
    ("JPMS", "What is the --add-reads flag?", "Adds module readability edge at runtime"),
    ("JPMS", "What is the jlink tool?", "Creates custom runtime image with only needed modules"),
    ("JPMS", "What is the jdeps tool?", "Analyzes JAR dependencies and suggests module descriptors"),
    ("JPMS", "What is the jmod tool?", "Creates JMOD files for modular JARs with native code"),
    ("JavaFX", "What is JavaFX?", "Rich client application platform with hardware-accelerated UI"),
    ("JavaFX", "What is the Stage in JavaFX?", "Top-level window container for JavaFX application"),
    ("JavaFX", "What is the Scene in JavaFX?", "Container for the UI graph in a stage"),
    ("JavaFX", "What is the Node in JavaFX?", "Base class for all UI elements in the scene graph"),
    ("JavaFX", "What is the Scene Graph?", "Tree structure of visual nodes for rendering"),
    ("JavaFX", "What is the FXML file?", "XML-based markup for defining JavaFX UI layout"),
    ("JavaFX", "What is the @FXML annotation?", "Marks fields and methods accessible from FXML"),
    ("JavaFX", "What is the FXMLLoader class?", "Loads FXML files and creates object hierarchy"),
    ("JavaFX", "What is the Controller in JavaFX?", "Class with @FXML fields binding FXML elements to code"),
    ("JavaFX", "What is the Property pattern in JavaFX?", "Observable properties for data binding and listeners"),
    ("JavaFX", "What is the Observable pattern?", "ObservableValue with ChangeListener for change notification"),
    ("JavaFX", "What is the Binding API?", "Creates computed values that auto-update on dependency changes"),
    ("JavaFX", "What is the JavaFX CSS styling?", "Styles UI with CSS selectors and properties"),
    ("JavaFX", "What is the JavaFX charts API?", "Built-in chart types: Line, Bar, Pie, Area, Scatter"),
    ("JavaFX", "What is the JavaFX media support?", "MediaPlayer for audio and video playback"),
    ("JavaFX", "What is the JavaFX WebView?", "Embedded Chromium-based web browser component"),
    ("JavaFX", "What is the JavaFX Animation API?", "Timeline, Transition, KeyFrame for animations"),
    ("JavaFX", "What is the JavaFX Canvas API?", "Immediate mode rendering with GraphicsContext"),
    ("JavaFX", "What is the JavaFX concurrency?", "Platform.runLater and Task/Service for background work"),
    ("JavaFX", "What is the JavaFX Print API?", "PrinterJob and PageLayout for printing support"),
    ("CDI", "What is CDI (Contexts and Dependency Injection)?", "Jakarta EE standard DI with bean discovery and scopes"),
    ("CDI", "What is the @Inject annotation?", "Injects CDI beans by type"),
    ("CDI", "What is the @Named annotation?", "Qualifies bean with name for EL access"),
    ("CDI", "What is the @ApplicationScoped annotation?", "Single bean instance per application lifetime"),
    ("CDI", "What is the @RequestScoped annotation?", "Bean instance per HTTP request"),
    ("CDI", "What is the @SessionScoped annotation?", "Bean instance per HTTP session"),
    ("CDI", "What is the @ConversationScoped annotation?", "Bean instance spanning multiple requests with begin/end"),
    ("CDI", "What is the @Dependent pseudo-scope?", "Bean instance tied to injecting bean lifecycle"),
    ("CDI", "What is the @Singleton annotation?", "Single instance like traditional singleton"),
    ("CDI", "What is the @Produces annotation?", "Factory method or field that creates beans"),
    ("CDI", "What is the @Disposes annotation?", "Cleanup method for producer-created beans"),
    ("CDI", "What is the @Qualifier annotation?", "Custom annotation for disambiguating bean types"),
    ("CDI", "What is the @Alternative annotation?", "Marked bean replaces default when activated in beans.xml"),
    ("CDI", "What is the @Specializes annotation?", "Replaces parent bean completely"),
    ("CDI", "What is the @Interceptors annotation?", "Declares interceptor binding for cross-cutting logic"),
    ("CDI", "What is the @Decorator annotation?", "Delegates to decorated bean with ability to override methods"),
    ("CDI", "What is the @Observes annotation?", "Event observer method for CDI event notifications"),
    ("CDI", "What is the Event interface in CDI?", "Fires events synchronously or asynchronously"),
    ("CDI", "What is the beans.xml file?", "CDI configuration for alternatives, interceptors, decorators"),
    ("CDI", "What is bean discovery mode?", "annotated (default), all (scan entire archive), none"),
    ("Web Services", "What is JAX-WS?", "Java API for XML Web Services with SOAP protocol"),
    ("Web Services", "What is the @WebService annotation?", "Marks class or interface as web service endpoint"),
    ("Web Services", "What is the @WebMethod annotation?", "Exposes method as web service operation"),
    ("Web Services", "What is the SOAP protocol?", "XML-based messaging protocol for web services"),
    ("Web Services", "What is WSDL?", "Web Services Description Language for service contract"),
    ("Web Services", "What is the wsimport tool?", "Generates client stubs from WSDL"),
    ("Web Services", "What is JAX-RS?", "Java API for RESTful Web Services"),
    ("Web Services", "What is the @Path annotation?", "Maps URI path to resource class or method"),
    ("Web Services", "What is the @GET/@POST/@PUT/@DELETE annotations?", "HTTP method binding for JAX-RS resource methods"),
    ("Web Services", "What is the @Produces annotation?", "Specifies response MIME types"),
    ("Web Services", "What is the @Consumes annotation?", "Specifies request MIME types"),
    ("Web Services", "What is the @QueryParam annotation?", "Binds URI query parameter to method parameter"),
    ("Web Services", "What is the @PathParam annotation?", "Binds path template parameter to method parameter"),
    ("Web Services", "What is the Response object in JAX-RS?", "Builds HTTP response with status, headers, entity"),
    ("Web Services", "What is the ExceptionMapper in JAX-RS?", "Maps exceptions to HTTP responses"),
    ("Web Services", "What is JMS (Java Message Service)?", "Messaging API for point-to-point and pub/sub communication"),
    ("Web Services", "What is a Queue in JMS?", "Point-to-point destination where one consumer receives message"),
    ("Web Services", "What is a Topic in JMS?", "Pub/sub destination where all subscribers receive message"),
    ("Web Services", "What is the MessageProducer in JMS?", "Sends messages to a destination"),
    ("Web Services", "What is the MessageConsumer in JMS?", "Receives messages from a destination"),
    ("JMX", "What is JMX (Java Management Extensions)?", "Manages and monitors JVM resources via MBeans"),
    ("JMX", "What is an MBean?", "Managed Bean exposing attributes and operations for management"),
    ("JMX", "What is the JMX MBeanServer?", "Registry for managing MBeans in JVM"),
    ("JMX", "What is the JMX Platform MBeanServer?", "Default MBeanServer for JVM platform monitoring"),
    ("JMX", "What is JConsole?", "JMX-compliant monitoring tool for JVM metrics"),
    ("JMX", "What is VisualVM?", "Visual monitoring tool with JMX and profiling capabilities"),
    ("JMX", "What is the JMX Remote API?", "Enables remote MBeanServer access via RMI"),
], "Senior", "Java")

# === PYTHON FRESH: GUI, Functional, Security, Profiling, Packaging ===
gen([
    ("GUI", "What is Tkinter?", "Standard Python GUI toolkit with native OS widgets"),
    ("GUI", "What is the Tk class?", "Main application window in Tkinter"),
    ("GUI", "What is the Widget class?", "Base class for all Tkinter UI elements"),
    ("GUI", "What is the pack geometry manager?", "Packs widgets in order along sides of parent"),
    ("GUI", "What is the grid geometry manager?", "Arranges widgets in rows and columns"),
    ("GUI", "What is the place geometry manager?", "Positions widgets at absolute or relative coordinates"),
    ("GUI", "What is the Button widget in Tkinter?", "Clickable button with text and command callback"),
    ("GUI", "What is the Label widget?", "Displays text or image in Tkinter"),
    ("GUI", "What is the Entry widget?", "Single-line text input field"),
    ("GUI", "What is the Text widget?", "Multi-line text editor with rich formatting"),
    ("GUI", "What is the Canvas widget?", "Drawing surface for shapes, text, and images"),
    ("GUI", "What is the Listbox widget?", "Selectable list of items"),
    ("GUI", "What is the Frame widget?", "Container for organizing other widgets"),
    ("GUI", "What is the Toplevel widget?", "Additional window separate from main Tk window"),
    ("GUI", "What is the ttk (Themed Tk) module?", "Modern themed Tkinter widgets with improved appearance"),
    ("GUI", "What is PyQt/PySide?", "Python bindings for Qt application framework"),
    ("GUI", "What is the QWidget class?", "Base class for all UI objects in Qt"),
    ("GUI", "What is the QMainWindow class?", "Main application window with menu, toolbar, status bar"),
    ("GUI", "What is the QPushButton?", "Clickable button widget in Qt"),
    ("GUI", "What is the QVBoxLayout?", "Vertically arranging layout manager in Qt"),
    ("Functional", "What is map() vs comprehension?", "map() is lazy; comprehension is eager and more readable"),
    ("Functional", "What is filter() vs comprehension?", "filter() is lazy; comprehension with if clause"),
    ("Functional", "What is the functools.reduce() pattern?", "Reduces iterable to single value via binary function"),
    ("Functional", "What is currying in Python?", "Transforming multi-argument function into nested single-arg functions"),
    ("Functional", "What is the toolz library?", "Functional programming utilities for iteration and dicts"),
    ("Functional", "What is the fn.py library?", "Functional programming in Python with Scala-like features"),
    ("Functional", "What is the returns library?", "Typed monads for pure functional Python"),
    ("Functional", "What is the effect library?", "Algebraic effects for Python"),
    ("Functional", "What is the PyMonad library?", "Monads and monoid for functional Python"),
    ("Functional", "What is immutable data structures in Python?", "pyrsistent library for persistent data structures"),
    ("Secure Coding", "What is the subprocess.PIPE security risk?", "Shell injection via shell=True with untrusted input"),
    ("Secure Coding", "What is the os.path.join() security issue?", "Absolute path in later arguments overrides base"),
    ("Secure Coding", "What is the tarfile extraction vulnerability?", "Path traversal via ../ in filenames within archive"),
    ("Secure Coding", "What is the pickle security risk?", "Arbitrary code execution via malicious pickled data"),
    ("Secure Coding", "What is the yaml.load() vulnerability?", "Arbitrary code execution with unsafe YAML loading"),
    ("Secure Coding", "What is the requests library SSL verification?", "verify=True by default, disable only with caution"),
    ("Secure Coding", "What is the bcrypt library?", "Password hashing with salt and configurable cost factor"),
    ("Secure Coding", "What is the passlib library?", "Password hash management with multiple schemes"),
    ("Secure Coding", "What is the cryptography library?", "Modern cryptographic recipes and primitives"),
    ("Secure Coding", "What is the secrets module vs random?", "secrets for cryptographically secure random values"),
    ("Profiling", "What is cProfile?", "Built-in deterministic profiler for Python functions"),
    ("Profiling", "What is python -m cProfile?", "Profiles script execution from command line"),
    ("Profiling", "What is the pstats module?", "Analyzes and sorts profiling statistics"),
    ("Profiling", "What is the SnakeViz tool?", "Visualizes cProfile output as flame charts"),
    ("Profiling", "What is the py-spy tool?", "Sampling profiler for Python without code changes"),
    ("Profiling", "What is the memory_profiler library?", "Line-by-line memory usage analysis for Python"),
    ("Profiling", "What is the objgraph library?", "Visualizes object references for debugging memory leaks"),
    ("Profiling", "What is the guppy/heapy library?", "Heap memory analysis for Python objects"),
    ("Profiling", "What is the pyflame tool?", "Uber's sampling profiler for Python (deprecated)"),
    ("Profiling", "What is the profiling asyncio code?", "Using aiomonitor and aiohttp-devtools for async profiling"),
    ("Packaging", "What is the wheel distribution format?", "Built package format with .whl extension for fast installs"),
    ("Packaging", "What is the sdist distribution?", "Source distribution for building on target system"),
    ("Packaging", "What is the setup.py sdist command?", "Creates source distribution tarball"),
    ("Packaging", "What is the setup.py bdist_wheel command?", "Creates wheel distribution"),
    ("Packaging", "What is the MANIFEST.in file?", "Includes additional files in source distribution"),
    ("Packaging", "What is the entry_points in setup.py?", "Defines console scripts and plugin discovery"),
    ("Packaging", "What is the console_scripts entry point?", "Creates command-line executable on pip install"),
    ("Packaging", "What is the extras_require in setup.py?", "Optional dependencies for extra features"),
    ("Packaging", "What is the dependency_links (deprecated)?", "Custom URLs for dependency resolution"),
    ("Packaging", "What is pip install -e?", "Editable install for development with live code updates"),
], "Senior", "Python")

# === TYPESCRIPT FRESH: Angular, Vue, Svelte, tRPC, Express + TS, NestJS, Prisma ===
gen([
    ("Angular", "What is Angular?", "Frontend framework with TypeScript, DI, and component architecture"),
    ("Angular", "What is the @Component decorator?", "Marks class as Angular component with template and styles"),
    ("Angular", "What is the @NgModule decorator?", "Defines module with declarations, imports, providers"),
    ("Angular", "What is the Angular template syntax?", "{{ interpolation }}, [property binding], (event binding)"),
    ("Angular", "What is *ngIf?", "Structural directive for conditional rendering"),
    ("Angular", "What is *ngFor?", "Structural directive for list iteration"),
    ("Angular", "What is the @Input decorator?", "Accepts data from parent component"),
    ("Angular", "What is the @Output decorator?", "Emits events to parent component"),
    ("Angular", "What is a service in Angular?", "Singleton class for business logic and data access"),
    ("Angular", "What is dependency injection in Angular?", "Hierarchical injector system providing services"),
    ("Angular", "What are Angular pipes?", "Transforms data in templates: date, currency, async, custom"),
    ("Angular", "What is the HttpClient in Angular?", "HTTP client with typed responses and interceptors"),
    ("Angular", "What is the Router in Angular?", "Client-side routing with lazy loading and guards"),
    ("Angular", "What is the @Injectable decorator?", "Marks service as available for dependency injection"),
    ("Angular", "What is the Angular CLI?", "Command-line tool for project generation and building"),
    ("Angular", "What is Angular Universal?", "Server-side rendering for Angular applications"),
    ("Vue", "What is Vue.js?", "Progressive JavaScript framework with reactive data binding"),
    ("Vue", "What is the Vue Options API?", "Component options: data, methods, computed, watch, lifecycle"),
    ("Vue", "What is the Composition API?", "Function-based component logic using ref, reactive, computed"),
    ("Vue", "What is the ref() function in Vue?", "Creates reactive value with .value access"),
    ("Vue", "What is the reactive() function?", "Creates deeply reactive object"),
    ("Vue", "What is the computed() function?", "Derived reactive value that caches and updates"),
    ("Vue", "What is the watch() function?", "Reactive side effect on data changes"),
    ("Vue", "What is the v-bind directive?", "Binds attribute to expression (shorthand : )"),
    ("Vue", "What is the v-model directive?", "Two-way data binding for form inputs"),
    ("Vue", "What is the v-if/v-show directives?", "v-if: conditional render; v-show: conditional display"),
    ("Vue", "What is a Vue component?", "Reusable instance with template, script, style"),
    ("Vue", "What is the provide/inject pattern?", "Dependency injection for deeply nested components"),
    ("Vue", "What is Vue Router?", "Official routing library for single-page Vue apps"),
    ("Vue", "What is Pinia?", "State management library for Vue with TypeScript support"),
    ("Svelte", "What is Svelte?", "Compiled frontend framework with no virtual DOM overhead"),
    ("Svelte", "What is a Svelte reactive declaration?", "$: prefix for reactive statements that auto-update"),
    ("Svelte", "What is the on:click directive?", "Event handler binding in Svelte"),
    ("Svelte", "What is the bind:value directive?", "Two-way binding for form inputs in Svelte"),
    ("Svelte", "What is Svelte store?", "Reactive state container with subscribe, set, update"),
    ("Svelte", "What is the writable() store?", "Readable and writable reactive state in Svelte"),
    ("Svelte", "What is the derived() store?", "Store computed from other stores"),
    ("Svelte", "What is {#if} block in Svelte?", "Conditional rendering block"),
    ("Svelte", "What is {#each} block in Svelte?", "Iteration block for lists"),
    ("Svelte", "What is SvelteKit?", "Full-stack framework for Svelte with SSR and routing"),
    ("tRPC", "What is tRPC?", "End-to-end type-safe APIs without code generation"),
    ("tRPC", "What is tRPC router?", "Server-side procedure definitions with input validation"),
    ("tRPC", "What is tRPC query?", "GET-like procedure for data fetching"),
    ("tRPC", "What is tRPC mutation?", "POST-like procedure for data modification"),
    ("tRPC", "What is tRPC subscription?", "WebSocket-based real-time data streaming"),
    ("tRPC", "What is the @trpc/client?", "Client-side proxy with full type inference"),
    ("tRPC", "What is the @trpc/next?", "Next.js integration for tRPC"),
    ("tRPC", "What is the @trpc/react-query?", "React bindings for tRPC with TanStack Query"),
    ("tRPC", "What is tRPC middleware?", "Request middleware for auth, logging, rate limiting"),
    ("tRPC", "What is tRPC context?", "Request-scoped data available to all procedures"),
    ("NestJS", "What is NestJS?", "Progressive Node.js framework with TypeScript and decorators"),
    ("NestJS", "What is the @Module decorator?", "Defines module with controllers, providers, imports"),
    ("NestJS", "What is the @Controller decorator?", "Marks class as HTTP controller with routes"),
    ("NestJS", "What is the @Injectable decorator?", "Marks class as provider for dependency injection"),
    ("NestJS", "What is a NestJS provider?", "Injectable service, repository, or factory"),
    ("NestJS", "What is the @Get decorator?", "Marks method as HTTP GET endpoint"),
    ("NestJS", "What is the @Body decorator?", "Extracts request body parameter"),
    ("NestJS", "What is the @Param decorator?", "Extracts route parameter"),
    ("NestJS", "What is the @Query decorator?", "Extracts query string parameter"),
    ("NestJS", "What is the @UseGuards decorator?", "Applies authentication/authorization guard"),
    ("NestJS", "What is the @UsePipes decorator?", "Applies validation/transformation pipe"),
    ("NestJS", "What is the @UseInterceptors decorator?", "Applies interceptor for request/response transformation"),
    ("NestJS", "What is the @UseFilters decorator?", "Applies exception filter for error handling"),
    ("NestJS", "What is the NestJS middleware?", "Function executed before route handler"),
    ("NestJS", "What is the TypeORM integration?", "Database ORM module for NestJS"),
    ("Prisma", "What is Prisma?", "TypeScript ORM with auto-generated query client"),
    ("Prisma", "What is the Prisma schema file?", "Data model definition with datasource, generator, models"),
    ("Prisma", "What is Prisma Client?", "Auto-generated type-safe query builder for Node.js"),
    ("Prisma", "What is prisma.model.findUnique()?", "Finds single record by unique identifier"),
    ("Prisma", "What is prisma.model.findMany()?", "Returns multiple records with filter, order, pagination"),
    ("Prisma", "What is prisma.model.create()?", "Creates new record in database"),
    ("Prisma", "What is prisma.model.update()?", "Updates existing record by unique identifier"),
    ("Prisma", "What is prisma.model.delete()?", "Deletes record by unique identifier"),
    ("Prisma", "What is Prisma Migrate?", "Declarative schema migration tool"),
    ("Prisma", "What is prisma db push?", "Pushes schema to database without migration files"),
], "Middle", "TypeScript")

# === GO FRESH: Reflection, Code Generation, testify testing, Profiling, embed ===
gen([
    ("Reflection", "What is reflect.TypeOf()?", "Returns reflect.Type of interface value"),
    ("Reflection", "What is reflect.ValueOf()?", "Returns reflect.Value wrapping interface value"),
    ("Reflection", "What is reflect.Type.Kind()?", "Returns the underlying kind (struct, slice, map, etc.)"),
    ("Reflection", "What is reflect.Value.Kind()?", "Returns the underlying kind of reflected value"),
    ("Reflection", "What is reflect.Value.Interface()?", "Returns underlying value as interface{}"),
    ("Reflection", "What is reflect.Value.Field()?", "Returns struct field reflect.Value by index"),
    ("Reflection", "What is reflect.Type.NumField()?", "Returns number of fields in struct type"),
    ("Reflection", "What is reflect.Type.FieldByName()?", "Returns struct field by name with found flag"),
    ("Reflection", "What is reflect.Value.Elem()?", "Dereferences pointer or interface value"),
    ("Reflection", "What is reflect.Value.Set()?", "Sets value on writable reflect.Value"),
    ("Reflection", "What is reflect.Value.Call()?", "Calls reflected function value with arguments"),
    ("Reflection", "What is reflect.MakeFunc()?", "Creates function value from given type and callback"),
    ("Reflection", "What is reflect.StructTag?", "Parses struct tag string for field metadata"),
    ("Reflection", "What is reflect.DeepEqual()?", "Recursive equality comparison for complex values"),
    ("Reflection", "What is the reflect.Select() function?", "Simulates select statement with reflected channels"),
    ("Code Gen", "What is go generate?", "Runs commands specified by //go:generate directives"),
    ("Code Gen", "What is the //go:generate directive?", "Specifies command to run before compilation"),
    ("Code Gen", "What is the stringer tool?", "Auto-generates String() method for enum types"),
    ("Code Gen", "What is golang.org/x/tools/cmd/stringer?", "Tool implementing stringer for integer constants"),
    ("Code Gen", "What is the mockgen tool?", "Generates mock implementations from Go interfaces"),
    ("Code Gen", "What is gomock?", "Mocking framework for Go with generated mocks"),
    ("Code Gen", "What is counterfeiter?", "Mock generation tool for Go interfaces"),
    ("Code Gen", "What is the deepcopy gen tool?", "Generates deep copy methods for Go structs"),
    ("Code Gen", "What is the genny tool?", "Generics for Go using type parameter substitution"),
    ("Code Gen", "What is the oapi-codegen tool?", "Generates Go code from OpenAPI specs"),
    ("Testing", "What is the testify/assert package?", "Assertion library with descriptive failure messages"),
    ("Testing", "What is assert.Equal()?", "Asserts two values are deeply equal"),
    ("Testing", "What is assert.NotNil()?", "Asserts value is not nil"),
    ("Testing", "What is assert.Contains()?", "Asserts string/slice contains expected element"),
    ("Testing", "What is assert.Error()?", "Asserts function returns non-nil error"),
    ("Testing", "What is assert.NoError()?", "Asserts function returns nil error"),
    ("Testing", "What is assert.Greater()?", "Asserts first value is greater than second"),
    ("Testing", "What is assert.InDelta()?", "Asserts float values within delta tolerance"),
    ("Testing", "What is assert.IsType()?", "Asserts value is of expected type"),
    ("Testing", "What is assert.Panics()?", "Asserts function panics"),
    ("Testing", "What is assert.Regexp()?", "Asserts string matches regex pattern"),
    ("Testing", "What is require vs assert?", "require fails immediately; assert continues test"),
    ("Testing", "What is testing.T.Run()?", "Runs subtest with given name and function"),
    ("Testing", "What is testing.Cleanup()?", "Registers cleanup function called after test"),
    ("Testing", "What is the go-cmp library?", "Comparison library with readable diffs for tests"),
    ("Testing", "What is cmp.Diff()?", "Returns human-readable difference between values"),
    ("Profiling", "What is pprof CPU profiling?", "Samples CPU usage to identify hot functions"),
    ("Profiling", "What is pprof memory profiling?", "Allocation profiling to find memory bottlenecks"),
    ("Profiling", "What is pprof goroutine profile?", "Stack traces of all goroutines for leak detection"),
    ("Profiling", "What is pprof mutex profile?", "Mutex contention profile for synchronization issues"),
    ("Profiling", "What is pprof block profile?", "Blocking operations profile for identifying stalls"),
    ("Profiling", "What is go tool pprof -http?", "Starts web UI for pprof visualization"),
    ("Profiling", "What is the pprof flame graph?", "Visual representation of CPU usage stack traces"),
    ("Embed", "What is Go embed directive?", "Embeds files into binary at compile time"),
    ("Embed", "What is //go:embed", "Compile-time file embedding into variable"),
    ("Embed", "What is embed.FS?", "Read-only file system of embedded files"),
    ("Embed", "What is embed.FS.Open()?", "Opens embedded file for reading"),
    ("Embed", "What is embed.FS.ReadFile()?", "Reads embedded file content as bytes"),
    ("Embed", "What is embed.FS.ReadDir()?", "Reads embedded directory entries"),
    ("Embed", "What are the embed patterns?", "Path glob: * for files, ** for recursive"),
], "Senior", "Go")

# === RUST FRESH: Embedded, FFI, Profiling, proptest, Build Scripts ===
gen([
    ("Embedded", "What is #![no_std]?", "Disables standard library for embedded/bare-metal"),
    ("Embedded", "What is the core crate?", "Minimal Rust standard library for no_std environments"),
    ("Embedded", "What is the alloc crate?", "Heap allocation for no_std via global allocator"),
    ("Embedded", "What is #[global_allocator]?", "Assigns custom memory allocator for the program"),
    ("Embedded", "What is the cortex-m crate?", "Abstractions for ARM Cortex-M microcontrollers"),
    ("Embedded", "What is the embedded-hal trait?", "Hardware abstraction layer for embedded peripherals"),
    ("Embedded", "What is the rtic framework?", "Real-Time Interrupt-driven Concurrency for embedded"),
    ("Embedded", "What is the embassy framework?", "Async embedded framework with async executors"),
    ("Embedded", "What is the PAC (Peripheral Access Crate)?", "Low-level register definitions for MCU"),
    ("Embedded", "What is the HAL (Hardware Abstraction Layer)?", "Higher-level abstractions over PAC registers"),
    ("Embedded", "What is the panic-halt crate?", "Halts execution on panic for embedded devices"),
    ("Embedded", "What is the panic-itm crate?", "Outputs panic messages via ITM debugging"),
    ("Embedded", "What is the panic-semihosting crate?", "Outputs panic messages via semihosting"),
    ("Embedded", "What is the probe-run tool?", "Run and debug embedded programs with defmt"),
    ("Embedded", "What is defmt?", "Efficient logging with binary format for embedded"),
    ("Embedded", "What is the svd2rust tool?", "Generates PAC from SVD microcontroller descriptions"),
    ("FFI", "What is FFI (Foreign Function Interface)?", "Calling C code from Rust using extern blocks"),
    ("FFI", "What is the extern \"C\" block?", "Declares C functions callable from Rust"),
    ("FFI", "What is the #[no_mangle] attribute?", "Prevents symbol name mangling for FFI exports"),
    ("FFI", "What is the extern \"C\" fn declaration?", "Exports Rust function with C calling convention"),
    ("FFI", "What is unsafe for FFI?", "Required for calling external functions"),
    ("FFI", "What is the std::ffi::CStr type?", "Borrowed C string representation"),
    ("FFI", "What is the std::ffi::CString type?", "Owned C string with null terminator"),
    ("FFI", "What is std::os::raw::c_char?", "Platform-specific char type for C compatibility"),
    ("FFI", "What is std::os::raw::c_int?", "Platform-specific int type for C compatibility"),
    ("FFI", "What is the libffi crate?", "Dynamically call C functions at runtime"),
    ("FFI", "What is the jni crate?", "Java Native Interface bindings for Rust"),
    ("FFI", "What is the napi-rs crate?", "Node.js native addon development with Rust"),
    ("FFI", "What is the pyo3 crate?", "Python extension module development in Rust"),
    ("FFI", "What is the Neon bindings?", "Node.js native modules in Rust"),
    ("Proptest", "What is property-based testing?", "Testing with random inputs to find edge cases"),
    ("Proptest", "What is the proptest crate?", "Property-based testing framework for Rust"),
    ("Proptest", "What is proptest::proptest!?", "Macro to define property-based test cases"),
    ("Proptest", "What is a proptest strategy?", "Defines how random values are generated"),
    ("Proptest", "What is proptest::arbitrary?", "Auto-derives strategies for types"),
    ("Proptest", "What is #[derive(Arbitrary)]?", "Automatically generates test strategies"),
    ("Proptest", "What is the prop_assert! macro?", "Assertion macro for proptest with better messages"),
    ("Proptest", "What is the proptest state machine?", "Model-based testing with state transitions"),
    ("Proptest", "What is the quickcheck crate?", "Original property-based testing library for Rust"),
    ("Proptest", "What is quickcheck::QuickCheck?", "Runner for quickcheck property tests"),
    ("Build Scripts", "What is build.rs?", "Build script executed before compiling the crate"),
    ("Build Scripts", "What is the Cargo build script?", "Rust file for code generation at compile time"),
    ("Build Scripts", "What is cargo:rustc-link-lib?", "Instructs Cargo to link native library"),
    ("Build Scripts", "What is cargo:rerun-if-changed?", "Rebuild if specified file changes"),
    ("Build Scripts", "What is cargo:rerun-if-env-changed?", "Rebuild if environment variable changes"),
    ("Build Scripts", "What is cargo:rustc-cfg?", "Sets conditional compilation flag from build script"),
    ("Build Scripts", "What is cargo:rustc-env?", "Sets environment variable for compile time"),
    ("Build Scripts", "What is the cc crate?", "Compiles C/C++ code from build script"),
    ("Build Scripts", "What is the autocfg crate?", "Detects compiler features from build script"),
    ("Build Scripts", "What is the bindgen tool?", "Generates Rust FFI bindings from C headers"),
], "Senior", "Rust")

# === REACT FRESH: MUI, React Hook Form, Recharts, react-i18next, NextAuth, Storybook ===
gen([
    ("MUI", "What is Material-UI (MUI)?", "React component library implementing Material Design"),
    ("MUI", "What is MUI ThemeProvider?", "Provides theme configuration to MUI components"),
    ("MUI", "What is MUI createTheme()?", "Creates custom theme with palette, typography, spacing"),
    ("MUI", "What is the MUI Grid component?", "Responsive layout grid from Material Design"),
    ("MUI", "What is the MUI Box component?", "Low-level container for CSS layout utilities"),
    ("MUI", "What is the MUI Container component?", "Centered horizontal container with max-width"),
    ("MUI", "What is the MUI Typography component?", "Text display with pre-defined variants"),
    ("MUI", "What is the MUI Button component?", "Clickable button with variants, colors, sizes"),
    ("MUI", "What is the MUI TextField component?", "Form input with label, error, helper text"),
    ("MUI", "What is the MUI Select component?", "Dropdown selection with single/multi options"),
    ("MUI", "What is the MUI Dialog component?", "Modal dialog for confirmations and forms"),
    ("MUI", "What is the MUI Snackbar component?", "Temporary notification at screen bottom"),
    ("MUI", "What is the MUI Drawer component?", "Slide-in panel from screen edge"),
    ("MUI", "What is the MUI AppBar component?", "Top app bar with navigation and actions"),
    ("MUI", "What is the MUI DataGrid component?", "Rich data table with sorting, filtering, pagination"),
    ("MUI", "What is the MUI Autocomplete component?", "Searchable select with free input option"),
    ("Forms", "What is React Hook Form?", "Performant form library with uncontrolled inputs"),
    ("Forms", "What is the useForm() hook?", "Creates form instance with register, handleSubmit"),
    ("Forms", "What is register() in RHF?", "Registers input with validation rules"),
    ("Forms", "What is handleSubmit() in RHF?", "Handles form submission with validation"),
    ("Forms", "What is the Controller component?", "Wraps controlled components for RHF integration"),
    ("Forms", "What is formState in RHF?", "Contains errors, isDirty, isValid, isSubmitting"),
    ("Forms", "What is the useFieldArray() hook?", "Manages dynamic form fields (add, remove, move)"),
    ("Forms", "What is the useWatch() hook?", "Subscribes to field value changes"),
    ("Forms", "What is the zodResolver in RHF?", "Integrates Zod schema validation with RHF"),
    ("Forms", "What is Formik?", "Form library with Field, Form, ErrorMessage components"),
    ("Forms", "What is the useFormik() hook?", "Formik hook with initial values and validation"),
    ("Forms", "What is Formik validationSchema?", "Yup/Zod validation schema for form validation"),
    ("Forms", "What is Formik FieldArray?", "Dynamic form fields with push, remove methods"),
    ("Data Viz", "What is Recharts?", "Declarative charting library for React with SVG"),
    ("Data Viz", "What is the BarChart component?", "Horizontal or vertical bar chart"),
    ("Data Viz", "What is the LineChart component?", "Line chart with x/y axis and data points"),
    ("Data Viz", "What is the PieChart component?", "Pie chart with labels and colors"),
    ("Data Viz", "What is the AreaChart component?", "Area chart with filled regions"),
    ("Data Viz", "What is the XAxis/YAxis component?", "Chart axis with label, tick, domain config"),
    ("Data Viz", "What is the Tooltip component?", "Hover tooltip displaying data point values"),
    ("Data Viz", "What is the Legend component?", "Chart legend for data series identification"),
    ("Data Viz", "What is the ResponsiveContainer?", "Auto-sizing chart wrapper for responsive layout"),
    ("Data Viz", "What is Victory (Victory Native)?", "Chart library for React and React Native"),
    ("i18n", "What is react-i18next?", "Internationalization framework for React with hooks"),
    ("i18n", "What is i18next?", "Internationalization framework with plural and interpolation"),
    ("i18n", "What is i18next init()?", "Initializes i18next with resources and language"),
    ("i18n", "What is the useTranslation() hook?", "Returns t() function and i18n instance"),
    ("i18n", "What is the t() function?", "Translates key with interpolation and pluralization"),
    ("i18n", "What is the Trans component?", "Component with rich HTML in translations"),
    ("i18n", "What is the i18n.changeLanguage()?", "Switches active language at runtime"),
    ("i18n", "What is the i18n.language property?", "Returns current active language code"),
    ("i18n", "What is the i18n.options property?", "Returns i18next configuration options"),
    ("i18n", "What is the i18next LTR/RTL support?", "Automatic text direction based on language"),
    ("Auth", "What is NextAuth.js?", "Authentication library for Next.js with multiple providers"),
    ("Auth", "What is NextAuth adapter?", "Database adapter for persisting users and sessions"),
    ("Auth", "What is NextAuth credentials provider?", "Custom email/password authentication"),
    ("Auth", "What is NextAuth OAuth provider?", "Social login with Google, GitHub, Discord, etc."),
    ("Auth", "What is NextAuth session strategy?", "JWT-based or database-based session management"),
    ("Auth", "What is the useSession() hook?", "Accesses session data and authentication status"),
    ("Auth", "What is the signIn() function?", "Initiates authentication with specified provider"),
    ("Auth", "What is the signOut() function?", "Ends current session"),
    ("Auth", "What is the getServerSession()?", "Server-side session retrieval for SSR"),
    ("Auth", "What is the Auth.js library?", "Framework-agnostic successor to NextAuth.js"),
], "Senior", "React")

# === KOTLIN FRESH: KSP, Scripting, Android Jetpack detail, Serialization detail ===
gen([
    ("KSP", "What is KSP (Kotlin Symbol Processing)?", "Compiler plugin API for annotation processing"),
    ("KSP", "What is the SymbolProcessor interface?", "Processes Kotlin symbols during compilation"),
    ("KSP", "What is the process() method in KSP?", "Called to process annotated symbols each round"),
    ("KSP", "What is the Resolver in KSP?", "Provides symbols from compilation environment"),
    ("KSP", "What is KSFunctionDeclaration?", "Represents a function declaration in KSP"),
    ("KSP", "What is KSClassDeclaration?", "Represents a class/object declaration in KSP"),
    ("KSP", "What is KSPropertyDeclaration?", "Represents a property declaration in KSP"),
    ("KSP", "What is KSAnnotation?", "Represents an annotation reference in KSP"),
    ("KSP", "What is the CodeGenerator in KSP?", "Generates Kotlin source files during compilation"),
    ("KSP", "What is KSP vs KAPT?", "KSP is faster and Kotlin-native; KAPT is Kotlin-Java interop"),
    ("Scripting", "What is Kotlin scripting?", "Running Kotlin code as scripts without compilation"),
    ("Scripting", "What is the kotlin-main-kts artifact?", "Script definition with main function"),
    ("Scripting", "What is the kotlin script template?", ".kts files with custom scripting API"),
    ("Scripting", "What is the $0 parameter in script?", "Path to the script file itself"),
    ("Scripting", "What is the args array in scripts?", "Command-line arguments passed to script"),
    ("Scripting", "What is the kotlin script compilation?", "Scripts are compiled before execution"),
    ("Scripting", "What is the scripting host API?", "Embedded scripting with ScriptEngine"),
    ("Scripting", "What is the Kotlin REPL?", "Read-Eval-Print-Loop for interactive Kotlin"),
    ("Serialization", "What is kotlinx.serialization?", "First-class serialization for Kotlin data classes"),
    ("Serialization", "What is the @Serializable annotation?", "Marks class as serializable"),
    ("Serialization", "What is Json { } in kotlinx?", "JSON configuration: pretty print, ignore unknown keys"),
    ("Serialization", "What is Json.decodeFromString()?", "Deserializes JSON string to Kotlin object"),
    ("Serialization", "What is Json.encodeToString()?", "Serializes Kotlin object to JSON string"),
    ("Serialization", "What is @Transient annotation?", "Excludes property from serialization"),
    ("Serialization", "What is @SerialName annotation?", "Custom serial name for property"),
    ("Serialization", "What is the custom serializer?", "User-defined KSerializer for custom logic"),
    ("Serialization", "What is the KSerializer interface?", "Defines serialization/deserialization logic"),
    ("Serialization", "What is the descriptor property?", "Serial descriptor describing serial structure"),
    ("Serialization", "What is SerializersModule?", "Registers custom serializers for polymorphic types"),
    ("Serialization", "What is the @Polymorphic annotation?", "Enables polymorphic serialization for sealed classes"),
    ("Android Room", "What is Room DAO?", "Data Access Object with SQL query methods"),
    ("Android Room", "What is @Insert in Room?", "Insert entity with conflict strategy"),
    ("Android Room", "What is @Update in Room?", "Updates matching entity by primary key"),
    ("Android Room", "What is @Delete in Room?", "Deletes matching entity"),
    ("Android Room", "What is @Query in Room?", "Custom SQL query returning entities or values"),
    ("Android Room", "What is @Transaction in Room?", "Runs method in database transaction"),
    ("Android Room", "What is Room TypeConverter?", "Converts custom types to/from SQLite types"),
    ("Android Room", "What is Room migration?", "Handles schema changes between versions"),
    ("Android Room", "What is Room fallbackToDestructiveMigration?", "Destructive migration recreating database"),
    ("Android Room", "What is the Room database builder?", "Builds RoomDatabase with version and migrations"),
    ("Android Jetpack", "What is the WorkManager?", "API for deferrable background work"),
    ("Android Jetpack", "What is a OneTimeWorkRequest?", "Work request that runs once"),
    ("Android Jetpack", "What is a PeriodicWorkRequest?", "Work request that repeats at interval"),
    ("Android Jetpack", "What is the Worker class?", "Extendable class with doWork() method"),
    ("Android Jetpack", "What is WorkManager constraints?", "Network type, battery, idle, storage conditions"),
    ("Android Jetpack", "What is the Navigation Component?", "Type-safe in-app navigation between screens"),
    ("Android Jetpack", "What is NavHost in Navigation?", "Composable container for navigation destinations"),
    ("Android Jetpack", "What is NavController?", "Manages app navigation and back stack"),
    ("Android Jetpack", "What is the Navigation Safe Args?", "Type-safe argument passing between destinations"),
    ("Android Jetpack", "What is the Deep Link in Navigation?", "Direct navigation from URI or intent"),
    ("Android Jetpack", "What is the ViewModel?", "Stores UI state across configuration changes"),
    ("Android Jetpack", "What is the viewModelScope?", "Coroutine scope tied to ViewModel lifecycle"),
    ("Android Jetpack", "What is LiveData?", "Observable data holder with lifecycle awareness"),
    ("Android Jetpack", "What is MutableLiveData?", "Mutable version of LiveData"),
    ("Android Jetpack", "What is the Data Binding library?", "Binds UI components to data sources declaratively"),
    ("Android Jetpack", "What is the Paging 3 library?", "Loads data pages incrementally from data sources"),
    ("Android Jetpack", "What is the PagingDataAdapter?", "RecyclerView adapter for paged data"),
    ("Android Jetpack", "What is the PagingSource class?", "DataSource for loading pages from a data source"),
    ("Android Jetpack", "What is the RemoteMediator in Paging?", "Handles network-database hybrid paging"),
    ("Android Jetpack", "What is the Hilt DI in Android?", "Standard DI library for Android with ViewModel injection"),
], "Senior", "Kotlin")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 16 added {len(new)} questions.")