"""Batch 14: Final ~460 questions to reach ~7000 total"""
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(a)}', 'Alternative', 'Misconception', 'Unsure'], '{diff}', '{lang}');\n")

def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# --- JAVA (+50) ---
gen([
    ("OOP", "What is varargs in Java?", "Variable-length arguments using ... syntax"),
    ("OOP", "What is the difference between abstract and interface?", "Abstract can have state; interface defines contract"),
    ("OOP", "What is the covariant return type?", "Overriding method can return subtype of original return type"),
    ("OOP", "What is the @Override annotation?", "Indicates method overrides superclass method"),
    ("OOP", "What is the @SuppressWarnings annotation?", "Suppresses compiler warnings"),
    ("OOP", "What is the @Deprecated annotation?", "Marks API as deprecated"),
    ("OOP", "What is the @SafeVarargs annotation?", "Suppresses heap pollution warnings on varargs"),
    ("OOP", "What is the @FunctionalInterface annotation?", "Ensures interface has exactly one abstract method"),
    ("OOP", "What is the @Native annotation?", "Marks field accessible from native code"),
    ("OOP", "What is the @Stable annotation?", "Indicates value will not change after first write"),
    ("OOP", "What is the transient keyword?", "Marks field as not serialized"),
    ("OOP", "What is the volatile keyword?", "Ensures visibility across threads"),
    ("OOP", "What is the strictfp keyword?", "Ensures strict floating-point behavior (rarely used)"),
    ("OOP", "What is the native keyword?", "Marks method implemented in native code"),
    ("OOP", "What is the synchronized keyword?", "Ensures thread-safe access to method or block"),
    ("OOP", "What is the instanceof operator?", "Checks if object is instance of a type"),
    ("OOP", "What is the ternary operator ?:", "Conditional expression with if-else logic"),
    ("OOP", "What is the bitwise AND & operator?", "Performs bitwise AND operation"),
    ("OOP", "What is the bitwise OR | operator?", "Performs bitwise OR operation"),
    ("OOP", "What is the XOR ^ operator?", "Performs bitwise exclusive OR operation"),
    ("OOP", "What is the left shift << operator?", "Shifts bits left, filling with zeros"),
    ("OOP", "What is the right shift >> operator?", "Shifts bits right, preserving sign"),
    ("OOP", "What is the unsigned right shift >>> operator?", "Shifts bits right, filling with zeros"),
    ("OOP", "What is the complement ~ operator?", "Inverts all bits"),
    ("OOP", "What is the short-circuit && operator?", "Evaluates right only if left is true"),
    ("OOP", "What is the short-circuit || operator?", "Evaluates right only if left is false"),
    ("OOP", "What is the for-each loop?", "Iterates over arrays and collections"),
    ("OOP", "What is the labeled break?", "Exits named block or loop"),
    ("OOP", "What is the labeled continue?", "Continues named loop"),
    ("OOP", "What is the return statement?", "Exits method and returns value if any"),
    ("OOP", "What is a literal in Java?", "Direct value in code like 42, 3.14, 'A', true"),
    ("OOP", "What is the underscore in numeric literals?", "1_000_000 for readability (Java 7+)"),
    ("OOP", "What is the binary literal?", "0b prefix for binary numbers"),
    ("OOP", "What is the hex literal?", "0x prefix for hexadecimal numbers"),
    ("OOP", "What is the octal literal?", "0 prefix for octal numbers (rare)"),
    ("OOP", "What is the diamond operator <>?", "Type inference for generics on right side"),
    ("OOP", "What is the unbounded wildcard <?>?", "Any type in generic parameter"),
    ("OOP", "What is the upper bounded wildcard <? extends T>?", "T or any subtype"),
    ("OOP", "What is the lower bounded wildcard <? super T>?", "T or any supertype"),
    ("OOP", "What is the PECS principle?", "Producer Extends, Consumer Super"),
    ("OOP", "What is the type inference?", "Compiler deducing generic types automatically"),
    ("OOP", "What is the var keyword (Java 10)?", "Local variable type inference"),
    ("OOP", "What is the String.join() method?", "Joins strings with delimiter"),
    ("OOP", "What is the String.repeat() method?", "Repeats string N times"),
    ("OOP", "What is the String.isBlank() method?", "Checks if string is empty or whitespace"),
    ("OOP", "What is the String.lines() method?", "Splits string into lines as Stream"),
    ("OOP", "What is the String.strip() vs trim()?", "strip handles Unicode whitespace; trim does not"),
    ("OOP", "What is the String.indent() method?", "Adjusts indentation of each line"),
    ("OOP", "What is the String.transform() method?", "Applies function to string"),
    ("OOP", "What is the String.formatted() method?", "Formats string with arguments"),
], "Junior", "Java")

# --- PYTHON (+60) ---
gen([
    ("Basics", "What is the any() function?", "Returns True if any element in iterable is truthy"),
    ("Basics", "What is the all() function?", "Returns True if all elements are truthy"),
    ("Basics", "What is the sum() function?", "Sums elements of iterable"),
    ("Basics", "What is the min() function?", "Returns minimum element"),
    ("Basics", "What is the max() function?", "Returns maximum element"),
    ("Basics", "What is the abs() function?", "Returns absolute value"),
    ("Basics", "What is the pow() function?", "Returns base raised to exponent"),
    ("Basics", "What is the round() function?", "Rounds to N decimal places"),
    ("Basics", "What is the divmod() function?", "Returns quotient and remainder as tuple"),
    ("Basics", "What is the isinstance() function?", "Checks if object is instance of type"),
    ("Basics", "What is the issubclass() function?", "Checks if class is subclass of another"),
    ("Basics", "What is the callable() function?", "Checks if object is callable"),
    ("Basics", "What is the hasattr() function?", "Checks if object has attribute"),
    ("Basics", "What is the getattr() function?", "Gets attribute by name"),
    ("Basics", "What is the setattr() function?", "Sets attribute by name"),
    ("Basics", "What is the delattr() function?", "Deletes attribute by name"),
    ("Basics", "What is the id() function?", "Returns unique identifier of object"),
    ("Basics", "What is the type() function?", "Returns type of object"),
    ("Basics", "What is the globals() function?", "Returns global symbol table dict"),
    ("Basics", "What is the locals() function?", "Returns local symbol table dict"),
    ("Basics", "What is the vars() function?", "Returns __dict__ of object"),
    ("Basics", "What is the hash() function?", "Returns hash value of object"),
    ("Basics", "What is the ord() function?", "Returns Unicode code point of character"),
    ("Basics", "What is the chr() function?", "Returns character from Unicode code point"),
    ("Basics", "What is the repr() function?", "Returns unambiguous string representation"),
    ("Basics", "What is the ascii() function?", "Returns ASCII-safe representation"),
    ("Basics", "What is the bin() function?", "Returns binary string representation"),
    ("Basics", "What is the oct() function?", "Returns octal string representation"),
    ("Basics", "What is the hex() function?", "Returns hex string representation"),
    ("Basics", "What is the eval() function?", "Evaluates string as Python expression"),
    ("Basics", "What is the exec() function?", "Executes string as Python code"),
    ("Basics", "What is the compile() function?", "Compiles source into code object"),
    ("Basics", "What is the __import__ function?", "Import hook for dynamic imports"),
    ("Basics", "What is the iter() function?", "Returns iterator from iterable"),
    ("Basics", "What is the next() function?", "Returns next item from iterator"),
    ("Basics", "What is the reversed() built-in?", "Returns reverse iterator"),
    ("Basics", "What is the sorted() built-in?", "Returns sorted list"),
    ("Basics", "What is the enumerate() built-in?", "Returns index-value pairs"),
    ("Basics", "What is the zip() built-in?", "Aggregates elements from iterables"),
    ("Basics", "What is the map() built-in?", "Applies function to iterable"),
    ("Basics", "What is the filter() built-in?", "Filters iterable by predicate"),
    ("Basics", "What is the slice() built-in?", "Creates slice object"),
    ("Basics", "What is the range() built-in?", "Creates arithmetic progression"),
    ("Basics", "What is the open() built-in?", "Opens file and returns file object"),
    ("Basics", "What is the input() built-in?", "Reads input from stdin"),
    ("Basics", "What is the print() built-in?", "Prints to stdout"),
    ("Basics", "What is the len() built-in?", "Returns length of sequence"),
    ("Basics", "What is the isinstance vs type()?", "isinstance handles inheritance; type does not"),
    ("Basics", "What is the __class__ attribute?", "Reference to object's class"),
    ("Basics", "What is the __dict__ attribute?", "Object's writable attribute dictionary"),
    ("Basics", "What is the __module__ attribute?", "Module name where class is defined"),
    ("Basics", "What is the __annotations__ attribute?", "Type annotations of module/class/function"),
    ("Basics", "What is the __doc__ attribute?", "Documentation string of object"),
    ("Basics", "What is the __name__ attribute?", "Name of module or class"),
    ("Basics", "What is the __file__ attribute?", "Path to module file"),
    ("Basics", "What is the __package__ attribute?", "Package name of module"),
    ("Basics", "What is the __loader__ attribute?", "Loader used to load module"),
    ("Basics", "What is the __spec__ attribute?", "Module specification"),
    ("Basics", "What is the __path__ attribute?", "Package path for submodules"),
    ("Basics", "What is the __version__ attribute?", "Version string of module"),
], "Junior", "Python")

# --- TYPESCRIPT (+60) ---
gen([
    ("Types", "What is the ThisType utility?", "Controls the type of this in objects"),
    ("Types", "What is the intrinsic keyword?", "Compiler-level string manipulation types"),
    ("Types", "What is a branded type?", "Type with unique brand for nominal-like typing"),
    ("Types", "What is the Flatten type pattern?", "Recursive conditional to flatten nested arrays"),
    ("Types", "What is the DeepReadonly type?", "Recursive readonly for nested objects"),
    ("Types", "What is the DeepPartial type?", "Recursive partial for nested objects"),
    ("Types", "What is the DeepRequired type?", "Recursive required for nested objects"),
    ("Types", "What is the UnionToIntersection type?", "Converts union to intersection via distributive law"),
    ("Types", "What is the IsNever type?", "Checks if type is never"),
    ("Types", "What is the IsUnion type?", "Checks if type is a union"),
    ("Types", "What is the LastOfUnion type?", "Gets last member of union type"),
    ("Types", "What is the UnionToTuple type?", "Converts union to tuple type"),
    ("Types", "What is the IsTuple type?", "Checks if type is a tuple"),
    ("Types", "What is the TupleToUnion type?", "Converts tuple to union type"),
    ("Types", "What is the Pop tuple type?", "Removes last element from tuple"),
    ("Types", "What is the Push tuple type?", "Adds element to end of tuple"),
    ("Types", "What is the Shift tuple type?", "Removes first element from tuple"),
    ("Types", "What is the Unshift tuple type?", "Adds element to start of tuple"),
    ("Types", "What is the Concat tuple type?", "Concatenates two tuples"),
    ("Types", "What is the Reverse tuple type?", "Reverses tuple order"),
    ("Types", "What is the Zip tuple type?", "Zips two tuples into pairs"),
    ("Types", "What is the IsEqual type?", "Checks if two types are exactly equal"),
    ("Types", "What is the Diff type?", "Subtracts one type from another"),
    ("Types", "What is the SymmetricDifference type?", "Elements in either but not both"),
    ("Types", "What is the FunctionPropertyNames type?", "Property names with function values"),
    ("Types", "What is the NonFunctionPropertyNames type?", "Property names with non-function values"),
    ("Types", "What is the WritableKeys type?", "Keys of writable properties"),
    ("Types", "What is the ReadonlyKeys type?", "Keys of readonly properties"),
    ("Types", "What is the RequiredKeys type?", "Keys of required properties"),
    ("Types", "What is the OptionalKeys type?", "Keys of optional properties"),
    ("Types", "What is the Unionize type?", "Makes all properties union of their types"),
    ("Types", "What is the Primitive type?", "Union of primitive types"),
    ("Types", "What is the Nullish type?", "null | undefined"),
    ("Types", "What is the Json type?", "Recursive type for JSON values"),
    ("Types", "What is the EmptyObject type?", "Type with no properties"),
    ("Types", "What is the Entries type?", "Object to [key, value] tuple array"),
    ("Types", "What is the FromEntries type?", "Tuple array to object type"),
    ("Types", "What is the PickByValue type?", "Pick properties matching value type"),
    ("Types", "What is the OmitByValue type?", "Omit properties matching value type"),
    ("Types", "What is the PickByValueExact type?", "Pick properties with exact value type"),
    ("Types", "What is the OmitByValueExact type?", "Omit properties with exact value type"),
    ("Types", "What is the At type?", "Index type supporting negative indices"),
    ("Types", "What is the IsAny type?", "Checks if type is any"),
    ("Types", "What is the IsUnknown type?", "Checks if type is unknown"),
    ("Types", "What is the IsLiteral type?", "Checks if type is literal value"),
    ("Types", "What is the If type?", "Conditional type with branches"),
    ("Types", "What is the Equal type?", "Deep equality type check"),
    ("Types", "What is the Not type?", "Boolean negation at type level"),
    ("Types", "What is the And type?", "Boolean AND at type level"),
    ("Types", "What is the Or type?", "Boolean OR at type level"),
    ("Types", "What is the IsStringLiteral type?", "Checks if type is string literal"),
    ("Types", "What is the IsNumberLiteral type?", "Checks if type is number literal"),
    ("Types", "What is the IsBooleanLiteral type?", "Checks if type is boolean literal"),
    ("Types", "What is the IsSymbol type?", "Checks if type is symbol"),
    ("Types", "What is the IsVoid type?", "Checks if type is void"),
    ("Types", "What is the IsNullable type?", "Checks if type includes null"),
    ("Types", "What is the IsUndefined type?", "Checks if type is undefined"),
    ("Types", "What is the IsFalsy type?", "Checks if type is falsy (false | 0 | '')"),
    ("Types", "What is the NonUndefined type?", "Excludes undefined from type"),
], "Senior", "TypeScript")

# --- GO (+50) ---
gen([
    ("Basics", "What is the go doc command?", "Shows documentation for package or symbol"),
    ("Basics", "What is the go env command?", "Shows Go environment settings"),
    ("Basics", "What is the go list command?", "Lists packages matching criteria"),
    ("Basics", "What is the go run command?", "Compiles and runs Go program"),
    ("Basics", "What is the go build command?", "Compiles packages and dependencies"),
    ("Basics", "What is the go install command?", "Compiles and installs packages"),
    ("Basics", "What is the go clean command?", "Removes compiled files"),
    ("Basics", "What is the go fmt command?", "Formats Go source code"),
    ("Basics", "What is the go vet command?", "Reports suspicious constructs"),
    ("Basics", "What is the go test command?", "Runs tests"),
    ("Basics", "What is the go tool command?", "Runs Go tools"),
    ("Basics", "What is the go generate command?", "Generates source code"),
    ("Basics", "What is the go get command?", "Downloads and installs packages (deprecated)"),
    ("Basics", "What is the go mod init command?", "Creates new go.mod file"),
    ("Basics", "What is the go mod download command?", "Downloads module dependencies"),
    ("Basics", "What is the go mod tidy command?", "Adds missing and removes unused modules"),
    ("Basics", "What is the go mod verify command?", "Verifies dependencies match go.sum"),
    ("Basics", "What is the go mod why command?", "Explains why packages are needed"),
    ("Basics", "What is the go mod graph command?", "Prints module dependency graph"),
    ("Basics", "What is the go mod vendor command?", "Creates vendor directory"),
    ("Basics", "What is the go mod edit command?", "Edits go.mod programmatically"),
    ("Basics", "What is the GOPATH environment variable?", "Go workspace directory"),
    ("Basics", "What is the GOPROXY environment variable?", "Go module proxy URL"),
    ("Basics", "What is the GONOSUMCHECK variable?", "Modules to skip checksum verification"),
    ("Basics", "What is the GONOSUMDB variable?", "Modules to skip sumdb checks"),
    ("Basics", "What is the GOINSECURE variable?", "Modules that bypass HTTPS"),
    ("Basics", "What is the GOFLAGS variable?", "Default go command flags"),
    ("Basics", "What is the GOROOT variable?", "Go installation directory"),
    ("Basics", "What is the GOBIN variable?", "Go binary installation directory"),
    ("Basics", "What is the GOPRIVATE variable?", "Private module patterns"),
    ("Basics", "What is the go.sum file?", "Module checksum file for integrity"),
    ("Basics", "What is the go.mod file?", "Module definition with dependencies"),
    ("Basics", "What is the GOWORK variable?", "Go workspace file path"),
    ("Basics", "What is the go.work file?", "Go workspace definition file"),
    ("Basics", "What is the build cache directory?", "Caches compiled artifacts"),
    ("Basics", "What is the test cache?", "Caches test results for unchanged code"),
    ("Basics", "What is the -count=1 flag?", "Disables test caching"),
    ("Basics", "What is the -run flag in tests?", "Runs specific test functions"),
    ("Basics", "What is the -bench flag?", "Runs benchmarks"),
    ("Basics", "What is the -coverprofile flag?", "Writes coverage to file"),
    ("Basics", "What is the -race flag?", "Enables data race detection"),
    ("Basics", "What is the -v flag in tests?", "Verbose test output"),
    ("Basics", "What is the -short flag?", "Runs tests in short mode"),
    ("Basics", "What is the testing.T type?", "Test context passed to test functions"),
    ("Basics", "What is the testing.B type?", "Benchmark context passed to benchmark functions"),
    ("Basics", "What is the testing.M type?", "Test main context for setup/teardown"),
    ("Basics", "What is the testing.TB interface?", "Shared interface for T and B"),
    ("Basics", "What is the Parallel tests?", "Runs tests in parallel"),
    ("Basics", "What is the TestMain function?", "Custom test setup and teardown"),
    ("Basics", "What is the Example function?", "Example test with output check"),
], "Junior", "Go")

# --- RUST (+50) ---
gen([
    ("Basics", "What is cargo new?", "Creates new Rust project"),
    ("Basics", "What is cargo init?", "Initializes Rust project in current directory"),
    ("Basics", "What is cargo build?", "Compiles project"),
    ("Basics", "What is cargo run?", "Compiles and runs project"),
    ("Basics", "What is cargo check?", "Checks code without producing binary"),
    ("Basics", "What is cargo test?", "Runs all tests"),
    ("Basics", "What is cargo bench?", "Runs benchmarks"),
    ("Basics", "What is cargo doc?", "Generates documentation"),
    ("Basics", "What is cargo publish?", "Publishes crate to crates.io"),
    ("Basics", "What is cargo install?", "Installs binary crate"),
    ("Basics", "What is cargo uninstall?", "Removes installed binary"),
    ("Basics", "What is cargo update?", "Updates dependencies"),
    ("Basics", "What is cargo search?", "Searches crates.io"),
    ("Basics", "What is cargo info?", "Shows crate information"),
    ("Basics", "What is cargo tree?", "Shows dependency tree"),
    ("Basics", "What is cargo outdated?", "Shows outdated dependencies"),
    ("Basics", "What is cargo audit?", "Checks for known vulnerabilities"),
    ("Basics", "What is cargo deny?", "License and vulnerability checker"),
    ("Basics", "What is cargo expand?", "Expands macros in source code"),
    ("Basics", "What is cargo watch?", "Runs command on file changes"),
    ("Basics", "What is cargo clippy?", "Runs linter"),
    ("Basics", "What is cargo fmt?", "Formats code with rustfmt"),
    ("Basics", "What is cargo fix?", "Auto-fixes compiler warnings"),
    ("Basics", "What is cargo add?", "Adds dependency to Cargo.toml"),
    ("Basics", "What is cargo remove?", "Removes dependency from Cargo.toml"),
    ("Basics", "What is cargo edit?", "Edits Cargo.toml (deprecated)"),
    ("Basics", "What is cargo generate?", "Generates project from template"),
    ("Basics", "What is cargo make?", "Task runner for Rust"),
    ("Basics", "What is cargo-release?", "Release automation tool"),
    ("Basics", "What is Cargo.toml?", "Project manifest with metadata and dependencies"),
    ("Basics", "What is Cargo.lock?", "Dependency lockfile for reproducible builds"),
    ("Basics", "What is the [dependencies] section?", "Lists crate dependencies"),
    ("Basics", "What is the [dev-dependencies] section?", "Dependencies for tests only"),
    ("Basics", "What is the [build-dependencies] section?", "Dependencies for build scripts"),
    ("Basics", "What is the [features] section?", "Feature flags for conditional compilation"),
    ("Basics", "What is the [profile] section?", "Compiler optimization profiles"),
    ("Basics", "What is the [workspace] section?", "Multi-crate workspace configuration"),
    ("Basics", "What is the [lib] section?", "Library target configuration"),
    ("Basics", "What is the [[bin]] section?", "Binary target configuration"),
    ("Basics", "What is the edition field?", "Rust edition: 2015, 2018, 2021"),
    ("Basics", "What is the version field?", "Crate version (semver)"),
    ("Basics", "What is the description field?", "Short crate description"),
    ("Basics", "What is the license field?", "Crate license identifier"),
    ("Basics", "What is the repository field?", "Source repository URL"),
    ("Basics", "What is the documentation field?", "Docs.rs URL (auto-generated)"),
    ("Basics", "What is the categories field?", "Crate categories for crates.io"),
    ("Basics", "What is the keywords field?", "Search keywords for crates.io"),
    ("Basics", "What is the readme field?", "Readme file path"),
    ("Basics", "What is the homepage field?", "Project homepage URL"),
], "Junior", "Rust")

# --- REACT (+50) ---
gen([
    ("Hooks", "What is the useRef for DOM access?", "Accessing DOM elements directly"),
    ("Hooks", "What is the forwardRef + useImperativeHandle?", "Exposing custom methods via ref"),
    ("Hooks", "What is the useMemo for expensive computations?", "Memoizing computation results"),
    ("Hooks", "What is the useCallback for child props?", "Preventing unnecessary child re-renders"),
    ("Hooks", "What is the useEffect for data fetching?", "Fetching data on component mount"),
    ("Hooks", "What is the useEffect cleanup for intervals?", "Clearing timers on unmount"),
    ("Hooks", "What is the useReducer for complex state?", "State logic with reducer pattern"),
    ("Hooks", "What is the useContext for theming?", "Sharing theme across component tree"),
    ("Hooks", "What is the useDebugValue for custom hooks?", "Displaying custom hook info in DevTools"),
    ("Hooks", "What is the useDeferredValue for expensive renders?", "Deferring rendering of slow parts"),
    ("Hooks", "What is the useTransition for UX?", "Keeping UI responsive during updates"),
    ("Hooks", "What is the useId for accessibility?", "Generating unique IDs for aria-*"),
    ("Hooks", "What is the useSyncExternalStore for external state?", "Subscribing to external stores"),
    ("Hooks", "What is the useInsertionEffect for CSS-in-JS?", "Injecting styles before layout"),
    ("Hooks", "What is the useEffectEvent (experimental)?", "Extracting non-reactive logic from effects"),
    ("Hooks", "What is the useOptimistic for mutations?", "Optimistic state updates before server"),
    ("Hooks", "What is the useFormStatus hook?", "Reading parent form submission status"),
    ("Hooks", "What is the useFormState hook?", "Managing form state with server actions"),
    ("Hooks", "What is the use hook for contexts?", "Reading context outside JSX"),
    ("Hooks", "What is the use hook for promises?", "Suspending with promise directly"),
    ("State", "What is the Zustand store creation?", "Creating store with create function"),
    ("State", "What is the Zustand selector?", "Selecting partial state for performance"),
    ("State", "What is the Zustand subscribe?", "Subscribing to store outside React"),
    ("State", "What is the Jotai atom?", "Atom unit for state management"),
    ("State", "What is the Jotai derived atom?", "Atom computed from other atoms"),
    ("State", "What is the Jotai atomWithStorage?", "Persistent atom with localStorage"),
    ("State", "What is the Recoil atom?", "State atom in Recoil"),
    ("State", "What is the Recoil selector?", "Derived state in Recoil"),
    ("State", "What is the Recoil useRecoilState?", "State hook in Recoil"),
    ("State", "What is the Redux Toolkit createAsyncThunk?", "Async thunk with lifecycle actions"),
    ("State", "What is the Redux Toolkit createEntityAdapter?", "Normalized state management"),
    ("State", "What is the Redux Toolkit RTK Query?", "Data fetching and caching solution"),
    ("State", "What is the RTK Query createApi?", "API definition with endpoints"),
    ("State", "What is the RTK Query useQuery?", "Auto-fetching hook for queries"),
    ("State", "What is the RTK Query useMutation?", "Data mutation hook"),
    ("State", "What is the RTK Query tag system?", "Cache invalidation via tags"),
    ("State", "What is the MobX observable?", "Observable state in MobX"),
    ("State", "What is the MobX action?", "State mutation in MobX"),
    ("State", "What is the MobX computed?", "Derived values in MobX"),
    ("State", "What is the MobX reaction?", "Side effects on state changes"),
    ("State", "What is the MobX React observer?", "React integration with MobX"),
    ("State", "What is the Valtio proxy?", "Mutable state proxy in Valtio"),
    ("State", "What is the Valtio snapshot?", "Immutable snapshot of proxy state"),
    ("State", "What is the useSyncExternalStore with Zustand?", "Using external stores in React 18"),
    ("State", "What is the Pinia store?", "Vue-like state management for React"),
    ("State", "What is the XState state machine?", "Finite state machines in React"),
    ("State", "What is the XState actors?", "Actor model implementation"),
    ("State", "What is the TanStack Query (React Query)?", "Server state management library"),
    ("State", "What is the TanStack Query queryKey?", "Unique identifier for queries"),
    ("State", "What is the TanStack Query queryClient?", "Client instance for managing queries"),
    ("State", "What is the TanStack Query useQueryClient?", "Accessing query client from hooks"),
], "Senior", "React")

# --- KOTLIN (+50) ---
gen([
    ("Coroutines", "What is the Flow collect vs collectLatest?", "collectLatest cancels previous collector"),
    ("Coroutines", "What is the Flow first terminal operator?", "Returns first element and cancels flow"),
    ("Coroutines", "What is the Flow single terminal operator?", "Returns single element or throws"),
    ("Coroutines", "What is the Flow reduce terminal operator?", "Accumulates to single result"),
    ("Coroutines", "What is the Flow fold terminal operator?", "Accumulates with seed value"),
    ("Coroutines", "What is the Flow count terminal operator?", "Counts elements matching predicate"),
    ("Coroutines", "What is the Flow toCollection terminal?", "Collects to mutable collection"),
    ("Coroutines", "What is the Flow toList terminal?", "Collects to list"),
    ("Coroutines", "What is the Flow toSet terminal?", "Collects to set"),
    ("Coroutines", "What is the Flow catching exceptions?", "Using catch operator for error handling"),
    ("Coroutines", "What is the Flow retry operator?", "Retries on exception"),
    ("Coroutines", "What is the Flow retryWhen operator?", "Retries with custom condition"),
    ("Coroutines", "What is the Flow cancellable operator?", "Makes flow check cancellation"),
    ("Coroutines", "What is the Flow safeFlow builder?", "Flow builder with cancellation check"),
    ("Coroutines", "What is the SharedFlow replay cache?", "Replays N most recent values to new collectors"),
    ("Coroutines", "What is the SharedFlow extraBufferCapacity?", "Extra buffer on top of replay"),
    ("Coroutines", "What is the SharedFlow onBufferOverflow?", "Strategy when buffer overflows: DROP_OLDEST, DROP_LATEST, SUSPEND"),
    ("Coroutines", "What is the StateFlow vs SharedFlow?", "StateFlow has current value; SharedFlow is event-like"),
    ("Coroutines", "What is the MutableStateFlow.value?", "Current value property"),
    ("Coroutines", "What is the StateFlow.value threading?", "Thread-safe value access and update"),
    ("Coroutines", "What is the Flow asStateFlow?", "Exposes mutable flow as read-only StateFlow"),
    ("Coroutines", "What is the Flow asSharedFlow?", "Exposes mutable flow as read-only SharedFlow"),
    ("Coroutines", "What is the Channel conflation?", "Channel keeping only the latest value"),
    ("Coroutines", "What is the Channel asReceiveChannel?", "Using channel as receive channel"),
    ("Coroutines", "What is the produce function overloads?", "Produce with dispatcher and capacity"),
    ("Coroutines", "What is the actor function overloads?", "Actor with dispatcher and capacity"),
    ("Coroutines", "What is the coroutineScope vs supervisorScope?", "supervisorScope isolates child failures"),
    ("Coroutines", "What is the withContext(NonCancellable)?", "Runs block with non-cancellable context"),
    ("Coroutines", "What is the Dispatchers.Default parallelism?", "Number of threads equals CPU cores"),
    ("Coroutines", "What is the Dispatchers.IO max threads?", "Limited to 64 or configured value"),
    ("Coroutines", "What is the limitedParallelism on dispatcher?", "Creates dispatcher with limited parallelism"),
    ("Coroutines", "What is the ThreadPoolExecutor to dispatcher?", "Converting executor to coroutine dispatcher"),
    ("Coroutines", "What is the rxJava2 coroutine integration?", "RxJava2 to coroutines interop"),
    ("Coroutines", "What is the Guava Future to coroutine?", "Guava ListenableFuture to Deferred"),
    ("Coroutines", "What is the awaitClose in callbackFlow?", "Callback registration in callbackFlow"),
    ("Coroutines", "What is the trySend vs offer in channels?", "trySend replaces deprecated offer"),
    ("Coroutines", "What is the tryReceive vs poll?", "tryReceive replaces deprecated poll"),
    ("Coroutines", "What is the ChannelResult type?", "Result of channel operation: success or closed"),
    ("Coroutines", "What is the ClosedSendChannelException?", "Thrown when sending to closed channel"),
    ("Coroutines", "What is the ClosedReceiveChannelException?", "Thrown when receiving from closed channel"),
    ("Coroutines", "What is the Job.invokeOnCompletion?", "Callback when job completes"),
    ("Coroutines", "What is the Deferred.isCompleted?", "Checks if deferred has completed"),
    ("Coroutines", "What is the Deferred.isCancelled?", "Checks if deferred is cancelled"),
    ("Coroutines", "What is the Job.children.forEach?", "Iterating over child jobs"),
    ("Coroutines", "What is the yield vs ensureActive?", "yield gives up thread; ensureActive checks cancellation"),
    ("Coroutines", "What is the currentCoroutineContext()?", "Returns current coroutine context"),
    ("Coroutines", "What is the coroutineContext[Job]?", "Accessing Job from coroutine context"),
    ("Coroutines", "What is the + operator for contexts?", "Combining context elements"),
    ("Coroutines", "What is the EmptyCoroutineContext?", "Default empty context"),
], "Senior", "Kotlin")

# --- GENERAL (+90) ---
gen([
    ("System Design", "What is the CAP theorem in practice?", "Tradeoff choice between CP and AP during partition"),
    ("System Design", "What is the PACELC in practice?", "Tradeoff between latency and consistency"),
    ("System Design", "What is the CRDT (Conflict-free Replicated Data Type)?", "Data type that resolves conflicts automatically"),
    ("System Design", "What is the OT (Operational Transformation)?", "Conflict resolution for collaborative editing"),
    ("System Design", "What is the vector clock?", "Tracking causality in distributed systems"),
    ("System Design", "What is the Lamport timestamp?", "Logical clock for event ordering"),
    ("System Design", "What is the hybrid logical clock?", "Combining physical and logical clocks"),
    ("System Design", "What is the Google Spanner?", "Globally distributed strongly consistent database"),
    ("System Design", "What is the TrueTime API?", "Google's synchronized clock with bounded uncertainty"),
    ("System Design", "What is the CockroachDB?", "Distributed SQL database inspired by Spanner"),
    ("System Design", "What is the YugabyteDB?", "Distributed SQL database for cloud-native apps"),
    ("System Design", "What is the TiDB?", "Distributed HTAP database compatible with MySQL"),
    ("System Design", "What is the Vitess?", "Database clustering system for horizontal scaling MySQL"),
    ("System Design", "What is the Cassandra database?", "Distributed wide-column NoSQL database"),
    ("System Design", "What is the Cassandra partition key?", "Determines data distribution across nodes"),
    ("System Design", "What is the Cassandra consistency level?", "ONE, QUORUM, ALL, LOCAL_QUORUM, etc."),
    ("System Design", "What is the Cassandra compaction?", "Merging SSTables for performance"),
    ("System Design", "What is the Cassandra hinted handoff?", "Temporary write storage for down nodes"),
    ("System Design", "What is the Cassandra gossip protocol?", "Node discovery and state dissemination"),
    ("System Design", "What is the Cassandra read repair?", "Fixing inconsistencies on read path"),
    ("System Design", "What is the MongoDB document model?", "JSON-like documents with flexible schema"),
    ("System Design", "What is the MongoDB replica set?", "Replica set with primary and secondaries"),
    ("System Design", "What is the MongoDB sharding?", "Horizontal scaling with shard key"),
    ("System Design", "What is the MongoDB aggregation pipeline?", "Data processing pipeline stages"),
    ("System Design", "What is the MongoDB change streams?", "Real-time data change notifications"),
    ("System Design", "What is the MongoDB index types?", "Single, compound, multikey, text, geospatial, hashed"),
    ("System Design", "What is the MongoDB transactions?", "Multi-document ACID transactions"),
    ("System Design", "What is the Couchbase database?", "Distributed NoSQL with memory-first architecture"),
    ("System Design", "What is the Couchbase N1QL?", "SQL-like query language for JSON"),
    ("System Design", "What is the Neo4j graph database?", "Property graph database with Cypher query language"),
    ("System Design", "What is the Cypher query language?", "Declarative graph query language"),
    ("System Design", "What is the ArangoDB multi-model?", "Document, graph, and key-value in one database"),
    ("System Design", "What is the InfluxDB time-series database?", "Purpose-built time series database"),
    ("System Design", "What is the TimescaleDB?", "Time-series extension for PostgreSQL"),
    ("System Design", "What is the ClickHouse?", "Column-oriented OLAP database"),
    ("System Design", "What is the Druid real-time analytics?", "High-performance OLAP data store"),
    ("System Design", "What is the Presto/Trino query engine?", "Distributed SQL query engine for data lakes"),
    ("System Design", "What is the Apache Spark?", "Unified analytics engine for big data processing"),
    ("System Design", "What is the Spark RDD?", "Resilient Distributed Dataset"),
    ("System Design", "What is the Spark DataFrame?", "Distributed data collection with schema"),
    ("System Design", "What is the Spark SQL?", "SQL queries on Spark DataFrames"),
    ("System Design", "What is the Spark streaming?", "Stream processing with micro-batches"),
    ("System Design", "What is the Apache Flink?", "Stream processing framework with event-time semantics"),
    ("System Design", "What is the Apache Beam?", "Unified batch and stream processing model"),
    ("System Design", "What is the Apache Airflow?", "Workflow orchestration with DAGs"),
    ("System Design", "What is the Prefect workflow?", "Modern workflow orchestration platform"),
    ("System Design", "What is the Dagster pipeline?", "Data orchestration with asset awareness"),
    ("System Design", "What is the dbt (data build tool)?", "SQL-first transformation tool for analytics"),
    ("System Design", "What is the looker analytics platform?", "Business intelligence and data exploration"),
    ("System Design", "What is the Metabase BI tool?", "Open-source business intelligence tool"),
    ("System Design", "What is the Superset BI tool?", "Apache data exploration and visualization"),
    ("System Design", "What is the Redash BI tool?", "Open-source data visualization and dashboard"),
    ("System Design", "What is the Tableau BI tool?", "Enterprise visual analytics platform"),
    ("System Design", "What is the Power BI tool?", "Microsoft business analytics service"),
    ("System Design", "What is the Qlik BI tool?", "Associative data indexing BI platform"),
    ("System Design", "What is the Sigma BI tool?", "Spreadsheet-like BI for cloud data warehouses"),
    ("System Design", "What is the Snowflake data warehouse?", "Cloud data warehouse with separated storage and compute"),
    ("System Design", "What is the Snowflake clustering?", "Micro-partition clustering for query performance"),
    ("System Design", "What is the Snowflake time travel?", "Accessing historical data up to 90 days"),
    ("System Design", "What is the Snowflake zero-copy cloning?", "Instant database clones without extra storage"),
    ("System Design", "What is the Snowflake data sharing?", "Sharing data without copying"),
    ("System Design", "What is the BigQuery data warehouse?", "Google's serverless data warehouse"),
    ("System Design", "What is the BigQuery slots?", "Compute capacity unit for BigQuery"),
    ("System Design", "What is the BigQuery partitioning?", "Partitioning by date, integer, or ingestion time"),
    ("System Design", "What is the BigQuery clustering?", "Sort-based clustering for query optimization"),
    ("System Design", "What is the Redshift data warehouse?", "AWS petabyte-scale data warehouse"),
    ("System Design", "What is the Redshift distribution style?", "KEY, ALL, EVEN distribution across nodes"),
    ("System Design", "What is the Redshift sort key?", "Compound or interleaved sort keys"),
    ("System Design", "What is the Synapse Analytics?", "Azure limitless analytics platform"),
    ("System Design", "What is the Databricks lakehouse?", "Unified data, analytics, and AI platform"),
    ("System Design", "What is the Delta Lake format?", "ACID transactions on data lakes with Parquet"),
    ("System Design", "What is the Apache Iceberg format?", "Open table format for large analytic datasets"),
    ("System Design", "What is the Apache Hudi format?", "Incremental processing on data lakes"),
    ("System Design", "What is the Parquet file format?", "Columnar storage format for analytics"),
    ("System Design", "What is the ORC file format?", "Optimized Row Columnar format"),
    ("System Design", "What is the Avro file format?", "Row-based serialization format"),
    ("System Design", "What is the Arrow columnar format?", "In-memory columnar format for analytics"),
    ("System Design", "What is the Flight SQL protocol?", "High-performance database protocol using Arrow"),
    ("System Design", "What is the DuckDB embedded database?", "In-process OLAP database for analytics"),
    ("System Design", "What is the SQLite embedded database?", "Embedded SQL database engine"),
    ("System Design", "What is the Protocol Buffers (protobuf)?", "Binary serialization format from Google"),
    ("System Design", "What is the FlatBuffers?", "Zero-copy serialization by Google"),
    ("System Design", "What is the Cap'n Proto?", "Fast data interchange format"),
    ("System Design", "What is the MessagePack?", "Efficient binary JSON-like format"),
    ("System Design", "What is the BSON format?", "Binary JSON used by MongoDB"),
    ("System Design", "What is the CBOR format?", "Concise Binary Object Representation"),
    ("System Design", "What is the YAML vs JSON vs TOML?", "YAML: human-readable; JSON: common; TOML: ini-like config"),
    ("System Design", "What is the TOML format?", "Minimal configuration file format"),
    ("System Design", "What is the ini file format?", "Legacy configuration format with sections"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + ''.join(new) + after)
print(f"Batch 14 added {len(new)} questions.")