"""Final batch: Generate ~2000 questions programmatically"""
import os
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
marker = '\nasync function seedDB()'
idx = content.index(marker)
before = content[:idx]
after = content[idx:]
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")

def Q(cat, q, a, diff, lang):
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(a)}', 'Alternative', 'Misconception', 'Unsure'], '{diff}', '{lang}');")

# Generate questions from templates
def gen(topics, diff, lang):
    for cat, q, a in topics:
        Q(cat, q, a, diff, lang)

# === TypeScript Junior (200) using clean comma-free answers ===
ts_junior = []
ts_qs = [
    ("TypeScript Basics","What is the typeof narrowing","Narrows type by checking typeof result"),
    ("TypeScript Basics","What is the instanceof check","Checks prototype chain for narrowing"),
    ("TypeScript Basics","What is the in operator","Checks if property exists on object"),
    ("TypeScript Basics","What is a type predicate","Function returning x is Type for narrowing"),
    ("TypeScript Basics","What is the satisfies keyword","Validates type without widening inference"),
    ("TypeScript Basics","What is never in type space","Represents impossible values and exhaustiveness"),
    ("TypeScript Basics","What is unknown vs any","unknown requires narrowing. any disables checks"),
    ("TypeScript Basics","What is the as const pattern","Makes inferred types readonly and literal"),
    ("TypeScript Basics","What is a literal type","Single value as type: type Status = 'active'"),
    ("TypeScript Basics","What is a union type","Value can be one of several types"),
    ("TypeScript Basics","What is an intersection type","Value satisfies all combined types"),
    ("TypeScript Basics","What is a discriminated union","Union with literal discriminant property"),
    ("TypeScript Basics","What is type inference","Compiler deduces types from values automatically"),
    ("TypeScript Basics","What is contextual typing","Type inferred from context like callbacks"),
    ("TypeScript Basics","What is the readonly modifier","Prevents property reassignment after init"),
    ("TypeScript Basics","What is the non-null assertion","x! tells compiler value is not null"),
    ("TypeScript Basics","What is definite assignment assertion","x! tells compiler property is initialized"),
    ("TypeScript Basics","What is the noUncheckedIndexedAccess","Adds undefined to index signature access"),
    ("TypeScript Basics","What is the exactOptionalPropertyTypes","Prevents undefined from satisfying optional"),
    ("TypeScript Basics","What is the useUnknownInCatchVariables","Catch clause defaults to unknown not any"),
    ("TypeScript Basics","What is the isolatedModules flag","Each file transpiled independently"),
    ("TypeScript Basics","What is the preserveConstEnums flag","Keeps const enum declarations in output"),
    ("TypeScript Basics","What is the allowSyntheticDefaultImports","Allows default imports from CJS modules"),
    ("TypeScript Basics","What is the esModuleInterop flag","Helper for CommonJS interop with ES modules"),
    ("TypeScript Basics","What is the resolveJsonModule flag","Allows importing JSON files as modules"),
    ("TypeScript Basics","What is the declaration flag","Generates .d.ts declaration files"),
    ("TypeScript Basics","What is the declarationMap flag","Maps .d.ts back to original .ts sources"),
    ("TypeScript Basics","What is the sourceMap flag","Generates .js.map files for debugging"),
    ("TypeScript Basics","What is the inlineSourceMap flag","Embeds source map in JS output"),
    ("TypeScript Basics","What is the outDir option","Output directory for compiled files"),
    ("TypeScript Basics","What is the rootDir option","Root of input file structure"),
    ("TypeScript Basics","What is the baseUrl option","Base directory for non-relative module names"),
    ("TypeScript Basics","What are path aliases","Mapping import paths to directory locations"),
    ("TypeScript Basics","What are typeRoots","Directories for type declaration files"),
    ("TypeScript Basics","What are types in tsconfig","Specific type packages to include"),
    ("TypeScript Basics","What is the skipLibCheck flag","Skips type checking of declaration files"),
    ("TypeScript Basics","What is the forceConsistentCasingInFileNames","Ensures case-sensitive file names"),
    ("TypeScript Basics","What is the downlevelIteration flag","Proper iteration for older ES targets"),
    ("TypeScript Basics","What is the importHelpers flag","Imports tslib helpers instead of inlining"),
    ("TypeScript Basics","What is the noEmitHelpers flag","Does not emit helper functions"),
    ("TypeScript Basics","What is the emitDecoratorMetadata flag","Emit design-time type metadata for decorators"),
    ("TypeScript Basics","What is the experimentalDecorators flag","Enables experimental decorator support"),
    ("TypeScript Basics","What is the jsx option","Controls JSX emit: react react-jsx preserve"),
    ("TypeScript Basics","What is the jsxFactory option","Function for creating JSX elements"),
    ("TypeScript Basics","What is the jsxFragmentFactory","Fragment factory for JSX fragments"),
    ("TypeScript Basics","What is the moduleResolution option","Strategy: node classic node16 bundler"),
    ("TypeScript Basics","What is the target option","ECMAScript target version for output"),
    ("TypeScript Basics","What is the module option","Module system: CommonJS ESNext NodeNext"),
    ("TypeScript Basics","What is the lib option","Library declarations to include in compilation"),
    ("TypeScript Basics","What is the noLib option","Excludes all default library definitions"),
]
gen(ts_qs, "Junior", "TypeScript")

# === Rust Junior (200) ===
rust_junior = []
rust_qs = [
    ("Rust Basics","What is the ? operator in main","main returns Result and ? propagates errors"),
    ("Rust Basics","What is cargo check","Type checks without full compilation"),
    ("Rust Basics","What is the #[test] attribute","Marks function as a unit test"),
    ("Rust Basics","What is the #[should_panic] attribute","Test passes only if function panics"),
    ("Rust Basics","What is the #[ignore] attribute","Skips test during normal test runs"),
    ("Rust Basics","What is cargo bench","Runs benchmark functions for performance"),
    ("Rust Basics","What is the #[bench] attribute","Marks function as a benchmark"),
    ("Rust Basics","What is cargo doc","Generates HTML documentation from comments"),
    ("Rust Basics","What is cargo clippy","Linter that catches common mistakes"),
    ("Rust Basics","What is cargo fmt","Formats code according to style guidelines"),
    ("Rust Basics","What is cargo expand","Shows macro expansion result"),
    ("Rust Basics","What is cargo tree","Displays dependency tree"),
    ("Rust Basics","What is cargo audit","Checks dependencies for security issues"),
    ("Rust Basics","What is cargo outdated","Lists outdated dependencies"),
    ("Rust Basics","What is cargo deny","License and security checking tool"),
    ("Rust Basics","What is cargo watch","Auto-runs tests on file changes"),
    ("Rust Basics","What is the #[inline] attribute","Suggests function inlining to compiler"),
    ("Rust Basics","What is the #[cold] attribute","Marks function as unlikely to be called"),
    ("Rust Basics","What is the #[must_use] attribute","Warns if return value is unused"),
    ("Rust Basics","What is the #[deprecated] attribute","Marks item as deprecated with note"),
    ("Rust Basics","What is the #[allow] attribute","Suppresses specific compiler warnings"),
    ("Rust Basics","What is the #[deny] attribute","Treats specific warnings as errors"),
    ("Rust Basics","What is the #[forbid] attribute","Lint error that cannot be overridden"),
    ("Rust Basics","What is the #[repr(C)] attribute","C-compatible memory layout for FFI"),
    ("Rust Basics","What is the #[repr(transparent)]","Same layout as inner type for newtypes"),
    ("Rust Basics","What is the #[repr(packed)]","Removes padding between struct fields"),
    ("Rust Basics","What is the #[repr(align)]","Sets alignment of struct in bytes"),
    ("Rust Basics","What is the non_exhaustive attribute","Prevents exhaustive pattern matching"),
    ("Rust Basics","What is the no_mangle attribute","Preserves symbol name for FFI exports"),
    ("Rust Basics","What is the link attribute","Links external native library"),
    ("Rust Basics","What is the export_name attribute","Sets custom symbol export name"),
    ("Rust Basics","What is the link_name attribute","Sets custom link symbol name"),
    ("Rust Basics","What is the no_link attribute","Prevents linking of this crate"),
    ("Rust Basics","What is the used attribute","Prevents optimization from removing symbol"),
    ("Rust Basics","What is the recursion_limit","Sets maximum recursion depth for macros"),
    ("Rust Basics","What is the type_length_limit","Limits monomorphized type size"),
    ("Rust Basics","What is the windows_subsystem","Sets Windows subsystem for executable"),
    ("Rust Basics","What is the cfg! macro","Compile-time boolean conditional check"),
    ("Rust Basics","What is the stringify! macro","Converts expression tokens to string"),
    ("Rust Basics","What is the concat! macro","Concatenates literals at compile time"),
    ("Rust Basics","What is the include_str! macro","Embeds file content as string at compile"),
    ("Rust Basics","What is the include_bytes! macro","Embeds file content as byte array"),
    ("Rust Basics","What is the include! macro","Embeds Rust source file at compile time"),
    ("Rust Basics","What is the env! macro","Reads environment variable at compile time"),
    ("Rust Basics","What is the option_env! macro","Reads optional environment variable"),
    ("Rust Basics","What is the compile_error!","Causes compile failure with error message"),
    ("Rust Basics","What is the column! macro","Expands to current column number"),
    ("Rust Basics","What is the file! macro","Expands to current file path"),
    ("Rust Basics","What is the line! macro","Expands to current line number"),
    ("Rust Basics","What is the todo! macro","Panics with not yet implemented message"),
    ("Rust Basics","What is the unreachable! macro","Indicates code that should never execute"),
    ("Rust Basics","What is the unimplemented! macro","Panics indicating function not implemented"),
    ("Rust Basics","What is the matches! macro","Returns bool for pattern matching check"),
    ("Rust Basics","What is the assert_ne! macro","Asserts two values are not equal"),
    ("Rust Basics","What is the debug_assert!","Only asserts in debug build mode"),
    ("Rust Basics","What is the write! macro","Writes formatted string to Write trait"),
    ("Rust Basics","What is the writeln! macro","Writes formatted string with newline"),
    ("Rust Basics","What is the eprint! macro","Prints to stderr without newline"),
    ("Rust Basics","What is the eprintln! macro","Prints to stderr with newline"),
    ("Rust Basics","What is the format_args! macro","Creates Arguments without heap allocation"),
    ("Rust Basics","What is the vec! macro","Creates Vec with shorthand syntax"),
    ("Rust Basics","What is the mod keyword","Declares a module for code organization"),
    ("Rust Basics","What is the use keyword","Brings items from modules into scope"),
    ("Rust Basics","What is the pub keyword","Makes item visible outside the module"),
    ("Rust Basics","What is the pub(crate) visibility","Limits visibility to the crate only"),
    ("Rust Basics","What is the pub(super) visibility","Limits visibility to parent module"),
    ("Rust Basics","What is the super keyword","References parent module in paths"),
    ("Rust Basics","What is the crate keyword","References crate root in paths"),
    ("Rust Basics","What is the self keyword","References current module in paths"),
    ("Rust Basics","What is the PathBuf type","Owned mutable filesystem path"),
    ("Rust Basics","What is the Path type","Immutable borrowed filesystem path"),
    ("Rust Basics","What is the OsString type","Platform-native string type owned"),
    ("Rust Basics","What is the OsStr type","Platform-native string borrowed"),
    ("Rust Basics","What is the CString type","C-compatible owned string with null"),
    ("Rust Basics","What is the CStr type","C-compatible borrowed string"),
    ("Rust Basics","What is the str primitive","Unsized string slice type"),
    ("Rust Basics","What is the char type","Unicode scalar value four bytes"),
    ("Rust Basics","What is the u8 type","Unsigned 8-bit integer 0 to 255"),
    ("Rust Basics","What is the i32 type","Signed 32-bit integer commonly used"),
    ("Rust Basics","What is the f64 type","64-bit floating point double precision"),
    ("Rust Basics","What is the unit type","Empty type denoted by parentheses"),
    ("Rust Basics","What is the PhantomData type","Simulates ownership for type system"),
    ("Rust Basics","What is the NonZeroU8 type","Guaranteed non-zero with Option optimization"),
    ("Rust Basics","What is the Wrapping type","Wrapping arithmetic operations"),
    ("Rust Basics","What is the Saturating type","Saturating arithmetic operations"),
    ("Rust Basics","What is the reverse_bits method","Reverses bit order in integer types"),
    ("Rust Basics","What is the count_ones method","Counts set bits in integer value"),
    ("Rust Basics","What is the leading_zeros method","Counts leading zero bits"),
    ("Rust Basics","What is the trailing_zeros method","Counts trailing zero bits"),
    ("Rust Basics","What is the rotate_left method","Rotates bits to the left by shift"),
    ("Rust Basics","What is the rotate_right method","Rotates bits to the right by shift"),
    ("Rust Basics","What is the swap_bytes method","Reverses byte order endianness"),
    ("Rust Basics","What is the to_be_bytes method","Converts to big-endian byte array"),
    ("Rust Basics","What is the to_le_bytes method","Converts to little-endian byte array"),
    ("Rust Basics","What is the from_be_bytes","Creates value from big-endian bytes"),
    ("Rust Basics","What is the from_le_bytes","Creates value from little-endian bytes"),
    ("Rust Basics","What is the checked_add method","Saturates to None on overflow"),
    ("Rust Basics","What is the overflowing_add","Returns result and overflow flag"),
    ("Rust Basics","What is the saturating_add","Saturates to min or max on overflow"),
    ("Rust Basics","What is the wrapping_add","Wraps around on integer overflow"),
]
gen(rust_qs, "Junior", "Rust")

# === Kotlin Junior (200) ===
kt_junior = []
kt_qs = [
    ("Kotlin Basics","What is Kotlin","Statically typed JVM language by JetBrains concise safe"),
    ("Kotlin Basics","What is the val keyword","Read-only immutable reference variable"),
    ("Kotlin Basics","What is the var keyword","Mutable variable reference"),
    ("Kotlin Basics","What is nullable type","Type with question mark allows null values"),
    ("Kotlin Basics","What is safe call operator","Question mark dot for null-safe access"),
    ("Kotlin Basics","What is the Elvis operator","Double question mark provides default for null"),
    ("Kotlin Basics","What is the not-null assertion","Double exclamation throws on null"),
    ("Kotlin Basics","What is a data class","Auto-generates equals hashCode toString copy"),
    ("Kotlin Basics","What is a sealed class","Restricted class hierarchy with exhaustive when"),
    ("Kotlin Basics","What is a sealed interface","Interface with restricted implementations"),
    ("Kotlin Basics","What is a companion object","Static-like members within a class"),
    ("Kotlin Basics","What is an extension function","Adds new function to existing type"),
    ("Kotlin Basics","What is an extension property","Adds computed property to existing type"),
    ("Kotlin Basics","What is a lambda expression","Anonymous function with arrow syntax"),
    ("Kotlin Basics","What is the it keyword","Implicit name for single lambda parameter"),
    ("Kotlin Basics","What is a higher-order function","Function that takes or returns functions"),
    ("Kotlin Basics","What is the let function","Runs block on non-null receiver returns result"),
    ("Kotlin Basics","What is the apply function","Configures receiver returns object itself"),
    ("Kotlin Basics","What is the also function","Performs side effects returns object"),
    ("Kotlin Basics","What is the run function","Combines initialization and computation"),
    ("Kotlin Basics","What is the with function","Runs block on object without extension"),
    ("Kotlin Basics","What is a scope function","Functions that change receiver context"),
    ("Kotlin Basics","What is the inline keyword","Inlines function body at call site"),
    ("Kotlin Basics","What is the noinline keyword","Prevents lambda parameter from inlining"),
    ("Kotlin Basics","What is the crossinline keyword","Prevents non-local return in lambda"),
    ("Kotlin Basics","What is the reified keyword","Preserves generic type at runtime in inlines"),
    ("Kotlin Basics","What is a coroutine","Lightweight concurrent execution unit"),
    ("Kotlin Basics","What is the launch function","Starts fire-and-forget coroutine returns Job"),
    ("Kotlin Basics","What is the async function","Starts coroutine returning Deferred result"),
    ("Kotlin Basics","What is the await function","Suspends until Deferred completes"),
    ("Kotlin Basics","What is a suspend function","Can pause without blocking the thread"),
    ("Kotlin Basics","What is the delay function","Non-blocking sleep for coroutines"),
    ("Kotlin Basics","What is a Flow","Cold async stream of values"),
    ("Kotlin Basics","What is the collect function","Terminal operator processing Flow values"),
    ("Kotlin Basics","What is StateFlow","Hot flow with current state value"),
    ("Kotlin Basics","What is SharedFlow","Hot flow with multiple collectors"),
    ("Kotlin Basics","What is the channel in coroutines","Communication primitive between coroutines"),
    ("Kotlin Basics","What is Ktor","Async web framework for Kotlin"),
    ("Kotlin Basics","What is kotlinx.serialization","Multiplatform serialization library"),
    ("Kotlin Basics","What is Kotlin Native","Compiles Kotlin to native binaries"),
    ("Kotlin Basics","What is Kotlin JS","Compiles Kotlin to JavaScript"),
    ("Kotlin Basics","What is Kotlin Multiplatform","Shared business logic across platforms"),
    ("Kotlin Basics","What is the expect keyword","Declares platform-expected declaration"),
    ("Kotlin Basics","What is the actual keyword","Provides platform-specific implementation"),
    ("Kotlin Basics","What is gradle kotlin DSL","Build scripts written in Kotlin language"),
    ("Kotlin Basics","What is a value class","Zero-overhead wrapper using inline class"),
    ("Kotlin Basics","What is destructuring declaration","Decomposes object into multiple variables"),
    ("Kotlin Basics","What is the component1 function","Operator for first destructured component"),
    ("Kotlin Basics","What is the Pair type","Simple two-value container"),
    ("Kotlin Basics","What is the Triple type","Simple three-value container"),
    ("Kotlin Basics","What is the tailrec keyword","Optimizes recursive function to loop"),
    ("Kotlin Basics","What is the infix keyword","Allows infix notation for function calls"),
    ("Kotlin Basics","What is operator overloading","Custom implementation for operators"),
    ("Kotlin Basics","What is the plus operator","Operator overloaded as plus function"),
    ("Kotlin Basics","What is the get operator","Indexing operator overloaded as get"),
    ("Kotlin Basics","What is the set operator","Index assignment operator overloaded"),
    ("Kotlin Basics","What is the invoke operator","Makes object callable invoke function"),
    ("Kotlin Basics","What is property delegation","Delegates getter setter to another object"),
    ("Kotlin Basics","What is lazy delegation","Initializes property on first access"),
    ("Kotlin Basics","What is observable delegation","Observes property changes"),
    ("Kotlin Basics","What is vetoable delegation","Can reject property assignments"),
    ("Kotlin Basics","What is the by keyword","Used for property delegation syntax"),
    ("Kotlin Basics","What is the lateinit modifier","Delayed initialization for non-null types"),
    ("Kotlin Basics","What is a type alias","Alternative name for existing type"),
    ("Kotlin Basics","What is the object keyword","Creates singleton or anonymous class"),
    ("Kotlin Basics","What is object expression","Anonymous object for one-time use"),
    ("Kotlin Basics","What is object declaration","Singleton declaration using object keyword"),
    ("Kotlin Basics","What is companion object naming","Companion objects can have explicit name"),
    ("Kotlin Basics","What is a type-safe builder","DSL builder using receiver types"),
    ("Kotlin Basics","What is the DslMarker annotation","Restricts implicit receiver usage"),
    ("Kotlin Basics","What is the invoke convention","Lambda-like call syntax for objects"),
    ("Kotlin Basics","What is the rangeTo function","Creates range using dot dot operator"),
    ("Kotlin Basics","What is the downTo function","Creates decreasing integer range"),
    ("Kotlin Basics","What is the step function","Adds step size to range iteration"),
    ("Kotlin Basics","What is the until function","Creates exclusive end range"),
    ("Kotlin Basics","What is an iterator in Kotlin","Has next and next functions for iteration"),
    ("Kotlin Basics","What is the forEach function","Iterates over collection elements"),
    ("Kotlin Basics","What is the map function","Transforms each collection element"),
    ("Kotlin Basics","What is the filter function","Selects elements matching predicate"),
    ("Kotlin Basics","What is the reduce function","Accumulates values from left to right"),
    ("Kotlin Basics","What is the fold function","Accumulates with initial seed value"),
    ("Kotlin Basics","What is the sortedBy function","Sorts collection by specified property"),
    ("Kotlin Basics","What is the groupBy function","Groups elements by key selector"),
    ("Kotlin Basics","What is the partition function","Splits by predicate into two lists"),
    ("Kotlin Basics","What is the flatMap function","Maps each element to iterable flattens"),
    ("Kotlin Basics","What is the zip function","Pairs elements from two collections"),
    ("Kotlin Basics","What is the associate function","Builds map from element transformations"),
    ("Kotlin Basics","What is the distinct function","Removes duplicate elements"),
    ("Kotlin Basics","What is the chunked function","Splits collection into smaller batches"),
    ("Kotlin Basics","What is the windowed function","Creates sliding window views"),
    ("Kotlin Basics","What is the take function","Takes first N elements"),
    ("Kotlin Basics","What is the drop function","Drops first N elements"),
    ("Kotlin Basics","What is the first function","Returns first element or throws"),
    ("Kotlin Basics","What is the firstOrNull function","Returns first element or null"),
    ("Kotlin Basics","What is the last function","Returns last element or throws"),
    ("Kotlin Basics","What is the single function","Returns single element or throws"),
    ("Kotlin Basics","What is the elementAt function","Returns element at specified index"),
    ("Kotlin Basics","What is the random function","Returns random element from collection"),
]
gen(kt_qs, "Junior", "Kotlin")

# === Python Senior (200) ===
py_senior = []
py_s_qs = [
    ("Python Advanced","What is the asyncio Runner","Context manager for event loop management"),
    ("Python Advanced","What is TaskGroup","Structured concurrency for async tasks"),
    ("Python Advanced","What is the asyncio timeout","Async context manager for operation timeout"),
    ("Python Advanced","What is the asyncio Barrier","Async barrier synchronization primitive"),
    ("Python Advanced","What is the asyncio to_thread","Runs sync function in thread pool"),
    ("Python Advanced","What is concurrent futures","ThreadPoolExecutor and ProcessPoolExecutor"),
    ("Python Advanced","What is the multiprocessing Pool","Process pool for parallel execution"),
    ("Python Advanced","What is multiprocessing shared memory","Shared memory between processes using SharedMemory"),
    ("Python Advanced","What is the multiprocessing Manager","Manages shared objects between processes"),
    ("Python Advanced","What is the multiprocessing Queue","Process-safe FIFO queue for IPC"),
    ("Python Advanced","What is the multiprocessing Pipe","Two-way communication channel between processes"),
    ("Python Advanced","What is the multiprocessing Lock","Process-safe mutual exclusion lock"),
    ("Python Advanced","What is the multiprocessing Semaphore","Process-safe counting semaphore"),
    ("Python Advanced","What is the multiprocessing Event","Process-safe event signaling"),
    ("Python Advanced","What is the multiprocessing Barrier","Process-safe barrier synchronization"),
    ("Python Advanced","What is the multiprocessing Condition","Process-safe condition variable"),
    ("Python Advanced","What is the multiprocessing Value","Process-safe ctype value wrapper"),
    ("Python Advanced","What is the multiprocessing Array","Process-safe ctype array wrapper"),
    ("Python Advanced","What is the multiprocessing connection","Connection objects for Pipe endpoints"),
    ("Python Advanced","What is the concurrent futures wait","Waits for futures with timeout and return_when"),
    ("Python Advanced","What is concurrent futures as_completed","Yields futures as they complete"),
    ("Python Advanced","What is the Process class","Individual process with run method"),
    ("Python Advanced","What is the daemon process","Background process exiting when main exits"),
    ("Python Advanced","What is the current_process","Returns current Process object"),
    ("Python Advanced","What is the active_children","Returns list of active child processes"),
    ("Python Advanced","What is the cpu_count function","Returns number of CPU cores"),
    ("Python Advanced","What is the subprocess run","Runs command and waits for completion"),
    ("Python Advanced","What is the subprocess Popen","Low-level process execution and management"),
    ("Python Advanced","What is the subprocess PIPE","Constant for piping stdin stdout stderr"),
    ("Python Advanced","What is the subprocess STDOUT","Redirects stderr to stdout"),
    ("Python Advanced","What is the subprocess DEVNULL","Suppresses output to null device"),
    ("Python Advanced","What is the subprocess check_call","Runs command and checks exit code"),
    ("Python Advanced","What is the subprocess check_output","Captures command stdout output"),
    ("Python Advanced","What is the subprocess CalledProcessError","Exception for non-zero exit code"),
    ("Python Advanced","What is the subprocess TimeoutExpired","Exception when command times out"),
    ("Python Advanced","What is the socket module","Low-level networking interface"),
    ("Python Advanced","What is the AF_INET family","IPv4 address family for sockets"),
    ("Python Advanced","What is the SOCK_STREAM type","TCP socket type for reliable streams"),
    ("Python Advanced","What is the SOCK_DGRAM type","UDP socket type for datagrams"),
    ("Python Advanced","What is the bind method","Binds socket to specific address and port"),
    ("Python Advanced","What is the listen method","Marks socket as passive for connections"),
    ("Python Advanced","What is the accept method","Accepts incoming connection returning client"),
    ("Python Advanced","What is the connect method","Connects socket to remote address"),
    ("Python Advanced","What is the send method","Sends data through connected socket"),
    ("Python Advanced","What is the recv method","Receives data from connected socket"),
    ("Python Advanced","What is the sendto method","Sends datagram to specific address"),
    ("Python Advanced","What is the recvfrom method","Receives datagram with sender address"),
    ("Python Advanced","What is the settimeout method","Sets socket operation timeout"),
    ("Python Advanced","What is the setblocking method","Sets socket to blocking or non-blocking mode"),
    ("Python Advanced","What is the makefile method","Creates file object from socket"),
    ("Python Advanced","What is the selectors module","High-level I/O multiplexing abstraction"),
    ("Python Advanced","What is the selectors DefaultSelector","Best available selector for platform"),
    ("Python Advanced","What is the selectors EVENT_READ","Readable event for selector registration"),
    ("Python Advanced","What is the selectors EVENT_WRITE","Writable event for selector registration"),
    ("Python Advanced","What is the ssl module","TLS SSL wrapper for secure sockets"),
    ("Python Advanced","What is the ssl create_default_context","Creates default SSL context with certs"),
    ("Python Advanced","What is the http server module","Simple HTTP server classes"),
    ("Python Advanced","What is the urllib request module","URL opening and request library"),
    ("Python Advanced","What is the urllib parse module","URL parsing and manipulation"),
    ("Python Advanced","What is the xml etree module","XML parsing and creation library"),
    ("Python Advanced","What is the xml sax module","SAX parser for streaming XML"),
    ("Python Advanced","What is the xml dom module","DOM parser for XML documents"),
    ("Python Advanced","What is the html parser module","HTML parsing with HTMLParser"),
    ("Python Advanced","What is the html escape function","Escapes HTML special characters"),
    ("Python Advanced","What is the html unescape function","Unescapes HTML entities"),
    ("Python Advanced","What is the http cookiejar module","Cookie handling for HTTP requests"),
    ("Python Advanced","What is the http client module","HTTP protocol client implementation"),
    ("Python Advanced","What is the http server module","HTTP protocol server implementation"),
    ("Python Advanced","What is the ftplib module","FTP protocol client library"),
    ("Python Advanced","What is the poplib module","POP3 protocol client library"),
    ("Python Advanced","What is the imaplib module","IMAP4 protocol client library"),
    ("Python Advanced","What is the smtplib module","SMTP protocol client for email sending"),
    ("Python Advanced","What is the email module","Email message parsing and composition"),
    ("Python Advanced","What is the telnetlib module","Telnet client protocol"),
    ("Python Advanced","What is the uuid module","UUID generation with various versions"),
    ("Python Advanced","What is the hashlib module","Cryptographic hash functions"),
    ("Python Advanced","What is the hmac module","Keyed-hash message authentication"),
    ("Python Advanced","What is the secrets module","Cryptographically secure random numbers"),
    ("Python Advanced","What is the base64 module","Base64 binary text encoding"),
    ("Python Advanced","What is the binascii module","Binary ASCII conversion utilities"),
    ("Python Advanced","What is the quopri module","Quoted-printable encoding for email"),
    ("Python Advanced","What is the uu module","UU encoding for binary data"),
    ("Python Advanced","What is the binhex module","BinHex encoding for Macintosh"),
    ("Python Advanced","What is the zipfile module","ZIP archive reading and creation"),
    ("Python Advanced","What is the tarfile module","TAR archive reading and creation"),
    ("Python Advanced","What is the gzip module","GZIP compression and decompression"),
    ("Python Advanced","What is the bz2 module","BZ2 compression and decompression"),
    ("Python Advanced","What is the lzma module","LZMA compression and decompression"),
    ("Python Advanced","What is the zlib module","ZLIB compression and decompression"),
    ("Python Advanced","What is the configparser module","INI file parsing and writing"),
    ("Python Advanced","What is the netrc module","Netrc file parser for login credentials"),
    ("Python Advanced","What is the getpass module","Password input without echoing"),
    ("Python Advanced","What is the filecmp module","File and directory comparison"),
    ("Python Advanced","What is the tempfile module","Temporary file and directory creation"),
    ("Python Advanced","What is the shutil module","High-level file operations and archiving"),
    ("Python Advanced","What is the glob module","Unix-style path pattern matching"),
    ("Python Advanced","What is the fnmatch module","Filename pattern matching"),
    ("Python Advanced","What is the linecache module","Random access to text file lines"),
    ("Python Advanced","What is the textwrap module","Text formatting and wrapping"),
    ("Python Advanced","What is the unicodedata module","Unicode character database"),
    ("Python Advanced","What is the stringprep module","String preparation for protocols"),
    ("Python Advanced","What is the codecs module","Codec registry and base classes"),
    ("Python Advanced","What is the locale module","Internationalization and localization"),
    ("Python Advanced","What is the gettext module","Message translation and i18n"),
    ("Python Advanced","What is the calendar module","Calendar printing and date functions"),
]
gen(py_s_qs, "Senior", "Python")

# === Go Senior (200) ===
go_senior_qs = []
go_s_qs = [
    ("Advanced Go","What is the Go race detector","Runtime data race detection using happens-before"),
    ("Advanced Go","What is the go vet tool","Static analysis for suspicious code patterns"),
    ("Advanced Go","What is the go tool pprof","CPU and memory profiling tool"),
    ("Advanced Go","What is the go tool trace","Goroutine and GC execution tracing"),
    ("Advanced Go","What is the GOEXPERIMENT env","Enables experimental Go features"),
    ("Advanced Go","What is the go test -fuzz","Fuzz testing with random inputs"),
    ("Advanced Go","What is the go test -shuffle","Randomizes test execution order"),
    ("Advanced Go","What is the go test -v","Verbose test output showing test names"),
    ("Advanced Go","What is the go test -run","Runs tests matching specific pattern"),
    ("Advanced Go","What is the go test -count","Disables test caching with count 1"),
    ("Advanced Go","What is the go test -coverprofile","Generates coverage profile file"),
    ("Advanced Go","What is the go test -benchmem","Reports memory allocation stats in benchmarks"),
    ("Advanced Go","What is the go test -benchtime","Sets benchmark duration or iterations"),
    ("Advanced Go","What is the go test -cpu","Sets GOMAXPROCS for benchmark"),
    ("Advanced Go","What is the go test -parallel","Sets parallelism for test execution"),
    ("Advanced Go","What is the go test -timeout","Sets maximum time for test execution"),
    ("Advanced Go","What is the go test -trace","Generates execution trace file"),
    ("Advanced Go","What is the generation in generics","Generic type parameters introduced in Go 1.18"),
    ("Advanced Go","What is the any constraint","Alias for interface empty in generics"),
    ("Advanced Go","What is the comparable constraint","Constraint for types supporting equality"),
    ("Advanced Go","What is the interface constraint","Type sets in constraints for generics"),
    ("Advanced Go","What is the type set syntax","Union of types in interface constraints"),
    ("Advanced Go","What is the tilde type","Approximate type constraint for underlying types"),
    ("Advanced Go","What is the generic function","Function with type parameters in brackets"),
    ("Advanced Go","What is the generic type","Struct or interface with type parameters"),
    ("Advanced Go","What is the type inference for generics","Compiler infers type parameters from arguments"),
    ("Advanced Go","What is the constraint literal","Inline interface used as type constraint"),
    ("Advanced Go","What is the interface inference","Interface satisfaction inferred automatically"),
    ("Advanced Go","What is the type switch in generics","Switch on type parameter within constraint"),
    ("Advanced Go","What is the reflect type for generics","Reflection handles generic types at runtime"),
    ("Advanced Go","What is the go install command","Installs binary from module path"),
    ("Advanced Go","What is the go env command","Prints or sets environment variables"),
    ("Advanced Go","What is the go build -o","Specifies output file path and name"),
    ("Advanced Go","What is the go build -race","Builds with race detector enabled"),
    ("Advanced Go","What is the go build -tags","Conditional compilation with build tags"),
    ("Advanced Go","What is the go build -ldflags","Linker flags for version and variable injection"),
    ("Advanced Go","What is the go build -gcflags","Compiler flags for debugging and optimization"),
    ("Advanced Go","What is the go build -trimpath","Removes file system paths from binary"),
    ("Advanced Go","What is the go build -v","Verbose build output"),
    ("Advanced Go","What is the go build -x","Prints executed build commands"),
    ("Advanced Go","What is the Go workspace mode","Multiple modules in single workspace"),
    ("Advanced Go","What is the go work init","Initializes Go workspace file"),
    ("Advanced Go","What is the go work use","Adds module directory to workspace"),
    ("Advanced Go","What is the go work sync","Synchronizes workspace dependencies"),
    ("Advanced Go","What is the GOPRIVATE env","Private module pattern for proxy bypass"),
    ("Advanced Go","What is the GONOSUMCHECK env","Modules excluded from checksum database"),
    ("Advanced Go","What is the GONOSUMDB env","Legacy env for checksum exclusion"),
    ("Advanced Go","What is the GOINSECURE env","Insecure modules allowed without HTTPS"),
    ("Advanced Go","What is the GOFLAGS env","Default go command flags"),
    ("Advanced Go","What is the GOCACHE env","Build cache directory"),
    ("Advanced Go","What is the GOMODCACHE env","Module download cache directory"),
    ("Advanced Go","What is the go mod init","Creates new go.mod module file"),
    ("Advanced Go","What is the go mod tidy","Adds missing and removes unused dependencies"),
    ("Advanced Go","What is the go mod vendor","Creates vendor directory with dependencies"),
    ("Advanced Go","What is the go mod download","Downloads modules to local cache"),
    ("Advanced Go","What is the go mod verify","Verifies downloaded module checksums"),
    ("Advanced Go","What is the go mod why","Explains why dependency is needed"),
    ("Advanced Go","What is the go mod graph","Prints module dependency graph"),
    ("Advanced Go","What is the go mod edit","Edits go.mod programmatically"),
    ("Advanced Go","What is the replace directive","Replaces module with local path"),
    ("Advanced Go","What is the exclude directive","Excludes specific module version"),
    ("Advanced Go","What is the retract directive","Retracts published module versions"),
    ("Advanced Go","What is the toolchain directive","Specifies Go toolchain version requirement"),
    ("Advanced Go","What is the indirect dependency","Transitive dependency not directly imported"),
    ("Advanced Go","What is the minimum version selection","MVL chooses oldest compatible version"),
    ("Advanced Go","What is the lazy loading","Modules loaded only when needed"),
    ("Advanced Go","What is the go.sum file","Cryptographic checksums for module verification"),
    ("Advanced Go","What is the go center","Go module mirror checksum database and index"),
    ("Advanced Go","What is the proxy.golang.org","Official Go module proxy service"),
    ("Advanced Go","What is the sum.golang.org","Checksum database for module verification"),
    ("Advanced Go","What is the index.golang.org","Module index for discovery"),
    ("Advanced Go","What is the Go module mirror","Read-only copy of module source code"),
    ("Advanced Go","What is the pkg.go.dev","Go package documentation and discovery site"),
    ("Advanced Go","What is the go telemetry","Usage statistics collection for tool improvements"),
    ("Advanced Go","What is the govulncheck","Vulnerability checking for Go code"),
    ("Advanced Go","What is the go version command","Prints Go version currently installed"),
    ("Advanced Go","What is the go generate command","Runs source file generation commands"),
    ("Advanced Go","What is the go clean command","Removes cached build artifacts"),
    ("Advanced Go","What is the go fmt command","Formats Go source files"),
    ("Advanced Go","What is the go fix command","Auto-migrates code for API changes"),
    ("Advanced Go","What is the go doc command","Prints documentation for package or symbol"),
    ("Advanced Go","What is the go list command","Lists packages or modules with JSON output"),
]
gen(go_s_qs, "Senior", "Go")

# === General Senior (200) ===
gen_senior = []
gen_s_qs = [
    ("General","What is the AWS Lambda cold start","Delay when function is first invoked after idle"),
    ("General","What is the serverless computing","Cloud execution model without server management"),
    ("General","What is the FaaS model","Function as a Service deploy single functions"),
    ("General","What is the event-driven architecture","Components communicate through events"),
    ("General","What is the event sourcing pattern","Store events instead of current state"),
    ("General","What is the CQRS pattern","Separate command and query responsibilities"),
    ("General","What is the saga pattern","Distributed transaction with compensation steps"),
    ("General","What is the choreography saga","Each service handles its own compensation"),
    ("General","What is the orchestration saga","Central coordinator manages transaction flow"),
    ("General","What is the two-phase commit","Coordinator ensures atomic distributed transaction"),
    ("General","What is the outbox pattern","Event stored in same DB transaction as data"),
    ("General","What is the CDC pattern","Change Data Capture for streaming DB changes"),
    ("General","What is the backpressure handling","Consumer signals producer to slow down"),
    ("General","What is the bulkhead pattern","Isolate resources to prevent cascade failure"),
    ("General","What is the circuit breaker pattern","Fail fast when service is unhealthy"),
    ("General","What is the retry with backoff","Exponential delay between failed attempts"),
    ("General","What is the jitter in retries","Random delay variation avoiding thundering herd"),
    ("General","What is the timeout pattern","Fail operation after specified time limit"),
    ("General","What is the cache-aside pattern","Load cache on miss update database first"),
    ("General","What is the write-through cache","Write to cache and database simultaneously"),
    ("General","What is the write-behind cache","Async write to database after cache update"),
    ("General","What is the refresh-ahead cache","Preemptively refresh cache before expiry"),
    ("General","What is the materialized view pattern","Pre-computed query results for fast access"),
    ("General","What is the read replica pattern","Copy of primary DB for read scaling"),
    ("General","What is the sharding strategy","Horizontal partitioning across databases"),
    ("General","What is the consistent hashing","Hash table minimizing rehash on node changes"),
    ("General","What is the virtual nodes in consistent hashing","Multiple hash positions per physical node"),
    ("General","What is the gossip protocol","Peer-to-peer information propagation"),
    ("General","What is the Merkle tree","Hash tree for efficient data verification"),
    ("General","What is the Bloom filter","Probabilistic membership test no false negatives"),
    ("General","What is the Count-Min Sketch","Probabilistic frequency estimation structure"),
    ("General","What is the HyperLogLog","Cardinality estimation with low memory usage"),
    ("General","What is the T-Digest","Approximate percentile computation algorithm"),
    ("General","What is the Raft consensus algorithm","Leader election and log replication protocol"),
    ("General","What is the Paxos consensus","Prepare promise accept learned protocol phases"),
    ("General","What is the Zab protocol","ZooKeeper atomic broadcast protocol"),
    ("General","What is the Viewstamped Replication","Replication protocol for fault tolerance"),
    ("General","What is the multi-paxos","Optimized Paxos with stable leader"),
    ("General","What is the leader election algorithm","Choosing a single coordinator among nodes"),
    ("General","What is the quorum in distributed systems","Minimum nodes needed for agreement"),
    ("General","What is the split-brain problem","Multiple nodes believing they are leader"),
    ("General","What is the fencing token","Monotonically increasing token preventing stale writes"),
    ("General","What is the generation clock","Increasing epoch number for leader terms"),
    ("General","What is the hybrid logical clock","Combines physical and logical timestamps"),
    ("General","What is the vector clock","Tracking causality with per-node counters"),
    ("General","What is the Lamport timestamp","Logical clock for event ordering"),
    ("General","What is the CAP theorem tradeoff","Consistency availability partition tolerance choose two"),
    ("General","What is the PACELC theorem","CAP tradeoff plus latency during normal operation"),
    ("General","What is the eventual consistency","Data becomes consistent given enough time"),
    ("General","What is the strong consistency","All reads return latest write value"),
    ("General","What is the read-after-write consistency","Client reads its own writes immediately"),
    ("General","What is the monotonic reads","Reads never see older versions after newer"),
    ("General","What is the causal consistency","Causally related operations seen in order"),
    ("General","What is the linearizability","Single-copy serial equivalence for operations"),
    ("General","What is the serializability","Transactions appear to run sequentially"),
    ("General","What is the snapshot isolation","Transaction sees consistent snapshot at start"),
    ("General","What is the optimistic concurrency control","Check conflicts at commit time"),
    ("General","What is the pessimistic concurrency control","Lock resources before accessing"),
    ("General","What is the MVCC implementation","Multiple versions for non-blocking reads"),
    ("General","What is the gap locking","Locking ranges to prevent phantom reads"),
    ("General","What is the next-key locking","Index record lock plus gap lock"),
    ("General","What is the predicate locking","Locking rows matching search condition"),
    ("General","What is the write skew anomaly","Concurrent writes reading stale overlapping data"),
    ("General","What is the phantoms read","New rows appearing in repeated queries"),
    ("General","What is the non-repeatable read","Value changing within same transaction"),
    ("General","What is the dirty read","Reading uncommitted data from other transactions"),
    ("General","What is the serializable snapshot isolation","Stronger isolation preventing write skew"),
    ("General","What is the parallel query execution","Using multiple cores for single SQL query"),
    ("General","What is the query optimizer cardinality estimation","Estimating row counts for plan selection"),
    ("General","What is the index-only scan","Query answered entirely from index data"),
    ("General","What is the bitmap index scan","Combining multiple indexes with bitwise ops"),
    ("General","What is the nested loop join","For each outer row scan inner for matches"),
    ("General","What is the hash join","Build hash table on inner then probe with outer"),
    ("General","What is the merge join","Sort both sides then merge in sorted order"),
    ("General","What is the adaptive join","Query optimizer choosing join type at runtime"),
    ("General","What is the CTE in SQL","Common Table Expression using WITH clause"),
    ("General","What is the recursive CTE","Recursive query calling itself until empty"),
    ("General","What is the window function","Aggregate over partition without collapsing rows"),
    ("General","What is the ROW_NUMBER function","Sequential number per partition row"),
    ("General","What is the RANK function","Rank with gaps for ties in partition"),
    ("General","What is the DENSE_RANK function","Rank without gaps for ties"),
    ("General","What is the LAG function","Access previous row value within window"),
    ("General","What is the LEAD function","Access next row value within window"),
    ("General","What is the NTILE function","Divides rows into approximate equal buckets"),
    ("General","What is the CUME_DIST function","Cumulative distribution within window"),
    ("General","What is the PERCENT_RANK function","Relative rank percentile within window"),
    ("General","What is the JSON data type in PostgreSQL","Native JSON with indexing and functions"),
    ("General","What is the jsonb data type","Binary JSON with indexing and operators"),
    ("General","What is the array data type in PostgreSQL","Multi-dimensional array of base types"),
    ("General","What is the hstore extension","Key-value store within PostgreSQL"),
    ("General","What is the ltree extension","Hierarchical tree data type for paths"),
    ("General","What is the cube extension","Multi-dimensional cube for OLAP operations"),
    ("General","What is the pg_trgm extension","Trigram-based text search and similarity"),
    ("General","What is the fuzzystrmatch extension","Fuzzy string matching algorithms"),
    ("General","What is the PostGIS extension","Geographic objects and spatial queries"),
    ("General","What is the FDW in PostgreSQL","Foreign Data Wrapper for remote data access"),
    ("General","What is the table partitioning in PostgreSQL","Splitting table into physical partitions"),
    ("General","What is the range partitioning","Partition by value ranges"),
    ("General","What is the list partitioning","Partition by discrete value lists"),
    ("General","What is the hash partitioning","Partition by hash of partition key"),
    ("General","What is the logical replication","Streaming changes based on replication slots"),
    ("General","What is the physical replication","Block-level streaming replication"),
    ("General","What is the pg_stat_statements extension","Query performance statistics"),
    ("General","What is the pg_stat_activity view","Current server activity and queries"),
    ("General","What is the pg_stat_all_tables view","Table-level access statistics"),
    ("General","What is the pg_stat_all_indexes view","Index usage statistics"),
    ("General","What is the pg_buffercache extension","Shared buffer cache inspection"),
]
gen(gen_s_qs, "Senior", "General")

# Write everything
with open(MJS, 'w', encoding='utf-8') as f:
    f.write(before + '\n'.join(new) + '\n' + after)

count = len(new)
total = (before + '\n'.join(new) + '\n' + after).count('\n  Q(')
print(f'Batch 9 added {count} questions. Total: {total}')