"""Batch 22: 2000 fresh questions - all new topics, no repeats, strict JSON"""
import json
MJS = 'C:/Users/Honor/Desktop/Code/java-interview-tinder/backend/src/scripts/seed-generated.mjs'
with open(MJS, 'r', encoding='utf-8') as f:
    content = f.read()
idx = content.index('\nasync function seedDB()')
new = []

def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')

def Q(cat, q, a, diff, lang):
    opts = [a, 'Common misconception', 'Alternative approach', 'I don\'t know']
    obj = {"category": cat, "question": q, "short_answer": a, "options": opts, "difficulty": diff, "language": lang}
    json.dumps(obj, ensure_ascii=False)
    assert all(isinstance(o, str) and len(o) > 0 for o in opts), f"Options validation failed for: {q[:50]}"
    new.append(f"  Q('{esc(cat)}', '{esc(q)}', '{esc(a)}', ['{esc(opts[0])}', '{esc(opts[1])}', '{esc(opts[2])}', '{esc(opts[3])}'], '{diff}', '{lang}');\n")

def g(t, d, l):
    for c, q, a in t:
        Q(c, q, a, d, l)

# === JAVA FRESH: Compiler API, Flow API, VarHandle, StackWalker, Process API, jpackage ===
g([
    ("Compiler API", "What is javax.tools.JavaCompiler?", "Programmatic interface to the Java compiler"),
    ("Compiler API", "What is JavaCompiler.getTask()?", "Creates compilation task with source files"),
    ("Compiler API", "What is the javax.tools.DiagnosticCollector?", "Collects compilation errors and warnings"),
    ("Compiler API", "What is the javax.tools.SimpleJavaFileObject?", "In-memory source file for compilation"),
    ("Compiler API", "What is the javax.tools.StandardJavaFileManager?", "File manager for Java source and class files"),
    ("Compiler API", "What is the javax.tools.ToolProvider?", "Provides access to system Java compiler"),
    ("Compiler API", "What is the javax.annotation.processing package?", "Annotation processor framework"),
    ("Compiler API", "What is AbstractProcessor?", "Base class for annotation processors"),
    ("Compiler API", "What is RoundEnvironment?", "Annotation processing round context"),
    ("Compiler API", "What is the Filer interface in annotation processing?", "Creates source, class, or resource files"),
    ("Flow API", "What is java.util.concurrent.Flow?", "Reactive Streams API with Publisher, Subscriber, Subscription"),
    ("Flow API", "What is Flow.Publisher?", "Producer of items for reactive stream"),
    ("Flow API", "What is Flow.Subscriber?", "Consumer of items in reactive stream"),
    ("Flow API", "What is Flow.Subscription?", "Controls demand and cancellation between Publisher and Subscriber"),
    ("Flow API", "What is Flow.Processor?", "Acts as both Subscriber and Publisher"),
    ("Flow API", "What is SubmissionPublisher?", "Concurrent publisher that submits items to subscribers"),
    ("Flow API", "What is the onSubscribe method?", "Called when Subscriber registers with Publisher"),
    ("Flow API", "What is the onNext method?", "Called when new item arrives at Subscriber"),
    ("Flow API", "What is the onComplete method?", "Called when Publisher has no more items"),
    ("Flow API", "What is the onError method?", "Called when Publisher encounters error"),
    ("VarHandle", "What is java.lang.invoke.VarHandle?", "Typed reference to variable for atomic operations"),
    ("VarHandle", "What is VarHandle.get() and set()?", "Volatile read and write of variable"),
    ("VarHandle", "What is VarHandle.compareAndSet()?", "Atomically sets value if current equals expected"),
    ("VarHandle", "What is VarHandle.getAndSet()?", "Atomically gets and sets new value"),
    ("VarHandle", "What is VarHandle.getAndAdd()?", "Atomically gets and adds delta"),
    ("VarHandle", "What is VarHandle.getOpaque()?", "Guarantees bitwise atomicity without ordering"),
    ("VarHandle", "What is VarHandle.getAcquire()?", "Read with acquire memory ordering semantics"),
    ("VarHandle", "What is VarHandle.setRelease()?", "Write with release memory ordering semantics"),
    ("VarHandle", "What is VarHandle.fullFence()?", "Full memory barrier for visibility"),
    ("VarHandle", "What is VarHandle vs AtomicInteger?", "VarHandle works on any field; AtomicInteger has dedicated class"),
    ("StackWalker", "What is java.lang.StackWalker?", "API for walking JVM stack frames efficiently"),
    ("StackWalker", "What is StackWalker.getInstance()?", "Gets StackWalker instance with options"),
    ("StackWalker", "What is StackWalker.walk()?", "Applies function to stream of StackFrame"),
    ("StackWalker", "What is StackWalker.forEach()?", "Iterates over stack frames"),
    ("StackWalker", "What is StackWalker.getCallerClass()?", "Gets caller class (with RETAIN_CLASS_REFERENCE option)"),
    ("StackWalker", "What is StackFrame.getFileName()?", "Gets source file name of stack frame"),
    ("StackWalker", "What is StackFrame.getLineNumber()?", "Gets line number of stack frame"),
    ("StackWalker", "What is StackFrame.getMethodName()?", "Gets method name of stack frame"),
    ("StackWalker", "What is StackFrame.getClassName()?", "Gets class name of stack frame"),
    ("StackWalker", "What is StackWalker.Option.RETAIN_CLASS_REFERENCE?", "Option to retain Class objects in stack frames"),
], "Senior", "Java")

# === JAVA: Process API, jpackage, Sound, Preferences, Desktop ===
g([
    ("Process API", "What is java.lang.ProcessBuilder?", "Creates operating system processes"),
    ("Process API", "What is ProcessBuilder.command()?", "Sets command and arguments for process"),
    ("Process API", "What is ProcessBuilder.directory()?", "Sets working directory for process"),
    ("Process API", "What is ProcessBuilder.environment()?", "Gets environment variables map"),
    ("Process API", "What is ProcessBuilder.inheritIO()?", "Redirects process IO to parent's IO"),
    ("Process API", "What is ProcessBuilder.redirectInput()?", "Redirects process input from file"),
    ("Process API", "What is ProcessBuilder.redirectOutput()?", "Redirects process output to file"),
    ("Process API", "What is Process.onExit() (Java 9)?", "Returns CompletableFuture on process exit"),
    ("Process API", "What is Process.info() (Java 9)?", "Returns ProcessHandle.Info snapshot"),
    ("Process API", "What is ProcessHandle.allProcesses()?", "Returns snapshot of all processes in system"),
    ("jpackage", "What is jpackage?", "Java tool for creating native installers"),
    ("jpackage", "What is jpackage --input?", "Directory containing input JARs"),
    ("jpackage", "What is jpackage --dest?", "Output directory for installer"),
    ("jpackage", "What is jpackage --name?", "Application name for installer"),
    ("jpackage", "What is jpackage --main-jar?", "Main JAR containing entry point"),
    ("jpackage", "What is jpackage --main-class?", "Fully qualified main class name"),
    ("jpackage", "What is jpackage --type?", "Installer type: exe, msi, dmg, pkg, deb, rpm"),
    ("jpackage", "What is jpackage --app-image?", "Directory with pre-built application image"),
    ("jpackage", "What is jpackage --icon?", "Application icon file path"),
    ("jpackage", "What is jpackage --vendor?", "Application vendor string"),
    ("Sound", "What is javax.sound.sampled package?", "Audio capture, mix, playback API"),
    ("Sound", "What is AudioSystem?", "Entry point for audio resources"),
    ("Sound", "What is AudioInputStream?", "Audio input stream with format info"),
    ("Sound", "What is Clip interface?", "Pre-loaded audio for looped playback"),
    ("Sound", "What is SourceDataLine?", "Output audio line for streaming playback"),
    ("Sound", "What is TargetDataLine?", "Input audio line for capturing audio"),
    ("Sound", "What is AudioFormat?", "Describes audio data format parameters"),
    ("Sound", "What is AudioFileFormat?", "Describes audio file format type"),
    ("Sound", "What is AudioSystem.getAudioInputStream()?", "Obtains audio input stream from file"),
    ("Sound", "What is AudioSystem.write()?", "Writes audio stream to file"),
    ("Preferences", "What is java.util.prefs.Preferences?", "User and system preference storage"),
    ("Preferences", "What is Preferences.userNodeForPackage()?", "Gets user preferences for class"),
    ("Preferences", "What is Preferences.systemNodeForPackage()?", "Gets system-wide preferences for class"),
    ("Preferences", "What is Preferences.put() and get()?", "Stores and retrieves string preferences"),
    ("Preferences", "What is Preferences.putInt() and getInt()?", "Stores and retrieves integer preferences"),
    ("Preferences", "What is Preferences.node()?", "Creates or accesses sub-node in tree"),
    ("Preferences", "What is Preferences.flush()?", "Writes preferences to backing store"),
    ("Preferences", "What is Preferences.sync()?", "Reads preferences from backing store"),
    ("Preferences", "What is Preferences.exportNode()?", "Exports preferences as XML document"),
    ("Preferences", "What is the preferences backing store?", "Windows: registry; Linux: ~/.java/"),
], "Senior", "Java")

# === PYTHON FRESH: Streamlit, Pillow, OpenCV, Dash, Rich, PyTorch, HuggingFace, Brython ===
g([
    ("Streamlit", "What is Streamlit?", "Python framework for data apps from simple scripts"),
    ("Streamlit", "What is st.write()?", "Universal writing function for text, data, charts"),
    ("Streamlit", "What is st.title()/st.header()/st.subheader()?", "Text display functions"),
    ("Streamlit", "What is st.dataframe()?", "Interactive data frame display"),
    ("Streamlit", "What is st.table()?", "Static table display"),
    ("Streamlit", "What is st.line_chart()/st.bar_chart()?", "Simple chart display functions"),
    ("Streamlit", "What is st.map()?", "Geospatial data display on map"),
    ("Streamlit", "What is st.sidebar?", "Sidebar container for widgets"),
    ("Streamlit", "What is st.button()/st.slider()/st.selectbox()?", "Interactive widget functions"),
    ("Streamlit", "What is st.cache_data()?", "Caches data computation results"),
    ("Streamlit", "What is st.session_state?", "Persistent state across reruns"),
    ("Streamlit", "What is st.file_uploader()?", "File upload widget"),
    ("Streamlit", "What is st.columns()?", "Creates side-by-side column layout"),
    ("Streamlit", "What is st.expander()?", "Collapsible container"),
    ("Streamlit", "What is st.form()?", "Grouped form with submit button"),
    ("Streamlit", "What is st.plotly_chart()?", "Displays Plotly interactive charts"),
    ("Streamlit", "What is st.altair_chart()?", "Displays Altair declarative charts"),
    ("Streamlit", "What is st.pydeck_chart()?", "3D map visualization with PyDeck"),
    ("Streamlit", "What is Streamlit sharing?", "Deploy and share Streamlit apps"),
    ("Streamlit", "What is Streamlit Community Cloud?", "Free hosting for Streamlit apps"),
    ("Pillow", "What is Pillow (PIL Fork)?", "Image processing library for Python"),
    ("Pillow", "What is Image.open()?", "Opens image file for reading"),
    ("Pillow", "What is Image.new()?", "Creates new blank image"),
    ("Pillow", "What is Image.save()?", "Saves image to file in specified format"),
    ("Pillow", "What is Image.resize()?", "Resizes image to given dimensions"),
    ("Pillow", "What is Image.thumbnail()?", "Resizes keeping aspect ratio to fit bounding box"),
    ("Pillow", "What is Image.crop()?", "Extracts rectangular region from image"),
    ("Pillow", "What is Image.rotate()?", "Rotates image by angle degrees"),
    ("Pillow", "What is Image.filter()?", "Applies filter like BLUR, SHARPEN, CONTOUR"),
    ("Pillow", "What is ImageEnhance module?", "Adjusts color, contrast, brightness, sharpness"),
    ("Pillow", "What is ImageDraw module?", "Draws shapes, text, and lines on images"),
    ("Pillow", "What is ImageFont module?", "Loads TrueType fonts for text rendering"),
    ("Pillow", "What is ImageOps module?", "Operations like autocontrast, equalize, solarize"),
    ("Pillow", "What is ImageColor module?", "Color name to RGB conversion"),
    ("Pillow", "What is ImageSequence module?", "Iterates over frames in multi-frame images"),
    ("Pillow", "What is ImageChops module?", "Channel operations: add, subtract, multiply, screen"),
    ("Pillow", "What is ImageStat module?", "Statistics: mean, median, standard deviation of pixels"),
    ("Pillow", "What is ImageMath module?", "Evaluates image expression with pixel operations"),
    ("Pillow", "What is ImageGrab module?", "Captures screen or clipboard contents"),
    ("Pillow", "What is ImageQt module?", "Conversion between PIL images and Qt pixmaps"),
    ("OpenCV", "What is OpenCV (cv2)?", "Computer vision library with real-time image processing"),
    ("OpenCV", "What is cv2.imread()?", "Reads image from file into numpy array"),
    ("OpenCV", "What is cv2.imwrite()?", "Writes numpy array as image file"),
    ("OpenCV", "What is cv2.cvtColor()?", "Converts between color spaces (BGR, RGB, GRAY, HSV)"),
    ("OpenCV", "What is cv2.resize()?", "Resizes image to specified dimensions"),
    ("OpenCV", "What is cv2.GaussianBlur()?", "Applies Gaussian blur for noise reduction"),
    ("OpenCV", "What is cv2.Canny()?", "Canny edge detection algorithm"),
    ("OpenCV", "What is cv2.threshold()?", "Applies binary threshold to grayscale image"),
    ("OpenCV", "What is cv2.findContours()?", "Finds object contours in binary image"),
    ("OpenCV", "What is cv2.drawContours()?", "Draws contours on image"),
    ("OpenCV", "What is cv2.matchTemplate()?", "Template matching for object detection"),
    ("OpenCV", "What is cv2.HoughLines()?", "Hough transform for line detection"),
    ("OpenCV", "What is cv2.cascadeClassier()?", "Haar cascade classifier for face detection"),
    ("OpenCV", "What is cv2.VideoCapture()?", "Captures video from camera or file"),
    ("OpenCV", "What is cv2.waitKey()?", "Waits for keyboard input with delay"),
    ("OpenCV", "What is cv2.putText()?", "Draws text on image"),
    ("OpenCV", "What is cv2.rectangle()/cv2.circle()?", "Draws geometric shapes on image"),
    ("OpenCV", "What is cv2.bitwise_and()/or()/xor()?", "Bitwise operations on images"),
    ("OpenCV", "What is cv2.inRange()?", "Creates mask for color range detection"),
    ("OpenCV", "What is cv2.warpAffine()?", "Affine transformation of image"),
    ("PyTorch", "What is PyTorch?", "Deep learning framework with dynamic computation graphs"),
    ("PyTorch", "What is torch.Tensor?", "Multi-dimensional array with GPU support"),
    ("PyTorch", "What is torch.nn.Module?", "Base class for neural network layers"),
    ("PyTorch", "What is torch.nn.Linear()?", "Fully connected neural network layer"),
    ("PyTorch", "What is torch.nn.Conv2d()?", "2D convolutional layer for image processing"),
    ("PyTorch", "What is torch.nn.ReLU()?", "Rectified Linear Unit activation function"),
    ("PyTorch", "What is torch.nn.Dropout()?", "Regularization layer that randomly zeros inputs"),
    ("PyTorch", "What is torch.nn.CrossEntropyLoss()?", "Loss function for multi-class classification"),
    ("PyTorch", "What is torch.optim.SGD()?", "Stochastic Gradient Descent optimizer"),
    ("PyTorch", "What is torch.optim.Adam()?", "Adaptive Moment Estimation optimizer"),
    ("PyTorch", "What is torch.utils.data.DataLoader?", "Batched data loading with shuffling"),
    ("PyTorch", "What is torch.utils.data.Dataset?", "Abstract class for custom datasets"),
    ("PyTorch", "What is torchvision?", "Computer vision models and datasets for PyTorch"),
    ("PyTorch", "What is torch.cuda.is_available()?", "Checks if CUDA GPU is available"),
    ("PyTorch", "What is torch.no_grad()?", "Disables gradient calculation for inference"),
    ("PyTorch", "What is model.train() vs model.eval()?", "Sets model training or evaluation mode"),
    ("PyTorch", "What is backward() in PyTorch?", "Computes gradients via backpropagation"),
    ("PyTorch", "What is torch.save() and torch.load()?", "Saves and loads model checkpoints"),
    ("PyTorch", "What is torch.jit.script()?", "Compiles PyTorch model for production"),
    ("PyTorch", "What is torch.onnx.export()?", "Exports model to ONNX format"),
    ("HuggingFace", "What is HuggingFace Transformers?", "Library for state-of-the-art transformer models"),
    ("HuggingFace", "What is pipeline() in transformers?", "High-level API for inference on tasks"),
    ("HuggingFace", "What is AutoModel.from_pretrained()?", "Loads pre-trained model by name"),
    ("HuggingFace", "What is AutoTokenizer.from_pretrained()?", "Loads tokenizer for model"),
    ("HuggingFace", "What is the tokenizer encode() method?", "Converts text to input IDs"),
    ("HuggingFace", "What is the tokenizer decode() method?", "Converts IDs back to text"),
    ("HuggingFace", "What is the Trainer class?", "Training loop with metrics and logging"),
    ("HuggingFace", "What is TrainingArguments?", "Configuration for training hyperparameters"),
    ("HuggingFace", "What is HuggingFace Datasets?", "Library for downloading and processing datasets"),
    ("HuggingFace", "What is HuggingFace Hub?", "Platform for sharing models and datasets"),
    ("HuggingFace", "What is fine-tuning in transformers?", "Adapting pre-trained model to specific task"),
    ("HuggingFace", "What is the generate() method?", "Auto-regressive text generation"),
    ("HuggingFace", "What is the save_pretrained() method?", "Saves model and config to directory"),
    ("HuggingFace", "What is the push_to_hub() method?", "Uploads model to HuggingFace Hub"),
    ("HuggingFace", "What is the TextClassificationPipeline?", "Pipeline for sentiment analysis etc."),
    ("HuggingFace", "What is the QuestionAnsweringPipeline?", "Pipeline for extractive QA"),
    ("HuggingFace", "What is the SummarizationPipeline?", "Pipeline for text summarization"),
    ("HuggingFace", "What is the TranslationPipeline?", "Pipeline for machine translation"),
    ("HuggingFace", "What is the TextGenerationPipeline?", "Pipeline for open-ended text generation"),
    ("HuggingFace", "What is the ZeroShotClassificationPipeline?", "Pipeline for zero-shot classification"),
], "Senior", "Python")

# === TYPESCRIPT FRESH: Effect-TS, Zod, Hono, Elysia, TanStack Router/Table/Virtual ===
g([
    ("Zod", "What is Zod?", "TypeScript-first schema validation with static inference"),
    ("Zod", "What is z.object()?", "Composite schema for object validation"),
    ("Zod", "What is z.string()?", "Validates string values with optional refinements"),
    ("Zod", "What is z.number()?", "Validates numeric values"),
    ("Zod", "What is z.array()?", "Validates arrays with element schema"),
    ("Zod", "What is z.enum()?", "Validates exactly one of string literals"),
    ("Zod", "What is z.union()?", "Validates one of multiple schemas"),
    ("Zod", "What is z.optional()?", "Makes schema accept undefined or value"),
    ("Zod", "What is z.nullable()?", "Makes schema accept null or value"),
    ("Zod", "What is z.discriminatedUnion()?", "Performance-optimized union with discriminator key"),
    ("Zod", "What is z.infer<T>()?", "Infers TypeScript type from Zod schema"),
    ("Zod", "What is schema.parse()?", "Validates and returns typed value or throws"),
    ("Zod", "What is schema.safeParse()?", "Validates returns { success, data/error }"),
    ("Zod", "What is zod.refine()?", "Custom validation with error message"),
    ("Zod", "What is zod.superRefine()?", "Advanced refinement with path and context"),
    ("Zod", "What is z.custom()?", "Creates custom schema with type guard"),
    ("Zod", "What is the z.Schema type?", "Base type for all Zod schemas"),
    ("Zod", "What is ZodEffects?", "Schema with effects (refine, transform, preprocess)"),
    ("Zod", "What is z.transformer()?", "Transforms validated data to different type"),
    ("Zod", "What is z.pipeline()?", "Pipes through multiple schemas sequentially"),
    ("Hono", "What is Hono?", "Ultralight web framework for multiple runtimes"),
    ("Hono", "What is new Hono()?", "Creates Hono application instance"),
    ("Hono", "What is app.get/post/put/delete()?", "Route definition with HTTP method"),
    ("Hono", "What is c.req.param()?", "Extracts URL path parameters"),
    ("Hono", "What is c.req.query()?", "Extracts query string parameters"),
    ("Hono", "What is c.req.json()?", "Parses request body as JSON"),
    ("Hono", "What is c.json()?", "Returns JSON response"),
    ("Hono", "What is Hono middleware?", "Functions with c and next for request processing"),
    ("Hono", "What is Hono bearer auth middleware?", "Validates bearer token"),
    ("Hono", "What is Hono cors middleware?", "Handles CORS headers"),
    ("Hono", "What is Hono JWT middleware?", "Validates JWT tokens"),
    ("Hono", "What is Hono etag middleware?", "Adds ETag headers for caching"),
    ("Hono", "What is Hono powered-by middleware?", "Adds X-Powered-By header"),
    ("Hono", "What is Hono logger middleware?", "Request logging"),
    ("Hono", "What is Hono timeout middleware?", "Request timeout handling"),
    ("Hono", "What is Hono RPC?", "Type-safe client from server definition"),
    ("Hono", "What is Hono JSX?", "Server-side JSX rendering"),
    ("Hono", "What is Hono validator?", "Request validation with Zod or Valibot"),
    ("Hono", "What is Hono Cloudflare Workers adapter?", "Runs Hono on Cloudflare Workers"),
    ("Hono", "What is Hono Deno adapter?", "Runs Hono on Deno"),
    ("TanStack", "What is TanStack Router?", "Type-safe router with URL state management"),
    ("TanStack", "What is TanStack Router route tree?", "Hierarchical route definition"),
    ("TanStack", "What is TanStack Router loaders?", "Data loading before route renders"),
    ("TanStack", "What is TanStack Router search params?", "Type-safe URL search parameter handling"),
    ("TanStack", "What is TanStack Router link options?", "Navigation with preloading and active states"),
    ("TanStack", "What is TanStack Table?", "Headless UI for tables with sorting, filtering, pagination"),
    ("TanStack", "What is useReactTable()?", "Creates table instance with column definitions"),
    ("TanStack", "What is TanStack Table column accessor?", "Defines data access path from row data"),
    ("TanStack", "What is TanStack Table sorting?", "Multi-column sorting with toggle direction"),
    ("TanStack", "What is TanStack Table filtering?", "Column filters and global filter"),
    ("TanStack", "What is TanStack Table pagination?", "Client or server-side pagination"),
    ("TanStack", "What is TanStack Table row selection?", "Single or multi-row selection"),
    ("TanStack", "What is TanStack Table column visibility?", "Toggle column show/hide"),
    ("TanStack", "What is TanStack Table column ordering?", "Drag-and-drop column reordering"),
    ("TanStack", "What is TanStack Virtual?", "Virtual scrolling for large lists and grids"),
    ("TanStack", "What is useVirtualizer()?", "Virtual scrolling hook for fixed-size items"),
    ("TanStack", "What is TanStack Virtual dynamic sizing?", "Estimated sizes for variable-height items"),
    ("TanStack", "What is TanStack Virtual smooth scroll?", "Programmatic scrolling with smooth behavior"),
    ("TanStack", "What is TanStack Virtual window scroller?", "Virtual component for window scrolling"),
    ("TanStack", "What is TanStack Form?", "Headless form library with validation"),
], "Senior", "TypeScript")

# === GO FRESH: slog, fuzzing, 1.21+ features, workspaces, tinygo, wasm ===
g([
    ("slog", "What is log/slog (Go 1.21)?", "Structured logging with levels and handlers"),
    ("slog", "What is slog.New()?", "Creates logger with handler"),
    ("slog", "What is slog.NewTextHandler()?", "Text-formatted log handler"),
    ("slog", "What is slog.NewJSONHandler()?", "JSON-formatted log handler"),
    ("slog", "What is slog.Info()/Debug()/Warn()/Error()?", "Leveled log functions"),
    ("slog", "What is slog.Int()/slog.String()/slog.Bool()?", "Attributed key-value pairs"),
    ("slog", "What is slog.Group()?", "Groups attributes under a key"),
    ("slog", "What is slog.Any()?", "Packs any value as log attribute"),
    ("slog", "What is slog.LogAttrs()?", "Low-level log with attributes"),
    ("slog", "What is slog.Handler interface?", "Custom handler for log output"),
    ("slog", "What is slog.LevelVar?", "Dynamic log level changing"),
    ("Fuzzing", "What is Go fuzzing?", "Automated test input generation for bug finding"),
    ("Fuzzing", "What is the Fuzz function?", "Fuzz test entry point with *testing.F"),
    ("Fuzzing", "What is f.Add()?", "Seeds fuzzer with initial corpus values"),
    ("Fuzzing", "What is f.Fuzz()?", "Runs fuzz target with generated inputs"),
    ("Fuzzing", "What is go test -fuzz?", "Runs fuzz tests indefinitely"),
    ("Fuzzing", "What is go test -fuzztime?", "Runs fuzzing for specific duration"),
    ("Fuzzing", "What is the fuzz corpus?", "Directory storing interesting inputs"),
    ("Fuzzing", "What is fuzzing coverage?", "Guides input generation through code paths"),
    ("Fuzzing", "What is the -fuzzcachedir flag?", "Specifies fuzz cache directory"),
    ("Go 1.21+", "What is the cmp package (Go 1.21)?", "Comparison utilities with Ordered constraint"),
    ("Go 1.21+", "What is cmp.Compare()?", "Compares ordered values returning -1, 0, 1"),
    ("Go 1.21+", "What is cmp.Less()?", "Boolean less-than comparison"),
    ("Go 1.21+", "What is cmp.Or()?", "Returns first non-zero argument"),
    ("Go 1.21+", "What is the slices package (Go 1.21)?", "Generic slice operations"),
    ("Go 1.21+", "What is slices.Sort()?", "Sorts slice in ascending order"),
    ("Go 1.21+", "What is slices.BinarySearch()?", "Binary search on sorted slice"),
    ("Go 1.21+", "What is slices.Compact()?", "Removes consecutive duplicate elements"),
    ("Go 1.21+", "What is slices.Delete()?", "Removes elements from slice by index range"),
    ("Go 1.21+", "What is slices.Insert()?", "Inserts elements at specified index"),
    ("Go 1.21+", "What is slices.Replace()?", "Replaces slice elements by index range"),
    ("Go 1.21+", "What is slices.Clip()?", "Removes unused capacity from slice"),
    ("Go 1.21+", "What is the maps package (Go 1.21)?", "Generic map operations"),
    ("Go 1.21+", "What is maps.Clone()?", "Creates shallow copy of map"),
    ("Go 1.21+", "What is maps.Copy()?", "Copies all key-value pairs from source to destination"),
    ("Go 1.21+", "What is maps.DeleteFunc()?", "Deletes map entries matching predicate"),
    ("Go 1.21+", "What is maps.Equal()?", "Checks if two maps are equal"),
    ("Go 1.21+", "What is maps.Keys()?", "Returns slice of map keys"),
    ("Go 1.21+", "What is maps.Values()?", "Returns slice of map values"),
    ("Go 1.21+", "What is clear() builtin (Go 1.21)?", "Deletes all entries from map or zeroes slice elements"),
    ("TinyGo", "What is TinyGo?", "Go compiler for microcontrollers and WebAssembly"),
    ("TinyGo", "What is TinyGo machine package?", "Hardware abstraction for MCU peripherals"),
    ("TinyGo", "What is machine.Pin?", "GPIO pin control for microcontrollers"),
    ("TinyGo", "What is machine.I2C?", "I2C bus communication protocol"),
    ("TinyGo", "What is machine.SPI?", "SPI bus communication protocol"),
    ("TinyGo", "What is machine.ADC?", "Analog-to-digital converter on pins"),
    ("TinyGo", "What is machine.PWM?", "Pulse Width Modulation for LED dimming and motors"),
    ("TinyGo", "What is machine.UART?", "Serial communication via UART"),
    ("TinyGo", "What is TinyGo targeting?", "---target flag for specific board"),
    ("TinyGo", "What is wasm target in TinyGo?", "tinygo build -o main.wasm -target=wasm"),
], "Senior", "Go")

# === RUST FRESH: fuzzing, tracing deep, config, validation, cross-compile, const generics, SIMD ===
g([
    ("Fuzzing", "What is cargo-fuzz?", "Fuzz testing framework using libFuzzer"),
    ("Fuzzing", "What is a fuzz target?", "Function that receives random input byte slice"),
    ("Fuzzing", "What is fuzz_target!(|data|)?", "Macro wrapping fuzz target function"),
    ("Fuzzing", "What is cargo fuzz run?", "Runs fuzz target indefinitely"),
    ("Fuzzing", "What is cargo fuzz build?", "Builds fuzz targets"),
    ("Fuzzing", "What is cargo fuzz list?", "Lists available fuzz targets"),
    ("Fuzzing", "What is cargo fuzz cmin?", "Minimizes fuzz corpus"),
    ("Fuzzing", "What is cargo fuzz tmin?", "Minimizes single test case"),
    ("Fuzzing", "What is coverage-guided fuzzing?", "Uses code coverage feedback to generate inputs"),
    ("Fuzzing", "What is AFL.rs?", "American Fuzzy Lop for Rust"),
    ("Tracing", "What is tracing crate?", "Structured diagnostics with spans and events"),
    ("Tracing", "What is tracing-subscriber?", "Collects and formats tracing data"),
    ("Tracing", "What is tracing-subscriber::Registry?", "Default registry storing span data"),
    ("Tracing", "What is tracing-subscriber::FmtSubscriber?", "Formats tracing output to stdout"),
    ("Tracing", "What is a tracing span?", "Duration with context fields for operation tracking"),
    ("Tracing", "What is the #[instrument] attribute?", "Auto-creates span for function"),
    ("Tracing", "What is tracing::info_span!()?", "Creates span with info level"),
    ("Tracing", "What is tracing::event!()?", "Records a point-in-time event"),
    ("Tracing", "What is tracing::Span::enter()?", "Enters span scope"),
    ("Tracing", "What is tracing::Span::in_scope()?", "Runs closure within span context"),
    ("Tracing", "What is tracing-opentelemetry?", "Exports tracing data via OpenTelemetry"),
    ("Tracing", "What is tracing-actor?", "Actor model pattern with tracing"),
    ("Tracing", "What is tracing-error?", "Captures span context in errors"),
    ("Tracing", "What is tracing-appender?", "Non-blocking log file writing"),
    ("Tracing", "What is tracing-flame?", "Generates flamegraph from tracing data"),
    ("Config", "What is figment?", "Configuration library with multi-provider support"),
    ("Config", "What is config-rs?", "Configuration management with file and env sources"),
    ("Config", "What is ConfigBuilder in config-rs?", "Adds sources with set_override, add_source"),
    ("Config", "What is config-rs FileSource?", "Reads TOML, JSON, YAML, HJSON, INI files"),
    ("Config", "What is config-rs EnvironmentSource?", "Reads environment variables with prefix"),
    ("Config", "What is figment::Provider trait?", "Custom config source implementation"),
    ("Config", "What is figment::Jail?", "Sandboxed config extraction for testing"),
    ("Config", "What is figment::Value?", "Dynamic config value representation"),
    ("Config", "What is figment serialize/deserialize?", "Serde integration for config extraction"),
    ("Config", "What is dotenvy?", "Loads .env file into environment variables"),
    ("Validation", "What is the validator crate?", "Derive macro for struct field validation"),
    ("Validation", "What is #[validate(email)]?", "Validates email format"),
    ("Validation", "What is #[validate(url)]?", "Validates URL format"),
    ("Validation", "What is #[validate(length(min=1, max=100))]?", "Validates string length range"),
    ("Validation", "What is #[validate(range(min=0, max=100))]?", "Validates numeric range"),
    ("Validation", "What is #[validate(custom = \"function\")]?", "Custom validation function"),
    ("Validation", "What is #[validate(must_match = \"other_field\")]?", "Ensures two fields match"),
    ("Validation", "What is Validate trait?", "Derives validation method for struct"),
    ("Validation", "What is the garde crate?", "Validation library with focus on error messages"),
    ("Validation", "What is garde::Validate?", "Derives validation with struct context"),
    ("Cross", "What is Rust cross-compilation?", "Compiling for different target platform"),
    ("Cross", "What is cargo build --target?", "Specifies target triple for compilation"),
    ("Cross", "What is a target triple?", "arch-vendor-os format like x86_64-unknown-linux-gnu"),
    ("Cross", "What is the cross tool?", "Cross-compilation with Docker images"),
    ("Cross", "What is cargo-zigbuild?", "Cross-compilation using Zig linker"),
    ("Cross", "What is --target x86_64-pc-windows-gnu?", "Cross-compiles for Windows from Linux"),
    ("Cross", "What is --target aarch64-apple-darwin?", "Cross-compiles for Apple Silicon Mac"),
    ("Cross", "What is rustup target add?", "Installs std library for target"),
    ("Cross", "What is .cargo/config.toml for cross?", "Configures linker and runner for targets"),
    ("Cross", "What is the MUSL target?", "Static linking with musl libc for portability"),
], "Senior", "Rust")

# === REACT FRESH: React Three Fiber, Radix UI, React Aria, Expo Router, Tamagui ===
g([
    ("R3F", "What is React Three Fiber?", "React renderer for Three.js 3D graphics"),
    ("R3F", "What is <Canvas> in R3F?", "Three.js scene container setting up renderer, camera, lighting"),
    ("R3F", "What is useFrame() in R3F?", "Runs callback on every animation frame for loops"),
    ("R3F", "What is <mesh> in R3F?", "3D mesh geometry with material"),
    ("R3F", "What is <boxGeometry>?", "Box geometry 3D shape"),
    ("R3F", "What is <meshStandardMaterial>?", "Physically-based rendering material"),
    ("R3F", "What is useGLTF()?", "Loads glTF 3D model files"),
    ("R3F", "What is <OrbitControls>?", "Camera control with orbiting, zoom, pan"),
    ("R3F", "What is <primitive> in R3F?", "Wraps external Three.js objects"),
    ("R3F", "What is <Text3D>?", "3D text geometry with font"),
    ("R3F", "What is THREE.Group in R3F?", "Container for grouped 3D objects"),
    ("R3F", "What is useLoader() in R3F?", "Generic loader for textures, models"),
    ("R3F", "What is useTexture() in R3F?", "Loads image textures"),
    ("R3F", "What is R3F events?", "Pointer events: onClick, onPointerDown, onPointerOver"),
    ("R3F", "What is R3F animations?", "Interpolating values with custom logic per frame"),
    ("R3F", "What is R3F physics (react-three/rapier)?", "Physics engine integration with Rapier"),
    ("R3F", "What is drei library?", "Utilities: helpers, controls, shapes for R3F"),
    ("R3F", "What is postprocessing in R3F?", "EffectComposer for bloom, outline, pixelate"),
    ("R3F", "What is R3F environment maps?", "HDRI environment for reflections and lighting"),
    ("R3F", "What is R3F InstancedMesh?", "Efficient rendering of many identical objects"),
    ("Radix UI", "What is Radix UI?", "Headless, accessible UI component primitives for React"),
    ("Radix UI", "What is Radix Dialog?", "Modal dialog with focus trap and keyboard navigation"),
    ("Radix UI", "What is Radix Popover?", "Floating content with positioning"),
    ("Radix UI", "What is Radix Tooltip?", "Hover tooltip with arrow positioning"),
    ("Radix UI", "What is Radix DropdownMenu?", "Context menu with keyboard navigation"),
    ("Radix UI", "What is Radix Select?", "Custom select with search and groups"),
    ("Radix UI", "What is Radix Tabs?", "Tabbed interface with keyboard activation"),
    ("Radix UI", "What is Radix Accordion?", "Collapsible content sections"),
    ("Radix UI", "What is Radix Toast?", "Notification with swipe dismiss"),
    ("Radix UI", "What is Radix ToggleGroup?", "Mutually exclusive toggle buttons"),
    ("Radix UI", "What is Radix Slider?", "Range slider with multiple thumbs"),
    ("Radix UI", "What is Radix Checkbox?", "Accessible checkbox with indeterminate state"),
    ("Radix UI", "What is Radix RadioGroup?", "Radio button group with keyboard navigation"),
    ("Radix UI", "What is Radix Switch?", "Toggle switch component"),
    ("Radix UI", "What is Radix ScrollArea?", "Custom scrollbar styling"),
    ("Radix UI", "What is Radix AspectRatio?", "Maintains aspect ratio of content"),
    ("Radix UI", "What is Radix Avatar?", "Image avatar with fallback initials"),
    ("Radix UI", "What is Radix HoverCard?", "Card revealed on hover with delay"),
    ("Radix UI", "What is Radix ContextMenu?", "Right-click menu on elements"),
    ("Radix UI", "What is Radix NavigationMenu?", "Accessible navigation with dropdowns"),
    ("Expo", "What is Expo Router?", "File-based routing for React Native"),
    ("Expo", "What is Expo Router file conventions?", "index.tsx, [param].tsx, (group) routes"),
    ("Expo", "What is expo-router Link?", "Typed navigation component"),
    ("Expo", "What is expo-router useRouter()?", "Programmatic navigation hook"),
    ("Expo", "What is expo-router useLocalSearchParams()?", "Accesses URL parameters"),
    ("Expo", "What is expo-router Stack navigator?", "Native stack navigation"),
    ("Expo", "What is expo-router Tabs navigator?", "Tab-based navigation"),
    ("Expo", "What is expo-router Drawer navigator?", "Drawer navigation"),
    ("Expo", "What is expo-router UnmatchedRoute?", "404 route handling"),
    ("Expo", "What is expo-router Redirect?", "Server-side redirect component"),
    ("Expo", "What is expo-constants?", "Exposes app configuration constants"),
    ("Expo", "What is expo-status-bar?", "Status bar configuration"),
    ("Expo", "What is expo-splash-screen?", "Splash screen management"),
    ("Expo", "What is expo-asset?", "Asset management for images, fonts"),
    ("Expo", "What is expo-font?", "Font loading with custom fonts"),
    ("Expo", "What is expo-linking?", "Deep linking utilities"),
    ("Expo", "What is expo-sensors?", "Device sensor access (accelerometer, gyroscope)"),
    ("Expo", "What is expo-camera?", "Camera access and control"),
    ("Expo", "What is expo-location?", "Device location services"),
    ("Expo", "What is expo-notifications?", "Push notification management"),
], "Senior", "React")

# === KOTLIN FRESH: KMP detail, Kotlin DataFrame, Kotlin Notebook, Kodein, kotlinx-io ===
g([
    ("KMP", "What is expect/actual for interfaces?", "Define interface expect, implement actual per platform"),
    ("KMP", "What is Kotlin Multiplatform Gradle plugin?", "kotlin(\"multiplatform\") with targets"),
    ("KMP", "What is the androidTarget in KMP?", "Configures Android target for shared code"),
    ("KMP", "What is the iosTarget in KMP?", "Configures iOS target with ARM64 architecture"),
    ("KMP", "What is the jsTarget in KMP?", "Configures JavaScript target for KMP"),
    ("KMP", "What is the linuxX64Target in KMP?", "Configures Linux desktop target"),
    ("KMP", "What is the mingwX64Target in KMP?", "Configures Windows desktop target"),
    ("KMP", "What is the macosX64Target in KMP?", "Configures macOS Intel target"),
    ("KMP", "What is Kotlin CocoaPods integration?", "Export Kotlin framework to CocoaPods"),
    ("KMP", "What is Kotlin Swift/ObjC interop?", "Kotlin code callable from Swift/Objective-C"),
    ("KMP", "What is Kotlin/JS React integration?", "Writing React components in Kotlin/JS"),
    ("KMP", "What is the @JsModule annotation?", "Maps Kotlin module to JS module"),
    ("KMP", "What is the @JsNonModule annotation?", "Marks declaration for non-module JS environments"),
    ("KMP", "What is Kotlin/Wasm target?", "WebAssembly compilation target"),
    ("KMP", "What is Kotlin/Native cinterop?", "C library interop from Kotlin/Native"),
    ("DataFrame", "What is Kotlin DataFrame?", "Data manipulation library for structured data"),
    ("DataFrame", "What is dataFrame.read()?", "Reads CSV, JSON, or other formats into DataFrame"),
    ("DataFrame", "What is df.filter() in Kotlin DataFrame?", "Filters rows by column condition"),
    ("DataFrame", "What is df.select() in Kotlin DataFrame?", "Selects specific columns"),
    ("DataFrame", "What is df.groupBy() in Kotlin DataFrame?", "Groups rows by column values"),
    ("DataFrame", "What is df.sortBy() in Kotlin DataFrame?", "Sorts rows by column"),
    ("DataFrame", "What is df.add() in Kotlin DataFrame?", "Adds new computed column"),
    ("DataFrame", "What is df.toList() in Kotlin DataFrame?", "Converts DataFrame to list of objects"),
    ("DataFrame", "What is DataFrame column accessors?", "Type-safe column references via extension properties"),
    ("DataFrame", "What is DataFrame visualization?", "Integrated plotting with Lets-Plot library"),
    ("Kotlin Notebook", "What is Kotlin Notebook?", "Interactive notebook environment for Kotlin"),
    ("Kotlin Notebook", "What is %use library directive?", "Adds dependency to notebook cell"),
    ("Kotlin Notebook", "What is Kotlin Notebook visualization?", "Integrated chart and table display"),
    ("Kotlin Notebook", "What is the Kotlin DataFrame in notebooks?", "Data exploration with DataFrame within notebooks"),
    ("Kotlin Notebook", "What is Kotlin Notebook Kandy?", "Charting library for notebooks"),
    ("Kotlin Notebook", "What is the Kandy plotting library?", "Declarative charting with Kotlin DSL"),
    ("Kotlin Notebook", "What is Kandy plot() function?", "Creates chart with data and layers"),
    ("Kotlin Notebook", "What is Kandy histogram?", "Distribution visualization with bins"),
    ("Kotlin Notebook", "What is Kandy boxplot?", "Statistical distribution with quartiles"),
    ("Kotlin Notebook", "What is Kandy line plot?", "Time series line chart"),
    ("Kodein", "What is Kodein-DI?", "Dependency injection library with simple DSL"),
    ("Kodein", "What is Kodein { } block?", "DI module declaration"),
    ("Kodein", "What is bind<Interface>() with singleton?", "Binds implementation as singleton"),
    ("Kodein", "What is bind<Interface>() with factory?", "Creates new instance on each injection"),
    ("Kodein", "What is Kodein.global?", "Global DI container for simple cases"),
    ("Kodein", "What is by kodein() delegate?", "Lazy injection property delegate"),
    ("Kodein", "What is KodeinAware interface?", "Makes class aware of Kodein container"),
    ("Kodein", "What is Kodein module imports?", "Composing modules with import()"),
    ("Kodein", "What is Kodein multibinding?", "Multiple implementations for same type"),
    ("Kodein", "What is Kodein erasure-based resolution?", "Resolves by runtime type erasure"),
], "Senior", "Kotlin")

# === GENERAL FRESH: AI/LLM, Blockchain, WebRTC, SQL optimization, API design, Machine Learning basics ===
g([
    ("LLM/AI", "What is a large language model (LLM)?", "Neural network trained on vast text data for text generation"),
    ("LLM/AI", "What is prompt engineering?", "Crafting input prompts for desired LLM output"),
    ("LLM/AI", "What is few-shot prompting?", "Providing examples in prompt for in-context learning"),
    ("LLM/AI", "What is chain-of-thought prompting?", "Step-by-step reasoning prompt for complex problems"),
    ("LLM/AI", "What is RAG (Retrieval-Augmented Generation)?", "Combines retrieval from knowledge base with LLM generation"),
    ("LLM/AI", "What is vector database?", "Stores embeddings for semantic similarity search"),
    ("LLM/AI", "What is embedding model?", "Converts text to numerical vectors preserving semantics"),
    ("LLM/AI", "What is cosine similarity?", "Measures similarity between two embedding vectors"),
    ("LLM/AI", "What is fine-tuning LLM?", "Further training pre-trained model on specific data"),
    ("LLM/AI", "What is LoRA (Low-Rank Adaptation)?", "Efficient fine-tuning by adding small adapter weights"),
    ("LLM/AI", "What is quantization in ML?", "Reducing model precision to lower memory usage"),
    ("LLM/AI", "What is the OpenAI API?", "API for GPT models with chat completions and embeddings"),
    ("LLM/AI", "What is the chat completions endpoint?", "Conversational AI with message history"),
    ("LLM/AI", "What is the Anthropic API?", "Claude AI model API with safety features"),
    ("LLM/AI", "What is LangChain?", "Framework for building LLM-powered applications"),
    ("LLM/AI", "What is LangChain chain?", "Sequence of LLM calls and tools for tasks"),
    ("LLM/AI", "What is LangChain agent?", "LLM with tool selection and execution loop"),
    ("LLM/AI", "What is LangChain memory?", "Conversation history management for chatbots"),
    ("LLM/AI", "What is LlamaIndex?", "Data framework for building LLM apps with custom data"),
    ("LLM/AI", "What is a tokenizer in LLMs?", "Splits text into tokens for model input"),
    ("Blockchain", "What is blockchain?", "Decentralized, immutable ledger of transactions"),
    ("Blockchain", "What is a block in blockchain?", "Data structure with transactions, hash, and previous hash"),
    ("Blockchain", "What is proof of work?", "Consensus mechanism requiring computational work"),
    ("Blockchain", "What is proof of stake?", "Consensus based on validator's staked tokens"),
    ("Blockchain", "What is a smart contract?", "Self-executing code on blockchain"),
    ("Blockchain", "What is Ethereum?", "Blockchain platform with smart contracts"),
    ("Blockchain", "What is a dApp (decentralized app)?", "Application running on blockchain with smart contracts"),
    ("Blockchain", "What is a wallet in crypto?", "Manages private keys for blockchain interactions"),
    ("Blockchain", "What is a merkle tree?", "Tree structure for efficient data verification"),
    ("Blockchain", "What is a nonce in blockchain?", "Number used once for block mining"),
    ("WebRTC", "What is WebRTC?", "Real-time peer-to-peer communication in browsers"),
    ("WebRTC", "What is RTCPeerConnection?", "WebRTC API for peer-to-peer connection"),
    ("WebRTC", "What is SDP in WebRTC?", "Session Description Protocol for media negotiation"),
    ("WebRTC", "What is ICE (Interactive Connectivity Establishment)?", "NAT traversal for peer-to-peer connections"),
    ("WebRTC", "What is STUN server?", "Discovers public IP and port of peer"),
    ("WebRTC", "What is TURN server?", "Relays media when direct P2P fails"),
    ("WebRTC", "What is a signaling server?", "Facilitates initial connection setup between peers"),
    ("WebRTC", "What is getUserMedia()?", "Accesses camera and microphone"),
    ("WebRTC", "What is getDisplayMedia()?", "Captures screen for sharing"),
    ("WebRTC", "What is RTCDataChannel?", "Low-latency data transfer between peers"),
    ("SQL", "What is a query execution plan?", "Database's step-by-step plan for executing query"),
    ("SQL", "What is EXPLAIN ANALYZE?", "Runs query and shows actual execution stats"),
    ("SQL", "What is a sequential scan?", "Full table scan reading all rows sequentially"),
    ("SQL", "What is an index scan?", "Uses index to locate specific rows efficiently"),
    ("SQL", "What is a bitmap scan?", "Combines multiple indexes with bitmap operations"),
    ("SQL", "What is a nested loop join?", "For each outer row, scans inner table"),
    ("SQL", "What is a hash join?", "Builds hash table on inner relation for probing"),
    ("SQL", "What is a merge join?", "Sorts both sides then merges like zipper"),
    ("SQL", "What is a covering index?", "Index containing all columns needed by query"),
    ("SQL", "What is a leading edge of index?", "First column(s) used for index seek"),
    ("SQL", "What is an index hint?", "Forces optimizer to use specific index"),
    ("SQL", "What is query parameterization?", "Replaces literals with parameters for plan reuse"),
    ("SQL", "What is a dead tuple in PostgreSQL?", "Deleted/updated row version still occupying space"),
    ("SQL", "What is autovacuum tuning?", "Marks parameters for vacuum frequency and thresholds"),
    ("SQL", "What is the work_mem setting?", "Memory per sort/hash operation before disk spill"),
    ("SQL", "What is the shared_buffers setting?", "Dedicated memory for caching database pages"),
    ("SQL", "What is the effective_cache_size?", "OS-level cache estimation for query planner"),
    ("SQL", "What is the maintenance_work_mem?", "Memory for VACUUM, CREATE INDEX operations"),
    ("SQL", "What is connection pooling benefit?", "Reduces connection overhead by reusing connections"),
    ("SQL", "What is a database connection leak?", "Connections not returned to pool, causing exhaustion"),
    ("API Design", "What is RESTful API design?", "Resource-based URL, HTTP methods, stateless communication"),
    ("API Design", "What is HATEOAS?", "Hypermedia links in API responses for discoverability"),
    ("API Design", "What is API versioning?", "Strategies: URL path, query param, header, content type"),
    ("API Design", "What is pagination in API?", "Offset-based, cursor-based, keyset pagination"),
    ("API Design", "What is cursor-based pagination?", "Uses opaque cursor for stable pagination"),
    ("API Design", "What is field selection in API?", "Client specifies which fields to include in response"),
    ("API Design", "What is idempotent API?", "Repeated requests produce same result"),
    ("API Design", "What is an API gateway pattern?", "Single entry point for routing, auth, rate limiting"),
    ("API Design", "What is Backend-for-Frontend (BFF)?", "Dedicated backend per client type"),
    ("API Design", "What is API deprecation strategy?", "Sunset header, versioning, migration period"),
], "Senior", "General")

with open(MJS, 'w', encoding='utf-8') as f:
    f.write(content[:idx] + ''.join(new) + content[idx:])
print(f"Batch 22 added {len(new)} questions.")