// RU top-up: Go Core (15) — the only DB category left thin after batches.
export const questions = [
  { category: 'Go Core', question: 'Что такое go vet на практике?', short_answer: 'Статанализ подозрительного кода: форматы, недостижимость, копии замков.', options: ['Статанализ подозрительных мест', 'Ветеринар', 'Форматирование', 'Тесты'], difficulty: 'Junior', language: 'Go' },
  { category: 'Go Core', question: 'Что такое goimports?', short_answer: 'Форматирование плюс автоуправление импортами: добавляет и удаляет.', options: ['Формат с управлением импортами', 'Импорт товаров', 'Таможня', 'Порты'], difficulty: 'Junior', language: 'Go' },
  { category: 'Go Core', question: 'Как задаётся видимость в Go?', short_answer: 'Подвох формулировки: в Go видимость — заглавной буквой имени, не ключевыми словами.', options: ['Заглавная буква имени', 'Ключевое слово public', 'Модификаторы', 'Аннотации'], difficulty: 'Junior', language: 'Go' },
  { category: 'Go Core', question: 'Экспорт из пакета?', short_answer: 'Имена с заглавной буквы видны снаружи, со строчной — только внутри.', options: ['Заглавная буква открывает доступ', 'Ключевое слово export', 'Комментарии', 'Файл exports'], difficulty: 'Junior', language: 'Go' },
  { category: 'Go Core', question: 'Что такое документация godoc?', short_answer: 'Комментарии над сущностями рендерятся в доки: pkg.go.dev читает их.', options: ['Доки из комментариев', 'Документы Word', 'Доктора', 'Договоры'], difficulty: 'Junior', language: 'Go' },
  { category: 'Go Core', question: 'Алиасы типов?', short_answer: 'type A = B — полное тожество; type A B — новый именованный тип.', options: ['Тождество против нового типа', 'Одинаковы', 'Псевдонимы файлов', 'Ярлыки'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Определённые типы?', short_answer: 'type Celsius float64 даёт методы и безопасность единиц.', options: ['Именованные типы с методами', 'Неопределённость', 'Динамические типы', 'Анонимные структуры'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Конверсии типов?', short_answer: 'Явные T(v) между совместимыми; строки/байты через []byte(s) и string(b).', options: ['Явные преобразования', 'Неявные всегда', 'Конверсий нет', 'Через interface'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Строковые руны в range?', short_answer: 'for i, r := range s даёт байт-смещение и руну.', options: ['Смещение и руна', 'Индекс и байт', 'Символы без индекса', 'Байты без рун'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Сравнение структур?', short_answer: '== сравнивает comparable-поля; слайсы/map внутри ломают сравнимость.', options: ['Побитово для сравнимых полей', 'Всегда можно', 'Нельзя никогда', 'Через reflect всегда'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Пустые структуры struct{}?', short_answer: 'Нулевой размер: сигналы, множества (map[T]struct{}), маркеры.', options: ['Сигналы и множества без памяти', 'Пустые файлы', 'Нулевые указатели', 'Заглушки'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Размер структур и выравнивание?', short_answer: 'Поля выравниваются: порядок от больших к малым экономит память.', options: ['Порядок полей влияет на размер', 'Размер всегда сумма', 'Выравнивания нет', 'Только unsafe видит'], difficulty: 'Middle', language: 'Go' },
  { category: 'Go Core', question: 'Оптимизация циклов?', short_answer: 'Вынос инвариантов, bounds check elimination, матрицы по строкам для кэша.', options: ['Инварианты, границы, кэш-дружелюбие', 'Циклы всегда быстры', 'Разворачивать вручную', 'Goto быстрее'], difficulty: 'Senior', language: 'Go' },
  { category: 'Go Core', question: 'Inlining в Go?', short_answer: 'Компилятор встраивает мелкие функции; -gcflags=-m показывает решения.', options: ['Авто-встраивание с диагностикой', 'Ключевое слово inline', 'Встраивания нет', 'Только вручную'], difficulty: 'Senior', language: 'Go' },
  { category: 'Go Core', question: 'Профили pprof?', short_answer: 'CPU/heap/goroutine профили через net/http/pprof и go tool pprof.', options: ['Профили производительности', 'Доказательства', 'Профком', 'Профайлинг личности'], difficulty: 'Senior', language: 'Go' },
];
