// RU batch TS-4: Compiler (8). Feeds the 'TypeScript Compiler Deep Dive' track.
export const questions = [
  { category: 'Compiler', question: 'Как работает tsc?', short_answer: 'Парсинг в AST, проверка типов (checker), стирание типов и emit JS.', options: ['AST, проверка и стирание типов', 'Компиляция в машинный код', 'Интерпретация', 'Транспиляция в Python'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Compiler', question: 'Что такое AST?', short_answer: 'Абстрактное синтаксическое дерево — структура программы для анализа и трансформаций.', options: ['Структура кода для анализа', 'Дерево в лесу', 'Файловая система', 'DOM страницы'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Compiler', question: 'Что такое emit?', short_answer: 'Генерация JS/d.ts/source maps из проверенного AST.', options: ['Генерация выходных файлов', 'Излучение радиации', 'Эмоции', 'Эмиссия акций'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Compiler', question: 'Что такое declaration emit?', short_answer: 'Генерация .d.ts для потребителей библиотеки без исходников.', options: ['Типы для потребителей', 'Декларация независимости', 'Таможенная декларация', 'Налоговая отчётность'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Compiler', question: 'Что такое source maps?', short_answer: 'Маппинг сгенерированного JS на исходный TS для отладки.', options: ['Отладка по исходникам', 'Географические карты', 'Карты сокровищ', 'Схемы метро'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Compiler', question: 'Что такое Language Service?', short_answer: 'API для IDE: автодополнение, навигация, рефакторинги поверх checker.', options: ['Движок IDE-функций', 'Языковые курсы', 'Переводчик', 'Словарь'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Compiler', question: 'Трансформеры AST?', short_answer: 'Плагины преобразования дерева (ts-patch): макросы и кодогенерация.', options: ['Преобразование дерева', 'Трансформеры-роботы', 'Розетки', 'Адаптеры питания'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Compiler', question: 'Почему tsc медленный на монорепо?', short_answer: 'Единый граф проверки: лечат project references, skipLibCheck и изоляцией.', options: ['Граф проверки лечат референсами', 'Медленный диск', 'Мало RAM', 'Плохой код'], difficulty: 'Senior', language: 'TypeScript' },
];
