// RU batch TS-3: NestJS (15) + OOP (15) + Async/Await (15) + Testing (10) + Design Patterns (10) + Modules (10).
export const questions = [
  // ─── NestJS · Junior (5) ───
  { category: 'NestJS', question: 'Что такое NestJS?', short_answer: 'Фреймворк для серверных приложений на TypeScript с модулями, DI и декораторами в духе Angular.', options: ['Серверный фреймворк с модулями и DI', 'Фронтенд-библиотека', 'База данных', 'Сборщик'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое модуль в NestJS?', short_answer: 'Модуль @Module группирует контроллеры, провайдеры и импорты — единица организации приложения.', options: ['Группа контроллеров и провайдеров', 'Файл маршрутов', 'Таблица БД', 'Docker-контейнер'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое контроллер?', short_answer: 'Класс с @Controller, чьи методы с @Get/@Post обрабатывают HTTP-запросы и возвращают ответы.', options: ['Класс обработки HTTP-запросов', 'Компонент React', 'Миграция БД', 'Конфиг файл'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое провайдер?', short_answer: 'Провайдер — сервис/репозиторий, создаваемый DI-контейнером и внедряемый через конструктор.', options: ['Сервис, создаваемый DI-контейнером', 'Провайдер интернета', 'Плагин IDE', 'Хук React'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Как внедрить зависимость?', short_answer: 'Через конструктор: constructor(private users: UsersService) — контейнер сам создаст и подсунет экземпляр.', options: ['Через параметр конструктора', 'Через глобальные переменные', 'Через наследование', 'Через import напрямую'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── NestJS · Middle (7) ───
  { category: 'NestJS', question: 'Что такое Guards?', short_answer: 'Guards решают, пускать ли запрос (аутентификация/роли), возвращая boolean или бросая исключение.', options: ['Проверка доступа к маршруту', 'Охранники типов', 'Файрвол сервера', 'Тесты безопасности'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое Interceptors?', short_answer: 'Перехватчики оборачивают выполнение: логирование, таймауты, маппинг ответа через RxJS-операторы.', options: ['Обёртки вокруг обработчика запроса', 'Перехватчики кликов', 'Браузерные расширения', 'Прокси-серверы'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое Pipes?', short_answer: 'Pipes трансформируют и валидируют вход: ValidationPipe с class-validator, ParseIntPipe для параметров.', options: ['Трансформация и валидация входных данных', 'Трубы Unix', 'Каналы Go', 'Потоки Node.js'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое Exception Filters?', short_answer: 'Фильтры ловят исключения и формируют единый формат ошибок для клиента.', options: ['Единый формат ошибок API', 'Фильтры спама', 'CSS-фильтры', 'Поиск по логам'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Как работать с базами в NestJS?', short_answer: 'Через TypeORM/Prisma/Mongoose-модули: entity, репозиторий через @InjectRepository, транзакции.', options: ['ORM-модули с entity и репозиториями', 'Только raw SQL', 'Базы не поддерживаются', 'Только MongoDB'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Что такое скоупы провайдеров?', short_answer: 'SINGLETON (по умолчанию), REQUEST (на запрос) и TRANSIENT (каждый раз новый) управляют временем жизни.', options: ['Время жизни: singleton, request, transient', 'Области видимости переменных', 'CSS-скоупы', 'Зоны DNS'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'NestJS', question: 'Как тестировать NestJS-приложение?', short_answer: 'TestingModule с overrideProvider мокает зависимости; e2e — через supertest поверх INestApplication.', options: ['TestingModule с моками и supertest e2e', 'Тесты не поддерживаются', 'Только ручное тестирование', 'Только jest без модулей'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── NestJS · Senior (3) ───
  { category: 'NestJS', question: 'Монолит или микросервисы в NestJS?', short_answer: 'Монолит с модулями проще стартовать; микросервисы (TCP/Redis/Kafka-транспорт) — при независимом масштабировании команд.', options: ['Монолит проще, микросервисы при независимом масштабировании', 'Всегда микросервисы', 'Всегда монолит', 'NestJS только монолит'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Как устроены гибридные приложения?', short_answer: 'Одно приложение слушает HTTP и подключает микросервисный транспорт для очередей/событий.', options: ['HTTP + транспорт очередей в одном приложении', 'Два отдельных репозитория', 'Невозможно', 'Только gRPC'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'NestJS', question: 'Как оптимизировать холодный старт?', short_answer: 'Ленивые модули, минимум синхронных require на старте, кэширование DI-графа, serverless-оптимизации.', options: ['Ленивые модули и меньше синхронной работы на старте', 'Больше провайдеров', 'Отключить логи', 'Увеличить RAM всегда'], difficulty: 'Senior', language: 'TypeScript' },
  // ─── OOP · Junior (5) ───
  { category: 'OOP', question: 'Что такое инкапсуляция?', short_answer: 'Сокрытие внутреннего состояния за методами: private-поля, публичный API, инварианты под контролем.', options: ['Сокрытие состояния за методами', 'Наследование полей', 'Полиморфизм вызовов', 'Абстракция интерфейса'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое наследование?', short_answer: 'Класс-наследник получает поля и методы родителя через extends и может их переопределять.', options: ['Получение членов родителя через extends', 'Копирование объектов', 'Композиция сервисов', 'Импорт модулей'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое полиморфизм?', short_answer: 'Один интерфейс — разные реализации: вызов метода ведёт себя по-разному у наследников.', options: ['Разное поведение при общем интерфейсе', 'Множество параметров', 'Перегрузка операторов', 'Динамическая типизация'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое абстракция?', short_answer: 'Выделение существенного: абстрактные классы и интерфейсы фиксируют «что», скрывая «как».', options: ['Фиксация существенного через интерфейсы', 'Удаление кода', 'Сложные иерархии', 'Отсутствие типов'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое конструктор?', short_answer: 'Специальный метод constructor, инициализирующий поля при создании через new.', options: ['Метод инициализации при создании', 'Деструктор', 'Статический метод', 'Геттер'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── OOP · Middle (7) ───
  { category: 'OOP', question: 'Композиция или наследование?', short_answer: 'Композиция гибче: поведение собирается из частей, наследование жёстко связывает иерархией — предпочитают композицию.', options: ['Композиция гибче жёсткой иерархии', 'Всегда наследование', 'Одинаково', 'ООП устарело'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое принцип LSP?', short_answer: 'Наследник должен быть взаимозаменяем с родителем без нарушения поведения вызывающего кода.', options: ['Взаимозаменяемость наследника и родителя', 'Длина методов', 'Именование классов', 'Число параметров'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое ISP?', short_answer: 'Много узких интерфейсов лучше одного толстого: клиенты не зависят от лишних методов.', options: ['Узкие интерфейсы вместо толстых', 'Один интерфейс на всё', 'Интернет-провайдер', 'Скорость интернета'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое DIP?', short_answer: 'Зависимость от абстракций, а не конкретики: модули получают интерфейсы через DI.', options: ['Зависимость от абстракций через DI', 'Прямые импорты классов', 'Глобальные синглтоны', 'Наследование всего'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое SRP?', short_answer: 'У класса одна причина для изменений — одна ответственность, иначе его делят.', options: ['Одна ответственность на класс', 'Один метод на класс', 'Один файл на проект', 'Одна строка на функцию'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Что такое OCP?', short_answer: 'Открыт для расширения, закрыт для изменения: новое поведение — новыми классами, а не правкой старых.', options: ['Расширение без изменения существующего', 'Запрет наследования', 'Только финальные классы', 'Изменение всего сразу'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'OOP', question: 'Статика против инстанс-методов?', short_answer: 'Статика — функции уровня класса без состояния (утилиты), инстанс — поведение объекта с доступом к this.', options: ['Статика без состояния, инстанс с this', 'Одинаково', 'Статика быстрее всегда', 'Инстанс запрещён'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── OOP · Senior (3) ───
  { category: 'OOP', question: 'Где ООП мешает в TS?', short_answer: 'Глубокие иерархии и ceremony ради ceremony: для данных и функций проще типы + чистые функции.', options: ['Глубокие иерархии вместо простых типов и функций', 'ООП всегда идеально', 'Типы мешают ООП', 'Функции запрещены'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'OOP', question: 'Как моделировать состояние без классов?', short_answer: 'Discriminated unions + чистые transition-функции: состояние как данные, переходы как функции.', options: ['Данные-union и функции переходов', 'Состояние только в классах', 'Глобальные переменные', 'localStorage'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'OOP', question: 'DDD за 2 минуты?', short_answer: 'Единый язык, ограниченные контексты, сущности/value-объекты/агрегаты, модель отражает домен, а не БД.', options: ['Язык, контексты, агрегаты вокруг домена', 'Только микросервисы', 'Только базы данных', 'Диаграммы ради диаграмм'], difficulty: 'Senior', language: 'TypeScript' },
  // ─── Async/Await · Junior (5) ───
  { category: 'Async/Await', question: 'Что такое Promise?', short_answer: 'Объект eventual-результата: pending/fulfilled/rejected, цепочки через then/catch/finally.', options: ['Объект будущего результата с состояниями', 'Поток операционной системы', 'Колбэк-функция', 'Событие DOM'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что делает async?', short_answer: 'Помечает функцию возвращающей Promise: return становится resolve, throw — reject.', options: ['Функция возвращает Promise', 'Функция выполняется в потоке', 'Блокирует цикл событий', 'Отключает ошибки'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что делает await?', short_answer: 'Приостанавливает async-функцию до результата промиса, не блокируя event loop.', options: ['Пауза до результата без блокировки потока', 'Блокировка всего процесса', 'Ожидание в цикле', 'Сон потока'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Как ловить ошибки async?', short_answer: 'try/catch внутри async или .catch() на промисе; необработанный reject роняет процесс.', options: ['try/catch или .catch()', 'Ошибок не бывает', 'Только .then()', 'Игнорировать'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что такое Promise.all?', short_answer: 'Параллельный запуск с результатом-массивом; падает целиком при первом reject.', options: ['Всё параллельно, общий провал при первой ошибке', 'Последовательно', 'Только первый результат', 'Игнорирует ошибки'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── Async/Await · Middle (7) ───
  { category: 'Async/Await', question: 'Чем allSettled отличается от all?', short_answer: 'allSettled ждёт всех и возвращает статусы fulfilled/rejected каждого — частичные результаты сохраняются.', options: ['Ждёт всех со статусами каждого', 'То же самое', 'Быстрее', 'Только для двух промисов'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что делает Promise.race?', short_answer: 'Возвращает первый settled результат; остальные продолжают выполняться в фоне.', options: ['Первый завершившийся результат', 'Самый быстрый отменяется', 'Гонка потоков', 'Случайный результат'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Как ограничить параллелизм?', short_answer: 'Пул/очередь (p-limit) или чанки: N одновременных задач вместо Promise.all на тысячах.', options: ['Пулы и чанки вместо unbounded all', 'Ограничить нельзя', 'Только последовательно', 'Увеличить RAM'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что такое AbortController?', short_answer: 'Отмена fetch/операций через signal: abort() прерывает ожидание и бросает AbortError.', options: ['Отмена асинхронных операций по сигналу', 'Контроллер домена', 'Перезапуск процесса', 'Отмена компиляции'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Как сделать retry с backoff?', short_answer: 'Цикл с задержкой 2^n + jitter, лимит попыток, проброс последней ошибки и идемпотентность операции.', options: ['Повторы с растущей задержкой и лимитом', 'Бесконечный цикл', 'Retry не нужен', 'Только одна попытка'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Чем Observable отличается от Promise?', short_answer: 'Observable ленив, много значений и отменяем (RxJS); Promise — одно значение, eager, без отмены.', options: ['Много значений, лень и отмена против одного eager-значения', 'Одинаково', 'Promise отменяем', 'Observable только для DOM'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Что такое unhandled rejection?', short_answer: 'Промис упал без .catch/try — Node роняет процесс; вешают обработчик unhandledRejection с логом.', options: ['Необработанная ошибка промиса роняет процесс', 'Безвредное предупреждение', 'Ловится сама', 'Только в браузере'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── Async/Await · Senior (3) ───
  { category: 'Async/Await', question: 'Как избежать гонок в async-коде?', short_answer: 'Сериализация критических секций (мьютекс/очередь), идемпотентность, compare-and-set вместо read-modify-write.', options: ['Сериализация секций и идемпотентность', 'Гонок в JS не бывает', 'Больше await везде', 'Глобальный флаг'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Микрозадачи против макрозадач?', short_answer: 'await/then — микроочередь (вся draining до рендера), setTimeout/IO — макро; порядок влияет на задержки UI.', options: ['Микро draining до макро и рендера', 'Одинаковые очереди', 'Макро быстрее', 'Разницы нет'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Async/Await', question: 'Когда async/await вредит?', short_answer: 'Последовательные await независимых запросов вместо all, await в циклах, скрытая серийность — лечится параллелизмом.', options: ['Серийность независимых операций вместо параллелизма', 'Никогда не вредит', 'Всегда вредит', 'Только в циклах for'], difficulty: 'Senior', language: 'TypeScript' },
  // ─── Testing · Junior (4) ───
  { category: 'Testing', question: 'Что такое unit-тест?', short_answer: 'Проверка малой единицы (функции) изолированно: вход → ожидание, зависимости замоканы.', options: ['Изолированная проверка единицы кода', 'Тест всего приложения', 'Ручное тестирование', 'Проверка типов'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Testing', question: 'Что такое Jest/Vitest?', short_answer: 'Раннеры тестов для JS/TS: describe/it/expect, моки, снапшоты, покрытие из коробки.', options: ['Фреймворки запуска тестов с expect и моками', 'Браузеры', 'Сборщики', 'Линтеры'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Testing', question: 'Что такое мок?', short_answer: 'Подмена зависимости контролируемой заглушкой: vi.fn(), vi.mock() для изоляции юнита.', options: ['Контролируемая подмена зависимости', 'Копия продакшн-БД', 'Скриншот', 'Лог файл'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Testing', question: 'Что такое e2e-тест?', short_answer: 'Сквозная проверка сценария пользователя через реальный UI/API (Playwright, Cypress).', options: ['Сценарий пользователя через реальный интерфейс', 'Проверка одной функции', 'Проверка типов', 'Нагрузочный тест'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── Testing · Middle (4) ───
  { category: 'Testing', question: 'Как тестировать async-код?', short_answer: 'Await ожиданий, фейковые таймеры, мок fetch, явные таймауты против висящих тестов.', options: ['Ожидания, фейк-таймеры и моки сети', 'Sleep на глаз', 'Async не тестируют', 'Только e2e'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Testing', question: 'Что такое Testing Library?', short_answer: 'Тесты React через поведение пользователя (getByRole, userEvent) вместо деталей реализации.', options: ['Тесты поведения через доступные роли', 'Тесты CSS', 'Скриншоты', 'Проверка бандла'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Testing', question: 'Снапшоты: за и против?', short_answer: 'Хороши для регресса разметки, плохи как замена ассёртам — шумные диффы все approve не глядя.', options: ['Регресс разметки да, замена ассёртам нет', 'Всегда зло', 'Всегда добро', 'Только для API'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Testing', question: 'Что такое интеграционный тест?', short_answer: 'Проверка связки модулей: API + БД, компоненты с провайдерами — ловят стыковочные ошибки.', options: ['Проверка связки модулей и стыков', 'Тест интегралов в математике', 'Сборка проекта', 'Деплой на прод'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── Testing · Senior (2) ───
  { category: 'Testing', question: 'Пирамида тестирования?', short_answer: 'Много быстрых юнитов, меньше интеграционных, мало e2e: скорость фидбэка против уверенности.', options: ['Юниты внизу, e2e наверху пирамиды', 'Только e2e', 'Только юниты', 'Пирамида устарела'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Testing', question: 'Флаки-тесты: борьба?', short_answer: 'Карантин, детерминизм (сиды, фейк-время), ретраи только в CI-ленте, root-cause анализ.', options: ['Детерминизм, карантин и анализ причин', 'Больше ретраев навсегда', 'Удалить тесты', 'Игнорировать'], difficulty: 'Senior', language: 'TypeScript' },
  // ─── Design Patterns · Junior (3) ───
  { category: 'Design Patterns', question: 'Что такое Singleton?', short_answer: 'Один экземпляр на приложение: приватный конструктор + статическое поле/метод доступа.', options: ['Гарантированно один экземпляр', 'Много экземпляров', 'Наследование', 'Интерфейс'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Factory?', short_answer: 'Метод/функция, создающая объекты, скрывая выбор конкретного класса от клиента.', options: ['Создание объектов без знания класса', 'Завод автомобилей', 'Билд-скрипт', 'DI-контейнер'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Observer?', short_answer: 'Подписка на события: subject уведомляет observers (EventEmitter, сигналы).', options: ['Подписка и уведомления о событиях', 'Наблюдение за файлами', 'Паттерн базы данных', 'Сортировка'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── Design Patterns · Middle (5) ───
  { category: 'Design Patterns', question: 'Что такое Strategy?', short_answer: 'Взаимозаменяемые алгоритмы за общим интерфейсом: сортировки, сериализаторы, стратегии оплаты.', options: ['Смена алгоритма через общий интерфейс', 'Военная стратегия', 'План спринта', 'Маршрутизация'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Decorator (паттерн)?', short_answer: 'Обёртка, добавляющая поведение без изменения объекта (не путать с @-синтаксисом).', options: ['Динамическое добавление поведения обёрткой', 'Только @-синтаксис', 'Наследование', 'Удаление методов'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Adapter?', short_answer: 'Приводит несовместимый интерфейс к ожидаемому: обёртка-переходник между API.', options: ['Переходник между интерфейсами', 'Паттерн питания', 'Сетевой адаптер', 'Конвертер валют'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Builder (паттерн)?', short_answer: 'Пошаговая сборка сложного объекта с цепочкой методов вместо телескопических конструкторов.', options: ['Пошаговая сборка цепочкой методов', 'Сборщик webpack', 'Конструктор с 10 параметрами', 'Фабрика синглтонов'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Что такое Repository?', short_answer: 'Абстракция хранилища: find/save за интерфейсом, домен не знает про SQL.', options: ['Хранилище за интерфейсом', 'Git-репозиторий', 'Папка с файлами', 'Кэш Redis'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── Design Patterns · Senior (2) ───
  { category: 'Design Patterns', question: 'Антипаттерн Service Locator?', short_answer: 'Скрытые зависимости через глобальный локатор вместо явного DI — неявность и сложный рефакторинг.', options: ['Скрытые зависимости вместо явного DI', 'Паттерн навигации', 'Поиск сервисов в DNS', 'Каталог услуг'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Design Patterns', question: 'Когда паттерны вредны?', short_answer: 'Преждевременная абстракция и Enterprise FizzBuzz: сложность без выгоды, YAGNI важнее каталога.', options: ['Сложность без выгоды нарушает YAGNI', 'Паттерны всегда полезны', 'Паттерны устарели', 'Только Singleton вреден'], difficulty: 'Senior', language: 'TypeScript' },
  // ─── Modules · Junior (4) ───
  { category: 'Modules', question: 'Что такое import/export?', short_answer: 'ESM-синтаксис обмена кодом между файлами: именованные и default-экспорты.', options: ['Обмен кодом между модулями', 'Импорт картинок', 'Экспорт в PDF', 'Таможня'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Modules', question: 'Чем default отличается от named?', short_answer: 'Default один на модуль с любым именем импорта, named — строгие имена в фигурных скобках.', options: ['Один свободный против строгих именованных', 'Одинаковы', 'Default быстрее', 'Named устарели'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Modules', question: 'Что такое barrel-файлы?', short_answer: 'index.ts, реэкспортирующий публичное API папки: import {A} from «./ui» вместо глубоких путей.', options: ['Реэкспорт публичного API папки', 'Бочки с данными', 'Архивы tar', 'Бандлы webpack'], difficulty: 'Junior', language: 'TypeScript' },
  { category: 'Modules', question: 'Что такое циклические импорты?', short_answer: 'A импортирует B, B — A: частично инициализированные модули, undefined на старте, лечится выносом общего.', options: ['Взаимные импорты с частичной инициализацией', 'Быстрые импорты', 'Параллельная загрузка', 'Кэширование модулей'], difficulty: 'Junior', language: 'TypeScript' },
  // ─── Modules · Middle (4) ───
  { category: 'Modules', question: 'Как устроен бандлинг?', short_answer: 'Сборщик (Vite/Rollup) строит граф импортов, tree-shakes мёртвое и выдаёт чанки для браузера.', options: ['Граф импортов, tree-shaking и чанки', 'Склейка строкой', 'Копирование файлов', 'Минификация типов'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Modules', question: 'Что такое tree-shaking?', short_answer: 'Удаление неиспользуемых экспортов при сборке; требует ESM и sideEffects-флагов.', options: ['Удаление мёртвого кода при сборке', 'Тряска дерева каталогов', 'Сжатие картинок', 'Удаление тестов'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Modules', question: 'Что такое code splitting?', short_answer: 'Разбиение бандла на чанки с ленивой загрузкой (import()) для быстрой первой отрисовки.', options: ['Ленивые чанки для быстрой загрузки', 'Разбивка монитора', 'Сплит A/B тестов', 'Шардирование БД'], difficulty: 'Middle', language: 'TypeScript' },
  { category: 'Modules', question: 'Зачем type-only импорты?', short_answer: 'import type стирается полностью: ноль runtime-связей, чище граф и быстрее сборка.', options: ['Ноль runtime-связей для типов', 'Быстрее типы проверяются', 'Меньше RAM', 'Красивый код'], difficulty: 'Middle', language: 'TypeScript' },
  // ─── Modules · Senior (2) ───
  { category: 'Modules', question: 'Монорепо: как делить код?', short_answer: 'Workspace-пакеты с явными зависимостями, project references, версионирование API между пакетами.', options: ['Пакеты с явными зависимостями и референсами', 'Один огромный пакет', 'Копипаст между проектами', 'Git-сабмодули всегда'], difficulty: 'Senior', language: 'TypeScript' },
  { category: 'Modules', question: 'Что такое dual package (CJS+ESM)?', short_answer: 'Публикация обоих форматов через exports-мапу с осторожностью против dual package hazard (два состояния).', options: ['Оба формата с exports-мапой и без двойного состояния', 'Только CJS', 'Только ESM', 'Форматы не важны'], difficulty: 'Senior', language: 'TypeScript' },
];
