// RU batch GO-5: Design Patterns (12). Feeds the 'Design Patterns in Go' track.
export const questions = [
  { category: 'Design Patterns', question: 'Какие паттерны идиоматичны для Go?', short_answer: 'Простые: functional options, middleware-цепочки, worker pools, интерфейсы вместо иерархий.', options: ['Опции, middleware, пулы, интерфейсы', 'Наследование и фабрики везде', 'Синглтоны повсюду', 'Паттерны не нужны'], difficulty: 'Junior', language: 'Go' },
  { category: 'Design Patterns', question: 'Что такое functional options?', short_answer: 'Настройка через функции-параметры: NewServer(WithPort(8080)) вместо телескопических конструкторов.', options: ['Настройка функциями-параметрами', 'Функциональное программирование', 'Опции компилятора', 'Флаги CLI'], difficulty: 'Junior', language: 'Go' },
  { category: 'Design Patterns', question: 'Что такое middleware-цепочка?', short_answer: 'Обёртки handler: logging(auth(handler)) с порядком снаружи внутрь.', options: ['Вложенные обёртки хендлера', 'ПО промежуточного слоя', 'База данных', 'Очередь сообщений'], difficulty: 'Junior', language: 'Go' },
  { category: 'Design Patterns', question: 'Синглтон в Go?', short_answer: 'sync.Once или пакетные переменные вместо классического Singleton.', options: ['Once или пакетная переменная', 'Глобальный указатель', 'Статический класс', 'Двойная проверка вручную'], difficulty: 'Junior', language: 'Go' },
  { category: 'Design Patterns', question: 'Стратегия через интерфейсы?', short_answer: 'Поле-интерфейс со взаимозаменяемыми реализациями вместо switch.', options: ['Поведение полем-интерфейсом', 'Наследование', 'Флаги', 'Конфиги'], difficulty: 'Middle', language: 'Go' },
  { category: 'Design Patterns', question: 'Адаптер в Go?', short_answer: 'http.HandlerFunc приводит функцию к интерфейсу Handler.', options: ['Функция к интерфейсу', 'Переходник питания', 'Конвертер валют', 'Патч-корд'], difficulty: 'Middle', language: 'Go' },
  { category: 'Design Patterns', question: 'Декоратор в Go?', short_answer: 'Обёртка функций/хендлеров без наследования: метрики, ретраи, кэш.', options: ['Обёртка поведения', 'Аннотации', 'Наследование', 'Макросы'], difficulty: 'Middle', language: 'Go' },
  { category: 'Design Patterns', question: 'Пайплайн из горутин?', short_answer: 'Стадии-каналы с fan-out/fan-in для потоковой обработки.', options: ['Стадии-каналы обработки', 'Нефтепровод', 'CI-конвейер', 'Конвейер завода'], difficulty: 'Middle', language: 'Go' },
  { category: 'Design Patterns', question: 'Очередь задач на каналах?', short_answer: 'Буферный канал + воркеры + graceful drain при shutdown.', options: ['Канал с воркерами и drain', 'Слайс без синхронизации', 'База данных', 'Файл'], difficulty: 'Middle', language: 'Go' },
  { category: 'Design Patterns', question: 'Когда интерфейсы вредят?', short_answer: 'Преждевременные абстракции и моки всего: YAGNI, конкретика сначала.', options: ['Абстракции без второй реализации', 'Интерфейсы всегда полезны', 'Конкретика вредна', 'Тесты не нужны'], difficulty: 'Senior', language: 'Go' },
  { category: 'Design Patterns', question: 'Шаблонный метод без наследования?', short_answer: 'Скелет через функции-поля/хуки вместо абстрактных классов.', options: ['Хуки вместо иерархии', 'Наследование обязательно', 'Копипаст', 'Макросы'], difficulty: 'Senior', language: 'Go' },
  { category: 'Design Patterns', question: 'Антипаттерны Go?', short_answer: 'Гонки за «умным» кодом: init-магия, пустые интерфейсы везде, игнор ошибок.', options: ['Магия, any-везде, игнор ошибок', 'Антипаттернов нет', 'Только goto', 'Мало комментариев'], difficulty: 'Senior', language: 'Go' },
];
